### ISSUE TITLE
Añadir reemplazo de n por ñ

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#108]
En una evaluación del corrector ortográfico es-ES en Mozilla Add-ons, he recibido la queja de que "manana" no obtiene como sugerencia "mañana". He comprobado que, en LibreOffice sí que se ofrece, aunque en una lista muy larga y en la zona media.

He pensado que podría funcionar añadir una entrada de reemplazo así en el fichero de afijos:

REP n ñ

Si he entendido bien las instrucciones, esto haría que, ante palabras no encontradas que contengan una "n", Hunspell pruebe a sustituir la "n" por "ñ" para ver si existe una palabra definida. En el ejemplo, imagino que Hunspell calcularía las opciones "mañana", "manaña" y "mañaña".

¿Qué os parece la idea?

**Comment by sbosio** [comment]
Me parece que el corrector de Mozilla corta la lista en las primeras 5
sugerencias y como mañana no aparece entre esas 5 primeras, no se ofrece
como reemplazo. No sé por qué habrán ellos implementado de esta forma el
ofrecimiento de reemplazos del corrector. Para muchos errores, seguramente
esas 5 sugerencias se quedan cortas, porque tampoco aparecen en el mismo
orden que en LibreOffice, lo que sugiere que también cambian el orden de
prioridad de los reemplazos ofrecidos.

No debería ser necesario agregar la sentencia REP, porque se usa con
sustituciones de más de un carácter. Las sustituciones o agregados de un
único carácter son controlados por la sentencia TRY y el orden de prioridad
se fija de acuerdo a la posición de cada letra en esa sentencia. Por eso
tiene un ordenamiento que obedece a la frecuencia con la cual cada letra
aparece en las palabras del diccionario. Esto por supuesto no asegura que
para un error en particular su reemplazo correcto aparezca al tope de la
lista de reemplazos ofrecidos.

Creo que las entradas REP tienen prevalencia sobre las sugerencias
generadas por la sentencia TRY. Se podría añadir y probar si cambia el
orden de prioridad de los reemplazos ofrecidos. Pero esto únicamente
solucionaría el problema con esa palabra (o particularmente con cualquier
palabra que lleve ñ y se haya escrito con n), y no con muchas otras que van
a seguir sufriendo el mismo "ninguneo" por el límite máximo de 5
ofrecimientos de Mozilla.

También se podría agendar una incidencia en el bugtracker de Mozilla, pero
me parece que es una decisión de diseño de ellos contra la cual poco
podemos hacer. En las instrucciones de cómo usar el corrector de Mozilla
(página en inglés:
https://support.mozilla.org/en-US/kb/how-do-i-use-firefox-spell-checker),
dice que si ninguna de las sugerencias de reemplazo es correcta, la palabra
debe corregirse manualmente.

Saludos

**Comment by RickieES** [comment]
Dejé esto en el limbo y realmente, con lo que nos contó Santiago, creo que queda claro que mi propuesta trata de arreglar en nuestro diccionario una decisión de diseño de Mozilla para todo su sistema de corrección ortográfica, lo que no me parece una buena idea, así que cierro el _issue_.
