### ISSUE TITLE
Añade instrucciones de instalación de diccionarios para Vim/Neovim

### ISSUE THREAD

**Issue by jorgesumle** [sbosio/rla-es#109]
En la página del wiki "Generar diccionario corrector" he añadido las instrucciones de instalación de diccionario para los editores Vim y Neovim. ¿Por favor alguien puede revisar mis cambios? Aquí está la página de wiki modificada: https://github.com/jorgesumle/rla-es/wiki/Generar-diccionario-corrector

**Comment by RickieES** [comment]
Ante todo, muchas gracias por tu aportación. Es fantástico tener información específica que expanda las posibilidades de uso del corrector en más herramientas y, sinceramente, yo no conocía esta información.

Voy a hacer una pequeña corrección en el apartado de LibreOffice que ya existía. En cuanto a la parte relativa a Vim, he seguido los pasos y funciona perfectamente. En mi caso (Linux Mint, basada en Ubuntu), la ruta al directorio spell de vim es /usr/share/vim/vim74/spell. ¿En tu caso es realmente /usr/vim, sin ningún otro directorio por medio?

**Comment by jorgesumle** [comment]
> /usr/share/vim/vim74/spell. ¿En tu caso es realmente /usr/vim, sin ningún otro directorio por medio?

Me he equivocado al escribirlo. Efectivamente, va el directorio share de por medio (`/usr/share/vim/vim74/spell`). Acabo de corregir ese error.

**Comment by RickieES** [comment]
@jorgesumle , podemos dar por cerrado este _issue_, ¿verdad?

**Comment by jorgesumle** [comment]
¿Alguien con permisos en este repositorio debería actualizar el wiki (https://github.com/sbosio/rla-es/wiki/Generar-diccionario-corrector), no?

**Comment by RickieES** [comment]
Caramba, ni me había dado cuenta de que los cambios no los habías hecho en el wiki del proyecto, sino en tu _fork_. :nerd_face: 

Voy a ello.

**Comment by RickieES** [comment]
Hecho, perdon el despiste: :innocent: 

https://github.com/sbosio/rla-es/wiki/Generar-diccionario-corrector/40e982ac9c44b7d3d26bb47f43e26e62d70e5024

Cierro el _issue_.
