### ISSUE TITLE
Palabras erróneas en el último diccionario generado es_ES.dic (v.2.1)

### ISSUE THREAD

**Issue by DavidPDev** [sbosio/rla-es#112]
Buenas, he utilizado el último diccionario generado (desde el link de openoffice)
http://extensions.openoffice.org/en/project/diccionario-de-correccion-ortografica-separacion-silabica-y-sinonimos-en-espanol-espana
Y me he encontrado con muchas palabras que están incluidas dentro del archivo es_ES.dic y que no existen en el DRAE.
No se si es un fallo en la generación del diccionario o es que yo desconozco el funcionamiento del mismo, pero creo que dichas palabras que no existen en español no deberían estar incluidas en el archivo final.

![fallo1](https://cloud.githubusercontent.com/assets/25801199/24716503/8ab4fd40-1a2f-11e7-807e-c4ce59697652.JPG)

Estas son algunas de las palabras que he encontrado en el último es_ES.dic:

ardoz
art
blv
coord
cta
cte
ctvo
cu
der
dir
dra
eva
gta
hab
hna
hno
icod
ilmo
ing
lic
lie
loc
nro
pat
pol
rdo
reg
rel
rep
rte
rvd
rvdo
sdad
sic
sig
soc
sta
tel
vall
vdo
vol

**Comment by DavidPDev** [comment]
Ahora me he dado cuenta que algunas de estas palabras son abreviaturas, aun así no estoy seguro que debieran estar en incluidas en el archivo es_ES.dic pues se consideran como válidas muchas palabras que no lo son.
Yo he utilizado el diccionario para validar palabras generadas "aleatoriamente" y me da como palabras correctas en español todas esas abreviaturas.

**Comment by RickieES** [comment]
No consigo encontrar de dónde sale "ardoz". Del resto, muchas son abreviaturas, efectivamente, pero hay otras que tampoco encuentro (vall, sta) y me pregunto si alguna de ellas no las tendrás en tu diccionario personal.

Sobre si deben incluirse o no las abreviaturas, supongo que es una cuestión de opiniones. En el sitio web del equipo de traducción de Mozilla a es-ES (español de España) hicimos una encuesta y dos de cada tres respondieron que sí:

http://www.proyectonave.es/node/351

**Comment by DavidPDev** [comment]
Ok, gracias por aclararlo. Me parece razonable que el diccionario incluya abreviaturas comunes, aunque algunas, para mi, son muy inusuales.
En cuanto a la palabra "Ardoz" (por ejemplo) he encontrado que está incluida en el fichero "toponimos-municipios.txt" (dentro de la carpeta de \palabras\toponimos\l10n\es_ES). Supongo que se debe al municipio de "Torrejón de Ardoz".
La palabra "Vall" también está en el fichero de municipios (¿?).
La palabra "Sta" creo que está en el de abreviaturas con cambio de género: "sto/G". Ignoro qué significa la abreviatura "Sto. o Sta." , quizás Señorito, Señorita :) 

![fallo2](https://cloud.githubusercontent.com/assets/25801199/25086158/4e5317e8-2366-11e7-944f-5be077b6d3fb.JPG)

Por mi este Issue se puede cerrar.
Aun así me entran dudas de si un diccionario "general" como este debería incluir nombres de ciudades, provincias, países, etc. de un país en particular (en este caso España). Y porque no el resto de países de habla hispana.

**Comment by RickieES** [comment]
Sí, tienes razón, Ardoz y Vall están en el fichero de topónimos. Desde luego, para mí "Sta" es abreviatura de "señorita".

Si el diccionario se genera con la opción -r:

https://github.com/sbosio/rla-es/blob/master/ortograf/herramientas/make_dict.sh#L174

se genera únicamente con las palabras incluidas en la RAE; en caso contrario, se incluyen las palabras no incluidas en la RAE (lo que incluye las abreviaturas) y los topónimos.

En todos los casos se incluyen, respetando la inclusión o no del modificador -r, las palabras generales y las de la localización específica. En el caso de los topónimos, si no se especificó el modificador RAE, se incluyen los topónimos del mundo (continentes y nombres de países, si no recuerdo mal) y los de la localización específica. Hay topónimos específicos para varias localizaciones, pero nos gustaría que colaboradores de cada país incluyeran los topónimos más habituales de cada localización, ya que son ellos los que mejor conocen cuáles incluir.

Desde el proyecto, y teniendo en cuenta que hay más de 20 variantes regionales, generamos únicamente el diccionario completo (con ortografía y sinónimos) sin el modificador -r, pero es bastante fácil generar las versiones más _puristas_, incluyendo -r y eliminando -c.

De acuerdo con lo que dices en tu comentario anterior, cierro el _issue_.
