### ISSUE TITLE
Archivos .old innecesarios

### ISSUE THREAD

**Issue by Miguel-Dorta** [sbosio/rla-es#113]
Existen en el repositorio una serie de archivos con extensión .old, consecuencia del commit [Cambio de la codificación de los ficheros de ISO a UTF-8](https://github.com/sbosio/rla-es/commit/9d7b51829c7862ed2aff282b06f41a33779607a1). El contenido de estos es redundante ya que Git es un sistema de control de versiones.

Los archivos con esta extensión son:
rla-es/ortograf/palabras/RAE/Adjetivos.old
rla-es/ortograf/palabras/RAE/Adverbios.old
rla-es/ortograf/palabras/RAE/ConjugacionesIrregulares.old
rla-es/ortograf/palabras/RAE/Conjunciones.old
rla-es/ortograf/palabras/RAE/Contracciones.old
rla-es/ortograf/palabras/RAE/Interjecciones.old
rla-es/ortograf/palabras/RAE/NombresComunes.old
rla-es/ortograf/palabras/RAE/NombresFemeninos.old
rla-es/ortograf/palabras/RAE/NombresMasculinos.old
rla-es/ortograf/palabras/RAE/NombresMasculinosFemeninos.old
rla-es/ortograf/palabras/RAE/Preposiciones.old
rla-es/ortograf/palabras/RAE/Pronombres.old
rla-es/ortograf/palabras/RAE/VerbosIntransitivos.old
rla-es/ortograf/palabras/RAE/VerbosIntransitivosPronominales.old
rla-es/ortograf/palabras/RAE/VerbosPronominales.old
rla-es/ortograf/palabras/RAE/VerbosTransitivos.old
rla-es/ortograf/palabras/RAE/VerbosTransitivosIntransitivos.old
rla-es/ortograf/palabras/RAE/VerbosTransitivosIntransitivosPronominales.old
rla-es/ortograf/palabras/RAE/VerbosTransitivosPronominales.old
rla-es/ortograf/palabras/RAE/l10n/es_AR/Adjetivos.old
rla-es/ortograf/palabras/RAE/l10n/es_AR/NombresComunes.old
rla-es/ortograf/palabras/RAE/l10n/es_AR/VerbosPronominales.old
rla-es/ortograf/palabras/RAE/l10n/es_AR/VerbosTransitivosPronominales.old
rla-es/ortograf/palabras/RAE/l10n/es_BO/VerbosPronominales.old
rla-es/ortograf/palabras/RAE/l10n/es_ES/Adjetivos.old
rla-es/ortograf/palabras/RAE/l10n/es_ES/VerbosTransitivos.old
rla-es/ortograf/palabras/RAE/l10n/es_MX/NombresMasculinosFemeninos.old
rla-es/ortograf/palabras/RAE/l10n/es_MX/VerbosIntransitivos.old

**Comment by sbosio** [comment]
No Miguel, los archivos ".old" no son una consecuencia de ese commit.

Son unos archivos donde yo fui (hace muchos años ya) trabajando la
eliminación de los términos que según RAE son anticuados o están desusados.
En su momento tenía un archivo que había compilado con un robot que extraía
la información del sitio del DRAE, e iba buscando aquellos términos cuyas
únicas acepciones eran anticuadas o desusadas. Los sacaba de su archivo
original (p. ej. Adjetivos.txt) y lo movía al archivo '.old'
correspondiente. La idea era no perder esos lemas, por si a alguien le
interesaba compilar uno que incluyera esos términos (no sé para qué, pero
uno nunca sabe). En su momento debo haber avanzado hasta la letra "D", pero
luego perdí ese archivo y no pude continuar, además que es un trabajito de
hormiga. Es decir que, en el diccionario actual, deben haber muchos lemas
anticuados o desusados, sobre todo los lemas que comienzan con la letra
inicial 'D' o posterior en el abecedario.

Saludos,

Santiago

**Comment by Miguel-Dorta** [comment]
Vale, lo comprendo entonces. Cierro el problema.
