### ISSUE TITLE
Reglas seseo y ceceo

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#114]
En España el seseo y ceceo se considera erróneo por lo que se deberían añadir al fichero de afijos estos reemplazos
REP s          c
REP c          s

Se supone que estas reglas mejorarían los errores por seseo y ceceo pero la verdad es que no he encontrado ningún caso donde el diccionario actual no recomiende la palabra correcta. ¿Veis esta regla útil?

**Comment by sbosio** [comment]
En realidad las sentencias REP sirven para reemplazos de dos o más
caracteres. Las sugerencias de reemplazo de un único carácter son generadas
por la sentencia TRY en el orden en que aparecen los caracteres en la
sentencia. La única duda que me queda es si, en caso de agregar esas
reglas, las sugerencias que reemplazan "s" por "c" y viceversa aparecerían
primero en la lista.

Saludos,

**Comment by sbosio** [comment]
Hice algunas pruebas y aunque agregué esas sentencias REP no se modificó el orden de preferencia de las sugerencias.
Como comenté anteriormente, constituyen sustituciones de una única letra, y esa es una de las técnicas que aplica el algoritmo para ofrecer las sugerencias. La eliminación, inserción y sustitución de un único carácter es una operación de costo mínimo, con lo cual las sugerencias donde se reemplaza 's' por 'c' tienden a aparecer entre las primeras opciones. Además suelen aparecer entre las primeras sugerencias porque la 's' y la 'c' son la séptima y octava letra en la sentencia TRY (es decir que solo aparecería otra sugerencia por encima si al eliminar la letra o realizar un reemplazo por 'a', 'e', 'r', 'o', 'i', 'n', que tienen mayor prioridad, se obtiene un lema válido).
Cierro el registro porque no me parece que debamos hacer nada al respecto.
