### ISSUE TITLE
Duda sobre la palabra [acomedir] vs. [acomedirse]

### ISSUE THREAD

**Issue by edgardorios** [sbosio/rla-es#116]
Hola:

En el diccionario de la RAE pude encontrar la palabra _[acomedirse](http://dle.rae.es/?id=0X3kjbT)_, pero no pude encontrar _acomedir_. Por otra parte, aunque busqué en los archivos de afijos, no pude entender como usar _/XD_. ¿Alguien me pudiera por favor orientar sobre si debería proponer un cambio para esta palabra?

Al buscar la palabra, la encontré en: _es_GT_, _es_CO_, _es_MX_ y _es_PE_.
[acomedir/XD](https://github.com/sbosio/rla-es/search?utf8=%E2%9C%93&q=acomedir&type=)

[ortograf/palabras/RAE/l10n/es_GT/VerbosPronominales.txt](https://github.com/sbosio/rla-es/blob/ecc5362045fcebafecf8b5b2bf7684c5b2209921/ortograf/palabras/RAE/l10n/es_GT/VerbosPronominales.txt)
[ortograf/palabras/RAE/l10n/es_CO/VerbosPronominales.txt](https://github.com/sbosio/rla-es/blob/ecc5362045fcebafecf8b5b2bf7684c5b2209921/ortograf/palabras/RAE/l10n/es_CO/VerbosPronominales.txt)
[ortograf/palabras/RAE/l10n/es_MX/VerbosPronominales.txt](https://github.com/sbosio/rla-es/blob/ecc5362045fcebafecf8b5b2bf7684c5b2209921/ortograf/palabras/RAE/l10n/es_MX/VerbosPronominales.txt)
[ortograf/palabras/RAE/l10n/es_PE/VerbosPronominales.txt](https://github.com/sbosio/rla-es/blob/ecc5362045fcebafecf8b5b2bf7684c5b2209921/ortograf/palabras/RAE/l10n/es_PE/VerbosPronominales.txt)

Gracias de antemano por su ayuda.

**Comment by sbosio** [comment]
Esta es una difícil.

En realidad, puede considerarse un error que reconozca la palabra
"acomedir". El verbo tiene uso únicamente pronominal, en este caso es un
verbo reflexivo (la acción recae sobre el sujeto que la lleva a cabo). Los
infinitivos de los verbos exclusivamente pronominales llevan el pronombre
"se" en posición enclítica. Lo correcto sería que existiera la palabra
"acomedirse" con las reglas aplicadas para su conjugación.

La solución correcta sería duplicar todas y cada una de las reglas que
intervienen en la conjugación de los verbos para que, además de aceptar las
terminaciones en "ar", "er" e "ir", también acepten "arse", "erse" e
"irse", y cambiar todas las palabras de los archivos
"VerbosPronominales.txt" por sus versiones que terminan en "se". De esta
manera nos aseguraríamos de que no se dé por válidos estos infinitivos de
verbos exclusivamente pronominales sin el pronombre "se".

El tema pasa por cuánto se incrementaría la cantidad de reglas de reemplazo
para las banderas de conjugación, solo para acomodar la corrección de estos
casos puntuales. Digo, que no sé si sería una buena decisión, aunque
obviamente sería lo correcto.

Para tu segunda pregunta, no es una única regla, sino dos. Quiere decir que
para derivar todas las palabras válidas desde el lema "acomedir" se debe
aplicar la regla de sufijos "X" y la regla "D".

La regla "X" genera las conjugaciones para los verbos completamente
irregulares. En realidad son las conjugaciones para todas las terminaciones
distintas de esos verbos. No puedo asegurar que sean el 100%, pero en su
momento agregué todas las correspondientes a los verbos modelos que
encontré con todas sus variantes.

La regla "D" genera los participios pasados con sus concordancias de género
y número.

Es decir que si encuentras un verbo que sea completamente irregular en su
conjugación que no esté en el diccionario, con solo agregar la palabra en
el fichero correcto (de acuerdo a su uso o usos: transitivo, intransitivo,
pronominal, etc.) y aplicarle las reglas "XD", casi con seguridad que
obtendrías todas las conjugaciones válidas, salvo que justo la terminación
de ese verbo no sea una de las que se reconoce en la regla "X".

Lo mismo sucede con los verbos regulares (en este caso necesitan al menos
tres banderas: "RED") y con los irregulares de presentes de indicativo y
subjuntivo (banderas "IRD"). Después hay muchas banderas más relacionadas
con verbos, que generan formas derivadas con clíticos de objeto directo,
indirecto o pronombres, por ejemplo "solicitar -> solicítalo". A medida que
se van detectando, se van agregando más banderas en los lemas base.

Saludos,

Santiago

**Comment by edgardorios** [comment]
¡Gracias por tu respuesta Santiago!

Voy a necesitar ponerme a estudiar sobre el tema antes de de proponer algo en este sentido. Te agradezco infinitamente que te hayas tomado el tiempo de enviar una explicación con tanto detalle.

Saludos.
Edgardo

**Comment by sbosio** [comment]
Cierro este issue etiquetándolo por ahora como que no se arreglará. Podrá reabrirse a futuro si alguien tiene tiempo disponible para realizar la duplicación de las reglas de verbos necesarias para poder eliminar los infinitivos de los lemas correspondientes a verbos exclusivamente pronominales que actualmente no terminan con "se" que sería lo correcto.
