### ISSUE TITLE
Duda sobre prefijo [ex]

### ISSUE THREAD

**Issue by edgardorios** [sbosio/rla-es#117]
Hola:

Tengo instalado el diccionario _es_ES_. Hoy usé el prefijo _ex_ y solo me aceptó como correctas las formas:
_Ex presidente_ y _Ex-presidente_. Pero la forma _Expresidente_ la marca como incorrecta, ¿es esto un error?

Gracias de antemano por su ayuda.

**Comment by sbosio** [comment]
La respuesta es ambigua. Por un lado, la palabra no es reconocida porque el
diccionario no la tiene registrada. Sí registra "ex" y "presidente", pero
no la combinación. Haría falta aplicar la regla de prefijos "w" al lema
"presidente" en el archivo 'NombresComunes.txt'.

Las propuestas de reemplazo que te da la aplicación se deben a dos reglas
de Hunspell que se aplican a las palabras desconocidas para tratar de
obtener un posible reemplazo. Una de las reglas es añadir un espacio entre
las letras (por si el error se produjo porque faltó escribir el espacio
entre dos palabras), la otra es insertar un guion. Si en cualquiera de los
dos casos los dos grupos de caracteres que quedan a un lado y otro del
espacio o el guion son palabras reconocidas, las agrega a la lista de
reemplazos ofrecida. Esto no se puede cambiar más que modificando el
comportamiento de Hunspell. Desgraciadamente, en estos casos, pareciera que
"expresidente" es incorrecto (cuando no lo es) y que lo correcto sería "ex
presidente" o "ex-presidente". Hay que recordar que este es un diccionario
ortográfico, y ortográficamente hablando esas dos últimas formas serían
correctas porque son dos palabras correctamente escritas, aunque
gramaticalmente es incorrecto, porque "ex" en este caso funciona como
prefijo y no como sustantivo, y desde 2010 se tiene que escribir pegado a
la palabra que modifica.

La única solución para esto es añadir la bandera "w" al lema original.

Saludos,

Santiago

**Comment by RickieES** [comment]
Esto está relacionado con un _issue_ de los primeros creados aquí en GitHub para este proyecto:

https://github.com/sbosio/rla-es/issues/10

**Comment by edgardorios** [comment]
¡Muchas gracias @sbosio y @RickieES!

Si les parece bien, leeré un poco más a detalle sobre el tema e intentaré añadir un _pull request_ sugiriendo ese cambio para _expresidente_.

Saludos.

**Comment by sbosio** [comment]
Realicé los cambios requeridos.
