### ISSUE TITLE
Solo con tilde

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#122]
Según la RAE http://www.rae.es/consultas/el-adverbio-solo-y-los-pronombres-demostrativos-sin-tilde no tengo claro si _sólo_ con tilde se debería marcar como un error y sacar del diccionario. ¿Cómo lo veis?

**Comment by sbosio** [comment]
Sí, vi hace poco esa misma explicación. Hasta hace no mucho se recomendaba utilizar la versión 'sólo' (como sinónimo de 'únicamente') cuando existía riesgo de anfibología, pero ahora se sugiere eliminar completamente la versión con tilde. Yo la eliminaría del diccionario.

**Comment by sbosio** [comment]
Quizás en vez de eliminarla, podríamos pasarla del fichero 'Adverbios.txt', al 'Adverbios.old' que lista las palabras anticuadas/desusadas.

**Comment by sbosio** [comment]
Realicé los cambios de acuerdo a lo conversado. Cierro el registro.
