### ISSUE TITLE
Agregar el archivo [NombresPropiosSiglas.txt] para [es_MX]

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#123]
Hola, buen día a todos:

¿Sería posible agregar un archivo para nombres propios a [es_MX] de manera que podamos agregar nombres propios usados en México?

ortograf/palabras/noRAE/l10n/es_MX/NombresPropiosSiglas.txt

Gracias.
Edgardo

**Comment by sbosio** [comment]
Sí Edgardo. Cualquier archivo que añadas en ese directorio que tenga extensión '.txt' será incluido al compilar el diccionario. El nombre que se le da al archivo no es relevante para la herramienta de compilación, únicamente lo utilizamos a efectos de organizar los lemas por categoría gramatical.

**Comment by EdgardoRios** [comment]
Gracias Santiago. Si necesito de su apoyo, se los haré saber.

**Comment by sbosio** [comment]
Edgardo, ya integré el «pull request» que enviaste. Si no crees que sean necesarias más modificaciones puedes cerrar este registro para que no quede pendiente.

**Comment by EdgardoRios** [comment]
¡Muchas gracias!
