### ISSUE TITLE
Subir diccionario corrector a Mozilla Add-ons [es_MX]

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#126]
Hola, buen día:

¿Me pudieran por favor ayudar a revisar si le hace falta algo al diccionario corrector que acabo de generar para [es_MX]?

He estado trabajando junto con otros miembros de la Comunidad Mozilla México y nuestra intención es subirlo a Mozilla Add-ons tan pronto como esté listo.

Saludos.
Edgardo

[spellcheck-es-MX-0.0.3.zip](https://github.com/sbosio/rla-es/files/1188277/spellcheck-es-MX-0.0.3.zip)

**Comment by RickieES** [comment]
No lo he instalado, pero he examinado el contenido del XPI y parece estar todo. Entiendo que vosotros ya lo habéis probado.

Eso sí, corrígeme si me equivoco, pero creo que os falta una tilde en cada México, dentro de install.rdf. :smile:

**Comment by EdgardoRios** [comment]
Gracias. Efectivamente ya lo hemos probado y todo parece estar bien.

En cuanto a la tilde, lo corregiré antes de subirlo a Mozilla Add-ons. 😄

**Comment by EdgardoRios** [comment]
El día de hoy acabamos de subir la primera versión del diccionario corrector [es_MX] a Mozilla Add-ons. Si todo va bien, me parece que pronto estaremos listos para informar a toda la comunidad.

¡Gracias por todo su apoyo!
