### ISSUE TITLE
Reglas de reemplazo

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#129]
El fichero de afijos tiene varias reglas de reemplazo REP en las que un error común se sustituyo por su forma correcta de manera automática.

Propongo añadir estas 2 nuevas reglas
REP llendo          yendo
REP dia             día

Por otro lado no tengo claro que vámonos sea un error y se deba sustituir por vayámonos pero mis conocimientos no dan para tenerlo claro. En http://aplica.rae.es/grweb/cgi-bin/v.cgi?i=QewlHdsFqqtCmhcr y https://twitter.com/raeinforma/status/654637042891145216 hablan de ello.

**Comment by sbosio** [comment]
@Almorca: El caso de 'llendo' <-> 'yendo' ya es manejado por las sentencias 'REP ll y' / 'REP y ll', y el caso de 'REP dia día' es manejado por el método de sugerencia normal a través de la sentencia TRY, ya que es el cambio de un único carácter.

La utilidad de las sentencias REP es la de indicarle al algoritmo de sugerencias reemplazos de dos o más caracteres que tienen algún grado de similitud, generalmente fonética, que inducen a cometer errores.

También entiendo yo que puede utilizarse para corregir errores comunes. Tal es el caso de las sentencias 'seci' -> 'cesi' y el de 'vámonos' -> 'vayámonos', pero como bien decís, este último caso lo puse yo porque lo consideraba un error, pero tiene un uso extendido y aceptado, por lo cual convendría eliminar esa regla.

**Comment by sbosio** [comment]
Por otro lado, lo que sí pareciera suceder es que las sugerencias que el algoritmo encuentra a través de la aplicación de una sentencia REP tienen mayor prioridad que las que encuentra al aplicar los reemplazos de la sentencia TRY.

**Comment by RickieES** [comment]
¿Merece la pena mantener este _issue_ abierto?

**Comment by Almorca** [comment]
De lo hablado yo eliminaría del fichero de afijos 
REP vámonos    vayámonos # Error común en el español
y con eso cerraría el issue.

**Comment by olea** [comment]
¿Entonces se puede fusionar la rama https://github.com/sbosio/rla-es/tree/issuse-129 ?

**Comment by Almorca** [comment]
Yo no veo inconveniente y estos días nadie se ha manifestado en contra.

**Comment by olea** [comment]
Fusionado en 43139e027b169060e81e9f6939bfe0dc02e760c8.
