### ISSUE TITLE
Nuevo sufijo para forma enclítica de imperativo con complemento directo e indirecto (p.e.: guárdatelo)

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#13]
En el registro 682 de la Forja de RedIRIS, una de las palabras que se pedían añadir es "guárdatelo". No he encontrado ningún afijo que derive esa forma enclítica de complemento directo e indirecto (que yo considero válido y relativamente habitual). En cambio, la bandera Ï hace eso mismo para las formas 1ª y 3ª (pero no la 2ª, desconozco la razón), aunque no incluía las construcciones para el verbo guardar (que he añadido).

Hay que valorar si procede añadir en esa bandera la 2ª forma singular y plural, o si habría que crear otra bandera.

**Comment by RickieES** [comment]
@sbosio, si tienes tiempo, me gustaría saber si recuerdas algún motivo en especial por el que el enclítico en segunda persona que se comenta aquí no esté en los afijos mientras que los de 1ª y 3ª sí.

Esto puede ser complicado de añadir de todas formas, pero al menos le podríamos echar un vistazo y decidir si añadimos la palabra guárdatelo de manera individual o investigamos más.

**Comment by RickieES** [comment]
Voy a replanificar esto, porque ya no llegamos y no me atrevo a hacer un cambio tan grande sin que lo pensemos bien.

**Comment by sbosio** [comment]
Cerrando el registro como duplicado del #75, ver comentarios en ese registro.
