### ISSUE TITLE
¿Está bien agregar la palabra [Mozilla]?

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#130]
Hola a todos:

Me gustaría agregar la palabra [Mozilla] al diccionario corrector, ¿está bien hacerlo?, de ser así, ¿en donde creen que sea conveniente agregarla?

Saludos.
Edgardo

**Comment by sbosio** [comment]
Creo que convendría hacerlo en el archivo 'noRAE/NombresPropiosSiglas.txt'.

**Comment by EdgardoRios** [comment]
Enterado. Acabo de hacer un "pull request" para que sea agregada.

Saludos y gracias de antemano.
Edgardo

**Comment by edittler** [comment]
Para la próxima vez, en vez de cerrar manualmente este issue, se pueden cerrar los issues desde los pull requests poniendo el texto "fixed #<numero de issue>".

**Comment by EdgardoRios** [comment]
Muchas gracias, intentaré hacerlo de esa manera en la siguiente ocasión.

_Nota: Me parece que es en estas ocasiones en donde un mensajero instantáneo sería de mucha utilidad, aunque tal vez solo para mí. :)_

**Comment by edittler** [comment]
¡No hay drama! Github es una herramienta que tiene muchas funcionalidades y siempre se aprende algo nuevo. Por si te interesa conocer más sobre esa funcionalidad siempre se puede consultar la [documentación](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by EdgardoRios** [comment]
Gracias nuevamente, consultaré la documentación.
