### ISSUE TITLE
Corrector ortográfico en LibreOffice y distribuciones Linux

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#135]
Hola, buen día:

¿Saben si el diccionario corrector desarrollado por este proyecto es usado por defecto en LibreOffice, o bien, en distribuciones Linux como: Debian, Fedora, openSUSE y Ubuntu?

Estuve navegando y encontré algunos enlaces que posiblemente no estén actualizados, o bien, tal vez sea otro corrector ortográfico el que este siendo usado en esos proyectos.

Por ejemplo, en Debian, en la página del paquete [`hunspell-es`](https://packages.debian.org/stretch/hunspell-es) se hace referencia a un "[homepage](https://wiki.documentfoundation.org/Language_support_of_LibreOffice)"; al entrar, encontré un [enlace](http://forja.rediris.es/projects/rla-es/) que me parece pudiera tratarse del sitio que usaba anteriormente este proyecto. De ser así, ¿a quién le podemos pedir ayuda para actualizarlo?

En cuanto a LibreOffice, encontré un enlace que hace referencia a este proyecto. Pero me surgió la duda. Si quiero usar el corrector ortográfico desarrollado por este proyecto en LibreOffice, ¿tengo que instalar la extensión después de instalar LibreOffice en español?, o bien, ¿si estoy instalando LibreOffice en español, vendría ya cargada la [extensión](https://extensions.libreoffice.org/extensions/spanish-dictionaries)?

Saludos.
Edgardo

**Comment by RickieES** [comment]
En cuanto a las distribuciones Linux, no tengo ni idea.

En LibreOffice, como parte del proceso de publicación, tenemos que subir las extensiones al catálogo de extensiones de LibreOffice (su "Mozilla Add-ons"). El problema es que el año pasado hubo muchos problemas con el sitio web de extensiones de LibreOffice, y tardamos (tardé) mucho. Una vez subida la nueva versión al sitio web, se puede hacer algo parecido a un pull-request en el repositorio de LibreOffice para que el binario se descargue ya con el diccionario. Esto último creo que no llegué a hacerlo esta vez.

Por último, en cuanto a OpenOffice, si no recuerdo mal, solo Santiago y JZArecta tenían acceso al catálogo de extensiones, y no sé si se llegó a subir la versión 2.2. No tengo idea de si hay luego un proceso similar para incluir el diccionario como parte de la descarga del binario.

Tanto en LibreOffice como en OpenOffice, el problema añadido es que no hay control estricto sobre quién puede publicar diccionarios como extensiones. Como resultado, si buscas, encontrarás muchas extensiones que son diccionarios correctores ortográficos de español, algunos genéricos y otros de variantes regionales. La mayoría están abandonados, y algunos de los que se mantienen partieron de un fork de RLA-ES sin siquiera dar crédito al proyecto de Santiago, ni mucho menos haber hecho lo que sería correcto, que es integrarse en el proyecto en lugar de duplicarlo.

**Comment by RickieES** [comment]
Cachis, se me olvidaba. :smile: La publicación se documenta en un _issue_:

https://github.com/sbosio/rla-es/issues/79

**Comment by olea** [comment]
> ¿Saben si el diccionario corrector desarrollado por este proyecto es usado por defecto en LibreOffice, o bien, en distribuciones Linux como: Debian, Fedora, openSUSE y Ubuntu?

En Fedora sí porque lo configuré yo :)

En las demás puedes verificar directamente si están usando el hunspell-es correcto. Lo único que te puedes encontrar es que también esté presente la versión ispell/aspell de COES, que fue el primer corrector español pero que siempre prefirió ir más por su cuenta.

A todo esto, estoy convencido (al 80%) de que Libreoffice siempre usará antes (¿o solamente?) hunspell que otra alternativa (en general aspell).

> Por ejemplo, en Debian, en la página del paquete hunspell-es se hace referencia a un "homepage"; al entrar, encontré un enlace que me parece pudiera tratarse del sitio que usaba anteriormente este proyecto. De ser así, ¿a quién le podemos pedir ayuda para actualizarlo?

Se informa en el BTS correspondiente. En Debian https://www.debian.org/Bugs/ o si sabes quién es el responsable del paquete te puedes dirigir directamente o, si es el caso, mandarle directamente el parche de corrección correspondiente.

De hecho me acabas de recordar que en Fedora lo tengo desactualizado...

Y sí, RLA antes se alojaba en la forja de RedIRIS porque pensé., iluso de mi, que una gran institución como esa mantendría un servicio decente :-/

**Comment by olea** [comment]
> Cachis, se me olvidaba. :smile: La publicación se documenta en un issue:
> #79

Lo suyo es que eso estuviera descrito en un texto o en el wiki del proyecto  ¿no? :-m

**Comment by olea** [comment]
> De hecho me acabas de recordar que en Fedora lo tengo desactualizado...

Madre mía, desactualizado pero del todo <facepalm/>

**Comment by EdgardoRios** [comment]
Saludos @RickieES y @olea 

Ayer mandé un correo a una persona que ayuda a mantener **hunspell** en fedora y me parece que ya hizo una [actualización](https://koji.fedoraproject.org/koji/buildinfo?buildID=956466) basado en la [última versión](https://github.com/sbosio/rla-es/releases/download/v2.2/es_ANY.oxt) que está publicada en este sitio.

Por mi parte, estoy investigando si les puedo enviar la versión de español de México `es_MX.oxt` para que también este disponible.

**Comment by olea** [comment]
> Ayer mandé un correo a una persona que ayuda a mantener hunspell en fedora y me parece que ya hizo una actualización basado en la última versión que está publicada en este sitio.

Pues no del todo: https://paste.fedoraproject.org/paste/D4RXP2rF68B1bgmNyfZVJA

Y ahora la pregunta del superdespistado... ¿es la v2.2 la última del todo? Pq no he sabido encontrar aquí en Github dónde se guardan 🙈

> Por mi parte, estoy investigando si les puedo enviar la versión de español de México es_MX.oxt para que también este disponible.

Para todas las cosas de Fedora yo tengo acceso directo. Y, ya puestos, sería para añadir todas las demás variantes. Si me provees la lista busco tiempo para actualizarlo.

**Comment by edittler** [comment]
> Y ahora la pregunta del superdespistado... ¿es la v2.2 la requeteúltima? Pq no he sabido encontrar aquí en Github dónde se guardan 🙈

A menos que un release esté en proceso de construcción, nuestra referencia debería ser la [página de releases del repositorio](https://github.com/sbosio/rla-es/releases). Y la última version es la 2.2.

**Comment by olea** [comment]
> A menos que un release esté en proceso de construcción, nuestra referencia debería ser la página de releases del repositorio. Y la última version es la 2.2.

Gracias majo. Pa la saca.

**Comment by EdgardoRios** [comment]
>Se informa en el BTS correspondiente. En Debian https://www.debian.org/Bugs/ o si sabes quién es el responsable del paquete te puedes dirigir directamente o, si es el caso, mandarle directamente el parche de corrección correspondiente.

Voy a revisar si encuentro a alguien que nos pueda ayudar en Debian.

>Para todas las cosas de Fedora yo tengo acceso directo. Y, ya puestos, sería para añadir todas las demás variantes. Si me provees la lista busco tiempo para actualizarlo.

Excelentes noticias @olea, entonces ya no escribiré nuevamente a esta otra persona. 👍 

Me parece que en el [enlace](https://github.com/sbosio/rla-es/releases) que envió @edittler vienen los archivos de todas las variantes; lástima que la mayoría de mis aportaciones han sido después de que se liberó la versión 2.2   🤓

**Comment by olea** [comment]
> Voy a revisar si encuentro a alguien que nos pueda ayudar en Debian.

Ante la duda, tira directamente del BTS, que para eso está. Ídem con cualquier otra distro o proyecto.

**Comment by RickieES** [comment]
> Lo suyo es que eso estuviera descrito en un texto o en el wiki del proyecto ¿no? :-m

Y así es: :smile: 

https://github.com/sbosio/rla-es/wiki/C%C3%B3mo-publicar-una-nueva-versi%C3%B3n-del-diccionario-RLA-ES

Cada _issue_ de publicación documenta primero lo que queremos alcanzar con la versión (o sea, que _issues_ queremos incluir y en qué plazo aproximado) y, una vez alcanzados, sigue los pasos que figuran en el wiki para hacer la publicación. Si el proceso tiene alguna divergencia con el wiki, se puede documentar primero en el _issue_ hasta que se encuentra la solución, y luego se traslada al wiki.

**Comment by EdgardoRios** [comment]
yo escribí:
>Por ejemplo, en Debian, en la página del paquete <a href="https://packages.debian.org/stretch/hunspell-es"><code>hunspell-es</code></a> se hace referencia a un "<a href="https://wiki.documentfoundation.org/Language_support_of_LibreOffice">homepage</a>"; al entrar, encontré un <a href="http://forja.rediris.es/projects/rla-es/">enlace</a> que me parece pudiera tratarse del sitio que usaba anteriormente este proyecto. De ser así, ¿a quién le podemos pedir ayuda para actualizarlo?

Acabo de actualizar en la Wiki de "The Document Foundation", la página "[Language support of LibreOffice](https://wiki.documentfoundation.org/Language_support_of_LibreOffice)". Pregunté, me dieron acceso, hice el cambio y pues ya está actualizado el enlace que les había comentado.

"Spanish - Spell check dictionaries - Included in bundle ([project website](https://github.com/sbosio/rla-es))"

yo escribí:
>Voy a revisar si encuentro a alguien que nos pueda ayudar en Debian.

@olea escribió:
>Ante la duda, tira directamente del BTS, que para eso está. Ídem con cualquier otra distro o proyecto.

Gracias @olea , en un principio envíe un mensaje a la lista `debian-openoffice@lists.debian.org` pero como aun no he recibido respuesta. Intentaré familiarizarme con el "Bug Tracking System" de Debian y contactarlos desde ahí.

Saludos.

**Comment by EdgardoRios** [comment]
Les comparto la información que he encontrado sobre distribuciones Linux.

**Arch Linux**
Me parece que está usando la [versión 2.2](https://www.archlinux.org/packages/extra/any/hunspell-es/). El proyecto "upstream" está correcto.

**Debian**
El archivo `/usr/share/doc/hunspell-es/changelog.gz` hace referencia a la última versión que pude encontrar publicada en Gerrit ([versión 2.1](https://gerrit.libreoffice.org/#/c/23768/)).

**Fedora**
Encontré un nuevo [enlace](https://src.fedoraproject.org/rpms/hunspell-es) que hace referencia a hunspell-es. Ahí el proyecto "upstream" ya está correcto.

**Gentoo**
Según veo, Gentoo usa una [versión](https://packages.gentoo.org/packages/app-dicts/myspell-es) muy vieja. La referencia al proyecto "upstream" aún apunta a [https://forja.rediris.es/projects/rla-es/](https://forja.rediris.es/projects/rla-es/).

**Ubuntu**
Creo que Ubuntu usa la misma [versión](https://packages.ubuntu.com/artful/hunspell-es) que Debian.

**Comment by olea** [comment]
@EdgardoRios 

> Gracias @olea , en un principio envíe un mensaje a la lista debian-openoffice@lists.debian.org pero como aun no he recibido respuesta. Intentaré familiarizarme con el "Bug Tracking System" de Debian y contactarlos desde ahí.

el contacto probablemente sea el responsable de hunspell-es. y ante la duda donde yo preguntaría es en https://lists.debian.org/debian-l10n-spanish/

yo estoy seguro que en algń momento del pasado hablé con alguien encargado en Debian, pero no consigo recuperar la información.

**Comment by olea** [comment]
@EdgardoRios 

> Les comparto la información que he encontrado sobre distribuciones Linux.
buen trabajo.

Algo que he verificado en Fedora, y que puede que ocurra en las demás, es que los paquetes no estaban usando todos los diccionarios regionales. Para tengo preparado el pull-rquest para la versión 2.3 en cuanto esté lista. Si pudieras verificar que el uso es el adecuado sería maravilloso.

Igualmente son relevantes los usos actuales de los otros recursos ofrecidos, que pueden ser distribuidos desde diferentes paquetes.: hyphen-es y mythes-es.

Por ahora estoy añadiendo estos detalles en https://github.com/sbosio/rla-es/wiki/C%C3%B3mo-publicar-una-nueva-versi%C3%B3n-del-diccionario-RLA-ES#pasos-para-actualizar-distros-linux

Si quieres puedes ampliar la sección con tus datos recopilados.

**Comment by cosmoscalibur** [comment]
@olea , efectivamente en Ubuntu sucede igual (y por ende probablemente en Debian). Cuando se instala `hunspell-es` los diccionarios regionales son enlaces simbólicos al diccionario de España.

**Comment by RickieES** [comment]
Voy a mantener este _issue_ abierto hasta que esté documentado cómo actualizar los correctores ortográficos en las distribuciones de Linux que ha incluido @olea en el wiki.

**Comment by RickieES** [comment]
Por lo que veo, tenemos actualizadas las instrucciones para algunas distribuciones, pero no para las demás. ¿Mantenemos el _issue_ abierto?

**Comment by EdgardoRios** [comment]
Hola @RickieES, buen día:

Me parece que el **issue** pudiera cerrarse. En caso necesario, pudiéramos reabrirlo (o crear otro) en caso de que surja nuevamente la inquietud.

Saludos.
@EdgardoRios

**Comment by RickieES** [comment]
Cerrado queda. :smile:
