### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#136]
Hola:

Encontré un error menor en la Wiki. Es solo el nombre del archivo `make_dict.sh`.

Se los describo a continuación:
- Página: Cómo publicar una nueva versión del diccionario RLA ES
- Apartado: Pasos para generar y subir la extensión a Mozilla Add-ons
- Error: ... con la orden `./make-dict.sh -c -l es-CD`
- Corrección: ... con la orden `./make_dict.sh -c -l es-CD`

¿Está bien hacer ese pequeño cambio?

Saludos.
Edgardo

**Comment by Almorca** [comment]
Arreglado.
