### ISSUE TITLE
Inquietud sobre relación de categoría de palabras y archivo asociado

### ISSUE THREAD

**Issue by cosmoscalibur** [sbosio/rla-es#138]
Buen día.  
Dado que he comenzado con una pequeña lista de colombianismos populares, me he encontrado con una dificultad al clasificar las categorías en sus respectivos archivos.  

+   Si una palabra pertenece a dos categorías, ¿debo ingresar la palabra en los dos archivos? Con la intención de no duplicar es claro que la incluya en una (tal vez arbitrariamente) pero si esto será el insumo del proyecto para corrección de gramática no sería conveniente.  
+   ¿A que corresponde la clasificación de género de los nombres? Observo en las tres versiones palabras que admiten la bandera `G`. En ese sentido, no me es clara la clasificación.  
+   Tampoco me es clara la diferencia del contenido de `NombresComunes` respecto a los archivos de nombres con indicación de género, pues no observo acorde a la RAE una diferenciación en categoría.

**Comment by cosmoscalibur** [comment]
Por el momento, mientras se dan respuestas a estas inquietudes, en la elaboración del _PR_ #137 tuve en cuenta lo siguiente:  

+   Las palabras que pertenecen a más de una categoría las ingrese en la categoría que primero se referencia en el diccionario de referencia para la palabra.  
+   Los archivos de nombres con único género los usé solo para los lemas que solo poseen forma de un solo género efectivamente (por ende tampoco tendrán la bandera `G` a pesar de lo observado en los archivos existentes) y en nombres masculinos-femeninos están los nombres que aceptan variante de género (bandera `G`) o que sirven para ambos géneros sin hacer modificación.  
+   Dado que no comprendo la naturaleza de `NombresComunes` en el directorio RAE (no veo algo común en los lemas respecto a las indicaciones que ofrece la consulta en la RAE), simplemente omito su presencia a la hora de considerar adiciones de lemas de nombres.  

Tengo algunos lemas ya identificados para seguir agregando, pero no me siento cómodo añadiendo ahora sin una revisión previa al _PR_ que luego haga inmanejable su revisión por el tamaño o por posibles cambios cuando se resuelvan las dudas que planteo aquí.

**Comment by sbosio** [comment]
El criterio es añadir las palabra a todos los archivos correspondientes a las distintas funciones gramaticales para sus distintas acepciones. Por ejemplo: "argentino" figura como adjetivo (el gentilicio), como nombre masculino/femenino (porque se usa el gentilicio a su vez como sustantivo), y como nombre masculino (. Ahora veo que hay una nueva acepción como nombre femenino, que no está ingresada, supongo que debe ser algo incorporado en la revisión 23 del DRAE.
