### ISSUE TITLE
Duda sobre inclusión de extranjerismos

### ISSUE THREAD

**Issue by cosmoscalibur** [sbosio/rla-es#139]
Revisando los archivos de palabras he encontrado múltiples extranjerismos incluidos en estos. ¿Puede incluirse un extranjerismo de amplio uso sin ser castellanizado o avalado por una academia? o ¿esos casos son errores?  

Me genera la duda por ejemplo _camping_, _casting_ y _catering_ que están incluidas en `RAE/NombresMasculinos.txt`. Si bien los lemas figuran en la RAE, hay que notar que su inclusión debe ser justamente en letra cursiva pues se esta usando directamente de la lengua extranjera (se puede ver que la RAE lo hace [así](http://dle.rae.es/?id=70iZNTk)). Luego, esto llevaría a una dificultad ya que técnicamente para no ser un error debería no solo escribirse con la correcta ortografía extranjera sino también usar el estilo de letra adecuado.  

Igualmente esta el lema _priori_ (que corresponde a una locución latina y por ende debe tratarse como extranjerismo) que esta en el archivo `RAE/Frases.txt`.  

Referencia: [Los extranjerismos y latinismos crudos (no adaptados) deben escribirse en cursiva](http://www.rae.es/consultas/los-extranjerismos-y-latinismos-crudos-no-adaptados-deben-escribirse-en-cursiva).

**Comment by EdgardoRios** [comment]
Hola:

Desde mi punto de vista, me parece que si los lemas figuran en la RAE, debería estar bien incluirlos dentro del archivo que corresponda. Solo como referencia, acabo de hacer una prueba usando otro corrector ortográfico, es uno que usan las aplicaciones de trabajo, y sí detectó los lemas camping, casting y catering como correctos.

Saludos.
Edgardo

**Comment by cosmoscalibur** [comment]
Hola @EdgardoRios , gracias por tu punto de vista. Entiendo la mención de que se encuentre en la RAE, como también advertí al poner al pregunta, pero justamente la RAE al incluir todas las voces no adaptadas las muestra en cursiva. Y como menciona el enlace (propio de la RAE), no basta con la ortografía correcta para estar bien, sino con el cambio de estilo.  

Si bien mi duda no lleva a discutir en si misma su inclusión, me gustaría plantear la opción de separar las voces no adaptadas en un archivo adicional. Esto podría ser útil para una herramienta posterior que pueda sugerir el cambio de estilo si se detecta como voz no adaptada (se que en el formato de hunspell es posible dejar anotaciones de tipo en los lemas -diferente a los comentarios que se usan aquí en el repositorio-).  

Saludos.

**Comment by Almorca** [comment]
La duda está en si alguien que solo quiere exclusivamente las palabras que aparecen en la RAE va a querer que estas palabras le aparezcan como correctas. Para mí la respuesta es sí.
Yo las añadiría en un nuevo fichero con nombre similar a los que existen pero con un prefijo que puede ser ext_
Por ejemplo: ext_NombresMasculinos.txt

**Comment by RickieES** [comment]
Buff, yo creo que o las tratamos como plenamente integradas, o las tratamos como no reconocidas en el diccionario de la RAE. Separarlas en otros archivos para que sigan apareciendo cuando se genera un diccionario que solo contenga los lemas válidos en el diccionario de la RAE me parece un trabajo improductivo.

Dicho lo cual, mi opinión es que si la RAE los considera extranjerismos, es irrelevante si podemos encontrarlos o no en el diccionario (cosa que sucederá, presumo, bien porque son de uso muy común, bien porque cuentan con una grafía alternativa adaptada plenamente). Tendríamos que considerarlos noRAE en todo caso.

**Comment by cosmoscalibur** [comment]
Hace unos días había preguntado a la RAE si el no poner cursiva en un extranjerismo no adaptado debía considerarse un error.  
[Respuesta por parte del equipo de RAEinforma](https://twitter.com/RAEinforma/status/907945174436892674): Si no se usa el texto en cursiva se debe considerar como un error ortotipográfico.  
Finalmente, es un error que tiene algo de ortográfico. A mi me gusta la idea de @Almorca de crear archivos correspondientes para los extranjerismos.

**Comment by cosmoscalibur** [comment]
Esto se corresponde más a una discusión, y de momento el manejo sería limitar a lemas en español
