### ISSUE TITLE
La definición del sufijo 'N' (terminación -illo, -illa) debería desdoblarse en dos casos según el género

### ISSUE THREAD

**Issue by sbosio** [sbosio/rla-es#14]
El sufijo con bandera '**N**' puede aplicarse a nombres y adjetivos tanto masculinos como femeninos, pero si bien las terminaciones de ciertos lemas en algunos casos diferencian el género, en otros no.
Por ejemplo: el lema _calzón_ (masculino), debe derivarse en _calzoncillo_, que puede lograrse con la regla existente: `SFX N ón        oncillo/S    ón`, pero el lema _canción_ (femenino) tiene la misma terminación y sería derivada incorrectamente como _cancioncillo_, en lugar de _cancioncilla_.
Mi propuesta sería dividir la regla en dos según su género (masculino o femenino), y otra opción sería incluir los lemas directamente, sin reglas de sufijo, pero no creo que sea bueno.
Dejo el problema planteado y me gustaría saber qué opinan otros, para proceder a darle una solución definitiva.

**Comment by RickieES** [comment]
Aunque este _issue_ no esté marcado para la 2.2, le estoy echando un ojo a los archivos que creaste en la rama. Lo que pasa es que esa rama se creó antes de pasar los archivos a UTF-8 y se visualiza mal en el navegador. No recordarás cómo creaste la lista, ¿verdad? Supongo que es con una expresión regular, pero como soy bastante torpe, probablemente me equivoque.

**Comment by Almorca** [comment]
Imagino que la expresión será algo así 
`grep` .*\/.*N.* *.txt
Otra opción es en Firefox ir a Ver -> Codificación de caracteres -> Occidental.

**Comment by RickieES** [comment]
Voy a intentar hacerme cargo de este _issue_. Voy a insertar mi propuesta de regla:

SFX N ción cioncilla/S ción

justo delante de esta:

SFX N ón        oncillo/S    ón

para que se aplique antes en los lemas terminados en ~ción. El cambio se debe hacer en todos los ficheros de afijos, pero creo que voy a comenzar haciéndolo solo en el general y probaré con es_ANY el resultado.

Seguidamente (al cambio en el fichero de afijos general únicamente), tendré que añadir la bandera N  a una selección de lemas que ahora mismo cuentan con el diminutivo añadido como lema independiente, para ver si funciona bien.

Si todo es correcto, añadiré el afijo en el resto de localizaciones y, dependiendo del tamaño de la colección de lemas y de mi tiempo disponible, veré si hago todos los cambios dentro de este _issue_ o si abro varios para ir haciendo el reemplazo paulatinamente.

**Comment by RickieES** [comment]
He hecho la prueba y todo ha funcionado bien, pero al mirar algunos de los lemas terminados en -cilla que preparó @sbosio he visto que no solo las palabras terminadas en -ción son candidatas a aplicar el sufijo, sino que también serían candidatas las terminadas en -sión, como pasión o transgresión.

Tengo que revisar si la regla se puede cambiar de -ción a -ión, o si es mejor dejarla como está y añadir una regla más para -sión.

**Comment by RickieES** [comment]
He estado mirando las palabras terminadas en -ión y he modificado las reglas de la bandera N para dejarlas así:

```
SFX N ión       ioncilla/S   [cglnstx]ión
SFX N ón        oncillo/S    [^i]ón
```
Así pues, palabras como canción, religión, rebelión, opinión, pasión, cuestión o flexión ya pueden recibir la bandera N para generar cancioncilla o cancioncillas, religioncilla, rebelioncilla, etc. Por su parte, camión generará camioncillo y cabrón (con perdón) :smiley: generará cabroncillo.

**Comment by RickieES** [comment]
He buscado lemas terminados en -illo:

```
grep -R -e illo$ | less
grep -R -e illo/G$ | less

```
Y, por increíble que parezca, no he encontrado ningún lema que deba suprimirse y sustituirse por la adición de la bandera N al lema principal. Casi todos son topónimos. Si no tenéis ninguna sugerencia, creo que podríamos dar por cerrado este _issue_.

**Comment by RickieES** [comment]
Lo cierro.
