### ISSUE TITLE
Duda sobre la palabra [reumatoide]

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#140]
¡Hola a todos!

Escribo para solicitar su apoyo, ¿está bien agregar la palabra [reumatoide]?, de ser así, ¿cuál sería el lugar adecuado?

En la RAE encontré lo siguiente:

>reumatoide
>Del gr. ῥεῦμα, -ατος reûma, -atos 'flujo de un humor' y -oide; cf. fr. rhumatoïde.
>artritis reumatoide

>artritis
>Del lat. tardío arthrītis, y este del gr. ἀρθρῖτις arthrîtis, der. de ἄρθρον árthron 'articulación'.
>1. f. Inflamación de las articulaciones.

>artritis reumatoide
>1. f. Med. Enfermedad crónica de las articulaciones, con inflamación de la membrana sinovial y progresiva deformidad de los huesos, especialmente patente en las manos.

Saludos.
Edgardo

**Comment by cosmoscalibur** [comment]
Siguiendo las categorías expuestas por la RAE, debería ser incluida en `NombresFemeninos.txt`, pues hace parte (y funciona como sinónimo) de un sustantivo compuesto femenino.

**Comment by sbosio** [comment]
Esos son los lemas que supuestamente iban en el fichero
"NombresCompuestos.txt". U originalmente era para esos casos, pero sería
bueno que al incluir el lema en esos ficheros, pusiéramos en la línea el
comentario de cuál es el lema compuesto al que pertenece, cosa que yo nunca
hice. Otra cuestión a considerar es que se me ha escapado separarlo en dos
ficheros para la clasificación según géneros.

Por ejemplo, podrías incluir "reumatoide" con el comentario "# artritis
reumatoide" para saber a futuro cuál es el otro sustantivo dentro del
nombre compuesto. En este caso no haría falta añadir "artritis" en una
línea del mismo fichero, ya que tiene entidad propia como nombre femenino y
ya se encuentra en el fichero correspondiente.

2017-08-29 14:23 GMT-03:00 Edward Yesid Villegas Pulgarin <
notifications@github.com>:

**Comment by cosmoscalibur** [comment]
¿ @sbosio cual es tu opinión al respecto de su presencia independiente acompañando otras palabras? Por ejemplo, existe "[factor reumatoide](https://es.wikipedia.org/wiki/Factor_reumatoide)", bajo lo cual "reumatoide" no tiene un significado dependiente de artritis (salvo si solo consideramos su acepción en la RAE).

**Comment by sbosio** [comment]
Es difícil de contestar. Creo que en todos los nombres compuestos uno de
los lemas actúa o tiene en forma independiente la función gramatical de
sustantivo (en este caso "artritis" o "factor") y el otro se asemeja mucho
a un adjetivo calificativo.

No soy lingüista, pero supongo que lo que hace que "reumatoide" no sea un
adjetivo calificativo es el hecho de que no tiene la función de "calificar"
al sustantivo, sino que constituye una subcategoría del mismo, lo tipifica.
Por lo tanto, "artritis reumatoide" o "factor reumatoide" serían ambos
nombres compuestos, solo que uno es reconocido por la RAE y el otro no (o
por lo menos aún no).

**Comment by cosmoscalibur** [comment]
Buen día @EdgardoRios y @sbosio .  
Vuelvo a esta discusión porque no había notado que ya había recibido respuesta de RAEinforma. Acorde a la [respuesta](https://twitter.com/RAEinforma/status/904987097978855425), la palabra 'reumatoide' se considera como un adjetivo, cuyo significado es:  
>semejante al reumatismo o de características clínicas parecidas a las del reumatismo.  

Con esta duda ya aclarada directamente por personal de la RAE, ¿deberíamos mover la palabra a `Adjetivos.txt` o conservarla en compuestos y añadirla como `noRAE/Adjetivos.txt` adicionalmente?

**Comment by EdgardoRios** [comment]
Hola @cosmoscalibur, espero estés muy bien. Una disculpa por no haber contestado antes.

Basado en la respuesta de RAEinforma, me parece que deberíamos dejarla tal como está actualmente, en el archivo `noRAE/Adjetivos.txt`.

Saludos.
Edgardo

**Comment by cosmoscalibur** [comment]
@EdgardoRios la verdad me había parecido ver que ya vos habías agregado la palabra en `RAE/NombresCompuestos.txt` y por eso yo solo la agregué en `noRAE/Adjetivos.txt`. Si es bueno mantener consistencia con cualquier resolución sobre criterios de adición, y en ese sentido me parece lo más prudente que se agregue también en `RAE/NombresCompuestos.txt` tal cual indica una aclaración de @sbosio sobre añadirse a todas las categorías que pertenezca el lema.  
Tal vez no lo pueda hacer rápido pero el primero que tenga tiempo puede añadirlo.
