### ISSUE TITLE
Pegándole

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#141]
Abro un _issue_ con el comentario de @Clefa en https://github.com/sbosio/rla-es/commit/13fb05024c320df824349552858ed3971283deb7#commitcomment-24058619

> 
> hola!. No entiendo mucho esta pagina GitHub. Pero quería dejar esta palabra que parece que no esta incluida
> "pegándole"
> Existe "pegándola" pero no el otro.
> 
> Luego palabras como "**des-**algo"
> ej, "Desequipar" las toma como erróneas.

Nota: _desequipar_ no aparece en la RAE

**Comment by Clefa** [comment]
Muchas cosas no aparecen en la RAE.
(Perdón si estoy posteando en el lugar que no corresponde. En serio no entiendo la interfaz de Github.)
Yo llegue acá porque uso el diccionario Argentino. Por tanto no es sorprendente que la RAE no tenga ciertos regionalismos.
Si este no es el lugar adecuado, te agradecería que me pudieras decir donde se supone que debo hacer la sugerencia.

La palabra **desequipar**, se usa tanto como **desmontar** o **sacar**.
**desestructurar**, **desamontonar**, **deconstruir**. También noto que no están, y me parecen palabras bastante comunes.

**Comment by EdgardoRios** [comment]
Agregué el verbo [deconstruir](https://github.com/sbosio/rla-es/commit/ba69c0ed2f232ef9becac18480d8c823e838ca77) a RAE.

**Comment by RickieES** [comment]
Desequipar, desestructurar y desamontonar no figuran como válidas en el DLE de la RAE. Yo propongo incluirlas en noRAE, porque las veo más o menos comunes.

Desmontar y deconstruir sí están en la RAE, y ambas están ya en RLA-ES (gracias, @EdgardoRios, por deconstruir). :)

**Comment by RickieES** [comment]
Con el fin de poder publicar la versión 2.4 y, como aquí creo que queda tarea por hacer, yo propongo mover este _issue_ al siguiente _milestone_ (temporalmente lo cambiaría a Después y luego a la 2.5). ¿Qué opináis?

**Comment by RickieES** [comment]
Voy a recopilar un poco el contenido de este _issue_, porque estuvimos pasando de una cosa a otra.

Comienzo por el título del _issue_, "pegándole". En la mayoría de sus acepciones, "pegar" es un verbo transitivo, por lo que, para mí, "pegándola" y "pegándolo" contienen un clítico de objeto directo en tercera persona en posición enclítica, y se derivan con la bandera "Ä". En cambio, "pegándole" es un clítico de objeto indirecto, que se deriva con la bandera "Æ". Esta bandera es lo que falta en el verbo "pegar", en VerbosTransitivosIntransitivosPronominales.txt.

En cuanto a desequipar, desestructurar y desamontonar, siguen sin estar incluidas en el DLE de la RAE. Nadie comentó mi proposición de incluirlas en noRAE, así que las voy a incluir.

**Comment by RickieES** [comment]
Y con esto cierro el _issue_.
