### ISSUE TITLE
¿Por qué hay palabras que están en el proyecto lemarios y no están aquí?

### ISSUE THREAD

**Issue by santilin** [sbosio/rla-es#143]
https://github.com/olea/lemarios

Por ejemplo, aaronita y aarónico. 

¿Se podrían mezclar ambos?

**Comment by cosmoscalibur** [comment]
Podrás encontrar muchos lemarios en cualquier parte de la red conteniendo palabras no incluidas en este proyecto (incluso, encontrarás palabras definidas en RAE que aún no aparecen).  
Puedes colaborar migrando las palabras que no encuentres. Ni siquiera el propio autor migra las palabras.  
Supongo que otro tema para vincularlo muy directamente puede ser un tema de licencia (el proyecto de lemas que citas posee una licencia más flexible como te explicó el propio autor olea/lemarios#7 ).

**Comment by santilin** [comment]
Entendido. 

Me gustaría añadir las palabras del lemario del proyecto lemarios a este lemario. Para ello, primero tengo que generar todas las palabras de este proyecto. ¿Cómo lo hago?

**Comment by olea** [comment]
Será que estoy susceptible pero me han molestado las afirmaciones de @cosmoscalibur. Siento que quiere menospreciar un esfuerzo ofrecido en abierto y que costó muchas horas.

> Podrás encontrar muchos lemarios en cualquier parte de la red conteniendo palabras no incluidas en este proyecto 

No hay ningún otro lemario en Internet que contenga _todos_ los lemas del DRAE (hasta la fecha en que fue publicado). Y si lo encuentras es que es derivado de éste.

> (incluso, encontrarás palabras definidas en RAE que aún no aparecen).

El lemario está generado con métodos automáticos de scrapping web que hace tiempo que dejaron de servir. Iniciativas como Dirae se han ocupado de hacer el seguimiento manual para mantener actualizado el listado. Por otro lado no he verificado si Dirae publica su lemario pero sí sé que no han contribuido sus añadidos al lemario original.


> Puedes colaborar migrando las palabras que no encuentres. Ni siquiera el propio autor migra las palabras.

Esto ya sí me hace hervir la sangre. 

Primero que yo no soy autor de nada, sólo he recopilado, que no es poco, pero no me atribuyo autoría que no tengo.

Segundo: haces una afirmación despectiva y despreciable tratando de minusvalorar mi trabajo. Si no te gusta ni lo menciones. Y si te parece que es aprovechable ¿por qué no lo has hecho tú en lugar de pretender ridiculizarme? ¿Por qué necesitas parecer que eres mejor que yo menospreciándome?

Háztelo ver.

> Supongo que otro tema para vincularlo muy directamente puede ser un tema de licencia (el proyecto de lemas que citas posee una licencia más flexible como te explicó el propio autor olea/lemarios#7 ).

No sé a qué te refieres exactamente con vincular. El leitmotiv de mis recopilaciones de palabras es que, si son mínimamente aprovechables, no tengan restricciones de uso, sea en sw libre o propietario, cualesquiera que sea, porque nadie tiene la propiedad sobre las palabras ni sobre la lengua.

Personalmente me hubiera gustado que los recursos RLA-ES mantuvieran unos derechos de explotación estilo CC-0, pero entiendo que el trabajo del proyecto es mayor y no trivial por lo que no he querido sacar la idea a colación y no generar ruido de poca utilidad.

**Comment by olea** [comment]
@santilin 

> Me gustaría añadir las palabras del lemario del proyecto lemarios a este lemario. 

Gracias :-)

> Para ello, primero tengo que generar todas las palabras de este proyecto. ¿Cómo lo hago?

No es tan trivial, por lo menos hacerlo en automático.

- Por un lado habrías descargar la última versión en desarrollo de RLA-ES
- o manualmente o con un script validar los listados de palabras que quieras para descartar las que ya están recogidas
- y, tercero, la que es para mi la parte más laboriosa: codificar en formato hunspell los morfemas derivados de los lemas detectados.

No es imposible pero sí un poco laborioso.

**Comment by sbosio** [comment]
Para generar el listado de palabras que el diccionario acepta como válidas
hay que utilizar la herramienta de desarrollo de Hunspell llamada
'unmunch'. No sé si trabajas sobre plataforma Windows o Linux.

Si se complica mucho, puedo generarlo yo y subirlo en algún lado desde
donde puedas descargarlo.

2017-09-13 3:55 GMT-03:00 santilin <notifications@github.com>:

**Comment by cosmoscalibur** [comment]
Hola @olea, (de paso me disculpo con @santilin y @sbosio , pero dado que acusación por una malinterpretación de Ismael Olea fue pública, me veo en la necesidad de hacer una aclaración igualmente pública -pero si tengo un apunte a la respuesta de Santiago casi al terminar este comentario).  

>Será que estoy susceptible pero me han molestado las afirmaciones de @cosmoscalibur. Siento que quiere menospreciar un esfuerzo ofrecido en abierto y que costó muchas horas.

Yo creo que el punto de partida de toda comunidad que tenga un fin común es partir primero que tal vez uno es susceptible antes de hacer interpretaciones que puedan dejar un mal ambiente en el camino. No menosprecio tu trabajo y de hecho será un insumo valioso para una rutina que estoy iniciando. Comprendo que el proyecto quedo sin actividad por causas ajenas a tu voluntad según leí en alguna discusión del repositorio.  

>No hay ningún otro lemario en Internet que contenga todos los lemas del DRAE (hasta la fecha en que fue publicado). Y si lo encuentras es que es derivado de éste.

Si notas yo nunca incluí la mención a lemas DRAE cuando mencione los otros proyectos (existen lemarios pensados para especialidades, como el incluido en CorrectM cuyas fuentes además de DRAE son diccionarios médicos). Tal vez pueda basarse en el tuyo para la parte DRAE pero como dije, yo no referí a lemas DRAE.  

Adicional a esto, tal vez si estas susceptible aún esto si pueda doler. Pero la afirmación que haces de contener todos los lemas DRAE es falsa. No dudo tu afirmación respecto a contenerlos todos hasta el 30 de diciembre de 2013, que es la última actividad registrada del repositorio, pero todos a la fecha es omitir lo dinámico del lenguaje. Te doy un ejemplo muy sencillo, de una de las palabras agregadas en 2014 a DRAE: [tuit](http://dle.rae.es/?id=asqoMGb). Se verifica rápidamente con `grep -r tuit` que dicho lema no existe en el lemario que recopilaste.  

>Primero que yo no soy autor de nada, sólo he recopilado, que no es poco, pero no me atribuyo autoría que no tengo.

Define DLE la palabra [autor] como "Persona que es causa de algo". Luego, eres el autor de la recopilación (así sea con una técnica automática). Pero si prefieres, hablare de ahora en adelante como recopilador.  

>Segundo: haces una afirmación despectiva y despreciable tratando de minusvalorar mi trabajo. Si no te gusta ni lo menciones. Y si te parece que es aprovechable ¿por qué no lo has hecho tú en lugar de pretender ridiculizarme? ¿Por qué necesitas parecer que eres mejor que yo menospreciándome?

Es tan falso que sea una afirmación despectiva o despreciativa que no citaste nada para afirmar esto. Decir que no lo migres no menosprecia el trabajo que has hecho en tu proyecto. La única razón de mencionarlo, es porque a raíz del RAEDME.md y de una discusión en la que yo estaba vi que participaste, se que sabes de la existencia de este proyecto (como nuevamente se verifica debido a esta participación). Si no supieras de la existencia del proyecto, la mención a que no lo migres no surgiría, pues no es obligación de un recopilador migrar su recopilación a la recopilación de otro recopilador. Incluso, aún conociendo la existencia de la recopilación, no hay obligación de migrarla ni de colaborar. Pero siendo más específico, la mención la hice porque claramente en el `README.md` dice que la idea era ser insumo para este proyecto.  

De hecho, en el siguiente comentario comentas las dificultades existentes, a las cuales hay que añadir que RLA-ES no agrega los lemas como una lista general sino acorde a sus categorías gramaticales y su distribución geográfica de uso. Por ejemplo, si bien [arequipe] existe en tu recopilación, no se puede saber en el lemario que corresponde a un nombre masculino usado en Colombia y Venezuela, y además se detectaría como errónea la formación válida de su plural [arequipes] (soy colombiano). Así que claramente la labor no es trivial, y si lo dice el recopilador que conoce como obtuvo los lemas, debe extenderse a muchos que deberían rehacer parte de la rutina original para hacer la clasificación.  

Así, y dado que esa mención no involucra tu proyecto sino la migración, decir que no lo haces no es un menosprecio ni ridiculización. De hecho, como lo dije al inicio, será un insumo para la rutina que estoy elaborando (espero poderla realizar en un tiempo prudente pero no es trivial y no tengo tanto tiempo para la rutina -me resulta más práctico clasificar y agregar en la medida que vea palabras no detectadas-) que se encargue de clasificar los lemas según localización y categoría gramatical con base a su definición en DLE tras lo cual se verifica si ya existe su lema en el proyecto -claro que lo voy a aprovechar y eso en si mismo ya dice que no considero poco tu aporte, ya que si lo fuera, haría mi propio lemario primero-. Luego, el trabajo manual solo será la validación de las palabras que requieran plural. Tal vez en este punto debo agregar al comentario de @sbosio que no basta con usar `unmunch` pues hay palabras detectadas como correctas no por tener la palabra en la categoría correcta sino porque la palabra coincide con la agregada en otra categoría (y ya fue aclarado por él que una palabra debe agregarse a todas las categorías, cosa que también debe incluirse al revisar este lemario). Debo añadir, nuevamente para @sbosio, que `unmunch` se considera actualmente obsoleto ya que hunspell inicio su propio equivalente que es `wordforms`. De alguna forma, me autoasigno al menos la primera parte que se requiere para este proceso, que es la clasificación de los lemas.  

El tema de licencia @olea, si fue un error de interpretación mio respecto a la comparación de licencias, pero claro, la restricción existente por licencia no va de Lemarios a RLA-ES sino de RLA-ES a Lemarios (claro, el problema es de usar algo de una licencia restrictiva a una con menos restricciones -o sin restricciones como es el caso de Lemarios-).  

Espero @olea sea claro que en ningún momento menosprecie tu proyecto ni trabajo, y que por el contrario valoro el proyecto en su estado actual (con la salvedad que, aunque no fue mi mención inicial sino la malinterpretación tuya, efectivamente no posee todos los lemas DRAE al día de hoy).  

Nuevamente me disculpo con @sbosio y @santilin que les llegue esta notificación, pero era necesaria la aclaración pública, pues de manera pública quedo igualmente la acusación a mi nombre (y al ser público, esto me afecta si solo queda la acusación injustificada).

**Comment by santilin** [comment]
Bueno, por mi parte no tengo nada que aportar a esto. Voy a abrir otra issue con la parte técnica del post.

**Comment by cosmoscalibur** [comment]
Se sigue la parte técnica (esencia inicial) en #146
