### ISSUE TITLE
Pregunta: AumentativosDiminutivos

### ISSUE THREAD

**Issue by cosmoscalibur** [sbosio/rla-es#145]
Hola comunidad.  
Ver comentario sobre [*Actualización (20190828)*](https://github.com/sbosio/rla-es/issues/145#issuecomment-525095518)

Tengo una pregunta respecto a los palabras de carácter apreciativo.  
Observo en el archivo de afijos que existen las banderas `U` (diminutivos) y `H` (aumentativos) pero se hace uso de un archivo adicional `AumentativosDiminutivos.txt` para incluirlos de forma manual en lugar de usar la bandera en el archivo original que aparece el lema base.  
¿En que casos se deben usar las banderas y en que casos incorporarlas directamente al archivo? Si tiene un proceder hacer uso de estas banderas (actualmente no hay lemas que lo usen), observo que no están presentes lo casos de lemas terminados en [nr] pero sería necesario crear banderas adicionales pues se presenta el caso de distinción de género.

**Comment by RickieES** [comment]
Si las banderas derivan bien los términos, yo sería partidario de eliminar las adiciones manuales en AumentativosDiminutivos.txt.

**Comment by RickieES** [comment]
Ya he hecho una prueba y creo que entiendo el problema, lo que no sé es cómo podemos solucionarlo elegantemente.

El primer diminutivo en noRAE/AumentativosDiminutivos.txt es "bajito/GS". Por supuesto, existe "bajo/GS" en RAE/Adjetivos.txt, donde he añadido la bandera U. He generado el archivo del diccionario con el modificador -r para que solo incluya términos de la RAE, y lo he instalado en LibreOffice, donde he escrito "bajito, bajita, bajitos, bajitas".

El resultado ha sido que me marcaba como correctas "bajito" y "bajitos", mientras que seguía marcando como erróneas "bajita" y "bajitas". He añadido entonces la bandera "G" a la regla del afijo que genera el diminutivo para términos acabados en "o", he vuelto a generarlo y he vuelto a probar, pero no ha funcionado. Creo que hunspell solo permite una sola bandera encadenada.

En definitiva, lo que sucede es que, para un lema base (como "bajo"), para obtener los diminutivos hay que aplicar en total hasta tres banderas: diminutivo (U) + plural (S) + femenino (G). No creo que podamos conseguir eso.

**Comment by RickieES** [comment]
> ¿Deberíamos incluir una bandera para diminutivos y aumentativos que admitan los dos géneros y el plural?

El otro día vi que la bandera G está configurada de tal forma que genera no solo el femenino, sino el femenino plural. Por ejemplo, de "bufón" permite derivar "bufona" y "bufonas". Eso funciona porque la bandera G solo se va a aplicar a los lemas que admiten femenino. Sin embargo, si modificamos o añadimos una bandera de diminutivos y aumentativos que admitan los dos géneros y el plural, solo podría aplicarse a lemas que admitan género y número. No lo veo inviable, pero tenemos que pensarlo bien y, sobre todo, tendrían que seguir existiendo banderas que no contemplasen el género.

**Comment by cosmoscalibur** [comment]
Claro @RickieES , ese es el motivo por el cual lo pregunto, porque incluiste "enfermo" y "enferma" como lemas separados para poder formar los diminutivos. Caso que con una bandera extra podría contemplar esos casos, que son muchos también. No se trata de eliminar el caso actual de único género.

**Comment by RickieES** [comment]
Me parece buena idea, pero creo que ya es mejor dejarlo para la próxima versión, así que cambio el _milestone_ a Después.

**Comment by cosmoscalibur** [comment]
Se puede dejar este caso al manejo actual. Tampoco ha sido común los reportes con formas diminutivas y se podrían seguir manejando por separado, y el costo de mantenimiento igual sería mejor por lema que hacer las modificaciones a todos los archivos de afijos.
