### ISSUE TITLE
Proyecto freeling

### ISSUE THREAD

**Issue by santilin** [sbosio/rla-es#147]
¿Conocéis el proyecto [FreeLing](http://nlp.lsi.upc.edu/freeling/node/1) ? 

Me lo he descargado y tienen un fichere de afijos muy parecido al de hunspell:

<code>
            Affixation rules file

 Each line is a affixation rule, with the following fields:

 1 Affix to erase form word form (e.g: gatito - ito = gat)

 2 Affix (* for emtpy string) to add to the resulting root
   to rebuild the lemma that must be searched in dictionary 
   (e.g:  gat+o = gato)

 3 Regexp condition on the parole tag of found dictionary entry

 4 Parole tag for suffixed word (* = keep tag in dictionary entry) 

 5 Check lemma adding accents

 6 Enclitic suffix (special accent behaviour in Spanish)

 7 Prevent later modules from assigning more tags to the word

8 Lemma to assign: any combination of: F,R,L,A,<literal> separated with '+'

                   where: F=original form, R=root found in dict, 

                           L=lemma in matching dict entry, A=affix

                    examples:  A+L=affix+lemma,  R=root,  R+mente= root+"mente"

 9 Consider the suffix always, not only for unknown words.

 10 How to retokenize the word if necessary (see uer manual).

a       *       ^(AQ|NC|VM)     *       0       0       0       A+L     0       -

an      *       ^(AQ|NC|VM)     *       0       0       0       A+L     0       -

</code>

Lo estoy probando porque contiene muchas herramientas para analizar el lenguaje natural.

**Comment by cosmoscalibur** [comment]
Si, conozco el proyecto desde que comencé a mirar las posibilidades de como colaborar con LT (acorde a la sección de LT para el lenguaje español, una de las fuentes de lemas es freeling). ¿Cuál es el punto?

**Comment by santilin** [comment]
El punto es que tienen categorizadas las palabras, de forma que se podría, por ejemplo, sacar el diccionario para openoffice a partir de su lemario.

**Comment by cosmoscalibur** [comment]
Supongo que por el momento, el punto de partida es atacar la generación del lemario actual del DLE, que discutimos en #146 . Ya luego Freeling sería un aporte para el caso noRAE y cuyo validación es otro proceso distinto al requerido para el anterior.

**Comment by olea** [comment]
@santilin 

> El punto es que tienen categorizadas las palabras, de forma que se podría, por ejemplo, sacar el diccionario para openoffice a partir de su lemario

IMO. lo maravilloso podría ser llegar a compartir una misma base de datos común para ambos proyectos. ese es el espíritu de RLA-ES.

problema aparte es si es técnicamente útil, asequible y, sobre todo, quién le daría el cariño.

**Comment by olea** [comment]
Hola:

La colaboración con Freeling podría ser maravillosa, pero hasta que alguien no se ponga manos a la obra cierro el boletín.
