### ISSUE TITLE
Modificaciones al DRAE

### ISSUE THREAD

**Issue by olea** [sbosio/rla-es#15]
Compiladas por Chewie: http://blog.dirae.es/entradas/novedades-drae/

**Comment by cosmoscalibur** [comment]
Para ir adelantando, el reporte 15 tiene pendientes los siguientes lemas (solo RAE): https://gist.github.com/cosmoscalibur/f89526d0432911b4ab57309432c10b0d  
Por la cantidad, dispongo este avance en la revisión de definiciones y categorías para que otros puedan colaborar en la adición. Aún tengo pendiente implementar una rutina que se encargue de la adición masiva.

**Comment by RickieES** [comment]
No veo viable tener esto para la versión 2.5. La lista de palabras es ennoooorme. :worried: ¿Qué opináis?

**Comment by RickieES** [comment]
Cambio el _milestone_ a Después.

**Comment by cosmoscalibur** [comment]
Aprovechando el aporte de @eksperimental con la frecuencia de aparición respecto al corpus de Wikipedia, en 038ad5f hemos logrado una cobertura mayor al 95% de la frecuencia de aparición. ¿Les parece si damos por cerrado el reporte? De paso, aplicar este mismo criterio para las listas de gran tamaño.

**Comment by olea** [comment]
Acabo de ver que Chewie está publicando [lemarios actualizados para cada edición](https://blog.dirae.es/entradas):

- https://dirae.es/static/lemario-23.2.txt
- https://dirae.es/static/lemario-23.3.txt
- y hasta un [lemario ordenado por frecuencia en el CREA](https://dirae.es/static/lemario_frecuencias-20110726.txt)

**Comment by cosmoscalibur** [comment]
Enlace no existe actualmente.
En el histórico del reporte, se logró una cobertura mayor al 95% basado en frecuencia relativa de aparición respecto a corpus de Wikipedia. Se cierra reporte.
