### ISSUE TITLE
Lemas en archivos *.old

### ISSUE THREAD

**Issue by cosmoscalibur** [sbosio/rla-es#156]
Mi inquietud sobre la necesidad de estos archivos la mencioné en #151 y la justificación de los mismos es explicada por @sbosio en #113 .

Desde mi punto veo una dificultad con dichos ficheros. Dado que no se compilan para generar el diccionario, su evaluación e inclusión resulta en un trabajo doble pues a partir del uso diario del corrector no será posible saber que el lema ya fue agregado (y continuamente será revisado por ende).  
Por ejemplo, estoy revisando una lista de lemas personalizada que me facilitaron donde esta el lema [aba] y efectivamente el corrector ortográfico lo muestra como un error, sin embargo el lema se encuentra en `interjecciones.old`. Agregar una opción adicional de compilación sin que esta sea el caso por defecto (como es mencionado en #151 por @sbosio ) lleva a que el usuario final típico (que usará las extensiones oficiales publicadas a través de firefox, libreoffice o de los repositorios linux) no vea finalmente un valor agregado en estos lemas y suponiendo que los reporte como errores el error sería permanente al no ser una opción por defecto en la generación de los diccionarios (y por ende en las versiones publicadas).  
Creería desde ese punto que es necesario definir entre una de las siguientes opciones, ya sea para dar un valor de utilidad a los lemas y facilidad de validación o para reducir el conjunto de archivos y la cantidad de validaciones:  
+   Compilación del diccionario por defecto con los archivos `*.old` y una opción de compilación para su exclusión (esto último opcional).  
+   Definir como regla para el repositorio la exclusión de los lemas que correspondan a arcaísmos (marca _ant._), en desuso (marca _des._) y poco usados (marca _p. us._) con la respectiva eliminación de los archivos `*.old` del repositorio.  
¿Que consideraciones tienen al respecto?

**Comment by sbosio** [comment]
Yo sigo insistiendo en la NO inclusión de los términos anticuados y desusados en forma predeterminado en los diccionarios que se distribuyen para uso público.
El diccionario de corrección ortográfica, como herramienta informática aplicada, y según una definición que alguna vez se nos dio cuando iniciábamos el proyecto, debe ser una recopilación del lenguaje "de uso actual", no una compilación de todos los términos válidos. No es un diccionario "culto", por llamarlo de algún modo, sino uno de "usos y costumbres".
El espíritu del diccionario debe ser el de capturar la mayoría de los errores que se cometen habitualmente al escribir.
Yo supongo que si una persona utiliza en un texto la interjección 'aba', conoce el término y su significado a la perfección e identifica rápidamente que se trata de un término que el diccionario no recoge, por lo cual lo añade a su diccionario personalizado. Pero por otro lado, es más probable que en la mayoría de los casos sea una error de tipeo por "iba", o una omisión de letra como en "daba".
La idea es que el diccionario no deba permitir falsos positivos, es decir reconocer como válidos lemas que no lo son, y que los falsos negativos sean siempre lemas de poco uso, o de usos muy específicos, como por ejemplo términos técnicos de algún área de conocimiento particular.
Para el caso que mencionas, en el que nosotros nos podemos ver obligados a revisar una y otra vez lemas anticuados o desusados, podríamos, como dije en #113 agregar una opción a la herramienta de compilación para incluir los lemas de los archivos .old, y utilizar esos diccionarios para filtrar una lista de palabras contribuidas, evitando tener que revisar todos los términos anticuados o desusados que ya han sido detectados previamente.

**Comment by Almorca** [comment]
Yo estoy de acuerdo con @sbosio

**Comment by cosmoscalibur** [comment]
¿Debe en ese mismo sentido las expresiones de carácter coloquial estar en los ficheros `*.old`?  
Ahora solo se me ocurre el ejemplo de [habemos] asociado a la locución [nos las habemos] (reportado en #59 , no está en DLE pero se explica su uso en DPD -noRAE-), pero si esté fuera agregado conduciría a un error común en la conjugación del verbo [haber].

**Comment by sbosio** [comment]
Creo que debería hacerse un análisis en cada caso.
En primera instancia, las expresiones erróneamente escritas no son algo que pueda resolverse desde el corrector ortográfico, sino que sería tarea de un corrector gramatical.
Luego, lo que queda por decidir es si se añade cada palabra que forma parte de la expresión, y aquí es donde hay que aplicar algún criterio de decisión, cosa que seguramente no es muy trivial, pero ante la duda se puede consensuar en grupo.
Por ejemplo, en este caso puede añadirse 'habemos' a un fichero `.old`, ya que es un arcaísmo. Pero no la añadiría al diccionario porque supongo que debe ser más frecuente el error de usar `habemos` en lugar de `hemos` que el único uso correcto que se da en la expresión.
Si a futuro un corrector gramatical incluye una regla para manejar el caso correcto del término `habemos`, podría añadirse al diccionario para que el corrector ortográfico no la etiquete como error, y sería tarea del corrector gramatical marcar el error cuando el término no aparece asociado a la expresión.
