### ISSUE TITLE
¿Dónde se debe agregar el verbo pronominal [achicopalarse]?

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#157]
Hola, buen día a todos:

Me gustaría agregar el verbo pronominal `achicopalarse` a RAE/l10n (_El Salv., Hond. y Méx._), pero no estoy seguro donde agregarlo. Por lo que entiendo, parece que en ocasiones hay que agregar un pronombre a su conjugación.

```
achicopalarse
1. prnl. El Salv., Hond. y Méx. achicarse (‖ humillarse).
```

Gracias de antemano por su apoyo.

Saludos.
Edgardo

**Comment by cosmoscalibur** [comment]
Hola @EdgardoRios , si observas esto corresponde a un tema gramatical la revisión del pronombre reflexivo antes de la conjugación del verbo. Existe directamente el archivo `VerbosPronominales.txt` para estos verbos y la forma impersonal `-se` ya esta incluida en la bandera `R`. En #116 justamente habías propiciado la aclaración respectiva para estos verbos.

**Comment by sbosio** [comment]
@EdgardoRios: como comentó @cosmoscalibur deberías agregar el verbo `achicopalar` en el archivo `VerbosPronominales.txt`, como mínimo con las banderas `R`, `E` y `D`. Se pueden incluir otras banderas para generar una mayor cantidad de conjugaciones con pronombres en posición enclítica. Las banderas útiles para los pronominales son:
- Bandera `ñ`: genera el infinitivo con pronombre personal reflexivo (p. ej `achicopalarme`).
- Bandera `ò`: genera el gerundio con pronombre personal reflexivo (p. ej. `achicopalándome`).
- Bandera `ô`: genera el imperativo con pronombre personal reflexivo (p. ej. `achicopálate`).
- Bandera `ø`: genera el subjuntivo con pronombre personal reflexivo (p. ej. `achicopálense`).

**Comment by EdgardoRios** [comment]
¡Muchas gracias @cosmoscalibur y @sbosio!

La próxima vez revisaré más a detalle 🙈 😄 .

Saludos.
Edgardo
