### ISSUE TITLE
DLE 23.1

### ISSUE THREAD

**Issue by cosmoscalibur** [sbosio/rla-es#158]
Hola compañeros.  
La RAE ha realizado una actualización a la actual edición en la versión electrónica para considerar. En el siguiente enlace se reseña el cambio y al final hay un enlace de una muestra de cambios. Estos cambios poseen la inclusión de lemas nuevos (algunos ya agregados como noRAE) así como otras modificaciones que no poseen impacto en el proyecto (nuevas acepciones a lemas existentes).  
Deje la referencia a dicha información en este reporte, como recordatorio de la reclasificación de múltiples lemas.  
[La RAE presenta la primera actualización de la 23.ª edición de su DLE](http://www.asale.org/noticias/la-rae-presenta-la-primera-actualizacion-de-la-23a-edicion-de-su-dle).

**Comment by cosmoscalibur** [comment]
Para efecto de seguimiento, dejo referencia de otros reportes relacionados con la adición de lemas nuevos al DLE: #73, #77.

**Comment by jorgesumle** [comment]
Lo ideal sería obtener una lista de todas las palabras de la RAE. ¿Cómo?

Propongo programar un guion que obtenga todas las palabras del diccionario. El diccionario en línea tiene una opción para encontrar las palabras que empiezan por la cadena que introduzcamos. A continuación muestro mi idea de cómo hacerlo en pseudocódigo. Como veréis, el guion tiene que ser recursivo y no basta con descargar el HTML, hay que ejecutar JavaScript porque si no, esa función de «empieza por» de la página del diccionario de la RAE no funciona.

Si queremos tener una lista de todas las palabras que empiezan por «a», escribiremos `https://dle.rae.es/a?m=31` (JavaScript debe estar habilitado). Pero hay un problema, si hay más de 40 palabras que empiezan por esa cadena, solo mostrará las 40 primeras. Por ello, solo podemos afirmar que tenemos la lista de palabras que empiezan por *cadena* completa cuando la página devuelva menos de 40 resultados. Sigamos con el ejemplo de la letra a.

«a» ha devuelto más de 40 resultados, así que tenemos que especificar más, la primera palabra es aba, así que probamos ahora «ab» (https://dle.rae.es/ab?m=31). Sigue mostrando 40 resultados. probamos ahora «aba», también saca más de cuarenta, añadimos esa palabra a nuestro listado porque no podemos refinar más «aba». El segundo resultado es abaá, vamos a buscar a ver (https://dle.rae.es/abaá?m=31), solo muestra un resultado, así que ya tenemos todas las palabras que comienzan por «abaá». Sigamos con el siguiente resultado de la lista de «aba»: «abab». Esta vez hay dos palabras: ababillarse y ababol. Ya tenemos todas las palabras que comienzan por «abab»...

**Comment by olea** [comment]
@jorgesumle las listas de palabras las tenemos:

- desde la vieja lista de 2012 (o antes): https://github.com/olea/lemarios
- a las que está sacando Chewie https://github.com/sbosio/rla-es/issues/15#issuecomment-618645328
  

El problema ahora es el trabajo de procesar y codificar las adiciones. Nada trivial.

**Comment by cosmoscalibur** [comment]
Refuerzo el punto de @olea respecto a la propuesta de @jorgesumle . De hecho, hay una biblioteca Python llamada PyRAE que antes usaba para depurar en las listas masivas, cuales lemas son RAE y cuales no. De ese trabajo, tengo aún una gran cantidad de lemas por agregar, porque el problema es su clasificación y la adición de las banderas adecuadas.

**Comment by olea** [comment]
Creo que esencialmente la idea de este boletín es la misma que la de #15, así que cierro aquí, si nadie tiene inconveniente.
