### ISSUE TITLE
Mover vídeo a es_ES

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#159]
En el _issue_ #100 se añadió la grafía "video", sin tilde, que es la más común en todos los países de habla hispana, excepto en España, donde se usa la grafía y pronunciación con tilde. Sin embargo, no se movió "vídeo" a la variante regional es_ES, de manera que, si bien ha mejorado el diccionario para todos los demás países, porque ya no marcan como incorrecta "video", siguen sin marcar como incorrecta "vídeo".

Estrictamente hablando, solo hace falta mover "vídeo" a es_ES. En la práctica, me gustaría que opináramos todos si situar "video", sin tilde, en el resto de localizaciones, de manera que en la variante es_ES se marque como incorrecta "video" y en todas las demás se marque como incorrecta "vídeo".

**Comment by RGB-es** [comment]
Según el diccionario panhispánico de dudas(1) ambas formas son correctas, si bien se tiene la distribución geográfica que indicas. Quizás en es_ES tenga sentido eliminar **video** ya que la forma **vídeo** es la única utilizada en España, pero en los otros no estoy tan seguro. Yo me inclinaría por dejar ambas como correctas en todos los diccionarios y que sea el usuario el que decida: la forma video es *mayoritaria* en América Latina, no exclusiva. 

(1) http://lema.rae.es/dpd/?key=v%C3%ADdeo

**Comment by cosmoscalibur** [comment]
Creería que esto nos debe llevar a una múltiple adición para "vídeo". Por un lado, como `RLA/l10n/es_ES` dada la respectiva distribución geográfica indicada en el DLE pero además agregarse como `noRAE`dado que el DPD deja claro el uso válido en el resto de regiones (simplemente es minoritario).

**Comment by cosmoscalibur** [comment]
Siguiendo DLE: Se retira 'vídeo' de RAE y se mueve  para RAE/es_ES.
Siguiente DPD: Se agrega 'vídeo' a noRAE.

**Comment by cosmoscalibur** [comment]
Dejo como referencia la respuesta de Fundéu sobre el tema en un [tuit](https://twitter.com/Fundeu/status/979398354777100288). Aclaran que en España se trata de un uso mayoritario de 'vídeo', lo cual implica que 'video' también se puede usar (tal y como se interpreta directamente de la consulta del DLE). Aunque me remiten el enlace del DPD, hay que recordar que su edición es anterior al DLE.

**Comment by RickieES** [comment]
No entiendo lo de añadir "vídeo" a noRAE, si entendemos el DPD como anticuado. Eso supone que, en las ediciones normales del diccionario, la grafía con tilde no se marcaría como errónea en las variantes distintas de es_ES. ¿Lo consideráis correcto?

**Comment by cosmoscalibur** [comment]
Hola @RickieES , entiendo tu duda y aclaro (argumento de una vez en lugar del si o no de la pregunta):  
No se trata de invalidar un recurso de consulta como el DPD. Se trata que si comparamos el DPD con el DLE y encontramos dos versiones diferentes, debe adoptarse la versión del más nuevo (eso no significa precisamente que el otro sea 'anticuado'). Ahora, si el asunto en discusión no es tratado en una de las fuentes, se adopta la única fuente (si es confiable).  
En este caso no pongo en duda el DPD (la propia RAE lo sigue recomendando para la resolución de dudas), pero al tratar el tema si 'vídeo' es la única forma válida en España como lo afirma, el DLE da por sentado en la convención usada que 'video' es de uso general (eso incluye España) y su edición es más reciente. Ahora, respecto al uso de 'video' como única forma válida en el resto de regiones, sabemos que el DLE no recoge todas las opciones, y de allí que el DPD sea el respaldo para decir que 'vídeo' sea noRAE para las demás regiones. No se si es claro ahora el argumento y si hay un contra a lo que expongo.  
Por otro lado, también referí a la respuesta de Fundéu, y es una respuesta de esta semana. Ante mis dudas siempre consulto con ellos como entidad avalada por la RAE y recomendada por ellos para las consultas lingüísticas, y dejan claro que la única diferencia es el uso mayoritario según la región. Siendo así, no veo duda en que ambas formas deben ser reconocidas como correctas sin importar la localización, pero si diferenciar entre RAE y noRAE. ¿Hay consenso en reconocer Fundéu como autoridad para la resolución de dudas, si estas son realizadas directamente por ellos y no en los foros?  
Por último, se puede validar la distribución geográfica en los registros de CORPES XXI y CREA, y ver como la grafía 'vídeo' es extendida también a las demás regiones (incluso su frecuencia normalizada muestra que es comparable el uso en España al de otras regiones).  
Siendo así, debería ser correcto que la versión RAE marqué errónea 'vídeo' pero no la versión 'noRAE' si se usa una localización diferente a es_ES.  
Quedo atento a comentarios para una posible corrección.

**Comment by olea** [comment]
@RickieES 

> No entiendo lo de añadir "vídeo" a noRAE, si entendemos el DPD como anticuado. Eso supone que, en las ediciones normales del diccionario, la grafía con tilde no se marcaría como errónea en las variantes distintas de es_ES. ¿Lo consideráis correcto?

Yo no. Si algo bueno tiene el DRAE es que es de referencia en __toda__ la hispanidad. Si nos hemos propuesto el DRAE como referencia, toda grafía que aprueban debemos reconocerla correcta sin importar quién escriba ni desde dónde. O dicho de otro modo mal y pronto: en mi opinión cualquier localismo que reconoce el DRAE está bien escrito en español, digamos, culto.

Otra cosa es trabajar con los topónimos o, por ejemplo, expresiones populares locales de origen indígena (por buscar un ejemplo extremo), etc, que si no los incluimos en un corrector general es, como yo lo entiendo, por pura eficiencia computacional y no por falta de propiedad o corrección.

**Comment by cosmoscalibur** [comment]
Pero con esto, ya hay muchas cosas que no me quedan claras sobre el proyecto y que podrían hasta explicar porque algo que notaba en los archivos que venían en los repositorios para hunspell-es eran idénticos (lo cual yo pensaba que era un error). Si tenemos versiones localizadas es para que los lemas se corrijan acorde a las regiones, y no para que se corrija considerando acorde a toda la variedad existente.

Si es tal cual indica @olea , solo necesitaríamos directorios regionales para los topónimos, pero no es así la distribución que actualmente tiene el proyecto. O, la discusión la entendió mal.

En este caso el tema es que 'vídeo' en la DLE solo es aceptada como variante de España, por ende iría en 'RAE/es_ES' (si seguimos lo que hay documentado al respecto). ¿Implica esto que debería ser simplemente 'RAE/' sabiendo que no hay más indicación sobre distribución geográfica?

**Comment by olea** [comment]
@cosmoscalibur 

> En este caso el tema es que 'vídeo' en la DLE solo es aceptada como variante de España

http://dle.rae.es/?id=bm7bAH0 :
![](https://i.imgur.com/lBkbb65.png)


¿Me quieres explicar dónde dice la RAE que sólo es aceptada para España?

PS: y por si no queda claro, lo mismo que argumento para una variante española me vale para cualquier americanismo infrecuente en la península.

**Comment by cosmoscalibur** [comment]
Hola @olea y @RickieES , con gusto les explico donde dice.  
Si se remiten a la guía de consulta del diccionario (barra lateral derecha, el símbolo con una interrogación blanca en círculo azul), y van a la sección 5 de la parte de Estructura de un artículo, que corresponde a envíos a otros artículos, encontraran que las entradas con una 'V.' al inicio seguido de un lema destacado en azul, debe seguirse el enlace para ver toda información relacionada a ambas entradas ('V.' significa 'ver').  
Luego, al seguir el enlace podrán apreciar que dice:  

> video
> Tb. vídeo en aceps. 1-4, Esp.

Los lemas correspondientes a variantes secundarias por si solos no representan información sobre distribución geográfica o categoría gramatical, y siempre debe remitirse al artículo al que envía el consultado.  

Igualmente, pueden validar en la versión impresa que el lema 'vídeo' no existe de manera independiente, y que al igual que sucede en la versión digital, se debe tomar su información desde el lema de 'video' que presenta la información de uso regional de la variante esdrújula.  

Aquí no se trata de un punto personal mio y no creo que se trate de puntos argumentados de nuestro parecer, sino de hacer una correspondencia clara de la estructura designada en el proyecto de lemas 'RAE' y 'noRAE' acorde a la información que se obtiene del DLE. Ahora, para hacer una adecuada interpretación de la información contenida, es igual que con cualquier herramienta, antes de crear un debate remitirse al manual de consulta de la herramienta (yo estaba fuera de contexto que era desconocimiento sobre el significado del 'V.' del lema).  

Creo que con esto he aclarado la duda suscitada y que no fue una arbitrariedad de mi parte la manera en que cerré el reporte. Aún así, si hay desacuerdo con esto, lo que veo es una falta de definición sobre el uso adecuado de los lemas 'RAE' y 'noRAE', que hasta donde entiendo, se debe reportar como 'RAE' el uso general o regional tal cual lo indique de manera explícita el DLE, y que no es sujeto de interpretación. Y 'noRAE' es todo aquello que consideremos en uso y que no sea presentado en el DLE (así el lema sea de uso general, si el DLE solo reporta ciertas regiones, las otras deben quedar como 'noRAE').  

Quedo atento a retroalimentación.  
Feliz día.

**Comment by RickieES** [comment]
Creo que @olea y yo estamos defendiendo posturas diferentes, casi contrarias, y responder a ambas a la vez por parte de @cosmoscalibur complica el seguimiento de la cuestión y alcanzar una postura común.

Para mí, el sentido de RAE/l10n/ab_CD es incluir el léxico que, siendo reconocido por la RAE, se limita a un ámbito regional determinado. En este sentido, para el lema que nos ocupa, "video" sin tilde debe estar en RAE y "vídeo" con tilde en RAE/l10n/es_ES, porque así lo establece el DLE, que es la fuente normativa principal. En mi opinión también, solo si en el DLE no se menciona diferenciación regional pero sí se hace en el DPD cabría atender a este. Si entiendo bien a @olea, él no está de acuerdo en esta categorización e incluiría ambas formas en RAE sin diferenciación regional. @cosmoscalibur sí estaría de acuerdo conmigo hasta este punto.

Donde tenemos la discrepancia @cosmoscalibur y yo es en si situar "vídeo" con tilde en noRAE. Él opina que debe añadirse ahí porque el DPD (que no el DLE) dice que la grafía llana se usa mayoritariamente en América Latina (y, por contraposición, la esdrújula se usaría también, aunque minoritariamente). Aunque entiendo su postura, creo que normativamente solo se acepta la forma llana con carácter general e incluir ambas, aunque una sea en noRAE, invalida la corrección ortográfica.

O, dicho de otra forma: si un español, por usar el corrector ortográfico RLA-ES es-ES completo, envía una carta con "video", y alguien le recrimina que ha olvidado la tilde, puede (podemos) usar el DLE para demostrar que la grafía llana es normativamente válida en España. En cambio, si un latinoamericano, por usar el corrector ortográfico RLA-ES es_XX (XX <> ES) completo, envía una carta con "vídeo" con tilde y alguien le recrimina haber usado la tilde, solo puede remitirse (podemos remitirnos) al DPD, que puede ser rebatido con el DLE más reciente y con más validez, o argumentar que se incluye como noRAE porque puede haber alguien que lo use.

Por otro lado, el objetivo de mis comentarios no que nos convenzamos unos a otros, :smiley:  sino conocer si el sentir general, especialmente de quienes van a usar variantes distintas de es_ES con el diccionario completo (incluyendo noRAE), consiste en preferir que "vídeo" con tilde se marque como correcta o incorrecta.

**Comment by cosmoscalibur** [comment]
Hola @RickieES , debo confesar que hasta yo estoy enredado, porque efectivamente veo que aquí se está hablando de dos temas distintos. Pero vamos al punto para dejar lo antes posible el reporte con solución definitiva.  

De los 3 cambios reflejados en el repositorio para este reporte, estamos de acuerdo en dos de ellos.  

Si lo que deseas es conocer el sentir (bueno, igual, eso significa al final que igual hay que 'convencer' indirectamente porque de otra forma no es posible tomar una decisión definitiva), en mi caso, como colombiano, no tengo problema con el uso de la versión completa que indique 'vídeo' como válida y ante las recriminaciones ortográficas de otros, tengo el soporte no solo del DPD sino de respuestas dadas por dos entidades que son autoridades del tema (siendo una justo la RAE). Y bueno, omitir como referencia el DPD además, deja un tema no muy claro sobre lo que es una fuente válida para los lemas noRAE y no creo que ante el DPD un usuario se atreva a negar su validez (si uno duda del DPD, se puede remitir a las otras obras que menciona la versión digital y buscar si hay cambios, en este caso, no encontrará contradicción). ¿@EdgardoRios desde México que opinión puede aportar al tema?  

Desde lo argumentativo, para el tercer cambio, si el tema se trata de uso, me parece que ver las métricas es importante. La frecuencia normalizada del lema 'video' en el CORPES XXI para España es de 7.89 (siendo el puesto 10 en orden usando esta métrica). Si usamos dicha referencia para 'video', contando España, hay en total 13 (de 22 listados) países con frecuencia normalizada superior a 7.89, y como dato curioso, se presenta mayor frecuencia normalizada del lema 'vídeo' en Puerto Rico (71.73 en comparación a 57.46 de España), Estados Unidos que es el tercero posee una frecuencia normalizada de 30.46. En la región Andina la frecuencia normalizada es 18.37. Desde este punto de vista, creo que hay un argumento fuerte para su inclusión y deja ver que no es normativo el uso de 'video' (en acuerdo no solo con el DPD, sino con la respuesta dada por Fundéu y por [RAE](https://twitter.com/RAEinforma/status/981145478657175552) -hoy me remitieron a la misma entrada del DPD-).  

Por otro lado, la existencia de la estructura de 'noRAE' y que sea posible compilar una versión 'RAE' y una versión 'completa', lleva también a un uso responsable por parte del usuario. En ese caso, la descripción de las distintas distribuciones del diccionario deberían aclarar si el compilado usa como fuente solo la versión RAE o si incluye también los lemas noRAE y las advertencias sobre esta última. Y bueno, podríamos definir que el compilado por defecto sea la versión RAE y solo el usuario informado, tenga unas indicaciones de como obtener la versión completa.
