### ISSUE TITLE
Error al ejecutar el script make_dict.sh

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#160]
Al ejecutar:

`herramientas $ ./make_dict.sh -t -c`
`./make_dict.sh: línea 113: ![: no se encontró la orden`
`Creando un diccionario para la localización 'es_AR'...`
 
Y, a partir de ahí, crea todas las variantes correctamente, excepto la genérica, que he creado con `make_dict.sh -c`.

Creo que el error podría ser porque la admiración para negar no puede ir fuera del corchete. He probado esto y funciona:

`  if [ ! -d "../palabras/RAE/l10n/$LOCALIZACION" -a \`
`       ! -d "../palabras/noRAE/l10n/$LOCALIZACION" ]; then`

La corrección, si la veis bien, la subiría con posterioridad a la etiqueta de la versión 2.3, que ya he añadido.

**Comment by cosmoscalibur** [comment]
Hola @RickieES , el error de la línea es por la ausencia del espacio obligatorio después de la negación. Había omitido hacer _commit/push_ de la corrección cuando me encontré con eso la primera vez.

**Comment by RickieES** [comment]
Vamos a dejar el _issue_ abierto para poder asignarle el siguiente _milestone_ cuando lo cree, y así no perdemos la pista de los cambios hechos en cada versión.

**Comment by RickieES** [comment]
Cierro de nuevo el _issue_ ahora que ya está corregido y hay nuevo hito.
