### ISSUE TITLE
Many words missing

### ISSUE THREAD

**Issue by Carmina16** [sbosio/rla-es#161]
I use the es-ANY extension for LibreOffice, and there is just a ton of missing words, such as.

acercársele, apagarlo, audazmente, autoconmiseración, bosquecillo, géiseres, ... , traumático, vocecita.

Are they not in the dictionary or something is wrong with the extension?

**Comment by RickieES** [comment]
The last two, traumático and vocecita, are not reported as wrong in the forthcoming version 2.3 of the extension.

With regards to the others, there are two main points:

1. All but "géiseres" are derivative words, either from verb conjugation (acercársele, apagarlo), adverb terms built with -mente (audazmente) from adjectives, or prefixes or suffixes (autoconmiseración, bosquecillo). These are not built automatically, we need to check every missing word created in this way to add proper flags to the original word. 
1. We don't aim to include every word in the dictionary, just the common ones. All the words you comment will likely fit in the criteria we use, so we will add them (just for the next version, as 2.3 is already being wrapped). Just don't expect that any word will be included; it will simply make the dictionary too big and slow.

**Comment by Carmina16** [comment]
OK, I've made the full list:

```
abrillantamiento
acercársele
advertidlo
afanosamente
ágilmente
apaciguantes
apagafuegos
apagarlo
aplastándola
aprendedlas
arrebatarle
audazmente
autoconmiseración
autocontrol
autoimpuesto
autoproclamado
barriobajero/G
borbotante
bosquecillo
callejuela
casita
cepillarla
cloqueos
clámide
cotilleos
cráteras
culparla
curármelo
depredación
derribándolo
desatarla
descríbela
deshacerlo
deshidratación
deshonrosamente
desopilante
despedazándolos
despertadla
desvaríos
dádmelo
educadamente
elite
enceguecedora
encontradlos
encuéntralo
enfebrecido
enfundarla
engañosamente
entrecortadamente
escupirlo
estratégicamente
exasperante
fajín
forzadamente
gordezuela
gotitas
géiseres
hablarlo
hibiscos
hirviente
impedidlo
imponerles
infaltable
insoportablemente
insubordinación
jenízaros
juntillas
mantenedlas
mantenedlos
metéoslas
montañismo
moverlo
murete
nororiental
nororientales
nítidamente
ocuparlo
ocurrírsele
ordenándole
palmadita/S
palmeándola
pasarle
paternalista
pensativamente
perderla
perderlo
perderlos
pinchándole
piroclástico/GS
quemándolos
relampagueante
relumbrante
relumbrantes
remojón
replantación
respingonas
respondedme
retenedla
retóricamente
reverentemente
revolcón
rufiana
seguirle
semidura
semioculta
semipenumbra
sonrisita/S
sorprendentemente
sueñecito
sufrientes
telepáticamente
tiendecita
traumático/GS
vocecita
```

**Comment by RickieES** [comment]
En este momento, la lista de palabras que sigue siendo marcada como incorrecta es la siguiente:

abrillantamiento
acercársele
advertidlo
ágilmente
apaciguantes
apagarlo
aplastándola
aprendedlas
audazmente
autoconmiseración
autoproclamado
barriobajero/G
borbotante
bosquecillo
cepillarla
culparla
curármelo
derribándolo
desatarla
descríbela
deshacerlo
deshonrosamente
despedazándolos
despertadla
dádmelo
educadamente
encontradlos
encuéntralo
enfebrecido
enfundarla
entrecortadamente
escupirlo
gotitas
hablarlo
hirviente
impedidlo
imponerles
insoportablemente
juntillas
mantenedlas
mantenedlos
metéoslas
murete
ocuparlo
ocurrírsele
ordenándole
palmadita/S
palmeándola
pasarle
pensativamente
pinchándole
quemándolos
relumbrante
relumbrantes
respondedme
retenedla
seguirle
semidura
semioculta
sonrisita/S
sueñecito
sufrientes
telepáticamente
tiendecita
vocecita

He tomado nota de los términos que sí se aceptan ahora como válidos, para el registro de cambios en la versión 2.5. Muevo el _milestone_ a Después.

**Comment by olea** [comment]
Según veo, los dos únicos lemas nuevos que recoge el DLE son:

* barriobajero
* enfebrecido

**Comment by RickieES** [comment]
Aunque solo te aparezcan esos dos lemas, hay muchas formas clíticas y enclíticas de verbos que son válidas y habría que añadirlas. Otras, aunque no aparezcan en el DLE como tales, son adverbios claramente bien formados y otras palabras que son diminutivos también válidos, como sueñecito. Ahora no tenemos tiempo de incluirlos todos (volvemos a lo de siempre, un _issue_ con una lista de 10 palabras es más fácil de resolver que uno con una lista de 30), así que vuelvo a cambiarle el _milestone_ a Después.

**Comment by olea** [comment]
> Aunque solo te aparezcan esos dos lemas, hay muchas formas clíticas y enclíticas de verbos que son válidas y habría que añadirlas.

Ya. Sólo era por ahorrar algo de trabajo. He estado haciendo pruebas para un flujo de trabajo de revisión, pero aún no tengo nada concluyente que poder enseñar.

**Comment by cosmoscalibur** [comment]
Actualización de pendientes

acercársele
advertidlo
apaciguantes
apagarlo
aplastándola
aprendedlas
bosquecillo
cepillarla
culparla
curármelo
derribándolo
desatarla
descríbela
despedazándolos
despertadla
dádmelo
encontradlos
encuéntralo
enfundarla
escupirlo
gotitas
hablarlo
impedidlo
imponerles
mantenedlas
mantenedlos
metéoslas
ocuparlo
ocurrírsele
ordenándole
palmadita
palmeándola
pasarle
pinchándole
quemándolos
relumbrante
relumbrantes
respondedme
retenedla
seguirle
sonrisita
sueñecito
sufrientes
tiendecita
vocecita

**Comment by cosmoscalibur** [comment]
Usando el criterio de listas masivas, se cierra este reporte al cubrir la gran mayoría de lemas. Los casos faltantes no poseen reglas creadas para su derivación. Si estos son de uso común, se abordaría en un nuevo reporte más específico ya que el trabajo requerido implica afectar varios afijos.

acercársele
descríbela
encuéntralo
metéoslas
ocurrírsele
sueñecito
tiendecita
