### ISSUE TITLE
Dirección de la FSF errónea en algunos textos de las licencias

### ISSUE THREAD

**Issue by olea** [sbosio/rla-es#162]
He descubierto que hay dos textos de licencias que refieren a direcciones postales de la FSF obsoletas:

- ortograf/aspell/Copyright
- sinonimos/palabras/COPYING_th_es_ES

Voy a hacer por corregirlo yo mismo, FYI.

**Comment by olea** [comment]
Listo.

**Comment by RickieES** [comment]
Gracias por darte cuenta. Te he asignado el _issue_ y lo he asignado al hito Después, hasta que creemos el 2.4.
