### ISSUE TITLE
¡Saludos a todos!

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#165]
Hola, espero todo vaya bien en su día:

Les escribo para saludarlos y a la vez para pedirles me disculpen por no haber podido participar en las actividades de los últimos meses. Debido a la implementación de la nueva versión de facturación electrónica en México en nuestro ERP, la cantidad de trabajo aumento de forma exponencial y aunque quisiera, de momento me resulta muy difícil participar en las actividades del proyecto.

Espero que hayan tenido felices fiestas y deseo que el 2018 traiga muchas cosas buenas para todos ustedes.

Reciban un abrazo fuerte desde México.

Saludos.
Edgardo

**Comment by RickieES** [comment]
Hola, @EdgardoRios. Este año pasado yo he estado involucrado en la implementación de la factura electrónica de gastos en nuestro ERP también (SAP) y es una lucha intensa, sí, sobre todo si el equipo de implementación no es interno y tiene pisa por cerrar el proyecto para poder facturar horas en lo que resta. Paciencia, y aquí te esperamos cuando tengas hueco.
