### ISSUE TITLE
palabra errada

### ISSUE THREAD

**Issue by JuanCarlosUNAL** [sbosio/rla-es#166]
La palabra **cédula** aparece sin tilde y con tilde, debería ser únicamente con tilde.

**Comment by RGB-es** [comment]
2018-02-18 16:20 GMT+01:00 Juan Carlos Gama <notifications@github.com>:

> La palabra *cédula* aparece sin tilde y con tilde, debería ser únicamente
> con tilde.
>
Cedula, sin tilde, es una conjugación de un verbo poco frecuente: cedular

http://dle.rae.es/?id=86T2Ntm

**Comment by cosmoscalibur** [comment]
Con la aclaración de @RGB-es , este reporte puede cerrarse.
