### ISSUE TITLE
Punto decimal y moneda de El Salvador

### ISSUE THREAD

**Issue by isaalx** [sbosio/rla-es#167]
Buen día,

El punto decimal y la moneda para El Salvador se muestra incorrecto en LibreOffice, la moneda es el dolar estadounidense ($ USD) y la el punto decimal es un punto (.) por consiguiente el separador de miles es una coma (,). 

He buscado como modificar los archivos pero no he encontrado en que lugar se guarda esa información.

Gracias por su colaboración.

**Comment by cosmoscalibur** [comment]
Buen día @isaalx .  
Este repositorio se asocia solo al proyecto del corrector de ortografía y no al proyecto en si de LibreOffice (para futuras referencias).  
Aún así, te dejo la ayuda al respecto: Herramientas >> Opciones >> Configuración de lenguaje >> Lenguajes. Allí podrás configurar lo que menciones.

**Comment by olea** [comment]
Isaalx: no sé cómo se implementa en LO pero sin duda es un error de l10n
pero no sé si del propio LO o de alguna dependencia como glibc.

Cómo te sugieren lo apropiado es reportarlo al menos al proyecto LO.

Ya de paso, si usas Linux, sería conveniente verificar si ocurre en otras
aplicaciones.
