### ISSUE TITLE
Palabras faltantes (revisado 20230816 con diccionario es)

### ISSUE THREAD

**Issue by RAVMN** [sbosio/rla-es#172]
Santander (Marca)
BBVA (Marca)
FayerWayer (Marca)
Sincronización
Expo
Mapocho (Válido solo para es-CL)
Preuniversitario
vehicular
satelital
Anonimizar
interoperabilidad
concecuencial
Anamnesis
Pápula
fístulas
pulsatil
miccional
miccional
Cardiovascular
ortopnea
Deshidratación
Glomerulonefritis
glomérulos
urémico
hipercalcemia
osteoporosis
trombótica
trombocitopénica
Vasculitis
electrolitos
cremaster
Alodinia
ilíaca
hematocrito
hemólisis
reticulocitos
reticulocitario
volemia
biosíntesis
Ingurgitación
Etiología
Exclúyete
díastole
diastólica
sistólico
archívalo
ocultamiento
Cartola
benzodiacepina / benzodiazepina
glicemia (glucemia está en el listado)
trombolisis
Monoplejia / Monoplejía
Tetraplejia / Tetraplejía
Parkinson (nombre propio, para la enfermedad correspondiente)
focalización
meníngeo
cerebrovascular
convalidación

**Comment by cosmoscalibur** [comment]
En el estado actual los lemas "sincronización" y "deshidratación" ya están agregados.

**Comment by RickieES** [comment]
Debido a que la lista de lemas indicados en este _issue_ es muy larga, nadie ha trabajado específicamente en ella y por eso sigue habiendo muchos lemas marcados como erróneos, así que muevo de nuevo el _milestone_ a Después.

**Comment by olea** [comment]
Según el estado actual del proyecto, faltarían estos lemas recogidos en el DLE:

- benzodiacepina
- cerebrovascular
- convalidación
- focalización
- glicemia
- glomérulo
- hematocrito
- hemólisis
- hipercalcemia
- meníngeo
- miccional
- ocultamiento
- osteoporosis
- Parkinson
- sistólico
- urémico
- vehicular
- volemia
