### ISSUE TITLE
[-] Palabra [truhán] con acento ortográfico

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#174]
Buen día:

Encontré que la palabra [truhán] ya no aparece con acento ortográfico en RAE.

```
truhan, na
Del fr. truand.
1. adj. Dicho de una persona: Sinvergüenza, que vive de engaños y estafas. U. t. c. s.
2. adj. Dicho de una persona: Que con bufonadas, gestos, cuentos o patrañas procura divertir y hacer reír. U. t. c. s.
```

![image](https://user-images.githubusercontent.com/18619087/39948173-5aca7186-553a-11e8-9c03-a37fefe870ac.png)

¿Está bien si elimino la variante acentuada?

Saludos.
Edgardo

**Comment by cosmoscalibur** [comment]
Siguiendo algunas discusiones previas, lo ideal es mover `truhán` a la versión `old` del archivo.

**Comment by cosmoscalibur** [comment]
Disculpa, lo había cerrado por error.

**Comment by EdgardoRios** [comment]
> Disculpa, lo había cerrado por error.
No hay problema, gracias.
