### ISSUE TITLE
Diccionario libre de la lengua española

### ISSUE THREAD

**Issue by Adrlopgal** [sbosio/rla-es#175]
Estimados desarrolladores:

Quería agradeceros el enorme esfuerzo que realizáis. Uso vuestras herramientas de corrección ortográfica y de sinónimos a diario en LibreOffice Writer. Me dirijo a vosotros porque tengo entre manos un proyecto ambicioso y no sé a quién acudir para que su realización merezca la pena. Soy escritor y me gustaría haber dado el salto definitivo a un sistema Gnu/Linux libre si no tuviera como impedimento la necesidad de acceder a software privativo para diccionarios como la RAE o el magnífico María Moliner. A mi juicio, existe una carencia bastante grande en cuanto a obras prácticas con una licencia libre. Por ello, me he propuesto escribir uno o más diccionarios completos equivalentes a los que podría editar una editorial y lanzarlos bajo una licencia libre. Allego este asunto porque no quisiera realizar este trabajo de una forma inútil y por la cual sólo sirva después para tener un bonito .pdf; pues no sería tan práctico. 

Así pues, quería preguntar si semejante hazaña contase con apoyos, con la idea en mente de que gente con mayores conocimientos informáticos como vosotros (yo no sé programar...) pudiera convertirlo y adaptarlo como creyese oportuno (p. ej: crear un .dict o integrarlo de alguna manera para ofimática) y que finalmente quede como software libre en beneficio de todos los hablantes.

La idea de enfocarlo a un software se debe principalmente al motivo de que los diccionarios actuales están sujetos a derechos de autor y se priva a los propios hablantes del libre acceso a la cultura. Para el diccionario de la RAE y el María Moliner (imprescindible para un escritor) se requiere uso de software privativo si uno quiere ejecutarlo en su propio ordenador o móvil. Y, en concreto, el de la Academia requiere conexión a internet y está metido en una base de datos ofuscada. Esto supone una seria limitación para gente que, por ejemplo, escribe en una biblioteca con conectividad limitada o nula, además de los riesgos de privacidad. Por otro lado, el María Moliner es un diccionario que supera en algunos puntos al DRAE y es una pena que semejante conocimiento esté en manos de la editorial Gredos (cualquier editorial en sí), la cual sacó hace 10 años una versión digital privativa de este maravilloso diccionario. Aprovecho para mencionar que es una fuente magistral que no recibe la suficiente atención. Hay vocablos en el María Moliner que no se encuentran en la RAE, por no hablar de sus explicaciones de ayuda ortográfica y gramatical para hablantes.

En conclusión, estoy dispuesto a realizar de buena fe un diccionario completo de la lengua española (tarde cuanto tarde) y deseaba saber si otra alma altruista tendría interés en sacar provecho de este material gracias a sus conocimientos informáticos para ponerlo en servicio práctico al ámbito hispanohablante. Huelga añadir que, estando ya aquí, trataré de aportar palabras al diccionario de sinónimos y al corrector ortográfico. Quedo a su disposición mientras esté a mi alcance hacerlo.

Un saludo cordial y gracias por vuestra atención.

**Comment by cosmoscalibur** [comment]
Buen día @Adrlopgal.  
No se en ese sentido, si resulta realmente necesario crear un proyecto independiente o unirse a [wikcionario](https://es.wiktionary.org/wiki/Wikcionario:Portada). Al igual que el DLE dependería de internet pero veo impráctico su uso local (en el caso de un celular o incluso de un computador si es de bajos recursos).  
Aún así, creo que si uno quisiera descargar el contenido de wikcionario es posible legalmente y hacer un software para su consulta sería un valor agregado al proyecto.

**Comment by cosmoscalibur** [comment]
Cierro el reporte por no estar relacionado con el proyecto y no tener respuesta del proponente.
