### ISSUE TITLE
División de palabras

### ISSUE THREAD

**Issue by fca1970** [sbosio/rla-es#178]
Hola,
No se que cambios ha sucedido últimamente pero, desde hace unos meses, me hace mal la división de palabras cuando hay varias consonantes. Algo parecido a lo que ocurría antes con el diccionario en inglés (el cual ahora lo hace mejor).
Por ejemplo, hoy mismo, la palabra "plasticidad" la divide como pla-sticidad en vez de plas-ticidad.
No se si es un problema de falta de términos incluidos en la lista de afijos o qué, pero en versiones más anteriores no hacía eso incluso aunque las palabras no estuvieran en el diccionario. Por ese motivo parece que se deba más al método de dividir que a la lista.

En cualquier caso, gracias por el trabajo de todos los colaboradores.
Paco

**Comment by sbosio** [comment]
Error confirmado, al menos en la versión actual de LibreOffice que poseo con el diccionario regional de Argentina activado. Lo extraño es que la herramienta de la línea de comandos en Python que separa la palabra de acuerdo con las reglas actuales lo hace correctamente y devuelve 'plas-ti-ci-dad'. Voy a tener que investigar un poco más, ya que supuestamente tanto el motor de separación de LibreOffice como el de la herramienta son los mismos y deberían devolver lo mismo.

**Comment by sbosio** [comment]
Ya encontré el problema. Las reglas no están con el formato correcto.

Hemos estado utilizando un diccionario de separación que contiene patrones de separación de sílabas de Tex, obtenidos utilizando la herramienta 'patgen' desde el archivo de entrenamiento etiquetado manualmente, que contiene más de 8.000 lemas etiquetados. Las reglas Tex están correctas, por eso al utilizar la herramienta de la línea de comandos la separación se realiza bien.

El problema es que LibreOffice, y supongo que todo el resto de las herramientas que utilizan librerías de separación silábica, usa 'Libhyphen'. Las reglas Tex deben ser preprocesadas por una herramienta de esta librería para adaptarlas y que funcionen correctamente. Lo confuso es que ambos formatos son muy parecidos, es más Libhyphen procesa las reglas Tex sin indicar ningún error, pero evidentemente no funcionan correctamente en algunos casos.

Voy a realizar algunos cambios en los ficheros, agregar un README en la carpeta para evitar esta confusión mía en el futuro (por si se vuelve a regenerar el archivo de reglas de Tex) y una página al Wiki explicando el proceso de generación.

**Comment by sbosio** [comment]
@fca1970: si te envío un nuevo fichero compilado con la extensión, ¿podrías añadirlo a tu instalación de LibreOffice y comprobar si funciona correctamente? Necesitaría saber qué localización tienes configurada, ¿será la de España?

**Comment by fca1970** [comment]
Claro, mándamelo. Es en la maquina del trabajo. COmo la de casa es más vieja tengo un linux menos actualizado y tampoco he renovado el dic

**Comment by sbosio** [comment]
No se pueden enviar ficheros con extensión OXT por Github, tendría que cambiarle la extensión. Te envío un enlace de Mega. Fíjate si puedes descargarlo, y probarlo. Si todo está bien, subiría la corrección para que esté disponible en la versión 2.4.

El enlace al paquete de extensión: https://mega.nz/#!2khzVIja!RCPXZlYvEJU8qWxx1T1soBjoE9OuXkHyX1V4-7MUWMQ

Saludos

**Comment by Almorca** [comment]
@sbosio @fca1970 ¿Cómo va este tema? ¿Hay que hacer alguna prueba más?

**Comment by sbosio** [comment]
@Almorca, según mis pruebas, el cambio es correcto. Puedo enviar la corrección y cerrar la incidencia, pero no he tenido confirmación de @fca1970.

**Comment by sbosio** [comment]
Cierro esta incidencia con las modificaciones requeridas para solucionar el problema con la separación silábica. Modifiqué partes del fichero README sobre separación silábica para explicar un poco mejor el proceso de generación y evitar futuros errores como el que cometí al generar la versión anterior, donde olvidé realizar el último paso de conversión del formato _Tex_ al de _Hyphen_.
