### ISSUE TITLE
openthes-es ha desaparecido

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#18]
Hace varios meses cerró el proyecto Berlios que era donde estaba alojado el proyecto Openthes-ES. No he encontrado ninguna nueva web que esté alojando el proyecto actualmente por lo que creo que ha desaparecido.
¿Alguien sabe algo?¿Si el proyecto ha desaparecido, lo albergamos dentro del proyecto RLA-ES para darle un mínimo soporte?

P.D. La última versión que he encontrado de la página está en http://web.archive.org/web/20140329072703/http://openthes-es.berlios.de/ de donde creo que se podría rescatar la información del proyecto.

**Comment by olea** [comment]
2015-02-22 13:52 GMT+01:00 Almorca <notifications@github.com>:

> ¿Si el proyecto ha desaparecido, lo albergamos dentro del proyecto RLA-ES
> para darle un mínimo soporte?


go for it!


-- 

Ismael Olea

http://olea.org/diario/

**Comment by RickieES** [comment]
He descargado el último paquete de sinónimos y el último volcado de la base de datos MySQL. Lo que no veo posible es descargar el código fuente de la aplicación web que permitía mantener el diccionario de sinónimos y actualizarlo.

He encontrado uno, pero está en Java+Grails (https://github.com/danielnaber/openthesaurus), por lo que no creo que podamos albergarlo en el servicio de páginas web de GitHub (que confieso que no conozco apenas).

No sé si con "lo albergamos dentro del proyecto RLA-ES" nos referimos a montar la aplicación web para permitir que se sigan añadiendo/actualizando palabras, en cuyo caso nos falta el código PHP, que teniendo la base de datos podría ser algo factible.

**Comment by sbosio** [comment]
Ricardo:

El código del proyecto está disponible en Github. Fue desarrollado por
Daniel Naber, y originalmente se usó para el alemán, y Marcelo Garrone lo
adaptó y lo montó en el sitio de Berlios para el español. El enlace al
código (habría que ver si no hay problemas con las versiones entre el
código actual que debe haber sido actualizado y la versión de la base de
datos) está aquí: https://github.com/danielnaber/openthesaurus.

Disculpen que esté muy desconectado, pero hace unos meses nuestra casa fue
arrasada por un incendio, y perdí no solo la casa, sino a mi esposa y
compañera de toda la vida, Ana, y a dos de los chicos que teníamos en
guarda preadoptiva. Por suerte cuento con una maravillosa familia y muchos
grandes amigos que nos han ayudado y nos siguen acompañando. Mi vida se
reduce básicamente ahora a acompañar a mis otros cinco hijos, y a mantener
la casa. Pero en todo lo que pueda, aunque más no sea darles una mano en
estas cosas, estaré acompañándolos.

Cordiales saludos para todos,

Santiago.


El 28 de febrero de 2015, 18:17, Ricardo Palomares <notifications@github.com

**Comment by RickieES** [comment]
Lo primero de todo, no puedo ni imaginar cómo debes sentirte tras una tragedia así. Mi ánimo más sincero y mi reconocimiento a tu fuerza para seguir adelante.

Parece superficial comentar algo del proyecto por lo insignificante que resulta comparado con la experiencia por la que has pasado. El proyecto parece ser el mismo que había encontrado yo y, por lo que he visto, me temo que el código disponible en GitHub solo es el de la nueva versión en Java+Grails. Al final del readme.md se comenta algo sobre una antigua versión en PHP, pero sospecho que de esa no vamos a encontrar el código fuente.

Para albergar el proyecto con Java+Grails necesitaríamos un alojamiento que admita Java. He estado mirando precios y ya no son tan caros como antes, pero confieso que no he tocado nada de Java en servidores, por lo que si falla algo al seguir las instrucciones de despliegue estaría un poco perdido. Además, se dice que la configuración es un poco inestable y hay que andar reiniciando la JVM de cuando en cuando.

**Comment by olea** [comment]
2015-03-07 13:53 GMT+01:00 Santiago Bosio <notifications@github.com>:

> Disculpen que esté muy desconectado, pero hace unos meses nuestra casa fue
> arrasada por un incendio, y perdí no solo la casa, sino a mi esposa y
> compañera de toda la vida, Ana, y a dos de los chicos que teníamos en
> guarda preadoptiva.
>

¡qué horror!

lo siento muchísimo :-(


-- 

Ismael Olea

http://olea.org/diario/

**Comment by Almorca** [comment]
Mi más sentido pésame Santiago. Mucho ánimo para ti y para tus hijos.

**Comment by RickieES** [comment]
Resulta que la última descarga de SpanishDictionaries.oxt que se puede obtener a través de web.archive.org contiene archivos con fecha de 2011. Aquí en el repositorio Git la fecha de esos archivos es de 2014, pero he mirado en el SVN de Forja y la fecha es 2013, así que están más actualizados que los de web.archive.org.

Así que voy a preparar la versión 0.8 tal y como la tenemos ahora. La siguiente cuestión abierta que tenemos es ¿dónde subimos los OXT? ¿Solo los ponemos disponibles en los catálogos de extensiones de OpenOffice.org y LibreOffice? Es decir, ¿no los hacemos accesibles desde aquí?

**Comment by Jzarecta** [comment]
Lo mejor es tenerlo en los respectivos repositorios. Ahi es donde se hace
referencia desde las respectivos proyectos.

2015-03-08 16:39 GMT-04:00 Ricardo Palomares <notifications@github.com>:

> Resulta que la última descarga de SpanishDictionaries.oxt que se puede
> obtener a través de web.archive.org contiene archivos con fecha de 2011.
> Aquí en el repositorio Git la fecha de esos archivos es de 2014, pero he
> mirado en el SVN de Forja y la fecha es 2013, así que están más
> actualizados que los de web.archive.org.
>
> Así que voy a preparar la versión 0.8 tal y como la tenemos ahora. La
> siguiente cuestión abierta que tenemos es ¿dónde subimos los OXT? ¿Solo los
> ponemos disponibles en los catálogos de extensiones de OpenOffice.org y
> LibreOffice? Es decir, ¿no los hacemos accesibles desde aquí?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbosio/rla-es/issues/18#issuecomment-77772804>.
>



-- 
Alexandro Colorado
Apache OpenOffice Contributor
882C 4389 3C27 E8DF 41B9  5C4C 1DB7 9D1C 7F4C 2614

**Comment by olea** [comment]
> ¿dónde subimos los OXT? ¿Solo los ponemos disponibles en los catálogos de extensiones de OpenOffice.org y LibreOffice? Es decir, ¿no los hacemos accesibles desde aquí?

Si sus antiguos custodios han desaparecido me parece correcto crearles una nueva referencia canónica en RLA-ES. Eso sí: es adecuado avisar al menos a los proyectos principales que los consuman, sobre todo si van a ser actualizados.

**Comment by RickieES** [comment]
Mi pregunta sobre los OXT no debería haber figurado aquí, sino en el issue de la versión 0.8. Ya está resuelto, si vas a la página principal del proyecto y, bajo la línea multicolor que muestra los distintos lenguajes usados en el repositorio haces clic en "Releases" encontrarás la versión 0.8 con sus binarios.

**Comment by RickieES** [comment]
Aunque fui yo el que asignó el milestone para este issue, creo que no debemos hacerlo depender de la versión, al menos de la 0.9. En última instancia, creo que tenemos tres opciones:

- no hacer nada y conservar la misma lista de sinónimos para siempre
- buscar un alojamiento que admita Java e instalar allí la versión actual de openthes, que está en Java+Grails. Yo estoy valorando la idea de tener un alojamiento de ese tipo, así que si al final me decido podría alojarlo. Pero, claro, hablamos de un alojamiento que estría en mis manos únicamente; no sé si eso os parece viable/aceptable.
- Intentar rehacer desde cero la aplicación en PHP, para que sea web, o en otro lenguaje (p.e., Java, que es lo que yo conozco más) para hacer una aplicación de escritorio y que cada uno de nosotros la use en local y suba al repositorio.

En cualquiera de los tres casos, no llegamos a la 0.9 y no veo motivo para demorar la versión.

**Comment by olea** [comment]
Dame más detalles de qué se requiere para alojar esa app. ¿Tienes acceso (y
derecho) al código fuente?

**Comment by RickieES** [comment]
En el [README del proyecto](https://github.com/danielnaber/openthesaurus/blob/master/README) que hemos citado anteriormente en este issue vienen los requisitos para instalar la aplicación, básicamente un Tomcat, por ejemplo.

**Comment by olea** [comment]
Vale. Me confirman que podemos tener alojamiento gratis para la aplicación por unos dos o tres años.

Yo tengo experiencia en sistemas pero nunca he trabajado con apps java. ¿Esperas hacerte cargo de la administración del servicio o busco ayuda externa?

**Comment by RickieES** [comment]
Pues, la verdad, jamás he tocado Java EE. Antes de ofrecerme, tendría que aprender a mantenerlo en local. También digo, ¿esperamos hacer muchas contribuciones a la lista de sinónimos y antónimos? Quizá esto es algo que podemos pensar en resolver a medio plazo, sin ninguna prisa. Tenemos muchas colecciones de palabras para añadirlas al diccionario ortográfico que seguramente mucha gente considera más útil y, sin embargo, no recuerdo, ni aquí ni en la forja de RedIRIS, haber visto ningún bug para añadir sinónimos. Estaría bien ver qué piensa el resto de la gente.

**Comment by olea** [comment]
Bueno, pues por lo pronto mi colega está dispuesto a ver si puede levantar
el servicio y os mantenemos al tanto de lso progresos.


2015-11-15 21:43 GMT+01:00 Ricardo Palomares <notifications@github.com>:

> Pues, la verdad, jamás he tocado Java EE. Antes de ofrecerme, tendría que
> aprender a mantenerlo en local. También digo, ¿esperamos hacer muchas
> contribuciones a la lista de sinónimos y antónimos? Quizá esto es algo que
> podemos pensar en resolver a medio plazo, sin ninguna prisa. Tenemos muchas
> colecciones de palabras para añadirlas al diccionario ortográfico que
> seguramente mucha gente considera más útil y, sin embargo, no recuerdo, ni
> aquí ni en la forja de RedIRIS, haber visto ningún bug para añadir
> sinónimos. Estaría bien ver qué piensa el resto de la gente.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbosio/rla-es/issues/18#issuecomment-156851789>.
>



-- 

Ismael Olea

http://olea.org/diario/

**Comment by RickieES** [comment]
Revisando la lista de _issues_ he visto el que se refiere a Proofing Tool GUI. Lo he descargado y parece que puede trabajar con archivos de sinónimos. Estoy en otro ordenador distinto al que uso para trabajar en RLA-ES y no lo he podido probar en real, pero a lo mejor podríamos atacar directamente los archivos en el repositorio cuando haga falta modificar los sinónimos, sin necesidad de usar la versión Java de OpenThes. Contaré más cuando lo sepa.

**Comment by edittler** [comment]
Parece que el sitio [openthes-es está activo de nuevo](http://openoffice-es.sourceforge.net/thesaurus/). Está [alojado en SourceForge](https://sourceforge.net/projects/openoffice-es/). El proyecto no parece estar actualizado ni activo, cualquier cosa se podría contactarse con Marcelo Garrone cuyo mail aparece en la web.

**Comment by sbosio** [comment]
Probé una vez a ingresar en el enlace y logré ingresar, la segunda vez ya me dio un error 502 (Bad gateway) y no funcionó más. No sé si hay algo que se pueda hacer al respecto.

**Comment by jgmy** [comment]
Hola a todos. 
Tras muchos años , vuelvo a interesarme por este proyecto que en tiempos usaba muy a menudo y me entero de los horribles sucesos acaecidos a su autor.
En el svn de sourceforge señalado por edittler parece seguir el código fuente del proyecto, aunque la base de datos existente parece ser un simple esqueleto. Quizá por eso no funciona la web.
¿Al final alojó alguien este proyecto en su propia web?
Muchas gracias.

**Comment by Almorca** [comment]
Hola @jgmy 
No hubo ninguna novedad y no se avanzó en nada más que lo que ves aquí.

**Comment by cosmoscalibur** [comment]
@sbosio @RickieES @olea , veo que esto es algo que probablemente no tenemos mucha acción y es mejor cerrar, o llevarlo mejor a una discusión (si lo habilitamos, en lugar de un reporte de error)

**Comment by RickieES** [comment]
Yo no veo factible acometer esto en un futuro próximo, la verdad. Si estás esperando tres votos a favor de cerrarlo, ya tienes el mío. :smiley:

**Comment by jgmy** [comment]
Hola a todos.
Cuando hace años voté a favor de integrar openthes con este proyecto,
openthes era la única manera de conseguir sinónimos para libreoffice /
openoffice.
Hoy por hoy, gracias a Copilot, los sinónimos de LibreOffice son mucho
mejores que los de Word.
Además, la inclusión de sinónimos en el DLE ha hecho innecesaria una web
especializada en suministrar sinónimos. Por tanto, estoy a favor de cerrar
la incidencia (aunque no soy un desarrollador).
Saludos, @jgmy.

**Comment by cosmoscalibur** [comment]
Cierre este reporte.
Fuera del alcance del proyecto.
