### ISSUE TITLE
Palabras faltantes

### ISSUE THREAD

**Issue by alexaguiarx** [sbosio/rla-es#182]
Hola, ¿qué tal?

Esta es la primera vez que participo en este proyecto, pero lo he venido siguiendo hace algún tiempo, me parece un proyecto bastante interesante. 

Bueno, quería reportar un par de palabras que no están registradas en la lista actualmente. No sé si hay alguna forma de agregarlas directamente yo. Bueno, en todo caso estás son las palabras:

- **Filántropo**
- **comelón**

Ambas palabras aparecen en el diccionario de la lengua española. La segunda es una variación del adj. comilón usada en varios países de América.

Muchas gracias y espero poder seguir participando en este interesante proyecto.

**Comment by cosmoscalibur** [comment]
También puedes contribuir agregando las palabras: https://github.com/sbosio/rla-es/wiki#proporcionar-un-parche-para-el-repositorio-github
