### ISSUE TITLE
Palabras que faltan en versión 2.3

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#183]
anaeróbico
autorizador
búfer / búferes
ciclables
confírmame
dadle
dinamizadora
enser
esprint
gestionarnos
infladores
medallista
mieses
mitigante
orografía
palmarés
parametría
parametrización
peatonalización
pódium
redistributivas
segurizar
telemática
tiramisú

**Comment by dapgo** [comment]
completitud

**Comment by RickieES** [comment]
Los lemas, orografía, palmarés y tiramisú ya no se marcan como erróneos con el diccionario 2.6. ¿Lo podéis confirmar alguno más, por favor? Esta colección de palabras no es muy larga y podría entrar para la 2.7.

**Comment by RickieES** [comment]
Estoy grabando commits por letra para este _issue_. Al llegar a la c, tengo una duda/problema con el término "confírmame". Si no me equivoco (estoy un poco oxidado), el sufijo que hace falta tocar es este:

SFX Í Y

Pero, claro, yo diría que hay que tocarlo para cada variante regional, porque "confírmame" es válido para es_ES, entre otros, pero en es_AR o es_UY el término correcto sería "confirmame", ¿me equivoco? Y, sin embargo, al ver el sufijo en el fichero de afijos de es_AR, me encuentro esta regla:

SFX Í ablar     áblame   ablar

que derivaría, de "hablar", "háblame", cuando yo entiendo que debería ser "hablame". De nuevo, ¿me equivoco?

**Comment by RickieES** [comment]
Aquí están los commits. Aclaro:

- completitud no me lo marca como erróneo, por lo que ya debía de estar añadido
- confírmame queda pendiente de mi comentario anterior sobre los afijos
- mitigante, parametría y segurizar no se reconocen por la RAE. Mitigante me parece más o menos frecuente, pero los otros dos no. ¿Opiniones? ¿Los buscamos en CORPUS para ver su frecuencia?
- Me asigno el issue, @Almorca

**Comment by cosmoscalibur** [comment]
"parametría" y "segurizar" tampoco los he visto. "mitigante" estoy de acuerdo con agregarlo en noRAE de uso general.

**Comment by Almorca** [comment]
Parametría es bastante común en España en el mundo informático sin embargo la Fundeu parece no verlo muy relevante ( https://www.fundeu.es/consulta/parametro-11199/ ). Segurizar creo que venía a raíz de este artículo ( https://www.fundeu.es/recomendacion/segurizar-securizar-securitizar/ )

**Comment by Almorca** [comment]
He de decir que lo de segurizar, aunque lo recomienda la Fundeu no lo he visto nunca ya que siempre se usa el término securizar.

**Comment by RickieES** [comment]
Yo parametría no lo he oído nunca en mis conversaciones con consultores informáticos en mi trabajo; en cambio, "parametrización" sí. He leído el artículo de Fundeu sobre segurizar y, en realidad, lo que dice de él es que, de lo malo, lo menos malo: mejor segurizar que securizar, pero lo suyo es usar asegurar.

CORPES y CDH, las aplicaciones que nos servían para conocer la frecuencia de uso de un lema, no me funcionan. En Google, "mitigante" ofrece 221.000 resultados, "parametría" 81.500 y "segurizar" 7.020.

Voy a añadir mitigante en noRAE como adjetivo entonces. ¿Cierro luego este _issue_?

**Comment by RickieES** [comment]
Cierro este _issue_ porque he creado el 253 para mirar lo de la bandera Í.
