### ISSUE TITLE
faltan: afijos, superlativos, adverbios

### ISSUE THREAD

**Issue by tomasuribex** [sbosio/rla-es#184]
Estimados amigos:

Os agradezco de entrada vuestro esfuerzo y señalo algunos problemas que he encontrado:

ADVERBIOS EN -MENTE:
alegóricamente
fidedignamente
precedentemente
pretendidamente

SUPERLATIVOS:
abundantísimo
numerosísimas
justísimo
dulcísima
clarísima

AFIJOS:
fijémoslo
saliéndole
retenerle
imponiéndole
respondedme
mandándomelo
sobrepujarnos
contristarte
presentársele
comprenderlo
seguirle
confirmándolo
piénsese
ateniéndonos
habiéndosele
imponerle

OTROS:

los números romanos no son reconocidos
Cf. abreviatura común
Epicuro
Bernabé
Teófilo
catequética
alocuciones
astrológica
cuerpecillos
plugo
estupros

Muchas gracias.

**Comment by RickieES** [comment]
Debido a que la lista de lemas indicados en este _issue_ es muy larga, nadie ha trabajado específicamente en ella y por eso sigue habiendo muchos lemas marcados como erróneos, así que muevo de nuevo el _milestone_ a Después.

**Comment by olea** [comment]
Revisando el listado: lemas nuevos:

- catequético

Lema existente pero forma no reconocida:

- plugo (del verbo [placer](https://dle.rae.es/placer))

El resto ya son -mente y enclíticos.

**Comment by cosmoscalibur** [comment]
Actualización de pendientes

# Afijos
fijémoslo
saliéndole
retenerle
imponiéndole
respondedme
mandándomelo
sobrepujarnos
contristarte
presentársele
comprenderlo
seguirle
confirmándolo
piénsese
ateniéndonos
habiéndosele
imponerle
# Otros
Epicuro
Bernabé
Teófilo
cuerpecillos


Tener presente que *plugo* se agrega a la colección *old* debido a que se reconoce como poco usado.

**Comment by cosmoscalibur** [comment]
Usando el criterio de listas masivas, se cierra este reporte al cubrir la gran mayoría de lemas. Los casos faltantes no poseen reglas creadas para su derivación. Si estos son de uso común, se abordaría en un nuevo reporte más específico ya que el trabajo requerido implica afectar varios afijos.

fijémoslo
presentársele
piénsese
habiéndosele
