### ISSUE TITLE
División de palabras "pro-nto"

### ISSUE THREAD

**Issue by xavi-mat** [sbosio/rla-es#185]
Saludos.
El LibreOffice me divide la palabra pronto de forma equivocada: pro-nto.
¿Se trata de un error que se debe corregir aquí?
(Uso LibreOffice 5.4.6.2 en Ubuntu)

**Comment by RickieES** [comment]
Sí, es parte del proyecto. Creo que, en el fichero https://github.com/sbosio/rla-es/blob/master/separacion/entrenamiento.txt habría que añadir "pron-to" y ver qué tal funciona. El sistema no se basa en dar la lista exacta de separaciones silábicas de todas las palabras, sino en crear patrones de separación, de ahí que a veces falle. Entiendo que, cuantos más ejemplos se den, más precisa será la separación. No obstante, como soy un novato en esta parte, no toco nada de momento, para que puedan verlo otros miembros con más experiencia en este tema.

**Comment by xavi-mat** [comment]
Gracias. He hecho el pull-request. Veremos los que tienen más experiencia si nos dicen si es la forma adecuada de hacerlo.

**Comment by sbosio** [comment]
Este error es un duplicado del problema evaluado en la incidencia #178. Pido que prueben reemplazando el diccionario que estén utilizando actualmente por el que se puede descargar del enlace de MEGA que figura entre los comentarios de dicha incidencia. Yo probé y la separación se hace correctamente con esa versión.
Esa corrección aún no ha sido publicada. Está programada para integrarse en la versión 2.4.
No sería necesario añadir 'pron-to' al listado, ya que el problema es el formato en que se publicaron las reglas en la versión 2.3.

**Comment by xavi-mat** [comment]
Gracias, @sbosio . He probado con el diccionario del enlace MEGA y ahora funciona bien. También la palabra "sorpresa" (sorp-resa), ahora la divide bien (sor-presa)
