### ISSUE TITLE
Palabras no reconocidas que he recopilado en mi diccionario personal (20181228)

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#187]
Mi diccionario personal de SeaMonkey (antes Mozilla Suite, antes Netscape 6 y 7) ha ido acumulando unas pocas palabras a lo largo de 15 años. Acabo de cotejar la lista respecto de lo que será la versión 2.4, y aún quedan unas pocas por añadir, que relaciono aquí:

adjuntarlo (añadir bandera À a adjuntar en VerbosTransitivos.txt)
apocalipsis (añadir a NombresMasculinos.txt, aunque la RAE dice que, a veces, se usa también en femenino)

complementariamente (añadir a noRAE/Adverbios.txt, ya que aún no tenemos bandera para añadir -mente)
Corán (añadir a NombresMasculinos.txt; aunque, estando reconocido por la RAE, no tenemos un archivo RAE/NombresPropios.txt, solo noRAE/NombresPropios.txt)
criptográficamente (añadir a noRAE/Adverbios.txt, ya que aún no tenemos bandera para añadir -mente)

daltónico (añadir a Adjetivos.txt)
discrecionalmente (añadir a noRAE/Adverbios.txt, ya que aún no tenemos bandera para añadir -mente)
distribuible (añadir bandera T a distribuir en VerbosTransitivos.txt)

Érase (añadir a ConjugacionesIrregulares.txt)
ergonomía (añadir a NombresFemeninos.txt)
etiquétanos (añadir bandera Í a VerbosTransitivosPronominales.txt)
exempleado (añadir bandera w a empleado en NombresMasculinos.txt)

florín (añadir a NombresMasculinos.txt)

generalista (añadir a Adjetivos.txt)
Gonzalo (añadir a noRAE/NombresPropiosSiglas.txt)

legaña (añadir a NombresFemeninos.txt)

mediateca (añadir a NombresFemeninos.txt)

paseíto (añadir bandera U a paseo en NombresMasculinos.txt)

rayarlo (añadir bandera À a adjuntar en VerbosTransitivosIntransitivos.txt)
reordenar (añadir bandera p a ordenar en VerbosTransitivosPronominales.txt)

taiwanés (añadir a Adjetivos.txt)
verificable (añadir bandera T a verificar en VerbosTransitivosPronominales.txt)

**Comment by RickieES** [comment]
Añadidos los cambios, con las siguientes diferencias respecto a lo indicado en el primer comentario del _issue_:

- Para que funcione el diminutivo en "paseo" he tenido que añadir una regla más a la bandera U, que es necesario replicar en todos los ficheros de afijos.
- Además de en distribuir, he añadido la bandera T en redistribuir (redistribuible).
- Finalmente he preferido añadir Corán en noRAE/NombresPropiosSiglas.txt, porque sería el único nombre propio en RAE/NombresMasculinos.txt.
- He hecho un par de pequeños cambios estéticos (reordenar algún lema y algunas banderas que no mantenían el orden general).

**Comment by cosmoscalibur** [comment]
@RickieES en el caso de apocalipsis, tal como entiendo lo que ha sido documentado a través de *issues* es aplicar la bandera o archivo, acorde a la acepción. Así, apocalipsis debería ser común y no masculino. Finalmente al ser lema RAE queda sujeto a la clasificación RAE, ¿no te parece?

**Comment by RickieES** [comment]
> @RickieES en el caso de apocalipsis, tal como entiendo lo que ha sido documentado a través de _issues_ es aplicar la bandera o archivo, acorde a la acepción. Así, apocalipsis debería ser común y no masculino. Finalmente al ser lema RAE queda sujeto a la clasificación RAE, ¿no te parece?

Lo puse como masculino porque la RAE lo define como masculino, con la coletilla de que se usa también como femenino (aunque a mí me suena rarísimo "la apocalipsis"). Pero reabro el _issue_ para que más gente pueda opinar. No obstante, de acuerdo a tu página en el wiki sobre clasificación de lemas, llegado el caso procedería moverlo a NombresAmbiguos.txt, no a NombresComunes.txt, ya que no se aplica a personas.

Yo, la verdad, no tengo tan claro que un lema etiquetado con un género masculino en la RAE con la coletilla "u.t.c.f." suponga la validación del uso de ambos géneros por la RAE, en lugar de indicar simplemente que se ha observado su uso en ese otro género. Si indicara lo primero, que se aplica a ambos géneros, lo etiquetaría como "m. o f.", como pasa con "mar", por ejemplo.

**Comment by RickieES** [comment]
He creado el _issue_ para discutir qué hacemos con apocalipsis y, en general, las coletillas de tipo "U.t.c.f.", y así cierro este para poder publicar la 2.4.
