### ISSUE TITLE
Madrid passes 

### ISSUE THREAD

**Issue by traceyad2032** [sbosio/rla-es#189]

**Comment by traceyad2032** [comment]
Madrid passes English spell check, but not Spanish<Mexican> spell check.
Just FYI, No reply necessary.
Thanks, Tracey
rla-es v2.3 Ortografía 2.3 24-02-2013

**Comment by RickieES** [comment]
Madrid is included as a place name (directory named 'toponimos' in 'ortograf/palabras') in the RLA-ES dictionaries only for Colombia and Spain. Could it be you're using another localization?

**Comment by Almorca** [comment]
Pensándolo creo que las capitales de países deberían estar en todos las localizaciones del diccionario. ¿Cómo lo véis?

**Comment by sbosio** [comment]
> Pensándolo creo que las capitales de países deberían estar en todos las localizaciones del diccionario. ¿Cómo lo véis?

Me has quitado las palabras de la boca, jajaja. Pienso lo mismo.

**Comment by traceyad2032** [comment]
Yes I am.
Sorry for the false alarm, Tracey

**Comment by cosmoscalibur** [comment]
Podría ser, en ese sentido, referencia la [lista de países y capitales](http://www.rae.es/diccionario-panhispanico-de-dudas/apendices/paises-y-capitales-con-sus-gentilicios) del diccionario panhispánico de dudas.
