### ISSUE TITLE
¿Es apocalipsis másculino, masculino y femenino, común o ambiguo?

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#190]
A raíz de un comentario en el issue #187, en el que se plantea si apocalipsis es masculino, másculino y femenino, común o ambiguo, en relación con la categorización que hace el DLE, abro este _issue_. Para el DLE, apocalipsis se define así:

>  apocalipsis
> Del lat. tardío apocalypsis, y este del gr. ἀποκάλυψις apokálypsis 'revelación'.
> 1. m. Fin del mundo. U. t. c. f.
> 2. m. Situación catastrófica, ocasionada por agentes naturales o humanos, que evoca la imagen de la destrucción total. Un apocalipsis nuclear. U. t. c. f.

Como veis, el DLE lo define como masculino, con la coletilla de que también se utiliza como femenino (U.t.c.f.). Mi opinión es que es el DLE lo considera masculino, indicando que se usa a veces como femenino, pero no que sea masculino o femenino, común ni ambiguo. Pero solo es mi opinión, y creo que aquí debemos aclararlo.

Pongo el ejemplo de apocalipsis porque es la que ha disparado la cuestión y, como yo la he añadido solo como masculina, el resultado de este _issue_ debe servir para decidir si hay que corregir esa entrada.

**Comment by olea** [comment]
Pues, desde mi ignorancia, nunca he dudado de que se trate de una palabra masculina :-m

**Comment by RickieES** [comment]
Como nadie más se ha pronunciado al respecto, doy por sentado que estamos de acuerdo en que apocalipsis es masculino y que la advertencia "U.t.c.f." en la entrada del DLE, en términos generales, no varía la consideración general del lema como masculino.

**Comment by jbezos** [comment]
Esto es lo que dice el DPD: «Aunque alguna vez se emplea con el género femenino etimológico, es hoy mayoritario y preferible su uso en masculino».
