### ISSUE TITLE
[es_co] No hay suficientes gentilicios de Colombia

### ISSUE THREAD

**Issue by dact221** [sbosio/rla-es#193]
Hola

Probando la versión 2.4 del diccionario en LibreOffice, descubrí que no hay suficientes gentilicios de Colombia. El diccionario reconoce unos pocos como «bogotano», «araucano», «cartagenero», «chocoano». Pero no incluye gentilicios para la mayoría de los municipios y departamentos: «atlanticense», «barranquillero», «antioqueño», «boyacense», «tunjano» y muchos más.

Sería buena idea tomar gentilicios de, al menos, los Anexos 1 y 2 del _Breve Diccionario de Colombianismos_ (BDC) de la Academia Colombiana de la Lengua. Estos dos anexos contienen gentilicios de los departamentos y de las capitales de los departamentos, respectivamente. Cabe notar que el Anexo 3 presenta una lista mucho más larga que incluye municipios menos poblados —aunque creo que es suficiente con solo los otros dos.

El BDC puede encontrarse en la página de la Academia:
www.academiacolombianadelalengua.co/bdc
(Si es necesario, también puede conseguirse en formato PDF).

**Comment by cosmoscalibur** [comment]
Muchas gracias @dact221 . Tengo pendiente la revisión del BDC para los gentilicios. Para la versión 2.5 registrare al menos los casos de municipios más poblados.

**Comment by dact221** [comment]
Creo que hacen un gran trabajo con estos diccionarios. Deseo contribuir al proyecto. ¿Existe alguna tarea con la que pueda ayudar? Tengo más de 5 años de experiencia en sistemas GNU/Linux, además sé programar en Python y Go.

**Comment by Almorca** [comment]
Cuidado con usar el BDC. Imagino que no estará bajo una licencia libre y si es así no tenemos permisos para copiar los lemas de ahí.

**Comment by dact221** [comment]
Estoy intentando contactar a la Academia Colombiana de la Lengua para consultar la licencia.

Los lemas de ese diccionario son solo una recopilación de voces del español hablado en Colombia, no son autoría intelectual de la Academia o sus miembros. Obviamente, no puede decirse lo mismo de las definiciones. Esa es mi opinión, pero igual esperaré respuesta de la Academia. Si no me responden por correo electrónico, intentaré llamar a su sede en Bogotá.

**Comment by cosmoscalibur** [comment]
Tengo la misma consideración que @dact221 , el asunto de licencia para estás obras está asociada a las definiciones y no en si mismo a los lemas. Al ser recolecciones de voces @Almorca , no hay forma alguna de validar que su inclusión fue porque sabíamos los gentilicios, porque se copiaron de alguna fuente, o como hacemos, que se validan los lemas consultando su existencia en las fuentes. Incluso, Wikipedia ha sido usada como fuente de lemas realizando extracción y en su momento tengo entendido que hubo extracción del sitio de la RAE.

**Comment by cosmoscalibur** [comment]
@dact221 para contribuir te recomiendo que leas los artículos de la [wiki](https://github.com/sbosio/rla-es/wiki) primero. Después de eso, cualquier [reporte abierto](https://github.com/sbosio/rla-es/issues) será de gran ayuda. Hay dos reportes en los cuales tengo las listas de lemas con sus definiciones RAE que puedo compartirte y así comenzar a evacuar esos (para contribuir de manera masiva lo más lento es la validación de los lemas).

**Comment by Almorca** [comment]
En España la Ley de propiedad intelectual dice los siguiente:

> Artículo 12. Colecciones. Bases de datos.
> 
> 1. También son objeto de propiedad intelectual, en los términos del Libro I de la presente Ley, las colecciones de obras ajenas, de datos o de otros elementos independientes como las antologías y las bases de datos que por la selección o disposición de sus contenidos constituyan creaciones intelectuales, sin perjuicio, en su caso, de los derechos que pudieran subsistir sobre dichos contenidos.
> 
> La protección reconocida en el presente artículo a estas colecciones se refiere únicamente a su estructura en cuanto forma de expresión de la selección o disposición de sus contenidos, no siendo extensiva a éstos.
> 
> 2. A efectos de la presente Ley, y sin perjuicio de lo dispuesto en el apartado anterior, se consideran bases de datos las colecciones de obras, de datos, o de otros elementos independientes dispuestos de manera sistemática o metódica y accesibles individualmente por medios electrónicos o de otra forma.
> 
> 3. La protección reconocida a las bases de datos en virtud del presente artículo no se aplicará a los programas de ordenador utilizados en la fabricación o en el funcionamiento de bases de datos accesibles por medios electrónicos.

Para mí esto hace que los diccionario de la RAE no sean una fuente válida de dónde obtener listados de palabras ya que estos estarían protegidos por derechos de autor. De ahí que proponga cambiar la licencia de los listados a CC-BY en #195 y usar listado de Wikipedia con los que no tendríamos problemas legales.

**Comment by cosmoscalibur** [comment]
@Almorca sería bueno mover toda discusión sobre la licencia a #195 para dar constancia de los argumentos en donde tiene sentido.
