### ISSUE TITLE
Palabras faltantes

### ISSUE THREAD

**Issue by lcamacho** [sbosio/rla-es#194]
Hola, me acabo de topar con que falta púrpura como adjetivo

**Comment by lcamacho** [comment]
También falta "pulitura" que no aparece en la rae

**Comment by lcamacho** [comment]
Otras palabras "surfactante" y "surfactantes"

**Comment by lcamacho** [comment]
Otra palabra "removedor"

**Comment by lcamacho** [comment]
Otra palabra "salpicará"

**Comment by cosmoscalibur** [comment]
Hola @lcamacho . ¿Me puedes confirmar que localización y versión estás usando? Igualmente, ¿es el complemento de la sección de liberaciones o compilaste el diccionario? Si es compilado, ¿que parámetros indicaste?  
Mi inquietud es porque en mi caso los términos "ángulo", "versátil", y "salpicará" son detectados como válidos.

**Comment by cosmoscalibur** [comment]
@dact221 si como mencionas es un uso regional, es factible agregarlo para la localización es_VE.

**Comment by lcamacho** [comment]
@cosmoscalibur estoy usando la extension para libreoffice version 2.4, descargado directo de la pagina de extensiones de libreoffice, la version de libreoffice es 6.1.4.2

**Comment by RickieES** [comment]
Eso es porque "angulo" es la primera persona singular del presente de indicativo del verbo "angular" (yo angulo, tú angulas, él angula, nosotros angulamos...). :smile: 

Aprovecho para pediros (lo tenemos que actualizar en la wiki) que, por favor, limitéis el número de palabras que indicáis en los _issues_ a un máximo de 10, a menos que vosotros mismos facilitéis la entrada concreta que hay que añadir y en qué archivos. Por ejemplo:

- púrpura en NombresFemeninos.txt y en Adjetivos.txt
- surfactante/S en Adjetivos.txt

etc. Si no os sentís suficientemente seguros para proporcionarnos esa información, entonces limitar el número de palabras en los _issues_ facilita que sean atendidos, ya que no suponen una cantidad demasiado grande de tiempo para los voluntarios. A su vez, eso hace más probable que las palabras aparezcan en la próxima versión del diccionario.

**Comment by dact221** [comment]
> Lo que ocurre es que si por ejemplo escribo "angulo" no me lo reconoce como error, hay algo que estoy haciendo mal? otras palabras si las detecta como errores si las escribo sin tilde

Lo que mencionas técnicamente se clasificaría como un error gramatical. Hunspell no tiene una heurística tan sofisticada como para ofrecer correcciones en esos casos. La diferencia entre «él» y «el» es otro claro ejemplo de la limitación del software. Por lo general, se requiere cierta sensibilidad por parte del usuario en esos casos.

Sin embargo, puedes añadir corrección gramatical a LibreOffice usando [LanguageTool](https://languagetool.org/) (local, vía Java) o [Scribens](https://www.scribens.com/) (en la nube).

P. D.: Microsoft Word ofrece «Angulo» (apellido) y «ángulo» como correcciones para «angulo»; no lo reconoce como conjugación del verbo «angular». Ni siquiera el paquete de ofimática de Microsoft es tan sofisticado.

**Comment by raulsaavedr** [comment]
Hola , tambien falta la palabra verificable/S en Adjetivos.txt

**Comment by RAVMN** [comment]
otras palabras respecto a 2.6 que me han reportado

miniaturización, reportería, implantable, reintervenciones

**Comment by jorgesumle** [comment]
También falta «recepcionar» («Arg., Nic., Perú y Ur.»).

**Comment by RickieES** [comment]
Los siguientes lemas mencionados en este _issue_ están reconocidos actualmente en la versión de desarrollo 2.8:

púrpura, púrpuras
salpicará
versátil, versátiles
ángulo
verificable, verificables

Y siguen marcados como erróneos estos:

surfactante
removedor
hidrofóbico
rin
polipropileno
miniaturización
reportería
implantable
reintervención
recepcionar

Descarto los que no figuren en la RAE. Voy a intentar añadir los que sean correctos.

**Comment by olea** [comment]
Justo estaba probando scripts para filtrar esta lista. A priori estos son los lemas que están en el DLE:

```
hidrofóbico
miniaturización
recepcionar
removedor
rin
surfactante
```

**Comment by RickieES** [comment]
Bueno, implantable no figura en el DLE como tal, pero claramente es una forma derivada de implantar.

Subo un cambio con los términos añadidos en la parte neutra.

**Comment by RickieES** [comment]
En lugar de miniaturización, he añadido minaturizar, con las banderas apropiadas.

**Comment by RickieES** [comment]
Cierro este _issue_ porque ya están añadidos los términos.
