### ISSUE TITLE
Plurales no reconocidas

### ISSUE THREAD

**Issue by Sanipachenko** [sbosio/rla-es#197]
Buenas tardes:
He notado que hay plurales que no son reconocidas como las de las vocales:
aes, es (bueno, en este caso no lo toma como error por ser una conjugación del verbo "ser"), ies, oes y ues. Si bien no son frecuentes en su uso, hay frases en las que se usan en narrativa mayormente que es "poner el punto sobre las ies", referido a ponerle el punto a las letras "i".

**Comment by fitojb** [comment]
Solo quería puntualizar:
> poner el punto sobre las ies

_**í**es_, con tilde porque, pese a ser llana terminada en ese, se pronuncia con hiato.

**Comment by olea** [comment]
@Sanipachenko  ¿puedes indicarnos la región del diccionario que usas?

**Comment by cosmoscalibur** [comment]
Confirmo que respecto a la última versión generada, los plurales de vocales que presentan afectación son: 'íes' y 'oes'.

**Comment by Sanipachenko** [comment]
Perdón, pero estoy más perdido que un político entre gente honesta. Si es algo que reporté, debe ser hace mucho y no recuerdo qué era. ¿Me refrescas?
Y sobre tu pregunta, español Argentina, mayormente.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Ismael Olea<mailto:notifications@github.com>
Enviado: miércoles, 29 de abril de 2020 10:23
Para: sbosio/rla-es<mailto:rla-es@noreply.github.com>
CC: Sanipachenko<mailto:sanipachenko@outlook.com.ar>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [sbosio/rla-es] Plurales no reconocidas (#197)


@Sanipachenko<https://github.com/Sanipachenko> ¿puedes indicarnos la región del diccionario que usas?

**Comment by olea** [comment]
> Perdón, pero estoy más perdido que un político entre gente honesta. Si es algo que reporté, debe ser hace mucho y no recuerdo qué era. ¿Me refrescas? Y sobre tu pregunta, español Argentina, mayormente.

:-)

https://github.com/sbosio/rla-es/issues/197


Tenías el enlace al pie del mensaje ;-)

**Comment by jorgesumle** [comment]
Esto ya fue solucionado (https://github.com/sbosio/rla-es/commit/1f2593b79fb3e37f0a61c6ca0956ce120cb1d7cb), así que se puede cerrar.
