### ISSUE TITLE
Spell check issues: Sólo, Lunes, lunes, centígrado

### ISSUE THREAD

**Issue by traceyad2032** [sbosio/rla-es#198]
Spell check issues: [Sólo, Lunes, lunes, centígrado] are flaged.
Just FYI, Tracey
BTW the other days of the week, month, and seasons check out OK 8-)

**Comment by cosmoscalibur** [comment]
Testing with the addon version 2.4 and LibreOffice 6.0 not reproduce this issue.
What version of the addon was used?

**Comment by traceyad2032** [comment]
v2.3(24-02-2013) downloaded es_es.oxt recently from OpenOffice (LibreOffice
only appears to have the es_all.oxt).
Is there a way I can download es_es.oxt v2.4 given a direct download link?
Please advise.
Thanks, Tracey

**Comment by cosmoscalibur** [comment]
@traceyad2032 https://github.com/sbosio/rla-es/releases/tag/v2.4 . You can download v2.4 from this link.
