### ISSUE TITLE
Reunión presencial durante LibreOffice Conference 2019 (Almería, España)

### ISSUE THREAD

**Issue by olea** [sbosio/rla-es#199]
Hola:

Quería compartiros que este año [LibOCon](https://libocon.org/) tiene lugar en Almería y que soy parte del equipo de organización. Actualmente la [llamada a la participación](https://libocon.org/2019/call-for-papers/) está abierta y me preguntaba si os gustaría realizar la primera reunión presencial de RLA-ES aprovechando la oportunidad. No estoy seguro pero tal vez hasta se pudiera pedir alguna ayuda a la TDF (¿y a Mozilla?) para sufragar gastos de viaje de compañeros al otro lado del Atlántico.

¿Qué os parece?

Ni qué decir tiene que sería un honor ser vuestro anfitrión :-)

**Comment by EdgardoRios** [comment]
Hola, buen día:

Me parece una excelente idea, el único inconveniente que veo es el económico. ¿Alguna idea de a quién pudiéramos acercarnos para preguntar si es posible recibir apoyo para los gastos de viaje?

En caso de no ser posible reunirme con ustedes de forma presencial, me encantaría poder hacerlo al menos por videoconferencia.

¡Saludos a todos!

**Comment by olea** [comment]
> ¿Alguna idea de a quién pudiéramos acercarnos para preguntar si es posible recibir apoyo para los gastos de viaje?

Sí, a la The Document Foundation. Pero antes quería saber la disposición del equipo. 

> En caso de no ser posible reunirme con ustedes de forma presencial, me encantaría poder hacerlo al menos por videoconferencia.

:-)

**Comment by cosmoscalibur** [comment]
Suena interesante si se puede. Si es algo que es posible gestionar con tiempo yo podría solicitar esa semana de vacaciones.

**Comment by olea** [comment]
> Si es algo que es posible gestionar con tiempo yo podría solicitar esa semana de vacaciones.

La propia actividad se puede solicitar ya.

**Comment by olea** [comment]
Se me ocurre que para darle más sustancia todavía al encuentro se podría hacer un pequeño maratón dándole cariño al proyecto (correcciones, añadidos, etc).

**Comment by cosmoscalibur** [comment]
Excelente idea @olea , creo que sería un espacio adecuado incluso para evacuar temas cuya discusión por github dilata demasiado.

**Comment by olea** [comment]
Para hacernos una idea: ¿de dónde vendríais cada uno? Aunque no sé si sería posible costear muchos viajes desde América, dicho desde lo más hondo de mi corazón :-(

**Comment by olea** [comment]
> Para hacernos una idea: ¿de dónde vendríais cada uno? 

Repasando por lo pronto:

- @sbosio, Argentina, aunque no recuerdo la ciudad
- @cosmoscalibur, Medellín
- @EdgardoRios, México ¿DF?
- @RickieES, España, pero no puede asistir por compromisos familiares
- @Almorca, que aún no me ha dicho nada
- y su servilleta @olea, que soy el que menos cuenta porque no hace ni el huevo.

Me imagino que es probable que pudiéramos contar con Caolán McNamara si asiste al congreso por su cuenta, que lleva cosas hunspell en Fedora y LIbreOffice, pero ya le avisaríamos en su caso.

**Comment by EdgardoRios** [comment]
> > Para hacernos una idea: ¿de dónde vendríais cada uno?
> 
> Repasando por lo pronto:
>     * @EdgardoRios, México ¿DF?

De [Monterrey](https://es.wikipedia.org/wiki/Monterrey), Nuevo León, México

**Comment by olea** [comment]
> De Monterrey, Nuevo León, México

Perfecto. Me he corregido en la entrada anterior para no perder el detalle.

**Comment by Almorca** [comment]
Buenas chicos.

Perdonad que no haya pasado antes por aquí pero tuve una época de mucho trabajo y después se me pasó venir a contestar. Gracias @olea por promover estoy y por mover cielo y tierra para dar conmigo.
Yo no puedo ir en esas fechas pero sí puedo ver si saco tiempo y le damos un empujón a esto para esas fechas.

**Comment by olea** [comment]
Bueno, con todo mi pesar os cuento que no he sido capaz de encontrar financiación para los viajes y para colmo la gente de España ni siquiera tiene disponibilidad.

Voy a cerrar este boletín. Ahora bien: sí que se podrían organizar quedadas telemáticas en directo para dar empujoncillos al proyecto. Entre el grupo Telegram y alguna cosa que podamos usar como Jitsi se pueden hacer cosas bonitas.
