### ISSUE TITLE
Tutoriales para contribucion

### ISSUE THREAD

**Issue by Jzarecta** [sbosio/rla-es#20]
Hola, creo que este proyecto podria usar una documentacion para usuarios comunes puedan contribuir mas facilmente a la manera como tenemos organizado tanto el codigo como las palabras. Es decir, algunas personas que le pase este proyecto para contribuir, no pudieron entender como meterle las palabras que ellos consideraban podrian entrar. 

La confusion principal fueron dos secciones:
En que folder/archivo lo meto
Como defino la palabra (en caso de haber conjugacion, plural, capitalizacion, etc).

**Comment by RickieES** [comment]
¿Cuál es el problema con la documentación del wiki? Aquí: https://github.com/sbosio/rla-es/wiki y aquí: https://github.com/sbosio/rla-es/wiki/Estructura-de-archivos-en-el-proyecto-RLA-ES hay bastante información al respecto, ¿no? ¿Qué crees que haría falta añadir?

**Comment by Almorca** [comment]
Hola @Jzarecta Si alguien quiere empezar a contribuir yo no tengo ningún problema en tutorizar a alguien hasta que se desenvuelva mínimamente en el proyecto.

**Comment by matiasdelellis** [comment]
Hola,
Me uno a esta issue. :smile:  
En mi caso particular, en principio, aprovechando que liberaron la versión 0.8 hace un tiempo, me gustaría mantener un paquete actualizado de las traducciones para Huayra GNU/Linux (Distribusion basada en debian, que forma parte del plan Conectar Igualdad de Argentina), que creo que aportaría una buena característica.

¿Me pueden orientar a como obtener los archivos .dic y .aff para distribuir? Sinceramente no lo encontré.. :disappointed:

Luego me gustaría arrancar a contribuir con palabras, pero mas adelante.. :wink: 

Muchas gracias.
Saludos,
Matias

**Comment by RickieES** [comment]
@matiasdelellis , lee este artículo del wiki:

https://github.com/sbosio/rla-es/wiki/Generar-diccionario-corrector

**Comment by matiasdelellis** [comment]
Hola @RickieES 
Gracias por la respuesta, pero hasta ahí habia llegado, y solo logro generar los diccionarios de libreoffice, y me interesa también los .dic y .aff para usarlo en el resto de las aplicaciones.

```
alumno@huayra:~/paquetes/sources/rla-es$ git clone https://github.com/sbosio/rla-es.git
Cloning into 'rla-es'...
remote: Counting objects: 2973, done.
remote: Total 2973 (delta 0), reused 0 (delta 0), pack-reused 2973
Receiving objects: 100% (2973/2973), 3.79 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (2101/2101), done.
Checking connectivity... done.
alumno@huayra:~/paquetes/sources/rla-es$ cd rla-es/ortograf/herramientas/
alumno@huayra:~/paquetes/sources/rla-es/rla-es/ortograf/herramientas$ ./make_dict.sh --localizacion=es_AR
Creando un diccionario para la localización 'es_AR'...
Creando el fichero de afijos... ¡listo!
Creando la lista de lemas etiquetados... ¡listo!
Creando extensión para OpenOffice.org/LibreOffice 3.x o superior (.oxt)... ¡listo!
¡Proceso finalizado!
alumno@huayra:~/paquetes/sources/rla-es/rla-es/ortograf/herramientas$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	es_AR.oxt

nothing added to commit but untracked files present (use "git add" to track)
alumno@huayra:~/paquetes/sources/rla-es/rla-es/ortograf/herramientas$
```

Saludos

**Comment by sbosio** [comment]
Matías, el archivo .oxt es en realidad un ZIP. Podés cambiarle la extensión
y descomprimirlo. Dentro encontrarás los dos archivos que buscás.

**Comment by RickieES** [comment]
Si necesitas algún detalle adicional a lo que ya te ha dicho @sbosio , en este otro documento del wiki, en la parte de creación del XPI para Mozilla se explica cómo tomar los archivos .dic y .aff:

https://github.com/sbosio/rla-es/wiki/C%C3%B3mo-publicar-una-nueva-versi%C3%B3n-del-diccionario-RLA-ES

**Comment by Almorca** [comment]
Cierro esta incidencia puesto que creo que no hay mucho más que aportar.
