### ISSUE TITLE
La palabra "escribiendo" no es reconocida

### ISSUE THREAD

**Issue by Dziban-dev** [sbosio/rla-es#201]
La palabra "escribiendo" no se encuentra en el diccionario, y aunque es fácil de agregar, me parece una palabra muy común como para que no esté incluida, estoy usando es_HN, no se si se si es solo un problema en la versión Hondureña.

Otras palabras que no reconoce: 
Incluido, incluida, Hondureña, encuentra

No se si es un error del programa que uso (WPS office) o que. obvio agrege las palabras al diccionario de forma manual. pero mejor reporto por las dudas.

**Comment by cosmoscalibur** [comment]
¿@Dziban-dev que versión del diccionario usas?

**Comment by Dziban-dev** [comment]
> ¿@Dziban-dev que versión del diccionario usas?

Hola, uso es_HN 2.4, sistema operativo Deepin OS(linux), progrma, wps writer. Probablemente el problema sea con mi programa porque no utiliza .oxt, para usarlos debo descomprimir los .oxt y seleccionar el .dic

**Comment by cosmoscalibur** [comment]
@Dziban-dev , ¿en el mismo directorio conservaste el archivo aff? El archivo dic por si solo no es suficiente.

**Comment by Dziban-dev** [comment]
Efectivamente, tengo todos los archivos que vienen dentro del .oxt en la misma carpeta.  como digo creo que el problema es de compatibilidad.

**Comment by RickieES** [comment]
Tanto en LibreOffice (con el diccionario es_ANY) como en Mozilla (con el diccionario es_ES) la palabra escribiendo no se marca como errónea, por lo que creo que no hay problema en el diccionario y debemos cerrar este _issue_. ¿Estás de acuerdo, @Dziban-dev?

**Comment by olea** [comment]
Aparentemente no es un error.

Si @Dziban-dev tiene más información que aportar reabriremos.
