### ISSUE TITLE
Forma correcta de agregar la palabra [corrígelo]

### ISSUE THREAD

**Issue by EdgardoRios** [sbosio/rla-es#202]
Hola, espero todo vaya bien en su día:

Les escribo porque estoy buscando la mejor manera de agregar la palabra [corrígelo]. Me parece que usar el archivo de afijos puede ser una buena opción, pero hasta donde he revisado, parece que tengo que agregar algunas líneas nuevas y no estoy seguro cuál sea el mejor camino a seguir.

Actualmente, la palabra [corregir] tiene los siguientes afijos /XDÀÈÕ.
Por ejemplo, [Õ] permite las siguientes variantes:
SFX Õ egir      ígeme   egir     ->     corrígeme
SFX Õ egir      ígenos  egir     ->     corrígenos

Pero no encontré algo como:
SFX ¿? egir      ígela     egir     ->     corrígela
SFX ¿? egir      ígelas    egir     ->     corrígelas
SFX ¿? egir      ígelo     egir     ->     corrígelo
SFX ¿? egir      ígelos   egir     ->     corrígelos

En caso de que sea buena idea agregar estas líneas al archivo de afijos, ¿qué letra debería utilizar para la nueva regla?

Gracias de antemano por su ayuda.

Saludos.
@EdgardoRios

**Comment by RickieES** [comment]
Casi preferiría que me lo dejaras a mí. Tengo varios cambios en local en los archivos de afijos, y si metemos mano los dos, igual nos toca estar haciendo merges. :smile:

**Comment by EdgardoRios** [comment]
Hola @RickieES:

Gracias por tu respuesta. Pondré atención a los cambios que hagas para entender que es lo que tenemos que hacer en este caso en particular.

Saludos.
@EdgardoRios

**Comment by RickieES** [comment]
Acabo de subir los cambios del issue #14 al repositorio, por si quieres ver cómo lo he hecho. También merece la pena repasar el issue #75, donde Santiago Bosio explica por qué no siempre se puede añadir una regla más a una bandera, aunque en este caso concreto (corrígelo) posiblemente sí corresponda a la misma bandera que la que permite generar corrígeme. Ahora estoy un poco espeso y no me atrevo a asegurarlo. :smile:

**Comment by sbosio** [comment]
Si me @EdgardoRios y @RickieES doy yo la solución y de paso explico esa parte, que parafraseando a Ricardo está bastante espesa.

La forma _correcta_ (si es que existe algo como eso) es añadir las reglas al conjunto que está etiquetado con el comentario correspondiente a la inflexión que se quiere añadir.

En este caso:
· *corrígelo*: 2da persona del singular, modo imperativo del verbo _corregir_ (verbo transitivo, completamente irregular, conjugado como _pedir_), con clítico de objeto directo en 3ra persona, en posición enclítica.

Esa clasificación es la que nos da cuál debería ser la bandera a aplicar al verbo en el listado de palabras, si las reglas de inflexión existen, o bien nos orienta a qué bandera deben añadirse las reglas de inflexión en los ficheros de afijos, para después aplicarla al lema en el listado de palabras.

**Comment by sbosio** [comment]
Con el _commit_ anterior quedaría solucionado el tema de esta incidencia, así que podría cerrarse e incluirse en la versión 2.5.

**Comment by RickieES** [comment]
Muchas gracias, Santiago, cada vez que apareces nos das una lección magistral. :smile: :tophat:

**Comment by EdgardoRios** [comment]
¡Muchas gracias a ambos!

¡Excelente explicación! En verdad que soy afortunado de colaborar en este grupo.

¡Abrazo fuerte!
Edgardo
