### ISSUE TITLE
Algunas palabras reportadas en 2011

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#203]
En 2011, aún con este proyecto en la Forja de RedIRIS, recibí algunos mensajes a través de mi pertenencia a Proyecto NAVE (traducción de Mozilla al español de España) informando de palabras que faltaban en el diccionario. Aprovechando que son listas cortas, voy a ir añadiéndolas poco a poco. Aquí está la primera, que reportó Gonzalo Higuera Díaz (incluyo solo las que a día de hoy siguen siendo marcadas como incorrectas):

- besito, besitos [noDRAE] --> los diminutivos no parecen incluirse en el DLE, pero puesto que el lema principal sí lo es, añado la bandera U a beso en NombresMasculinos.txt.
- cebarte [DRAE, de cebar]
- detallito, detallitos [noDRAE]
- enfermito, enfermita, enfermitos, enfermitas [noDRAE]
- enfermilla, enfermillo, enfermillos, enfermillas [noDRAE poco usual]
- fálico, fálica, fálicos, fálicas [DRAE]
- gomaespuma [DRAE]
- Lavapiés [es_ES-topónimo_Madrid]
- Merche [es_ES-nombre_contracción]
- princesita, princesitas [noDRAE]
- principito, principitos [noDRAE]

**Comment by RickieES** [comment]
Vaya, me surge una duda con "enfermo". Según el DLE, es adjetivo, que también se puede usar como sustantivo. En el repositorio lo tenemos definido como adjetivo, no sé si veis correcto aplicar la bandera de diminutivo.

Aparte de eso, como no se pueden aplicar dos banderas en cadena, no se puede derivar el género y número a la vez que el diminutivo. ¿Veis solución a esto?

**Comment by RickieES** [comment]
Y otra duda: tenemos "príncipe" en NombresMasculinosFemeninos.txt, pero yo creo que no tenemos "príncipas", ¿verdad? Opino que deberíamos moverlo a NombresMasculinos.txt. ¿Estáis de acuerdo?

**Comment by cosmoscalibur** [comment]
> Vaya, me surge una duda con "enfermo". Según el DLE, es adjetivo, que también se puede usar como sustantivo. En el repositorio lo tenemos definido como adjetivo, no sé si veis correcto aplicar la bandera de diminutivo.
> 
> Aparte de eso, como no se pueden aplicar dos banderas en cadena, no se puede derivar el género y número a la vez que el diminutivo. ¿Veis solución a esto?

Hola @RickieES , no hay problema con agregar "enfermo" en ambas categorías, y en cada caso con sus respectivas banderas. De esa forma, no se presenta el problema de banderas en cadena incompatibles.

> Y otra duda: tenemos "príncipe" en NombresMasculinosFemeninos.txt, pero yo creo que no tenemos "príncipas", ¿verdad? Opino que deberíamos moverlo a NombresMasculinos.txt. ¿Estáis de acuerdo?

Esto ya lo hemos advertido en otros reportes sobre la inconsistencia que hay de muchos sustantivos en los archivos. Se había mencionado de mover poco a poco esos sustantivos.

**Comment by RickieES** [comment]
Estoy teniendo un problema que no sé si os habéis encontrado en otras ocasiones. He añadido la bandera U (el diminutivo) en algunos lemas; la bandera U, a su vez, tiene la bandera S para añadir el plural, de modo que 

> beso/SU

debería permitir generar, en total, los siguientes lemas:

beso, besos, besito, besitos

Sin embargo, LibreOffice me seguía marcando como erróneo "besitos", así que lo que hice fue usar unmunch:

`unmunch es_ANY.dic es_ANY.aff | grep -e ^besi`

y me encuentro esto:

```
besico
besicos
besito/S|

```
El caso es que llegué a encontrar este mismo problema anteriormente, pero luego desapareció mágicamente. Ahora no lo consigo: he quitado y puesto de nuevo los espacios que definen la regla en los afijos, he intercambiado el orden de las banderas en beso, y sigue sin funcionar. ¿Alguien tiene alguna idea?

**Comment by RickieES** [comment]
Voy a subir los cambios para que podáis generar el diccionario vosotros y comprobar si tenéis el mismo problema, no vaya a ser que a mí me esté pasando por mi versión de Hunspell o de LibreOffice.

**Comment by cosmoscalibur** [comment]
Hola @RickieES , he validado el problema que comentas con los diminutivos, y está presenta para muchas categorías de sufijos. Hunspell no soporta usar banderas en las reglas de formación, y por eso que la definición del diminutivo (y otros) tuviera /S para para formar los plurales llevaba al error de `/S|`. Como desconozco los casos regionales, solo he corregido el problema para el archivo de afijos de Colombia. No se cuales de pueda simplemente reemplazar el archivo, copiar los bloques modificados completos o el detalle de categoría por categoría.  
La forma de corregir, es duplicar las entradas de cada categoría, unas para la forma singular y las otras para la forma plural, y duplicar el valor de la cabecera del sufijo.

**Comment by RickieES** [comment]
He encontrado un par de lemas en los que el diminutivo no se genera correctamente.

Por un lado, del lema "detalle" la bandera U deriva "detallecito", no "detallito". Sin embargo, he estado mirando otros lemas acabados en -lle y no creo que sea buena idea tocar la bandera U para que se derive "detallito", porque no habría una solución general (por ejemplo, del lema "calle" se derivaría "callito", en lugar de "callecita").

Con "príncipe" se deriva "príncipito" (con tilde), en lugar de "principito".

Creo que voy a eliminar la bandera U en ambos lemas. ¿Cabría añadirlos manualmente en NombresMasculinos.txt?

**Comment by RickieES** [comment]
Voy a cerrar este _issue_. Los dos lemas que faltan (detallito y principito) los añadiré en otro _issue_ diferente.
