### ISSUE TITLE
Algunos lemas con sufijos compuestos marcados erróneamente en LibreOffice

### ISSUE THREAD

**Issue by cosmoscalibur** [sbosio/rla-es#204]
**Actualización**: Con el fin de mantener el foco en el problema, edito el inicio de esta discusión. El problema aparece en LibreOffice y posiblemente otras aplicaciones (posiblemente con un motor diferente a Hunspell). Sin embargo, LibreOffice configurado con Hunspell también presenta inconveniente para algunos usuarios (soy uno de ellos).  

El error se presenta en lemas cuya formación depende de sufijos cuya regla contiene a su vez una bandera (sufijos A, B, C, F, H, J, K, L, M, N, P, Q, T, U). Se relacionan menciones en #145 y #203.

LibreOffice 6.0.7.3
Hunspell 1.6.2
Linux Mint 19 (tanto Hunspell como LO se instalaron del repositorio oficial)
Diccionario generado para es_CO con la versión 6abbfdf938797095f9edfd77e7ec8b1c19bda348 (archivo de sufijos restaurado).

**Comment by RickieES** [comment]
@sbosio, aunque coincido en que me sorprendió la creación de este _issue_ (@cosmocalibur, creo que vas a tener que hacer un backout del commit) :wink:, lo que sí es cierto es que el problema lo detecté precisamente en LibreOffice, que marca como erróneos lemas que debería considerar correctos aplicando en cadena los sufijos (el de una de las banderas del término original y el que tiene dicha bandera para, por ejemplo, generar el plural).

**Comment by RickieES** [comment]
He probado con la palabra "blanco". "blanco" está definido en Adjetivos.txt, así:

`blanco/NGS`

Y el sufijo N está definido así:

SFX N Y 19
SFX N a         illa/S       [bdfhjlmnprstv]a
SFX N o         illo/S       [bdhjlmnprstv]o
SFX N 0         cilla/S      ve
SFX N za        cilla/S      za
SFX N 0         ecilla/S     d
SFX N ión       ioncilla/S   [cglnstx]ión
SFX N ón        oncillo/S    [^i]ón
SFX N 0         cillo/S      or
SFX N zo        cillo/S      zo
SFX N 0         cillo/S      [djlnu]e
SFX N z         cecillo/S    z
SFX N 0         ecillo/S     ur
SFX N e         illo/S       [cpt]e
SFX N 0         illo/S       [ls]
SFX N 0         illo/S       [^ou]r
**SFX N co        quillo/S     co**
SFX N go        guillo/S     go
SFX N ca        quilla/S     ca
SFX N ga guilla/S ga

He marcado en negrita la regla que se aplicaría a "blanco", observad que lleva a su vez el sufijo /S. He probado a escribir esto en LibreOffice:

Blanco, blanca, blancos, blancas, blanquillo, blanquillos

Y ninguna la marca como incorrecta. Así que, a menos que "blanquillos" se derive de algún otro sitio, la aplicación de dos sufijos encadenados funciona correctamente con carácter general. Es solo en algunos casos en los que está fallando.

**Comment by RickieES** [comment]
Muchas gracias, @sbosio, por darte cuenta. ¡Me estaba volviendo loco! :smile:

Ya me funcionan algunos de los diminutivos. He visto que otros no, pero porque no se pueden derivar a partir de la bandera U, lo comento en el _issue_ 203.

**Comment by cosmoscalibur** [comment]
@sbosio solucionado.
