### ISSUE TITLE
Pregunta: Generar lista de palabras

### ISSUE THREAD

**Issue by jastabile** [sbosio/rla-es#207]
Para el proyecto de grado, estamos usando un vocabulario en español, pero lo usamos simplemente como una lista de palabras (un archivo con una palabra por renglón).

¿Es posible generar algo así desde el proyecto?
Usé el script make_dict.sh pensando que capaz generaba un archivo así (wordlist.tmp) pero no, la lista de palabras que genera son unas pocas palabras.

¿Hay hecho o es posible hacer un script que use todos los archivos y lemas para generar algo así?

**Comment by RickieES** [comment]
Nosotros solemos usar la utilidad unmunch, pero por lo que leo, está obsoleta y reemplazada por la utilidad wordforms. Echa un ojo a [la página de Hunspell](https://github.com/hunspell/hunspell).

**Comment by Almorca** [comment]
Cierro el issue.
