### ISSUE TITLE
Acentos que faltan:

### ISSUE THREAD

**Issue by angelmoure** [sbosio/rla-es#208]
como en: destruyalo , entregalo,  comelo, cortalo , etc no las detecta

**Comment by fitojb** [comment]
Tus últimos tres ejemplos son pronunciaciones válidas en el voseo.

**Comment by angelmoure** [comment]
Esas palabras son esdrújulas y por tanto deben llevar acento pero el programa de ortografía las da por buenas sin acento.

**Comment by angelmoure** [comment]
La verdad es que el diccionario deja mucho que desear. No conoce palabras como estadísticamente o catastrofista

**Comment by Almorca** [comment]
Hola @angelmoure , bienvenido.

Te animo a que veas como se insertan los lemas en el diccionario (explicado en https://github.com/sbosio/rla-es/wiki#examinar-los-afijos-y-sugerir-los-que-deben-aplicarse-a-cada-palabra ) y te anime a añadir las palabras que detectes que faltan.

Un saludo.

**Comment by olea** [comment]
> Esas palabras son esdrújulas y por tanto deben llevar acento pero el programa de ortografía las da por buenas sin acento.

@angelmoure ¿serías tan amable de indicarnos qué versión regional del corrector usas?

> La verdad es que el diccionario deja mucho que desear. No conoce palabras como estadísticamente o catastrofista

La vida es muy dura, pero como indica @Almorca aceptamos colaboraciones :-)

**Comment by angelmoure** [comment]
Pues lo intento, por eso quise avisar. Intentaré a ver si sé como hacer lo de GitHub nunca lo he usado.

**Comment by angelmoure** [comment]
me desacargué la version 2.5 de aquí https://extensions.libreoffice.org/extensions/spanish-dictionaries/2.5

**Comment by olea** [comment]
> me desacargué la version 2.5 de aquí https://extensions.libreoffice.org/extensions/spanish-dictionaries/2.5

 es_ANY.oxt, ¿correcto?

Ese es el diccionario general panhispánico y, como dice @fitojb, incluye variantes como la del voseo. Por lo tanto en este caso no hay defecto.

Si es tu preferencia puedes instalar una variante regional, como ejemplo es_ES, que para eso las tenemos: https://extensions.libreoffice.org/extensions/spanish-dictionaries/2.5/@@download/file/es_ES.oxt

**Comment by angelmoure** [comment]
vale , he visto que lo que falta corresponde a la categoría de afijos. por ejemplo entregar entrégalo. pero no sé como seguir

**Comment by olea** [comment]
> vale , he visto que lo que falta corresponde a la categoría de afijos. por ejemplo entregar entrégalo.

Para cada categoría tenemos diferentes localizaciones. Como decíamos antes para el caso «es» o «es_AR» el voseo está contemplado. Si te refieres a otra localización indícanoslo, por favor.

**Comment by angelmoure** [comment]
No, yo uso español de españa. pero no la reconoce como esdrújula y no la acentúa
