### ISSUE TITLE
Palabras que faltan en el diccionario

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#209]
baldosines, comercializadora, Completitud, escríbeles, historificación, peatonalizar, posteriori, refréscame, refundición, remediación, reubico

**Comment by Almorca** [comment]
baldosín/S - NombresMasculinos.txt
comercializadora/S - noRAE/NombresFemeninos.txt
completitud - NombresFemeninos.txt

**Comment by RickieES** [comment]
¿En lugar de comercializadora no debería ser comercializador/GS en NombresComunes.txt?

**Comment by Almorca** [comment]
Efectivamente @RickieES 
Veo que estoy oxidado.

**Comment by Almorca** [comment]
Para escríbeles sería:
En Afijos.txt
SFX Î ibir      íbele    ibir
SFX Î ibir      íbeles   ibir

I añadir la bandera ÎÏ a escribir
escribir/REÀÁÂÄÆÍ**ÎÏ**Úñòø

**Comment by Almorca** [comment]
historificación/S - noRAE/NombresFemeninos.txt

**Comment by Almorca** [comment]
peatonalizar/REDÀÄÌ - VerbosTransitivos.txt
y de paso añado Ì a patentar

posteriori - Frases.txt

SFX Í escar     éscame   escar
SFX Í escar     éscanos  escar

refrescar/REDÀÁÌ**Í**ñø

**Comment by Almorca** [comment]
refundición/S - NombresFemeninos.txt
remedición/S - NombresFemeninos.txt
remediación/S - noRAE/NombresFemeninos.txt
ubicar/pREDñòôø - añado bandera p

**Comment by Almorca** [comment]
Si nadie dice nada en unos días hago el commit con estos cambios.

**Comment by Almorca** [comment]
[es_DO.zip](https://github.com/sbosio/rla-es/files/4460545/es_DO.zip)

Estoy probando los cambios que he hecho y para el diccionario es_DO no funcionan correctamente. Adjunto el resultado del diccionario y el listado de palabras que no detecta. Esto se puede comprobar ejecutando
hunspell -d es_DO -G KO_es_DO.txt

Voy a seguir echando un ojo pero os lo pongo por aquí por si alguien más ve algo raro.

**Comment by Almorca** [comment]
Corregido. Había metido la pata al modificar el fichero de afijos.
