### ISSUE TITLE
¿Cómo se genera el diccionario para Firefox/Thunderbird?

### ISSUE THREAD

**Issue by simonbcn** [sbosio/rla-es#21]
Me he descargado el repositorio y he consultado el wiki pero no encuentro la información para crear el diccionario español para Firefox/Thunderbird.

**Comment by RickieES** [comment]
La verdad es que las herramientas (instrucciones y scripts) que uso para generarlo están fuera del repositorio, porque RLA-ES se creó mucho antes de que se comenzara a usar su trabajo para generar el diccionario para Mozilla.

Pensaré en añadir las instrucciones y ficheros de apoyo al repositorio, pero creo que ya para la 0.9, porque hay muchas cosas que cambiar (p.e.: RLA-ES usa la forma ab_CD, mientras que Mozilla usa ab-CD, con guion medio).

**Comment by RickieES** [comment]
Como parte del proceso de publicación de la versión 0.8, he añadido la información al documento del wiki [Cómo publicar una nueva versión del diccionario RLA-ES](https://github.com/sbosio/rla-es/wiki/C%C3%B3mo-publicar-una-nueva-versi%C3%B3n-del-diccionario-RLA-ES). Con esto creo que es suficiente para crear un XPI sin depender de mí.
