### ISSUE TITLE
Falta la palabra oxímoron

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#210]
Está en el DLE y es un sustantivo masculino. Lo que no sé es si admite plural.

**Comment by cosmoscalibur** [comment]
Su plural es "oxímoros". Entrada en el [diccionario panhispánico de dudas](https://www.rae.es/dpd/ox%C3%ADmoron).

**Comment by RickieES** [comment]
Gracias, @cosmoscalibur . Entonces no puedo aplicar el sufijo S, porque derivaría oxímorones. Tendré que añadir ambos lemas, porque no creo que haya suficientes casos similares para justificar la adición de una regla nueva al sufijo. Corregidme si pensáis lo contrario, por favor. :)

**Comment by RickieES** [comment]
Dejo abierto el _issue_ por lo del plural.

**Comment by Almorca** [comment]
Yo añadiría ambos lemas.

**Comment by cosmoscalibur** [comment]
Coincido con @Almorca . El manejo que he dado a plurales donde una regla no valdría la pena es agregar el lema del plural de manera independiente y le agrego en comentario el singular al que pertenece.

**Comment by sbosio** [comment]
Esta incidencia puede cerrarse ya que está resuelta en la rama master de acuerdo a lo sugerido por @Almorca y @cosmoscalibur. Yo soy de la misma opinión con cualquier irregularidad que complique la definición de los afijos, la sugerencia es añadir cada lema por separado, singular y plural.
