### ISSUE TITLE
No marcar grosso modo como error

### ISSUE THREAD

**Issue by jorgesumle** [sbosio/rla-es#215]
*Grosso modo* es una locución latina muy usada en castellano, [incluso aparece en la RAE](https://dle.rae.es/grosso%20modo). Sin embargo, el corrector marca como incorrecta la palabra *grosso*. Propongo añadir la palabra *grosso* al diccionario, aunque sea una palabra del latín. No hay que tener en cuenta la declinación latina ni el plural. En el ablativo singular del adjetivo *grossus a um* (*groso*) es de la única forma que aparece en el castellano actual.

**Comment by jorgesumle** [comment]
Pensándolo mejor, igual no es muy adecuado marcarlo como correcto. Lo mejor sería marcarlo como incorrecto solo cuando no apareciera en cursiva en un texto castellano, lo cual creo que no es factible o facilmente realizable, así que cierro esta incidencia.

**Comment by cosmoscalibur** [comment]
Para complementar, efectivamente este tipo de expresiones se deben marcar como erróneas porque no son expresiones en español. Aunque sean recolectadas por el diccionario por su uso, siguen siendo expresiones tipo extranjerismos.

**Comment by olea** [comment]
> no son expresiones en español.

¡Hombre! ¡decir que una entrada en el DRAE no es una expresión en español es muy atrevido! ;-) 

La relación del latín con las lenguas romances es obvia, y las locuciones latinas han sido siempre parte del habla culta.

Yo entiendo que sin la menor duda, sí, debe recogerla el corrector.

Aunque, [OjO al DPD](https://www.rae.es/dpd/grosso%20modo): 

> Es incorrecto anteponer la preposición a: a grosso modo.

X-)

**Comment by RickieES** [comment]
Ojo, que no todo lo que se recoge en el DLE está aceptado. Las locuciones latinas no son lemas en español, si no ha cambiado el criterio de la RAE:

https://www.fundeu.es/recomendacion/locuciones-latinas-latinismos-errores-frecuentes-621/

**Comment by olea** [comment]
> Ojo, que no todo lo que se recoge en el DLE está aceptado.

Mi regla es más sencilla: si el DRAE lo recoge, para mí es español :-)

Cuando no lo recoja pues ya se podrán  buscar consideraciones, pero mientras... :-)
