### ISSUE TITLE
«defínelo» está marcado como error

### ISSUE THREAD

**Issue by jorgesumle** [sbosio/rla-es#219]

**Comment by RickieES** [comment]
Me temo que para esto tampoco hay regla. Sería esta bandera (no sé por qué, me suena): :wink: 

> Verbos regulares en imperativo, con clíticos de objeto directo en
> 3ª persona, singular y plural; en posición enclítica.
>
> SFX Ì Y 388

Habría que añadir estas reglas:

SFX Ì inir      ínela    inir
SFX Ì inir      ínelas   inir
SFX Ì inir      ínelo    inir
SFX Ì inir      ínelos   inir

**Comment by cosmoscalibur** [comment]
SFX Í inir ínela inir
SFX Í inir ínelas inir
SFX Í inir ínelo inir
SFX Í inir ínelos inir

SFX Ì inir ínala inir
SFX Ì inir ínalas inir
SFX Ì inir ínalo inir
SFX Ì inir ínalos inir
