### ISSUE TITLE
¿No es necesario activar diccionario en OpenOffice/LibreOffice?

### ISSUE THREAD

**Issue by simonbcn** [sbosio/rla-es#22]
Una vez instalada la extensión en LibreOffice (es la suite que uso), ¿no es necesario activarla en el corrector?
Me refiero a esta opción:
![20150402_11 27 57_01](https://cloud.githubusercontent.com/assets/428231/6961440/5c1d8570-d92b-11e4-8dba-37b99a6207e4.jpg)

Si pulso en `Editar` me aparece `Español (España)` y `es`:
![20150402_11 28 43_01](https://cloud.githubusercontent.com/assets/428231/6961451/8a5ef00e-d92b-11e4-977d-de9f691a56d9.jpg)

**Comment by Almorca** [comment]
Sí, una vez instalado lo tienes que activar en las opciones aunque en Libreoffice viene activado por defecto y por tanto ese paso te lo puedes saltar. En cuanto a la segunda imagen que has puesto ¿no entiendo cuál es tu duda ahí?

**Comment by simonbcn** [comment]
En la segunda imagen me aparece "es" y "Español (España)", ¿dejo "Español (España)"?

**Comment by Almorca** [comment]
Sí, ''Español (España)'' es la buena y ''es'' no sé porque sale.

**Comment by simonbcn** [comment]
:+1:
