### ISSUE TITLE
Versión 2.6

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#221]
¿Cómo veis sacar una versión nueva del diccionario para Junio de manera que pueda entrar en la versión 7.0 de Libreoffice?

El roadmap de Libreoffice está en https://wiki.documentfoundation.org/ReleasePlan

**Comment by olea** [comment]
¿Sabes si tendría que estar listo antes de que congelen el código? Yo no tengo ni remota idea.

**Comment by olea** [comment]
Como tenemos #234 cierro acá.

**Comment by fitojb** [comment]
> ¿Sabes si tendría que estar listo antes de que congelen el código? Yo no tengo ni remota idea.

La congelación acaba de ocurrir, pero yo me encargo —⁠en cuanto tengáis listo el parche en Gerrit⁠— de que entre en la 7.0. Basta con hacer un cherry-pick de `master` a `libreoffice-7-0` :wink:
