### ISSUE TITLE
Propuesta de mejora: adopción de CLDR y regiones es_GQ, es_PH y es_US

### ISSUE THREAD

**Issue by olea** [sbosio/rla-es#223]
Hola:

He creado una rama con unos cuantos cambios al script de composición y configuración relacionada: https://github.com/sbosio/rla-es/tree/olea-devel 

Los cambios más importantes son:

- «es-ANY» ahora sólo es «es», como en CLDR.
- añadidas las configuraciones para crear es_GQ, es_PH y es_US, a falta de ir dándoles cariño
- otros cambios menores en make_dict.sh

Si los cambios os parecen bien los mezclamos a la rama principal.

**Comment by olea** [comment]
¿Alguna opinión o comentario antes de incorporar los cambios a la rama principal?

**Comment by Almorca** [comment]
Yo no he podido ver los cambios hechos en la rama pero estoy de acuerdo con los cambios que comentas.

**Comment by olea** [comment]
Si hoy no recibo aviso en contra esta tarde incorporo los cambios a la rama principal, incluyendo todas las mejoras de los últimos días.

;-)

**Comment by cosmoscalibur** [comment]
Es poco tiempo si realmente quieres una retroalimentación. Yo apenas puedo desocupar de pendientes. Si puedes esperar 24 horas, reviso que ya hoy puedo dedicarle tiempo al proyecto.

**Comment by olea** [comment]
Esta entrada ya es redundante cuando está abierto el PR: https://github.com/sbosio/rla-es/pull/228

Aquel lo creé porque he pensado que sería más cómodo para examinar los cambios. La conversación podremos seguirla allí.
