### ISSUE TITLE
«Palpos» marcada como error (palabra palpo, RAE)

### ISSUE THREAD

**Issue by jorgesumle** [sbosio/rla-es#224]
«Palpos» es el plural de «palpo» (sustantivo), que no está en el diccionario. Imagino que el singular no lo marca como error porque es la primera persona del singular del presente de indicativo del verbo palpar.

**Comment by serval2412** [comment]
Shouldn't it be closed too after merge of "Nuevas palabras para añadir #218" ?

**Comment by RickieES** [comment]
Esta palabra ya está reconocida como válida con la versión 2.6 del diccionario, asigno el _issue_ a esa versión y lo cierro.
This word is already accepted as valid with version 2.6 of the dictionary, so I set that version to this issue and close it.
