### ISSUE TITLE
Falta palabra «corion» (RAE)

### ISSUE THREAD

**Issue by jorgesumle** [sbosio/rla-es#225]

**Comment by olea** [comment]
Hola @jorgesumle:

Veo que estás muy activo y se agradece. Por reducir un poco la vista de la lista de pendientes tal vez podrías aprovechar algún issue que ya tengas abierto para incluir las carencias que vayas identificando. Gracias :)

**Comment by jorgesumle** [comment]
Eso iba haciendo, pero tengo un *pull request* [abierto](https://github.com/sbosio/rla-es/pull/218) desde hace 7 días. No sé si debería añadir ahí más palabras o preferís que sean pequeños para facilitar la revisión.

**Comment by olea** [comment]
Se pueden añadir commits a un PR abierto, así que por eso no debería haber problema siempre que la sintaxis del fichero siga siendo la correcta, ya sabes.

Yo creo que en general es mejor agrupar los envíos. Si alguien tiene algún problema ya nos lo dirá ;)

**Comment by serval2412** [comment]
Shouldn't this tracker be closed following f1526b972687deb3d9d5ea7853e3d33ce853bdc6 ?
    Añade sustantivo masculino corion

----------------- ortograf/palabras/RAE/NombresMasculinos.txt -----------------
index 05472e2..f939d20 100644
@@ -3802,6 +3802,7 @@ corezuelo/S
 corimbo/S
 corindón/S
 corinto/S
+corion/S
 cornatillo/S
 cornejo/S
 cornero/S

**Comment by RickieES** [comment]
Esta palabra ya está reconocida como válida con la versión 2.6 del diccionario; asigno el _issue_ a esa versión y lo cierro.
This word is already accepted as valid with version 2.6 of the dictionary, so I set that version to this issue and close it.
