### ISSUE TITLE
Modificación de afijos regionales para dejar de almacenarlos como parches.

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#23]
Puesto que tener los ficheros de afijos regionales en formato de parches .patch por ahora solo dificulta el trabajo y no parece aportar nada propongo modificarlos para almacenar los ficheros completos.
Que a mí se me ocurra lo único que aporta tener los ficheros locales en formato de parche es un menor tamaño de los ficheros en el repositorio. Por contra cada vez que se quiere añadir un cambio hay que generar el fichero completo a partir del parche, modificar el fichero y volver a generar el parche.
@olea si tienes tiempo me gustaría conocer tu opinión sobre el tema.

**Comment by RickieES** [comment]
> Que a mí se me ocurra lo único que aporta tener los ficheros 
> locales en formato de parche es un menor tamaño de los ficheros en
> el repositorio

Lo que sí tendremos que hacer es añadir una leyenda muy clara al principio del fichero principal de afijos para recordarnos que, cada vez que lo cambiemos, hay que modificar todos los demás ficheros regionales.

**Comment by olea** [comment]
> @olea si tienes tiempo me gustaría conocer tu opinión sobre el tema.

Pues sí creo que este modelo de trabajo actual parece subóptimo. Lo malo es que ahora mismo no tengo tiempo para proponer nada nuevo :-/

**Comment by sbosio** [comment]
Yo, que como decimos por aquí "fui el inventor de la pólvora" les explico
cuál fue la idea. No fue por un tema de espacio de almacenamiento, sino que
el comando "patch" puede parchar un fichero aún cuando las instrucciones
del .patch no coincidan precisamente con la posición indicada, lo que me
permitía hacer cambios al principal y que aún así siguiera funcionando sin
tener que tocar todos los regionales. Por supuesto que deja de funcionar,
desgraciadamente, cuando la operación es la modificación de reglas
existentes que cambian la cantidad de reglas de un grupo, por el tema del
número de reglas que va en el encabezado del grupo. Pero resultaba útil
sobre todo en la época en que iba añadiendo nuevas reglas.

También creo que hay que encontrarle una solución, pero me parece que la
única que va quedando es una aplicación con base de datos donde se
almacenen las reglas, con indicación de a qué localización es aplicable. No
encuentro manera de hacerlo a través de herramientas de la línea de
comandos que operen sobre los ficheros de texto.

Saludos,

Santiago

**Comment by RickieES** [comment]
En el issue #16 hay una propuesta basada en el uso de ramas de Git, junto con un hipotético script simple de corrección del contador de reglas.

**Comment by Almorca** [comment]
Mientras buscamos una solución definitiva a la gestión de afijos locales he modificado el diccionario para que los afijos locales dejen de estar en formato parche ya que es un paso que simplifica el pasar el diccionario a formato UTF-8.

**Comment by RickieES** [comment]
Genial. ¿Has retomado entonces el trabajo de conversión a UTF-8?

**Comment by Almorca** [comment]
Sí, ahora que tengo unos días de vacaciones estoy con ello.

**Comment by RickieES** [comment]
El script para crear diccionarios hace uso de los parches, por lo que habrá que revisarlo para que siga funcionando bien una vez no haya parches. No obstante, habrá que revisar el script para otras cosas, por lo que tendremos que abrir un issue específico.
