### ISSUE TITLE
Errores en la generación de OXT tras los cambios en el script make_dict.sh

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#237]
Los cambios en el script make_dict.sh han provocado una serie de errores:

- [x] El identificador en **description.xml** es distinto del usado en las versiones anteriores de las extensiones OXT, lo que causa que la nueva no se instale como actualización, sino como extensión diferente.
- [x] En dictionaries.xcu, los ficheros .aff y .dic se relacionaban antes como dos elementos XML "it" independientes, mientras que ahora son un solo elemento XML "it" con los archivos seprados por un espacio (esto puede ser correcto).
- [x] En dictionaries.xcu, en el nodo Locales del nodo de diccionario HunSpellDic, el código de __locale__ interno usaba guion medio (p.e: es-ES) mientras que ahora usa guion bajo (p.e.: es_ES).
- [x] En dictionaries.xcu, en el nodo HyphDic antes figuraba es_ANY y ahora solo es (esto probablemente es correcto).
- [x] En dictionaries.xcu, en el nodo ThesDic antes figuraba es_ANY y ahora solo es (esto probablemente es correcto).
- [x] En el fichero de afijos (de es_ES, en este caso) hay menos reglas, sin motivo aparente. Por ejemplo, falta la regla que contiene "SFX Í escar éscame escar".

**Comment by olea** [comment]
En el caso de los es-ANY no debemos usarlos más porque no forman parte de ninguna especificación de regiones. El equivalente formal  siempre es «es» ([ref](https://olea.org/diario/2020/04/25/l10n-lengua-espannola.html)).

**Comment by RickieES** [comment]
Por eso lo marco como que probablemente es correcto, pero prefiero esperar a ir depurando todo lo demás para que quede documentado que, efectivamente, esos cambios son correctos. Así, si más adelante alguien se pregunta por qué se cambiaron, encontrará la razón aquí.

**Comment by olea** [comment]
Sobre metadatos en ficheros xcu:

- El identificador está cambiado siguiendo el ejemplo de otros diccionarios de LO ([ejemplo de](https://git.libreoffice.org/dictionaries/+/refs/heads/master/de/dictionaries.xcu)).

- Lo de los ficheros en una o varias entradas también se ha replicado de ejemplos existentes, en particular del mismo fichero xcu para el alemán mencionado.

**Comment by olea** [comment]
Los ficheros xcu parace que ahora sí se generan correctamente (https://github.com/sbosio/rla-es/commit/3cb331c0961ef1454da0bfd545c69189ce5d08c5).

**Comment by olea** [comment]
He verificado que ahora en LibreOffice los diccionarios regionales (probados es_ES y es_UY) funcionan aparentemente bien.

Sin embargo el es.oxt, aunque se carga, no está operativo. Mañana lo seguiré viendo.

**Comment by olea** [comment]
> Sin embargo el es.oxt, aunque se carga, no está operativo. Mañana lo seguiré viendo.

Vale, ya sé qué pasa. Ahora estaba usando esta descripción en dictionaries.xcu:
``` xml
            <prop oor:name="Locales" oor:type="oor:string-list">
                <value>es</value>
            </prop>
```

porque se supone que si para la variante regional configurada no está disponible el recurso el predeterminado es el código de lengua. Pero no amigos, aquí no, hay que usar algo como
``` xml
            <prop oor:name="Locales" oor:type="oor:string-list">
                <value>es-AR es-BO es-CL es-CO es-CR es-CU es-DO es-EC es-ES es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-UY es-VE</value>
            </prop>
```
Mi gozo en un pozo.

\#SeñorLlévamePronto

**Comment by RickieES** [comment]
Acabo de generar es_ES y el OXT ya funciona correctamente con los dos archivos de test de las versiones 2.5 y 2.6. De momento no he mirado cómo está ahora el fichero de afijos, pero si tuviera errores, lo normal sería que fallaran muchas más cosas. No obstante, lo voy a intentar verificar.

Yo, para asegurarnos, creo que, además de las pruebas del resto de variantes regionales que queráis probar cada uno, hay que probar la versión neutral, que intento hacerlo yo si me da tiempo hoy. Aún no he probado nada del XPI.

Nos falta el changelog que manteníamos hasta ahora, no sé si alguien lo ha generado (yo no he probado la opción del script, lo confieso).

Para futuras versiones, ¿creéis que deberíamos pensar en montar algo para que cada uno que suba cambios pueda ir añadiendo los términos que ha añadido, de forma que construyamos rápidamente un texto para hacer las pruebas? No todo el mundo lo hará, pero facilitará mucho el trabajo ahora.

**Comment by olea** [comment]
> Yo, para asegurarnos, creo que, además de las pruebas del resto de variantes regionales que queráis probar cada uno, hay que probar la versión neutral,

En general la prueba que yo hago en LO es con el diccionario internacional y con alguna de las variantes regionales.

Tal y como funciona make_dict.sh hay dos tipos de caso: el general y el regional. Si una versión regional funciona doy por sentado que funcionarán todas las variantes. 

Eso sí, sólo lo verifico con LibreOffice pq no tengo costumbre con los XPI.



> Nos falta el changelog que manteníamos hasta ahora, no sé si alguien lo ha generado (yo no he probado la opción del script, lo confieso).

El script no genera el changelog, sólo sirve de ayuda para prepararlo porque no he encontrado una manera razonable de generar el texto automáticamente a partir del histórico de cambios de git sin que salgan entradas irrelevantes fuera del equipo de desarrollo.



> Para futuras versiones, ¿creéis que deberíamos pensar en montar algo para que cada uno que suba cambios pueda ir añadiendo los términos que ha añadido, de forma que construyamos rápidamente un texto para hacer las pruebas? No todo el mundo lo hará, pero facilitará mucho el trabajo ahora.

Hombre, siempre que se pueda sistematiza una metodología de pruebas se supone que es mejor para el control de calidad. En teoría hasta podría automatizarse en el script a través de hunspell.

**Comment by olea** [comment]
> Nos falta el changelog que manteníamos hasta ahora, no sé si alguien lo ha generado (yo no he probado la opción del script, lo confieso).

Por cierto: que no he preparado el changelog de 2.6 yo mismo porque entiendo que no nos hemos dado el visto bueno definitivo para publicar. No tendría inconveniente en hacerlo.

**Comment by olea** [comment]
Pregun: ¿creéis que están resueltos todos los problemas? ¿qué puede quedar pendiente en vuestra opinión?

**Comment by RickieES** [comment]
Yo lo siento, pero no he tenido tiempo de hacer las pruebas y hoy tampoco lo voy a tener.

**Comment by RickieES** [comment]
Me refiero a hacer las que faltaban (neutral y XPI) ni tampoco he podido preparar el Changelog.

**Comment by olea** [comment]
> tampoco he podido preparar el Changelog.

Esto lo podría hacer yo en cuanto me lo digas.

**Comment by RickieES** [comment]
Estoy generando el diccionario de español internacional y lo hago con el flag `-l es`. Me da varios mensajes de advertencia:

```
Creando el fichero de afijos:
Advertencia: no he encontrado el fichero ortografia/afijos/l10n/es/afijos.txt
Advertencia: no he encontrado el directorio ortografia/palabras/RAE/l10n/es
Advertencia: no he encontrado el directorio ortografia/palabras/noRAE/l10n/es
Advertencia: no he encontrado el directorio ortografia/palabras/toponimos/l10n/es

```
El caso es que, mirando el ZIP, el fichero AFF existe, pero no me queda claro si hay error o no. Sobre todo, porque parece que busca archivos que no existen. Si se están usando las variantes generales, quizá tengamos que modificar el texto para indicar que "Se usará el fichero general".

**Comment by olea** [comment]
@RickieES No es un error. 

Simplemente un mensaje informativo. La idea es advertir qué localización usa o no los tipos de fichero que menciona y cuya ruta está normalizada en la configuración del script. Por la manera en que se creó el script estos mensajes parecen falsos positivos porque las rutas de los ficheros de datos del caso «es» es diferente de todas las demás. Pero como has comprobado efectivamente el corrector se ha creado correctamente.

El mensaje es más relevante al generar las variantes locales puesto que en muchos casos esos ficheros no existen.

Simplemente me pareció interesante mostrar la información. Entiendo que el mensaje puede ser confuso. Podemos dejarlo, modificarlo o eliminarlo.  Aceptaré vuestra opinión.

**Comment by RickieES** [comment]
Como el error puede darse con variantes regionales, donde sí tendría importancia, no es buena idea lo que yo decía antes (porque no será verdad en ese caso que se añade el general, corrígeme si me equivoco). Yo propondría que lo pensemos, quizá en un __issue__ separado.

**Comment by RickieES** [comment]
Acabo de comprobar que la regla que puse como ejemplo que faltaba en el fichero afijos.txt del OXT de es_ES sí está en la última que generé tras las correcciones que hiciste (creo que nunca sabremos qué pasó ahí).

En cualquier caso, todos los puntos están resueltos. Si queréis, se puede cerrar este _issue_ y abrir uno nuevo para lo del mensaje que aparece en la variante general.

**Comment by olea** [comment]
Cierro pues.
