### ISSUE TITLE
PREGUNTA - como obtener listado de palabras

### ISSUE THREAD

**Issue by gabriel-tandil** [sbosio/rla-es#240]
Hola estimados!
Me interesaría poder generar un listado de palabras con todas sus variaciones desde su excelente diccionario.
Es para usarlo en otro proyecto libre: https://github.com/gabriel-tandil/TraditionalT9
¿Tienen alguna herramienta que ayude a construir dicho listado?
Cordiales saludos
Gabriel

**Comment by sbosio** [comment]
Gabriel:

Vas a necesitar las herramientas que proporciona la biblioteca Hunspell. Generalmente está disponible como paquete para cualquier distribución de Linux, con el instalador `brew` para MacOS, y quizás incluso haya manera de instalarla en Windows.

Particularmente vas a necesitar la herramienta `unmunch` que te permite generar todas las derivaciones desde los lemas base etiquetados que se recogen en el listado de palabras (fichero con extensión `.dic`) aplicando las reglas del fichero de afijos (con extensión `.aff`) en el paquete del diccionario.

Resumiendo, necesitarás instalar el software que contiene el comando `unmunch` y, desde una terminal de comandos ejecutarlo pasándole como parámetros el nombre del fichero `.dic` y el del fichero `.aff`. Esos dos fichero se encuentran empaquetados en la extensión publicada en las releases del proyecto. Esas extensiones `.oxt` no son más que ficheros ZIP que se pueden descomprimir. Si tienes problemas para descomprimirlos, cambia la extensión del fichero de `.oxt` a `.zip` e intenta nuevamente.

Saludos,

Santiago

**Comment by gabriel-tandil** [comment]
Gracias por tu explicación Santiago! en unos días seguramente me ponga con ello.
Saludos

**Comment by Almorca** [comment]
Cierro la pregunta al estar resuelta.
