### ISSUE TITLE
Palabra "Dilución" no es reconocida

### ISSUE THREAD

**Issue by ohnekopf** [sbosio/rla-es#241]
creo que el título lo explica mas o menos todo. 
Gracias por llevar a cabo este proyecto!

**Comment by sbosio** [comment]
@ohnekopf, ¿podrías verificar qué versión del diccionario tienes instalada? Porque el término `dilución` ya ha sido añadido cuando menos a la última versión publicada.

**Comment by rubusarbaro** [comment]
Actualiza tu diccionario, y si no está, solo añádela con tu programa de ofimática.

**Comment by RickieES** [comment]
Esta palabra ya está reconocida como válida con la versión 2.6 del diccionario, asigno el _issue_ a esa versión y lo cierro.
