### ISSUE TITLE
Creando nuevo proyecto inspirado en este

### ISSUE THREAD

**Issue by imigueldiaz** [sbosio/rla-es#243]
Buenos dias,

Mi nombre es Iñaki, y hace un par de meses empecé con una idea un poco ambiciosa y en la que iré despacito por falta de tiempo y de conocimientos pero creo que puede ser divertida para mí y además aprender cosas nuevas.

Mi idea es hacer un programa libre en node..js para que los que escribimos relatos, novelas o lo que sea hagamos una primera corrección más facilmente haciéndonos ver lo que normalmente no vemos, como los adverbios en -mente, gerundios, exceso de conjunciones, adjetivos antepuestos y cosas así. Se carga un fichero word / markdown / texto plano... en el programa y este con una API interna se encarga de marcar con diferentes colores, fuentes etc en hojas de estilo css lo que encuentre para que el escritor pueda corregirlo si lo desea.

Inspirado en esta idea y me encontré con el proyecto [Wulf/nodehun](https://github.com/Wulf/nodehun) que es una implementación de hunspell en node con metodos _analize()_ _generate()_ etc. y con esta  maravilla de trabajo que estais haciendo por aquí.

Mi intención actual es crear un proyecto inspirado en esta que a partir de las listas de palabras y afijos en ortografia/ y los diccionarios finales de las releases incorpore a los últimos la información morfológica que hunspell permite tanto en el .dic como en el .aff. Este diccionario con banderas MA es el que luego usaría para mi proyecto de correcciones.

Si tenéis alguna sugerencia o restricción —no voy a tocar en absoluto vuestro trabajo, solo descargar las fuentes en mi proyecto referenciando en todo momento a rla-es— solo tenéis que comentarmelo :)

Aún estoy en fase de estudiar las listas, leer la documentación de hunspell y de rla-es y los issues, pero me apetece hacerlo, porque aunque llevo 20 años programando en realidad estudié biblioteconomía (bibliotecología fuera de España) y me apasiona trabajar con las lenguas naturales y su procesamiento.

Un cordial saludo
Iñaki de Miguel Díaz

**Comment by olea** [comment]
Hola:

Muchas gracias por avisarnos. Como bien entiendes, el diccionario del corrector es ortogonal motor del corrector así que en teoría no deberían ser necesarias modificaciones técnicas en el primero.

En cualquier caso, si a lo largo de tu proyecto compilas otra clase de recursos lingüísticos se puede considerar incluirlos en el repositorio. Y obviamente estás invitado a enviar notificaciones de error y sugerencias.

Gracias y mucho ánimo.

**Comment by cosmoscalibur** [comment]
@olea  @imigueldiaz es de cuidado validar el uso de la licencia, dado que esto implica una modificación sobre los archivos compiladores para incluir las banderas hunspell de categorías, se constituiría en un trabajo derivado. En ese caso, se debe tener presente todas las repercusiones de compatibilidad de licencias.

**Comment by imigueldiaz** [comment]
> 
> 
> @olea @imigueldiaz es de cuidado validar el uso de la licencia, dado que esto implica una modificación sobre los archivos compiladores para incluir las banderas hunspell de categorías, se constituiría en un trabajo derivado. En ese caso, se debe tener presente todas las repercusiones de compatibilidad de licencias.

Por supuesto si llego a algo mi licencia será libre y me puedo adaptar a lo que vosotros consideréis oportuno, aunque para eso aún queda mucho mucho tiempo. :-)
