### ISSUE TITLE
Palabra faltante: «Postulación»

### ISSUE THREAD

**Issue by gersonbdev** [sbosio/rla-es#248]

**Comment by RickieES** [comment]
Postulación está reconocida en la versión 2.6 del diccionario (la añadió @cosmoscalibur hace dos años en https://github.com/sbosio/rla-es/commit/cea1dca28e9919be4768fa4e538d729e0b660489). ¿Qué versión y variante regional estás probando?

**Comment by gersonbdev** [comment]
Tengo la versión 2.5 marcada como la mas reciente en la [Release List](https://extensions.libreoffice.org/en/extensions/show/spanish-dictionaries) del sitio de extensiones de LibreOffice, al revisar el repositorio de GitHub puedo ver que hay una nueva versión, pero encontrarla puede llegar a ser muy poco intuitivo para algunas personas.

Podría ser prudente realizar un sitio de GitHub Pages que sirva como presentación del repositorio, además de mantener el sitio de LibreOffice actualizado con tal que note cambios en versiones desde el mismo gestor.

![Captura de pantalla de gestor de extensiones](https://user-images.githubusercontent.com/59992003/147610308-809a4a46-6f0b-4be8-a556-b0255c50397e.png)

**Comment by RickieES** [comment]
Ya, es un problema conocido, por eso verás que el _issue_ de la versión 2.6 sigue abierto. Podemos subir las nuevas versiones aquí y al repositorio de diccionarios de LibreOffice para que la versión es_ANY se incluya en los binarios del propio LibreOffice, pero yo no he recuperado el acceso al gestor de extensiones de LibreOffice (ahora mismo solo lo tiene @sbosio) y, por ello,no puedo subir nuevas versiones al catálogo de extensiones de LibreOffice.

**Comment by gersonbdev** [comment]
Vale entonces procederé a cerrar este problema.
