### ISSUE TITLE
Faltante issue 11

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#25]
Añado aquí el fichero que hay en contrib/faltantes_issue_11.txt para eliminarlo del repositorio.

**Comment by Almorca** [comment]
abceso
abreviatio
absuelto
abúlicos
abusivamente
académicamente          -> Añado 'académicamente' en Adverbios.txt
acérrima
acérrimas
acérrimo
acérrimos
acervo
aclimatación
acotarles
acrolecto
acrolectos
acronimia
acrósticas
acrósticos
actancial
actanciales
actante
actantes
actio
acusadamente
adagia
Adam
adlatio
adlativo
adscribible
adstrato
aféresis
aforístico
africanismos
Agamenón
agentivo
aglutinador
agón
agramaticalidad
agrietándola
agrietándolas
agrietándolo
agrietándolos
aimara
Al-Andalus
Alarcón
Alarcos
Albacete
Alfarache
alfonsí
alfonsíes
alienígena
alienígenas
Alighieri
aliteración
aliteraciones
aljamía
aljamianas
Allan
almacenadores
Almería
alófono
alófonos
alomorfo
alomorfos
alter
Alvar
Amadís
Amanda
Amberes
americanismo
americanismos
Américas
Américo
amoenus
amplificatio
amplísima
Anabel
anacreóntica
anacronía
anacronías
anáfora
anáforas
anagnórisis
analepsis
analizante
anárquica
anárquicas
Andalucías
andalusí
Anderson
andiplosis
André
Andrómaca
anecdótica
anecdóticas
anecdótico
anecdóticos
angelicata
animalización
anisocronías
anisosilábico
anisosilábicos
anisosilabismo
antepuesta
antepuestas
antepuesto
antepuestos
antiateo
antiburgués
antiburguesa
antiburguesas
antiburgueses
anticatólica
anticatólicas
anticatólico
anticatólicos
anticlímax
anticopia
antidogmatismo
antifranquista
antifranquistas
Antígona
antihéroe
antiheroico
antihonor
antiliberal
antiliberales
antilogía
antimarxista
antimarxistas
antimasónico
antimasónicos
antimentalismo
antinovela
antiorientado
antiorientados
antirrealista
antirrealistas
antirreformista
antirreformistas
antirretoricismo
antitradicionales
antiyanqui
antropocéntrica
antropólogo
antropólogos
antropónimos
aperturismo
aperturismos
apicoalveolar
apocalipsis
Apocalipsis
apofántico
Apollinaire
apólogo
apólogos
Apolonio
apóstrofe
apotegmática
apoyatura
Apuleyo
Aquiles
Aragón
Aranjuez
archidiácono
archilexema
archisenema
argótico
argumentalmente
argumentatio
Ariel
aristocratismo
Aristófanes
Aristóteles
arquetípico
arquetípicos
Artemis
Ártemis
artificiosidad
artúrico
asambleario
Asclepio
aservativos
asibilación
asimetría
asincronías
asíndeton
aspectualización
astrológicos
Asturias
asturleonés
asturleonesa
atelicidad
atélico
atemporal
atemporales
Atenas
atraerles
Austin
autarquía
autentificación
autobiografismo
autobiógrafo
autoconcepto
autoconocimiento
autoconsciencia
Autocontrol
autocuestionamiento
autodefinía
autodiégesis
autodiegético
autodirigida
autoevaluación
Autoevalucación
autoexiliarse
autoinfligido
autorial
autorpostulándose
autorregulación
autorreguladora
autoselección
autosolventa
autosuficiente
Avignon
axiológica
axiológicas
axiológico
Ayala
Áyax
Aznar
Azorín
Baco
Baena
Bajtín
baladísticos
Baltasar
Balzac
Barbadillo
Barcelona
Bargas
Baroja
barroquización
Bartolomé
Baudelaire
Bazán
beatería
Becket
Bécquer
behaviorista
Benavente
benevolentia
Berlanga
Bernárdez
Berrio
betacismo
betacista
Betis
bienamado
Bigotsky
Bilbao
bilingüe
bilingües
bilingüismo
Bilingüismo
bimembraciones
biografismo
biparentales
bisílabas
bisílabos
biunivocidad
biunívoco
Blas
Bloomfield
Bocaccio
Boccaccio
Borges
Boscán
bostezos
braille
Brecht
Breton
Brevemente
brevísimo
Brunetiere
bucolismo
buldero
Buñuel
Burgos
burlescamente
Buscón
buscona
cacereña
cacereñas
cacereños
Cádiz
calderoniano
caligrama
caligramas
Calila
Calisto
Camus
cancioncillas
cancioneril
canónigas
cantarcillo
cantarcillos
cantautor
cántica
captatio
Captatio
Carabagio
carolinguio
Carón
Caronte
Carpentier
Carreter
Carrión
Casandra
Cassany
castellanización
catáfora
catáforas
catalogación
Cataluña
categorización
categorizadores
categorizar
Catonis
Cáucaso
causalista
Cecilia
Celi
Cernuda
Cervantes
cf
Cf
Cfr
Chanson
chatarrerías
chats
chinato
chinita
Chomsky
ciceante
cientifismo
cinésicos
circunfijos
cívicamente
clarísima
clasema
Clasema
clasemas
clasificativos
Claudio
Clitemnestra
clítico
clíticos
coeducación
Coeducación
coeducativa
Coéforas
coevaluación
cognitivamente
cohesionadores
cohipónimos
coiné
Coiné
coinización
collage
colocativo
colofón
Colofón
colonialista
coloquialismo
coloquialismos
Coloquialismos
coloquializadoras
coloquialmente
Comala
Comenius
comparativismo
competencial
competenciales
Complementación
componencial
componenciales
comprenderlos
compromisivos
computacional
Computacional
conativa
concedérsele
concéntrico
concienciación
conclusiva
conclusivo
conductismo
Conductismo
conductista
conductistas
configuracional
configuradores
confijos
Constantinopla
constatación
constitucionalistas
constructivismo
Constructivismo
constructivista
constructo
Constructo
contextualización
Contextualización
contextualizadoras
contraargumentaciones
contraargumentar
contraargumentativo
contraargumentos
contrafactum
contragénero
contraponerle
contrarreforma
Contrarreforma
contrarreformismo
contrarreformista
contrarreformistas
contrastivas
contrastivos
Contreras
convencerle
convivencial
cooficial
coorientados
copernicana
copernicanas
coralidad
Corán
coreferencia
coreuta
Coreuta
coreutas
corifeo
Corifeo
correferencia
correferencial
corregirles
correlacional
corresponsalías
Cortázar
Coseriu
cosificación
cotexto
co-texto
Covadonga
Covarrubias
creacionista
Creonte
crescendo
críptico
criptojudíos
Crisotemis
cristológica
criterial
Criticism
cronémica
cronística
Cronografía
Crussoe
cuadraangular
cuantificación
cuantificativo
cuantitativamente
cuentacuentos
cuentecillos
cuentística
cuestionamiento
culteranista
culteranistas
cultista
cultistas
culturalismo
Culturalismo
culturalista
culturización
cunanagoto
cuplé
currículum
cuzqueñas
dactílico
dáctilo
dadaísmo
Dadaísmo
dadaísta
dadaístas
Dafne
Dalí
Dámaso
Danaides
Darío
Darwin
deambulante
deán
debatible
Decamerón
decelera
deceleración
decelerada
deceleran
decimonónica
decimonónico
decorum
decurso
dedeo
deductivamente
definirla
definirlas
definirlo
definirlos
Defoe
degradadora
degradarla
Deísmo
delectare
Delectare
Delibes
delimitación
Delimitación
delimitaciones
delimitativo
demarcativo
democráticamente
democratización
Democratización
denotación
Denotación
depuradamente
dequeísmo
desafricación
desaprende
desarticulación
desautomatización
desautomatizado
descalificación
descomprometida
descomprometido
descomprometidos
desconcentraba
desconstructivista
descontaminación
descontextualizada
descontextualizar
deseducación
desentrañarlos
desestructurados
desfonologización
deshacerlo
deshumanización
desinencial
desmotivación
Desmotivación
desordenándolas
desorganización
desplezándose
destacable
Destacable
destacables
desvaríos
deus
Deuteronomio
Deux
Deyanira
diacrítica
diacríticos
diacronía
diacrónica
diacrónico
diacrónicos
diafasía
diafasías
diafásica
diafásicas
diáfora
diáforas
Dialectalización
dialectología
Dialectología
dialectológicos
dialógica
dialógico
Dialógico-conversacional
dialógicos
dialógicos-conversacionales
diasistemática
diastrática
diastráticas
diastrático
Diastrático
diatopía
diatópica
diatópicas
diatópico
Diatópico
Díaz
dicendi
Dick
Dickens
dicotomía
Dicotomía
didactismo
Didactismo
Didascalia
didascalias
diégesis
diegética
diegético
diem
diferenciables
diglosia
Diglosia
dignificación
dignificador
dignificándola
Digreivo
digresar
digresivos
digresor
Dijk
diletantismo
dilogía
dimna
Dimna
Dionisio
Dioniso
Dionisos
diptongación
dirigírselas
dirigismo
dirigista
dirigistas
discronía
disfunciones
disociativas
dispositio
disquisiciones
distanciación
distica
dístico
dísticos
distinguidor
distinguidora
distinguidoras
distinguidores
distopía
distópica
distópico
distorsionador
distorsionadora
distractiva
distribucional
distribucionales
divirtiéndolos
dixit
documentalmente
dodecasílabo
dodecasílabos
dolce
Dostoievski
dramatización
druts
Duarte
Duero
Ebro
Ecalia
Eclesiastés
Ecoescuela
ecuacional
Ecuacional
ecuandicional
ecuandicionales
Edgar
Edipo
Egisto
égloga
églogas
Eiffel
ejemplificación
ejemplificaciones
ejemplificadores
Electra
elidirlo
elisión
elocutio
Eloisa
Emirato
empatía
empática
empatice
empático
empatizaba
empatizar
encajarlos
enclíticamente
encomiable
encomium
encorsetamiento
endocéntrica
endocéntrico
endocéntricos
endofórica
endofóricas
enfatizables
enfatizadores
ensambladora
ensayística
ensayísticas
ensayístico
ensayísticos
entenderle
entendible
entonativa
entreguerras
enunciador
enunciadores
enxiemplo
enxiemplos
epéntesis
epentética
epentéticos
episcopalistas
episódica
episódicamente
episódico
epistemología
equiparación
Eramismo
érase
Érase
Erasmo
eremus
ergativos
Erinis
Ernest
escapista
escarceos
escatología
escatológicas
escatológico
escatologización
escenificación
escenificaciones
escrituraria
escrutinan
esdrújulo
esdrújulos
esópica
Esopo
espacialidad
espaciotemporales
espadazo
españolización
espiritualizarla
Espronceda
esquematizarla
estandarización
Estandarización
estándolo
estativos
esteriorizada
estetizante
estilema
Estilización
estratégicamente
estratificación
estrenársela
Estridentismo
estructurable
estructurador
estructuradoras
estructuradores
estructuralismo
Estructuralismo
estructuralista
Estructuralista
estructuralmente
Estructuralmente
Eteocles
étimo
etimológicamente
etnografía
Etnografía
etnográfico
Etnográfico
etnógrafo
etnología
etnológico
Etnológico
etnometodología
etopeya
Euménides
Eurídice
Eurípides
europeísta
europeización
evaluativas
evaluativo
evaluativos
evitación
evocativo
excomulgación
excurso
excursus
exempla
exemplos
exemplum
exhaustividad
exilios
existencialista
exocéntrico
exocéntricos
Exocéntricos
exofórica
exofóricos
expansionista
experiencial
experimentalismo
explicit
expresionista
expresionistas
extradiegético
extraliteraria
extraliterarias
extraliterario
extraliterarios
extraoracionales
extrapolable
extrapolables
extratextual
extratextuales
extrayéndola
Extremadura
extremeñas
extremeño
Extremeño
extremeños
extrínseca
extrínsecas
Fabio
Facebook
fálico
famosísimo
fática
fático
fatum
Faulkner
Federico
Fedra
Feijoo
feísmo
feísta
fenhedor
Ferdinand
Fernán
fernandinas
ficcional
ficcionales
Ficcionalidad
ficcionaliza
ficcionalización
Figueroa
fijaarlo
filantropía
filantrópico
Filoctetes
finalización
flagelaciones
flashback
Flaubert
Florinda
focalizables
focalización
Focalización
focalizaciones
focalizador
folclorismo
fonologización
foracidad
formalización
Foster
fragmentación
Fragmentación
fragmentarismo
franquismo
franquista
franquistas
Franz
fraseológica
fraseológicas
fregona
Freud
fricatiza
fricatizarse
frustrante
fugit
fundamentalistas
futurismo
Futurismo
Galaeta
Galatea
Galdós
Galicia
García
garcilasiana
garcilasiano
garcilasismo
Garcilaso
Gasset
Gaula
gazmoña
geada
geminación
geminaciones
generativismo
Generativismo
generativista
Generativista
generativistas
genesíacos
Genette
geocultural
George
Gerard
Gerineldo
germana
germanas
Gertrudis
gestualidad
Gili
globalización
globalizadora
glosemática
Glotalización
gnómica
gobernarlo
Goethe
Goliardos
Góngora
Gonzalo
goticismo
Gracián
Graciela
gradativos
gravísimo
Gredos
Greenpeace
greguería
greguerías
Grice
Grimm
grosso
Guadalquivir
Guadarrama
Guadiana
Guevara
Guillén
guionizada
Gulliver
Gustave
hagiografía
hagiográfica
hagiográficas
hagiográfico
hagiográficos
Halliday
Hamon
hardware
Hasan
Hécuba
Hegel
helenística
helenísticas
helenístico
helenísticos
heliodoriana
Heliodoro
Hemingway
hemorrágica
Henón
heptasilábicos
Hera
Heracles
Hermíone
Hernán
Heródoto
heterodiégesis
heterodiegética
heterodiegético
heterónimo
heterónimos
hexadecasílabos
hexámetro
hexámetros
hexasílabas
hexasílabos
hidalguización
hiperactivo
hipérbaton
hipérbatos
hiperonimia
hiperónimo
hiperónimos
hipertema
hipodiegético
hipodiegéticos
hiponimia
hipónimo
hipónimos
hipotácticas
hipotaxis
Hiroshima
hispanización
Hispanoamérica
hispanoamericanista
historialistas
historiografía
Hitler
Hjelmslev
hobbit
Hoffman
holismo
Hollywood
Homero
homodiégesis
homodiegética
homodiegético
homologación
homonímicos
Horacio
Horestíada
Huelva
hybris
Iberoamérica
Ícaro
idealizante
ideolectos
ideológicamente
ideólogo
idiolecto
idiolectos
idiomáticas
idiomático
Ifigenia
igualársele
Ildefonso
Ilíada
illud
ilocucionario
ilocutiva
ilocutivas
ilocutivo
ilocutivos
imaginería
Imitatio
impactos
imparisílaba
imperfectivo
implementos
implicatura
implicaturas
importantísima
importantísimos
imprecisión
imprecisiones
inacusativo
inacusativos
inadecuadamente
inalámbrica
inalámbrico
Inclán
incluyente
inconcreción
incordiante
incrustación
indefinitud
indignante
indistinción
individualización
inductivamente
inergativos
infanzones
infieri
infijo
infijos
infiriéndolos
inflexiona
infórmale
informatividad
infracultura
ingresión
inmanentismo
inmanentista
inmovilismo
inodrinación
insospechadamente
inspirarle
institucionalización
intelectualista
intencionalidad
interaccionismo
interactividad
interactúa
interactúan
interactuar
interactúe
interactúen
interconectadas
interconexión
interdependientes
interdisciplinar
interdisciplinares
interdisciplinarias
interdisciplinariedad
interfijos
interiorización
interlocución
internacionalmente
internet
interordinación
interordinadas
interpolación
interpolaciones
interpotencian
interrelacionadas
interrelacionados
interrelacionan
interrelacionar
interruptivas
intertextuales
intertextualidad
intorpolación
intracomunicación
intradiegético
intrahistoria
intrahistórica
intralingüística
intralingüísticamente
intralingüísticas
intralingüístico
intralingüísticos
intransitiva
intransitivas
intrascendentales
intratextual
inventatio
inventio
irracionalistas
irradiador
Isidoro
ismo
isoglosas
isosilabismo
isotopías
Isotopías
Ítaca
italianista
italianizante
italianizantes
Jackson
Jakobson
jarcha
jarchas
Jasón
jerárquicamente
jerarquización
jergal
John
Jose
Jovellanos
jovencita
jovencitas
jovencito
jovencitos
Joyce
judeoconversa
juglaría
Julieta
Justina
Kafka
Kant
Karcevskij
kinésico
kinésicos
Kurt
lacrimógena
lacrimógenas
laísmo
laísmos
laístas
lambdacismo
lambdacista
Lanzarote
Lapesa
Lara
Larrea
latinización
Latinoamérica
lectoescritura
Leech
leísmo
leísmos
leístas
leixaprén
Lemnos
Leonarda
Leonardo
leonesismos
Leonor
Leopoldo
Letrán
lexemática
lexemáticas
lexicalización
lexicalizaciones
lexicográfico
lexicográficos
lexicología
lexicológico
lexicón
linealmente
listísimo
literariedad
literaturizado
literaturizar
littera
lleísmo
lleístas
Llorac
localista
localistas
locucionario
locus
locutivo
locutivos
logas
loísmo
loísmos
Lolita
Londres
Lope
Lorca
Lucanor
Lucas
Luciano
Lutero
Luzán
m
Mª
Macondo
macroestructura
macroestructuras
macrorreglas
macrotextual
magister
Malarmé
Mallarmé
Mallorca
maltratadores
maltratarle
manierismo
manifestarlo
Manrique
mantón
maquetado
Mari
Martí
Marx
masificación
matización
Maupassant
Max
mecanicista
Medea
Medinaceli
mediums
mejorándolo
Melibea
melipea
Mellville
memorístico
memorísticos
Menandro
Menelao
Menéndez
mentalismo
mercantilización
mercurios
meridionalismos
mesolecto
mesolectos
mester
mesteres
metacognitivas
metadatos
metadiscursivos
metafonía
metafónico
metalingüística
metalingüístico
metaliteraria
metaliterarias
metaliteratura
metanovela
Metanovela
metateórico
metodológicamente
metodólogo
mezclándolo
mezclarlo
Michel
microcuento
microestructura
microestructuras
microrrelato
microrrelatos
Mihura
Millán
mimética
mimético
mínimamente
minusválidos
Miriam
miscelánea
misceláneas
misceláneo
misceláneos
misógina
misóginos
Mister
mitificación
moaxaja
moaxajas
Moby
modalización
modalizador
modalizadores
modalizante
Molière
monema
monemas
monocéntrica
monoclausal
monocorde
monografía
monografías
monolingüe
monologal
monologales
monológico
monológicos
mononucleares
monoptongación
monoptongaciones
monorimos
monosémico
monotemático
monovalencia
Montaigne
Montalbán
Montemayor
Monterroso
Montesquieu
moralismo
moralización
moralizante
moralizantes
Moratín
morfemática
morfemáticas
morfológicamente
morfosintáctica
morfosintácticas
morfosintáctico
morfosintácticos
morfosistaxis
Moscú
movere
mozárabe
mozárabes
Mozart
muladíes
multidimensional
multidisciplinar
multifuncionales
multisociograma
mundonovismo
mundonovista
muñequización
musicología
Mussolini
náhuatl
naïf
Nápoles
narcotráfico
narratario
narratio
narratología
narratológicas
narratológicos
nasalización
naucheros
nazismo
Nebrija
necrófago
negarlas
negarle
negarlo
negarlos
nemotécnicas
neobarroco
neobarroquismo
neoclásica
Neoclásicas
neoclásico
neoclásicos
neogótico
neogramáticos
neolingüística
neopicaresca
neopopularismo
Neoptólemo
neorealismo
neorrealismo
neorrealista
neorrealistas
neorretórica
neosurrealismo
neotradicionalistas
neovanguardia
neovanguardista
Neruda
Neso
neurolingüística
neurolingüísticas
neuropsicológico
neutralizables
neutralización
New
Nietzsche
nítidamente
nº
nominación
nominaciones
nominalización
nominalizaciones
normalización
normalizadora
normativamente
nororiental
Novalis
novecentismo
novelable
novelística
novelísticas
novelístico
novelísticos
novelita
novelización
novella
novellieri
noventayochistas
nuovo
ó
º
objetivable
objetivismo
objetivista
obligándole
obligatoriamente
Obregón
Octavio
octosilábica
octosilábico
ocurrirle
Odiseo
Oliveiros
omne
Onetti
Onieva
online
onomasiológico
ontológicamente
optatividad
oralidad
oralizados
oralizar
Ordóñez
Orestea
Orestes
orgullosísimo
Orinoco
Ovidio
Oviedo
oxímoron
Ozores
p
pág
paganidad
págs
Paideia
paisajístico
palatalización
palatarizara
parábasis
paradigmáticamente
paradigmáticas
paradigmático
paradigmáticos
paradigmatismo
paradójicamente
paralelística
paralelísticas
paralelísticos
paralenguaje
paralingüísticas
paralingüístico
paralingüísticos
parasíntesis
parasintéticos
parataxis
paratexto
paratextos
parcelación
parecerles
parnasianismo
parnasianistas
paródica
paródico
paródicos
Párodos
paroxítono
particularizadora
pasivización
pasodoble
pastorela
paternalista
patronímicos
Paul
Peán
pedófilas
pedofilia
pendrive
Penélope
Pentateuco
perderlo
perfeccionismo
perfeccionista
perfeccionitsa
performativos
perifrásticas
perifrástico
perifrásticos
perlocucionario
perlocutivo
perlocutivos
permítanme
peronismo
peroratio
Persia
perspectivismo
pervivencia
Peter
Petersburgo
Petrarca
petrarquismo
Petronio
Piaget
picardía
Picasso
picha
Pidal
pigmalión
Pisones
plantearles
plantos
plasmación
Platón
Plauto
pleonástica
pleonásticos
pluralia
pluraria
pluriestilística
pluriestilístico
plurifuncionalidad
plurigenérica
plurigenérico
plurilingüe
plurilingüismo
plurisignificativa
pluritemática
Plutón
Poe
poemario
poemática
poéticamente
polarizadores
Polidoro
Polifemo
políglota
Polimestor
polimetría
polimétrica
políptoton
polirrítmica
polisémica
polisémicas
polisémico
polisémicos
polisílaba
polisílabos
polisíndeton
polisistemas
politización
polivalencia
polivalencias
Polixena
popularismo
popurrí
porteño
Portolés
Poseidón
posicional
positivimismo
posliminares
posmoderna
posmodernismo
posmoderno
posmodernos
posposición
postergación
posteriori
postformalismo
postismo
postistas
postramiento
póstumamente
posturales
potenciación
potenciador
Potier
Prada
Praga
preactivación
precediéndolos
predorso
predorsodental
predorsodentales
preensayística
prefijación
pregador
preintelectual
prelingüística
Prelingüística
prelingüístico
preludiendo
premoniza
prenarrativos
prepalatal
prepalatales
prerrealismo
prerrenacentista
prerrenacimiento
prerromántico
prerrománticos
prescriptiva
prescriptivo
presimbólicas
presumiblemente
presuposición
presuposiciones
pretendidamente
prevalencia
preverbal
primordialmente
priori
proadverbios
probatio
prodesse
Proedria
proforma
proformas
prolexis
Prometeo
promiscuos
pronominaliza
pronominalización
pronominalizado
pronominalizan
pronominalizar
pronominalizarse
pronominalmente
pronuntiatio
propedéutico
Propp
prosificación
prosificaciones
prosística
prosístico
prosísticos
prosopografía
prospectos
prototípica
prototípicas
prototípico
prototípicos
Proust
Provenza
provocándole
provocarle
proxémica
proxémico
proxémicos
proyectarle
psicocrítica
psicodélicas
psicolingüística
psicolingüísticas
psicológicamente
psicopedagógico
psicosomáticos
pulcramente
purgación
purificativo
puzles
quemarlos
quesuísmo
Quevedo
quiasmo
quiasmos
quincenalmente
quinésica
Quiñones
Quintiliano
quíntuple
quirófano
Quiroga
radicalidad
radicalización
Raimundo
Ramiro
rap
rapsódica
rapsódico
readaptado
reafirmación
realizarlas
realizarlo
realizarlos
recategoricen
rección
recconociéndole
recicladora
recombinarla
recortables
recreador
recreadores
recuperarlos
recurrencia
recursividad
recursivo
redescubrimiento
reduplicación
reduplicador
reelabora
reelaboración
reelaborada
reestructuración
referencial
referenciales
reflexividad
reformantes
reformismo
reformula
reformulación
reformulaciones
reformulado
Reformuladores
reformulan
reformular
reformularlas
refundición
refundiciones
refutatio
regeneracionistas
regionalmente
rehumanización
rehumanizar
reinterpretación
reinterpretaciones
reinterpretadas
relacionante
relacionantes
relectura
rematización
remodela
René
renegación
reordenan
representatividad
resaltable
reses
responsablemente
retardantes
retroalimentación
retroalimentan
retrocanalizar
retrospecciones
reutilizables
revalorización
ridiculización
Rimbaud
Rinconete
Rivas
Robinson
rococó
Rodolfo
Roland
Roldán
romain
Roman
romancística
romancísticas
romancístico
romancísticos
Romania
romantísticas
romantísticos
Rómulo
rotacista
Rotterdam
Rousseau
rúbrica
Rulfo
rupturista
ruralismo
s
sacándole
sáfico
Sahara
Salamanca
salirle
Samósata
Samuel
sangrándolo
Sannazaro
Santillana
sapiente
Sartre
Satán
Saussure
Schopenhauer
Scott
Searle
secuenciación
secularización
sema
semańtica
semánticamente
semas
semasiológico
sémico
semiconsonántica
semiconsonántico
semiconsonánticos
semilibre
semiológicas
semiótica
semióticas
semióticos
semivocálicos
Sendebar
senderismo
senema
señeras
sentenciosidad
serigrafías
serradillano
Serrat
seseante
Shakespeare
sicalípticas
Sicilia
Sidonia
significatividad
sigs
simbolización
Simpsons
sinapsia
síncopa
sinestésicos
singularia
singulativa
singulativo
sinonímica
sinonímicas
sinóptico
sintácticamente
sintagmatismo
sintetizante
sintonía
sintonías
sirventés
siseante
sistematización
situacional
situacionales
Skinner
slogan
snob
sobreentenderla
sobrenaturalidad
socialización
socioafectivo
socioeconómicas
socioeconómico
socioeconómicos
sociograma
sociolecto
sociolectos
sociolingüística
sociolingüísticas
sociolingüístico
sociolingüísticos
sociológicamente
sociopolítica
sociopolíticas
sociopolíticos
Sócrates
sofisticación
Sófocles
somatolalia
sonorización
Soria
sorprendentemente
sosegarlo
Sperber
Sta
Stendhal
Stevenson
stil
stilnovismo
subapartado
subapartados
subcampo
subdisciplina
subdisciplinas
subgrupo
sublenguaje
subliteratura
suboracional
suboracionales
subsistemas
subtemas
sufijación
sumativa
Sumativa
sunt
superconcepto
superestrato
superestructura
superestructural
superestructuras
supralingüísticas
supralingüísticos
supraoracional
suprasegmentales
sustantivación
sustantivadora
sustituyentes
Swift
Talavera
Tannen
tantum
Tarquinia
Tarquinias
Tarquinio
Tarquino
Tarquis
teatralización
Tebas
Tecmesa
tecnócratas
tecnolectos
Teicoscopía
Telémaco
teletienda
telicidad
télico
tematización
tematizaciones
tematizadores
temporización
Temporización
tempus
tendenciosidad
teocéntrica
teocentrismo
teorización
teosófico
Terencio
terminológica
terminológicamente
terminológicas
terribilis
Teseo
Tesnière
tetralogía
tetrástrofo
textualidad
textualización
Timoneda
tipificación
tipología
tipologías
Tiresias
Tisón
titán
titánica
Todorov
Tolkien
Tolomeo
Tolstoi
tonemas
topicalización
Topoi
toponímicas
Tormes
totalizadora
tradicionalizan
transcategorización
transcategorizadores
transcodifica
transcodificar
transcriptor
transexual
transfonologización
transitividad
transliteración
transpositora
transpositores
transversalidad
trasvasamiento
trasvasamientos
traumática
Trento
Triana
tricotomía
triplemente
Troya
tuércele
tutoría
tutorial
tutoriales
tutorías
tutorización
Úbeda
Ulises
ulterioridad
ultracorrecta
ultraísmo
ultraísta
ultraístas
Umberto
Unamuno
unidireccionalmente
unidiriccionales
unificador
unilateralidad
unimembres
urbis
Valdés
Valerio
Valéry
Válgame
Valladolid
Vallecas
Valle-Inclán
valorativa
valorativas
valorativo
variacionista
veámoslo
vehicula
vehiculan
vehicular
velarización
Velázquez
verbalización
verificable
verista
vernacularización
Verne
versiona
vertebrador
victimista
Victor
Vigotsky
Villena
violentación
Virgilio
visigótico
vivencial
vivirla
Vladimir
vocalización
voseante
Vulcano
Walt
Walter
watio
webquest
Weldrich
Werlich
Werther
Whitman
wiki
Wikipedia
wikis
William
Willson
Woolf
yámbico
yeísmo
yeísta
yeístas
Yocasta
yod
yuxtaponiéndolos
Zamora
zéjel
zéjeles
zejelesca
zejelescas
Zeus
Zola
Zorrilla

**Comment by eksperimental** [comment]
Acabo de subir el archivo como un gist: https://gist.github.com/eksperimental/46b300cb3059d6969eb9
No aconsejaria dejar listas tan largas en la discusiones, ya que dificulta su navegación.

**Comment by ezeperez26** [comment]
El archivo que se ha eliminado correspondía al _issue_ #11 de GitHub.
Quizás se borró pensando que procedía del antiguo repositorio.
De todas maneras, el archivo sigue disponible en el _branch_ [issue_11](https://github.com/sbosio/rla-es/tree/issue_11).
Como este _issue_ es un duplicado del #11, lo cierro. Toda discusión relacionada la continuamos allá.
