### ISSUE TITLE
¿Sufijo para formas verbales repetido?

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#251]
Trabajando en la versión 2.7 me he encontrado lo que parecen ser dos sufijos para formas verbales que hacen exactamente lo mismo:

> 
> Verbos en infinitivo con clíticos de objeto directo o indirecto en
> 1ª y 2ª persona, singular y plural; en posición enclítica.
> SFX Á Y 4
> SFX Á 0         me        r
> SFX Á 0         te        r
> SFX Á 0         nos       r
> SFX Á 0         os        r
> 
> Verbos que aceptan conjugación pronominal en infinitivo, con pronombre
> personal reflexivo/recíproco; en posición enclítica.
> SFX ñ Y 4
> SFX ñ 0        me            r
> SFX ñ 0        te            r
> SFX ñ 0        nos           r
> SFX ñ 0        os            r
> 

Ya sé que tienen definiciones diferentes, pero (y esto es una pregunta para quien sabe, @sbosio) ¿no son redundantes, en la práctica y formalmente?

**Comment by cosmoscalibur** [comment]
Aunque la formación pueda ser redundante, al usar una herramienta de análisis de sintaxis basada en hunspell, tener estas reglas separadas es útil (y considerando nuestra mención en el _readme_ para futura corrección gramatical).

**Comment by cosmoscalibur** [comment]
Basado en la distinción para un eventual futuro de corrector gramatical y de la posibilidad de usar el analizador de sintaxis de hunspell, se puede cerrar este reporte
