### ISSUE TITLE
Faltan «acrítico, ca» y su adverbio en -mente; «presciente»

### ISSUE THREAD

**Issue by jorgesumle** [sbosio/rla-es#261]
Por cierto, ¿hay alguien que pueda revisar y aceptar mis contribuciones? Llevan mucho tiempo abiertas.

**Comment by cosmoscalibur** [comment]
@jorgesumle , no requieres un   reporte nuevo para esto. Puedes hacer un comentario en el  _pull request_ de la contribución.  Veo que el comentario por lo mismo no corresponde al título, y que el título corresponde a otra contribución de la que solicitas revisión, por lo cual cierro el reporte.

**Comment by cosmoscalibur** [comment]
@jorgesumle , ajustar descripción del reporte para que corresponde y reabres. La idea es no mezclar discusiones de varios temas para que sean claros los reportes.
Respecto a los tiempos de respuesta y revisión, este proyecto es de voluntarios, y tras la pandemia para muchos ha sido complejo retomar (me incluyo).

**Comment by jorgesumle** [comment]
Lo de esta incidencia lo he añadido como *commit* a #256
