### ISSUE TITLE
Propuesta de particiones

### ISSUE THREAD

**Issue by pereelmagne** [sbosio/rla-es#264]
# Pere Farrando
# perefarrando2@gmail.com

### En general

alcohol, alcoholes (al-cohol)
brahmanismo, brahmanismos (brah-ma-nis-mo, *Ortografía lengua española* 2010, apartado f, p406-407)
ciberromance, ciberromances (ciber-)
ciudadrealeña, ciudadrealeñas, ciudadrealeño, ciudadrealeños
cohibir, cohibido, etc.
desabor, desabores (de-sa-bor, *Ortografía lengua española* 2010, p408)
euroescepticismo
euroescéptica, euroescépticas, euroescéptico, euroescépticos
geofísica, geofísicas, geofísico, geofísicos
sushi, sushis (su-shi, no sus-hi)
vehicular, vehiculares (vehi-cu-lar, *Ortografía lengua española* 2010, apartado f, p406-407)
vihuela, vihuelas (vihue-la, *Ortografía lengua española* 2010, apartado f, p406-407)

### Para respetar los prefijos

hiperrealismo, hiperrealismos (hiper-)
hiperrealista, hiperrealistas
interétnica, interétnicas, interétnico, interétnicos (inter-)
interinstitucional, interinstitucionales
interoceánica, interoceánicas, interoceánico, interoceánicos
interraciales, interracial
interregional, interregionales
interrelacionada, interrelacionadas, interrelacionado, interrelacionados
interrelacionar, etc.
interrelación, interrelaciones
interreligiosa, interreligiosas, interreligioso, interreligiosos
interregno, interregnos
medioambientales, medioambiental (medio-)
medioambiente
mileurista, mileuristas (mil-)
neognóstica, neognósticas, neognóstico, neognósticos (neo-)
postfija, postfijas, postfijo, postfijos (post-)
postverbales, postverbal
preptolemaica, preptolemaicas, preptolemaico, preptolemaicos (pre-)
reediciones, reedición (re-)
superratones, superratón (super-)
superrápida, superrápidas, superrápido, superrápidos

### Para evitar formas malsonantes

disputa, disputas (dispu-ta)
espectáculo, espectáculos (es-pec-tácu-lo)
tentáculo, tentáculos (ten-tácu-lo)

**Comment by cosmoscalibur** [comment]
Un avance importante queda en nuestra próxima versión. Algunos casos quedan fuera del alcance y no se resolverán.
