### ISSUE TITLE
Propuesta de vocabulario general

### ISSUE THREAD

**Issue by pereelmagne** [sbosio/rla-es#266]
## Vocabulario general

Por Pere Farrando <perefarrando2@gmail.com>

Abajo incluyo unas cuantas entradas con ciertos prefijos y sufijos.  

Para los verbos, indico toda la conjugación así: 'digitalizar, etc.'

Lista: 

alguerés, algueresa, alguereses
almodovariana, almodovarianas, almodovariano, almodovarianos
ángstrom, ángstroms
argán
ayurvédica, ayurvédicas, ayurvédico, ayurvédicos
biomédica, biomédicas, biomédico, biomédicos
biosfera, biosferas
búnker, búnkers
canelón, canelones
cantaor, cantaora, cantaoras, cantaores
canterana, canteranas, canterano, canteranos
cardiovascular, cardiovasculares
casuística
centrista, centristas
colofón, colofones
complementariedad, complementariedades
conectividad, conectividades
corazoncito, corazoncitos
correduría, corredurías
corresponsabilidad
crioterapia
criptomoneda, criptomonedas
cuatricromía, cuatricromías
dírham, dírhams
dírhem, dírhems
editaje, editajes
efeméride
empresariado, empresariados
enoturismo, enoturismos
epidural
escáner, escáneres
escapista, escapistas
excepcionalidad, excepcionalidades
faulkneriana, faulknerianas, faulkneriano, faulknerianos
fiscalidades
focaliza
freudiana, freudianas, freudiano, freudianos
fuagrás
globalidad, globalidades
gobernabilidad, gobernabilidades
góspel
hammam
helenística, helenísticas, helenístico, helenísticos
hitchcockiana, hitchcockianas, hitchcockiano, hitchcockianos
holística, holísticas, holístico, holísticos
hombrecitos
icónica, icónicas, icónico, icónicos
iconográfica, iconográficas, iconográfico, iconográficos
impatriada, impatriadas, impatriado, impatriados
insolidaria, insolidarias, insolidario, insolidarios
isotópica, isotópicas, isotópico, isotópicos
isótopo, isótopos
ítems
macroeconomía, macroeconomías
macroeconómica, macroeconómicas, macroeconómico, macroeconómicos
magnetoterapia
megafonía, megafonías
metacrilato, metacrilatos
microbioma, microbiomas
montaditos
mujercita, mujercitas
multidisciplinar, multidisciplinares
multisensorial, multisensoriales
narco, narcos
neopreno
numismática, numismáticas, numismático, numismáticos
orografía
ortotipografía, ortotipografías
ortotipográfica, ortotipográficas, ortotipográfico, ortotipográficos
parafarmacia, parafarmacias
payés, payesa, payesas, payeses
peregrinante, peregrinantes
pichichi, pichichis
pícnic, pícnics
piececito, piececitos
porticada, porticadas, porticado, porticados
posicional, posicionales
positividad, positividades
potenciador, potenciadora, potenciadoras, potenciadores
prevalencia, prevalencias
psicosocial, psicosociales
puzle, puzles
ramita, ramitas
ranking
rúcula
saharauis
saheliana, sahelianas, saheliano, sahelianos
salpicón, salpicones
serendipia
sistematicidad
solecito, solecitos
sónica, sónicas, sónico, sónicos
subcampeón, subcampeona, subcampeonas, subcampeones
tailandés, tailandesa, tailandesas, tailandeses
teletransporte, teletransportes
termolúdica, termolúdicas, termolúdico, termolúdicos
tipología, tipologías
transfronteriza, transfronterizas, transfronterizo, transfronterizos
trotskismo
trotskista, trotskistas
veinteañera, veinteañeras, veinteañero, veinteañeros
vinícola, vinícolas

### Prefijo auto-

autocomplacencia
autodefinir, etc.
autoproducir, etc.

### Prefijo co-

codirector, codirectora, codirectoras, codirectores
coguionista, coguionistas
cooficialidad
coorganización, coorganizaciones
coorganizador, coorganizadora, coorganizadores
copríncipe, copríncipes

### Prefijo des-

desconexión, desconexiones

### Prefijo -inter

interconectada, interconectadas, interconectado, interconectados
interinstitucional, interinstitucionales
intermodal, intermodales
interoceánica, interoceánicas, interoceánico, interoceánicos, 

### Prefijo post-

postconciliar, postconciliares
postoperatoria, postoperatorias, postoperatorio, postoperatorios

### Prefijo re-

redistributiva, redistributivas, redistributivo, redistributivos

### Prefijo semi-

semifinalista, semifinalistas
semipresencial, semipresenciales

### Sufijo -ador

dinamizador, dinamizadora, dinamizadoras, dinamizadores
goleador, goleadora, goleadoras, goleadores
vertebrador, vertebradora, vertebradoras, vertebradores

### Sufijo -ble

enchufable, enchufables
esquiable, esquiables
homologable, homologables

### Sufijo -ción

concienciación
cuantificación, cuantificaciones
degustación, degustaciones
dignificación
equipación, equipaciones
hidratación, hidrataciones
homogeneización, homogeneizaciones
homologación, homologaciones
miniaturización
minimización
potenciación
reactivación, reactivaciones
robotización
socialización, socializaciones

### Sufijo -ético

cibernética, cibernéticas, cibernético, cibernéticos

### Sufijo -ismo

barranquismo, barranquismos
escapismo, escapismos
europeísmo, europeísmos
termalismo, termalismos

### Sufijo -ísimo

amplísima, amplísimas, amplísimo, amplísimos
brillantísima, brillantísimas, brillantísimo, brillantísimos
contadísima, contadísimas, contadísimo, contadísimos
cuidadísima, cuidadísimas, cuidadísimo, cuidadísimos
facilísima, facilísimas, facilísimo, facilísimos
feísima, feísimas, feísimo, feísimos
importantísima, importantísimas, importantísimo, importantísimos
utilísima, utilísimas, utilísimo, utilísimos

### Sufiho -ista

europeísta, europeístas
expresionista, expresionistas

### Sufijo -izar

digitalizar, etc.
monitorizar, etc.
verbalizar, etc.

### Sufijo -mente

audazmente
genéticamente
estadísticamente
terminológicamente

### Sufijo -ólogo

enóloga, enólogas, enólogo, enólogos
neumóloga, neumólogas, neumólogo, neumólogos

### Sufijo -lógico

inmunológica, inmunológicas, inmunológico, inmunológicos
serológica, serológicas, serológico, serológicos

**Comment by olea** [comment]
> ## Propuesta de entradas para la extensión Hunspell de idioma español

Pregun: ¿cuál es el origen de esta selección?

**Comment by pereelmagne** [comment]
Proviene de mi trabajo como corrector y traductor. Se trata de las listas que mantengo para controlar lo que hago con los diccionarios de InDesign. En vez de utilizar el diccionario del usuario de InDesign por defecto, creo tres personalizados: uno para particiones, otro para nombres propios y otro para palabras de lengua general. Periódicamente voy viendo si se han incorporado palabras de mis listas, pero el Hunspell de español hace mucho tiempo que no se actualiza.

Luego, la organización que se ve aquí responde solamente a mi costumbre. Me sirve para ver qué sufijos y prefijos están más necesitados de una actualización. Yo no domino nada de programación y no sé cómo se crean los criterios en Hunspell. Solo sé que en catalán el paquete de Hunspell está en un estado óptimo de actualización. Cuando tengo sugerencias para el catalán, las doy en un grupo de Telegram y la persona responsable se encarga de introducirla rápidamente. Este es el objetivo. 

La diferencia con el catalán es que aquí (en Cataluña) existe una empresa, Softcatalà, que tiene personas trabajando en herramientas lingüísticas de todo tipo, entre las cuales el paquete Hunspell. Esta empresa tiene acceso a bases de datos de diccionarios y a corpus de textos. Ahí está la clave: partir de un material de base amplio. 

Solo comento esto como aportación, porque no tengo conocimientos ni de JavaScript, ni de Python, ni de nada por el estilo. Mi colaboración puede ser la de aportar casos que Hunspell no resuelva bien.

Espero que mis comentarios hayan sido de ayuda.

**Comment by olea** [comment]
Conozco a Softcatalà y a gente de allí y siempre me han dado envidia :-)

**Comment by cosmoscalibur** [comment]
Estado actual del reporte. He removido lo que ya se incluye.

# Listas
alguerés, algueresa, alguereses
almodovariana, almodovarianas, almodovariano, almodovarianos
ángstrom, ángstroms
argán
ayurvédica, ayurvédicas, ayurvédico, ayurvédicos
canelón, canelones
canterana, canteranas, canterano, canteranos
corazoncito, corazoncitos
crioterapia
cuatricromía, cuatricromías
dírham, dírhams
dírhem, dírhems
editaje, editajes
efeméride
empresariado, empresariados
enoturismo, enoturismos
epidural
escapista, escapistas
excepcionalidad, excepcionalidades
faulkneriana, faulknerianas, faulkneriano, faulknerianos
fiscalidades
fuagrás
globalidad, globalidades
góspel
hammam
hitchcockiana, hitchcockianas, hitchcockiano, hitchcockianos
hombrecitos
impatriada, impatriadas, impatriado, impatriados
insolidaria, insolidarias, insolidario, insolidarios
isotópica, isotópicas, isotópico, isotópicos
macroeconomía, macroeconomías
macroeconómica, macroeconómicas, macroeconómico, macroeconómicos
magnetoterapia
metacrilato, metacrilatos
microbioma, microbiomas
montaditos
mujercita, mujercitas
multisensorial, multisensoriales
narco, narcos
parafarmacia, parafarmacias
payés, payesa, payesas, payeses
peregrinante, peregrinantes
pichichi, pichichis
pícnic, pícnics
piececito, piececitos
potenciador, potenciadora, potenciadoras, potenciadores
psicosocial, psicosociales
puzle, puzles
ranking
rúcula
saharauis
saheliana, sahelianas, saheliano, sahelianos
salpicón, salpicones
sistematicidad
solecito, solecitos
teletransporte, teletransportes
termolúdica, termolúdicas, termolúdico, termolúdicos
transfronteriza, transfronterizas, transfronterizo, transfronterizos
trotskismo
veinteañera, veinteañeras, veinteañero, veinteañeros
# Prefijo auto-
autocomplacencia
autoproducir
# Prefijo co-
coguionista, coguionistas
cooficialidad
coorganización, coorganizaciones
coorganizador, coorganizadora, coorganizadores
copríncipe, copríncipes
# Prefijo -inter
intermodal, intermodales
interoceánica, interoceánicas, interoceánico, interoceánicos,
# Prefijo post-
postconciliar, postconciliares
postoperatoria, postoperatorias, postoperatorio, postoperatorios
# Prefijo semi-
semipresencial, semipresenciales
# Sufijo -ador

vertebrador, vertebradora, vertebradoras, vertebradores
# Sufijo -ble
enchufable, enchufables
esquiable, esquiables
homologable, homologables
# Sufijo -ción
equipación, equipaciones
minimización
robotización
# Sufijo -ismo
barranquismo, barranquismos
escapismo, escapismos
europeísmo, europeísmos
termalismo, termalismos
# Sufijo -ísimo
amplísima, amplísimas, amplísimo, amplísimos
brillantísima, brillantísimas, brillantísimo, brillantísimos
contadísima, contadísimas, contadísimo, contadísimos
cuidadísima, cuidadísimas, cuidadísimo, cuidadísimos
facilísima, facilísimas, facilísimo, facilísimos
feísima, feísimas, feísimo, feísimos
utilísima, utilísimas, utilísimo, utilísimos
# Sufijo -ista
europeísta, europeístas

# Sufijo -mente
audazmente
terminológicamente

# Sufijo -ólogo
enóloga, enólogas, enólogo, enólogos
neumóloga, neumólogas, neumólogo, neumólogos

# Sufijo -lógico
serológica, serológicas, serológico, serológicos

**Comment by cosmoscalibur** [comment]
Lemas pendientes

Estado actual del reporte. He removido lo que ya se incluye.

# Listas
alguerés, algueresa, alguereses
almodovariana, almodovarianas, almodovariano, almodovarianos
ayurvédica, ayurvédicas, ayurvédico, ayurvédicos
canelón, canelones
canterana, canteranas, canterano, canteranos
corazoncito, corazoncitos
crioterapia
cuatricromía, cuatricromías
dírham, dírhams
dírhem, dírhems
editaje, editajes
empresariado, empresariados
enoturismo, enoturismos
faulkneriana, faulknerianas, faulkneriano, faulknerianos
fuagrás
hammam
hitchcockiana, hitchcockianas, hitchcockiano, hitchcockianos
hombrecitos
impatriada, impatriadas, impatriado, impatriados
macroeconomía, macroeconomías
macroeconómica, macroeconómicas, macroeconómico, macroeconómicos
magnetoterapia
metacrilato, metacrilatos
microbioma, microbiomas
montaditos
mujercita, mujercitas
multisensorial, multisensoriales
parafarmacia, parafarmacias
payés, payesa, payesas, payeses
peregrinante, peregrinantes
pichichi, pichichis
piececito, piececitos
saheliana, sahelianas, saheliano, sahelianos
solecito, solecitos
teletransporte, teletransportes
termolúdica, termolúdicas, termolúdico, termolúdicos

# Prefijo post-
postconciliar, postconciliares
postoperatoria, postoperatorias, postoperatorio, postoperatorios
# Sufijo -ísimo
amplísima, amplísimas, amplísimo, amplísimos
brillantísima, brillantísimas, brillantísimo, brillantísimos
contadísima, contadísimas, contadísimo, contadísimos
cuidadísima, cuidadísimas, cuidadísimo, cuidadísimos
facilísima, facilísimas, facilísimo, facilísimos
feísima, feísimas, feísimo, feísimos
utilísima, utilísimas, utilísimo, utilísimos

**Comment by cosmoscalibur** [comment]
Estado de pendientes

alguerés/GS
almodovariano/GS
ayurvédico/GS
canelón/S
canterano/GS
crioterapia/S
cuatricromía/S
dírham/S
dírhem/S
editaje/S
empresariado/S
enoturismo/S
faulkneriano/GS
fuagrás
hammam
hitchcockiano/GS
hombrecito/S
impatriado/GS
magnetoterapia/S
metacrilato/S
montadito/S
mujercita/S
multisensorial/S
parafarmacia/S
payés/GS
peregrinante/S
pichichi/S
piececito/S
saheliano/GS
solecito/S
termolúdico/GS
