### ISSUE TITLE
No corrige unas palabras. ¿Cómo agrego palabras?

### ISSUE THREAD

**Issue by christianbueno1** [sbosio/rla-es#268]
Saludos.
### Palabras
nombre: pagina, grafico
diccionario: es_EC

###  Información
```
[chris@fedora ~]$ ll /usr/share/hunspell/es*
-rw-r--r--. 1 root root 160068 Jan  2  2018 /usr/share/hunspell/es_EC.aff
-rw-r--r--. 1 root root 677843 Jan  2  2018 /usr/share/hunspell/es_EC.dic

[chris@fedora hunspell-spelling-checker]$ cat /usr/share/hunspell/es_EC.dic |grep -P "^página|^gráfico"
gráfico/GS
gráfico/mGS
página/S

[chris@fedora hunspell-spelling-checker]$ hunspell --version
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.0)


Copyright (C) 2002-2014 László Németh. License: MPL/GPL/LGPL.

Based on OpenOffice.org's Myspell library.
Myspell's copyright (C) Kevin Hendricks, 2001-2002, License: BSD.

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
to the extent permitted by law.
[chris@fedora hunspell-spelling-checker]$ 
```
### archivo prueba: foo4.txt
```
Esta pagina contiene mucha informacion.
El grafico es muy explicativo.
```
### Ejecutando:
```
hunspell -d es_EC foo4.txt
```
### Que realiza actualmente.
Me permite corregir solo la palabra información. 

###  Que espero que realize.
Que me permita corregir también las palabras: página, gráfico.

De paso cuando ocurre ello, como puedo agregar estas palabras al sistema hunspell.

**Comment by Almorca** [comment]
Hola @christianbueno1 

La palabra grafico sin tilde hunspell no la detecta como incorrecta ya que es una conjugación del verbo graficar.

En concreto le aplica esta regla.
#
# Presente del indicativo.
#
SFX E ar        o         ar        # 1ª pers. sing., terminación -ar.
