### ISSUE TITLE
Falta palabra eñe

### ISSUE THREAD

**Issue by jorgesumle** [sbosio/rla-es#269]
https://dle.rae.es/e%C3%B1e

La olvidada letra eñe (ñ).

**Comment by benjavalero** [comment]
Si se ha mezclado en la rama principal, la incidencia podría darse por resuelta. ¿O hace falta que se incluya en una entrega?

**Comment by olea** [comment]
>  Si se ha mezclado en la rama principal, la incidencia podría darse por resuelta. ¿O hace falta que se incluya en una entrega?

@benjavalero  Saldrá en la próxima edición :)
