### ISSUE TITLE
Falta el adjetivo 'lésbico' y sus formas derivadas

### ISSUE THREAD

**Issue by sbosio** [sbosio/rla-es#27]
En el día de la visibilidad lésbica, veo que este adjetivo, precisamente, no integra el listado de palabras del diccionario. Sí está 'lesbio' que es sinónimo, pero últimamente la forma más extendida es la faltante, así que me propongo añadirla.

**Comment by sbosio** [comment]
Modificación realizada. Aproveché para añadir "safismo" (forma culta para el lema 'lesbianismo').

**Comment by RickieES** [comment]
@Almorca está en proceso de convertir la codificación de los archivos a UTF-8, así que le menciono en este comentario para que esté atento al cambio, por si plantea algún conflicto y necesita retrotraer tu modificación para completar la recodificación y volver a aplicarlo después.
