### ISSUE TITLE
No separa los hiatos y otros 

### ISSUE THREAD

**Issue by Javimoa95** [sbosio/rla-es#270]
Cuando pones "iodo" te separa como io-do en vez de i-o-do. Otro ejemplo es "aereo" que lo separa como aereo en vez de a-e-re-o

**Comment by Pompilos** [comment]
Hola, Javimo. Yo diría que io-do está así bien separado, porque la i- inicial ante vocal se convierte a efectos de pronunciación en una consonante (dicho con otras palabras, se pronuncia yo-do).

**Comment by cosmoscalibur** [comment]
Queda en nuestra próxima versión
