### ISSUE TITLE
¿Este proyecto está activo?

### ISSUE THREAD

**Issue by santilin** [sbosio/rla-es#274]
Hola, me gustaría saber si las extensiones de idioma de libre office se siguen construyendo a partir de este proyecto.
Gracias.

**Comment by olea** [comment]
> Yo puedo colaborar con el mantenimiento de la extensión ya que trabajo de programador y estoy conectado diariamente a Internet

@santilin bienvenido :-)

**Comment by santilin** [comment]
¿Hay alguna primera tarea sencilla que pueda hacer?
