### ISSUE TITLE
Error en la palabra permíteme

### ISSUE THREAD

**Issue by Seryve** [sbosio/rla-es#275]
"permíteme" de la primera persona del singular imperativo, la RAE lo acepta como valido. 

Se expresa en orden y petición.

**Comment by cosmoscalibur** [comment]
Sale en la siguiente versión

**Comment by RickieES** [comment]
En realidad, aunque se ha modificado la bandera correctamente, no se ha añadido esa bandera al verbo permitir. :smile: 

Lo he corregido en el commit ea82c12.
