### ISSUE TITLE
Meta informacion de los diccionarios

### ISSUE THREAD

**Issue by Jzarecta** [sbosio/rla-es#28]
Hoy me instale el diccionario 0.8 de AOO pero veo  que le faltan algunas cosas en especifico la fecha. Incluyo un screenshot comparativo como la extension de Marco presenta una fecha de lanzamiento mientras que la mia no la presenta. No se quien use aqui AOO, pero tambien podra probar como el sistema de actualizacion se 'salta' avisar de la nueva version. Esto es por que no se declara este campo.
Recomiendo revisar los XML asi como la documentacion de extensiones de AOO:
https://wiki.openoffice.org/wiki/Extensions_packaging
Pongo el screenshot:
http://i.imgur.com/sIK9MqA.png

**Comment by Jzarecta** [comment]
Algo mas que note es que no se declara el mimetype al descargar los diccionarios mientras que el de marco si quelo hace. La diferencia esque el navegador solo lo descarga como binario mientras que el de marco te sugiere abrirlo dentro de AOO.

**Comment by Jzarecta** [comment]
Estuve revisando el description.xml y ahi encontre la mayor diferencia:
en_EN/description.xml:
```xml
   <version value="2015.04.01" />
   <identifier value="org.openoffice.en.hunspell.dictionaries" />
```
en_mx:
```xml
   <version value="0.8" />
   <identifier value="spanish.es_MX.dicts.from.rla-es" />
```
Parece que las versiones estan mal-puestas o se deben hacer ajustes en estas.

**Comment by olea** [comment]
Es lo que te iba a decir: que el tal Marco está usando la fecha como número de versión.

**Comment by Jzarecta** [comment]
Envie un correo a api@openoffice para que nos den instrucciones de mejores practicas. El namespace tambien se ve algo interpretado.

**Comment by RickieES** [comment]
El formato de versión que usa Marco no es correcto, de acuerdo con la información que hay en el [wiki de OpenOffice.org](https://wiki.openoffice.org/wiki/Documentation/DevGuide/Extensions/Extension_Versions). El formato es el típico de 0.1.2.3... que seguimos nosotros.

Nuestro formato de identificador de extensión se aparta de la convención recomendada, pero es correcto y válido, y no conviene cambiarlo, porque eso sí que afectaría a las actualizaciones.

He revisado el resto de etiquetas del archivo description.xml y todas son correctas. A ver qué te dicen, pero yo no veo que haya un error ahí (aunque sí reconozco que tampoco se me presentó la actualización en LibreOffice).

Lo del MIME type tampoco creo que sea un problema del fichero en sí. En la versión 0.7 pasó al contrario: en el sitio de extensiones de LibreOffice, los archivos se descargaban como binarios, mientras que en el de OpenOffice.org se descargaban con el tipo correcto. Yo no he hecho nada diferente en la 0.8 al subir los archivos al gestor de extensiones de LibreOffice y esta vez ha funcionado bien.

**Comment by Jzarecta** [comment]
no es que sea incorrecto pero el problema la convención con relación a la aplicacion. Romper la relación con la aplicacion puede ser contraproducente. 
se pueden hacer pruebas adicionales:
* Borrar or respaldar el ~/.openoffice/ 
* Iniciar OpenOffice
* Instalar la version 0.7 del diccionario
* Reiniciar AOO
* Observar si sale la notificacion de actualizacion a la 0.8

**Comment by Jzarecta** [comment]
Nueva respuesta de Andrea sobre algunas notas suponiendo que la siguiente versiones crescan a ser 0.10. Para esta versión OpenOffice lo encontrara ser una versión inferior a la 0.9. Si la version crece a 1.0 entonces no tendríamos problemas. Algo para tener en cuenta.
http://mail-archives.apache.org/mod_mbox/openoffice-api/201505.mbox/%3C5547102F.7030407%40apache.org%3E

**Comment by RickieES** [comment]
Caramba, pues podrían actualizar la documentación de su wiki. De todas formas, esto de los números de versión enlaza con el issue #26.

**Comment by RickieES** [comment]
Necesitamos tomar una decisión sobre el asunto del esquema de numeración de versiones del complemento, y su implicación para la numeración de los complementos para Mozilla (issue #26).

Hay que hacer notar que el esquema de numeración basado en fechas [no es válido para Mozilla](https://developer.mozilla.org/en-US/docs/Toolkit_version_format) ni, en general, las extensiones para navegadores. Yo propongo mantener el formato actual de M.n. Quizá, como hemos convertido a UTF-8, podríamos pasar a 1.0 (en el complemento de Mozilla usaría 1.10) y, cuando decidamos pasar a 2.0, sincronizamos ambas numeraciones.

**Comment by olea** [comment]
Sí no crea problemas técnicos yo directamente unificaría la numeración a ese 1.10 que dices. Sí el cambio es a un número mayor puede parecer un poco raro pero a los sistemas de actualizaciones les dará igual y todo funcionaría.

**Comment by Almorca** [comment]
Yo pasaría directamente a la versión 2.0. Así arreglamos cuanto antes la diferencias.

**Comment by RickieES** [comment]
Pasar a la 1.10 no sirve, como se comenta en el enlace que puso Jzarecta a un mensaje de Andrea, de OpenOffice. Básicamente, los sitios web de extensiones sí procesan bien los números de versión, pero los programas usan una comprobación estrictamente alfanumérica, por lo que para ellos "1.9" > "1.10".

Pasar a la 2.0, desde luego, solventaría el problema ya mismo. Sería cuestión de explicar el gran salto en las notas de versión.

**Comment by olea** [comment]
> Pasar a la 2.0, desde luego, solventaría el problema ya mismo. Sería cuestión de explicar el gran salto en las notas de versión.

+1

**Comment by RickieES** [comment]
He renombrado el milestone de Versión 0.9 a Versión 2.0. Cuando prepare los XML para los complementos de LibreOffice/OpenOffice.org miraré si es posible añadir la fecha de publicación de alguna forma.

**Comment by RickieES** [comment]
Comprobé que no hay elemento XML para añadir la fecha de publicación. La versión 2.0 ya está publicada (las extensiones no se han subido al catálogo de OpenOffice porque ni Alejandro Moreno ni yo tenemos acceso).
