### ISSUE TITLE
Dudas sobre algunas aportaciones

### ISSUE THREAD

**Issue by Pompilos** [sbosio/rla-es#282]
Hola. Voy a añadir varios términos que faltan, y tengo alguna duda que no sé resolver con la wiki de ayuda:

1) Hay términos que aceptan dos acentuaciones según la RAE (prótomo/protomo). ¿Se pone dos veces o hay algún código para que el software dé ambas versiones como buenas?
2) Un término específico de Navarra, pero que sale en el DRAE, como «facería», ¿va al diccionario general? Si no, ¿cómo se pone en uno específico?
3) Hay un adjetivo, «metanero», que según el DRAE se aplica a los buques. Si solo se aplica a los buques, que son masculinos, ¿no hay que incluir la variación de género? O sea, ¿se escribirá «metanero/S» o «metanero/GS»?
4) No salen en el DRAE, pero yo diría que «difusionismo/S» y «datable/S» son términos habituales en el español de hoy y pueden incluirse en el diccionario. ¿Lo veis igual? 

Gracias. Un saludo.

**Comment by jorgesumle** [comment]
> Hay términos que aceptan dos acentuaciones según la RAE (prótomo/protomo). ¿Se pone dos veces o hay algún código para que el software dé ambas versiones como buenas?

Se pone dos veces.

> Un término específico de Navarra, pero que sale en el DRAE, como «facería», ¿va al diccionario general? Si no, ¿cómo se pone en uno específico?

Hay una carpeta llamada `noRAE` en el directorio `palabras`. Consulta https://github.com/sbosio/rla-es/wiki/C%C3%B3mo-colaborar-con-RLA-ES-y-con-el-corrector-ortogr%C3%A1fico#criterios-usados-para-admitir-palabras.

> Hay un adjetivo, «metanero», que según el DRAE se aplica a los buques. Si solo se aplica a los buques, que son masculinos, ¿no hay que incluir la variación de género? O sea, ¿se escribirá «metanero/S» o «metanero/GS»?

¿Y «embarcación metanera» se puede decir? También he visto por ahí «terminal metanera». No veo motivo para no aceptarlo como correcto en femenino, aunque se use poco en la práctica.

> No salen en el DRAE, pero yo diría que «difusionismo/S» y «datable/S» son términos habituales en el español de hoy y pueden incluirse en el diccionario. ¿Lo veis igual?

Yo, personalmente como almeriense, no uso esas palabras.

**Comment by olea** [comment]
> 4\. No salen en el DRAE, pero yo diría que «difusionismo/S» y «datable/S» son términos habituales en el español de hoy y pueden incluirse en el diccionario. ¿Lo veis igual?

«Difusionismo» es la primera vez que la veo y en el [CREA](https://corpus.rae.es/creanet.html) sólo lo usan tres autores :-)  «Datable» sí, como tecnicismo y según el CREA también aparentemente se usa muy poco.

Lo ideal sería incorporar lemas respaldados en alguna publicación de algún prestigio.

En estos dos casos, por ahora, yo declinaría ambos lemas.

**Comment by Pompilos** [comment]
Dudas resueltas. Cierro.
