### ISSUE TITLE
Formas verbales con pronombres enclíticos

### ISSUE THREAD

**Issue by mota88** [sbosio/rla-es#288]
Uno de los problemas más difíciles que encuentro en los (pocos) diccionarios de español que he encontrado hasta ahora, es la dificultad a la hora de conjugar verbos y a la hora de añadirles pronombres. En particular, ciertos verbos admiten algunos de los llamados _pronombres enclíticos_, los cuales van al final de la palabra, y otros no.

Por ejemplo, para el verbo _comer_ podemos escribir _comerlo_ y _comernos_, de forma que también la combinación de ambos pronombres _nos_ y _lo_ nos daría la forma _comérnoslo_. Este ejemplo está hecho con el infinitivo, _comer_, pero se pueden construir formas verbales análogas con el gerundio y los imperativos.

En la versión actual del diccionario he seleccionado dos verbos que aparecen en la lista VerbosTransitivosIntransitivosPronominales.txt, _comer_ y _tratar_, que salen marcados con reglas distintas. Para el caso de _comer_ la forma _comiéndomelos_ existe, mientras que el análogo para _tratar_, _tratándomelos_, no está. Sin embargo, tanto _tratándome_ como _tratándolo_ están en el diccionario, por lo que su combinación debería de estar, ¿es así?

En general, creo que hay muchas de estas formas verbales que no están y deberían estar, por ejemplo _ajústalo_, _abróchamelo_, _búscamelo_, _encontrándoselos_, etc.

Ya que no hay un diccionario, como la RAE, donde consultar este tipo de formas, ¿cuál es la manera de lidiar con estos casos a nivel de reglas? En mi opinión los diccionarios quedan muy cojos sin estas palabras.

**Comment by olea** [comment]
> ¿cuál es la manera de lidiar con estos casos a nivel de reglas? En mi opinión los diccionarios quedan muy cojos sin estas palabras.

Desde mi ignorancia:  caso por caso.

Para acelerarlo: hacerse con algún corpus textual, pasar el corrector, anotar las carencias e informar acá.

**Comment by olea** [comment]
Entiendo que, de alguna forma, éste boletín es duplicado de #75. Cierro.
