### ISSUE TITLE
Testeado

### ISSUE THREAD

**Issue by antoniovazquezblanco** [sbosio/rla-es#29]
Testeado no es reconocido por hunspell-es como una palabra ortográficamente correcta a pesar de que si se reconoce como tal por la RAE.

http://buscon.rae.es/drae/srv/search?id=3bMaPrtRbDXX23qsBinu
http://buscon.rae.es/drae/srv/search?id=RBpU1V4BXVcRjN1jca89

**Comment by RickieES** [comment]
Como la RAE lo define como específico de Argentina y Chile, mi propuesta es añadir la siguiente línea:

testear/RED

en el archivo VerbosTransitivos.txt de ortograf/palabras/RAE/l10n/es_AR y ortograf/palabras/RAE/l10n/es_CL.

**Comment by Almorca** [comment]
Tengo mis dudas con lo de añadirlo solo a los diccionarios de Argentina y Chile. Aunque a mi me gustar más usar probar, si que he oído bastante el término testear en España, sobre todo en informática.

**Comment by RickieES** [comment]
A mí, que vivo en España, testear me suena a barbarismo. Si se añade, habría de ser en noRAE.

De todas formas, Alejandro, yo estoy reteniendo los posibles cambios a la espera de que concluyas la conversión del formato de los archivos a UTF-8. No sé si necesitas ayuda o si andas muy liado y no puedes dedicarle tiempo. En este último caso, quizá convendría que subieras lo que tienes y resumieras el estado en el que está el proceso.

**Comment by antoniovazquezblanco** [comment]
Entiendo tu posición RickiES, pero para aquellos que a veces nos dedicamos al mundo del software, "testear" está muy extendido y personalmente no la uso con la misma connotación que probar. Bien sea añadido en noRAE u otra sección, considero que debería figurar en el diccionario.

Muchas gracias por vuestro tiempo.

**Comment by RickieES** [comment]
Buff, pero es que el corrector ortográfico está para marcar las palabras incorrectas. Si añadimos palabras incorrectas, hacemos que no se marquen, que es peor. Casi todas las aplicaciones que utilizan Hunspell como corrector ortográfico permiten añadir palabras a un diccionario personal para casos como este.

Por curiosidad, ¿cuál es la connotación que aprecias en testear que no ves en probar?

Yo también programo algo en mis ratos libres y tengo que tratar con técnicos, y moriré antes de aceptar ciertos usos. Por ejemplo, me matan cada vez que dicen que van a "debuguear" algo, en lugar de decir que van a depurarlo, o a ejecutarlo en modo depuración. :smile:

**Comment by antoniovazquezblanco** [comment]
He tardado en acostumbrarme a usar depurar en lugar de "debuguear".
En este caso particular, el uso que le estaba dando a la palabra "testear" era para referirme a la comprobación sistemática de algún trozo de código a través de pruebas automatizadas.
Por otra parte se supone que testar si está aceptado, pero la propia rae advierte de que se pretende suprimir la acepción que yo busco http://lema.rae.es/drae/?val=testear.
Comprendo la situación. Podría añadir testear a mi diccionario personal aunque no resulta del todo una solución bonita.

**Comment by eksperimental** [comment]
Ademas de testear, test es una palabra reconocida en toda la lengua castellana

**Comment by Almorca** [comment]
@eksperimental Test sólo es reconocido en el ámbito de los estudios psicológicos tal y como se puede leer en http://lema.rae.es/dpd/srv/search?key=test

En ese mismo enlace se puede leer:
«Por influjo del inglés to test, se han creado en español los verbos testar y testear —este último usado en el Cono Sur— con el sentido de ‘someter [algo] a una prueba o control’. Son calcos innecesarios del inglés, ya que, con ese mismo sentido, existen en español los verbos examinar, controlar, analizar, probar o comprobar. Lo mismo cabe decir de los participios respectivos, testado y testeado. En aquellas zonas donde se usa el verbo testear, se ha creado el sustantivo testeo, que puede sustituirse por voces más tradicionales en español, como comprobación, análisis o examen.»

Leyendo esto, y siendo no partidario del NoRAE, yo añadiría sólo la palabra en los diccionarios de  Argentina y Chile como era la primera idea de Rickie.

**Comment by RickieES** [comment]
De acuerdo a la 23ª edición del Diccionario de la RAE, "testear" es ahora válido en más países (Argentina, Bolivia, Chile, Paraguay y Uruguay):

http://dle.rae.es/?w=testear&m=form&o=h

Como decía anteriormente, hay que añadir

testear/RED

en VerbosTransitivos.txt de esos países.

Cuando suba los cambios correspondientes al issue #1, añadiré este.

**Comment by RickieES** [comment]
¿Alguien de alguna de esas localizaciones podría generar un diccionario para comprobar si todo está bien?

**Comment by RickieES** [comment]
Er... Bueno, doy por bueno el cambio.
