### ISSUE TITLE
«andéis» marcado como error

### ISSUE THREAD

**Issue by Pompilos** [sbosio/rla-es#293]
No sé dónde se corrige.

**Comment by RickieES** [comment]
Vaya, has encontrado un fallo en Matrix... :stuck_out_tongue: 

Andar es un verbo irregular y no están en los archivos Verbos*.txt, sino que su conjugación _completa_ estaría en ConjugacionesIrregulares.txt.

Pero resulta que, debido al voseo, no es posible incluir la conjugación completa en el archivo general, sino que las formas dependientes de tuteo/voseo deben figurar en cada variante regional correspondiente.

Así que he cogido (perdón por el juego de palabras para los argentinos) :wink: el archivo general ConjugacionesIrregulares.txt y he ido identificando las formas conjugadas que faltaban en ese archivo. Y son estas (para el tuteo):

- andáis
- andabais
- anduvisteis
- andaréis
- andaríais
- andéis
- anduviereis
- anduvieseis

De ellas, solo me marca como errónea "andéis", porque las demás están en es-ES/ConjugacionesIrregulares.txt. Lo que más me sorprende, no obstante, es por qué todas esas formas no están en el archivo neutro, porque ninguna afecta al voseo. [Según la RAE](https://www.rae.es/modelos-de-conjugacion-verbal), y lo que mi intuición me decía, solo se ve afectada la segunda persona del singular. ¿Alguien que conozca mejor las variantes regionales como es-AR, es-UY, etc. puede ilustrarnos? ¿Quizá el alma mater de RLA-ES, @sbosio? :smile:

**Comment by sbosio** [comment]
El "voseo" en Argentina se refiere particularmente sólo a la 2da persona del singular, se usa en reemplazo de "tú", pero no es equivalente al "voseo reverencial", que sería al que pertenecen todas esas formas conjugadas que tú pusiste (que se conjugan como la segunda del plural, "vosotros"), es justo lo contrario, es un uso cotidiano familiar, no reverencial. En Argentina la forma reverencial más utilizada utilizada es "usted/es". El uso del voseo reverencial es prácticamente nulo, igual que el uso de las segundas personas: del singular "tú" (reemplazada por "vos" -familiar-) y del plural "vosotros" (reemplazada por "ustedes").

Para el verbo "andar" las conjugaciones del voseo familiar de estas latitudes sería:
- andás
- andabas
- anduviste
- andarás
- andarías
- andés
- anduvieras o anduvieses (p. usado)
- andá (imperativo)

Si `andéis` no aparece, probablemente sea una omisión, debería estar en ConjugacionesIrregulares.txt

**Comment by Pompilos** [comment]
Ya lo he añadido a Conjugacionesirregulares.txt.

**Comment by RickieES** [comment]
@Pompilos, pero es que yo entiendo que no debemos añadirlo en RAE/ConjugacionesIrregulares.txt, sino en todos los RAE/l10n/es_XX/ConjugacionesIrregulares.txt apropiados, por lo que ha comentado Santiago. Si no has subido el cambio al repositorio principal, déjame un poco de margen, _please_, :smile: y subo yo el cambio a las variantes apropiadas.

**Comment by sbosio** [comment]
No @RickieES, justamente "andéis" debería ir en `RAE/ConjugacionesIrregulares.txt` porque sería una conjugación válida del voseo reverencial, que sí se considera parte común del español. Debería haber estado siempre allí, probablemente sea una omisión. 

Por más que en Argentina y otros países no sea muy utilizado, nadie lo consideraría un error ortográfico.

**Comment by RickieES** [comment]
Ya he fusionado el PR #301, así que cierro el _issue_, tras asignarlo a Pompilos, que es quien lo ha resuelto.
