### ISSUE TITLE
Errores detectados en la opción Subir a LibreOffice del script make_dict.sh

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#311]
Abro este _issue_ para documentar las cuestiones que he detectado al usar la opción -L o --subir-a-LibreOffice.

- [x] es/description.xml: falta hacer la sustitución de la variable "__VERSION__" por el valor concreto.
- [x] es/LGPLv2.1.txt (1): la primera línea modificada respecto a la versión existente actualmente en el repositorio dictionaries es "<<<<<<< HEAD:LICENSE/LGPLv2.1.txt", que sobra.
- [x] es/LGPLv2.1.txt (1): debajo del contenido actual se añade una sección para OpenThesaurus, que tiene dos partes diferenciables: unas notas de OpenThesaurus con su descripción, versión, requisitos e instalación, que en mi opinión no debe figurar ahí, y una nueva copia de la licencia LGPLv2.1, que entiendo que también sobraría.
- [x] Dictionary_es.mk (1): en la lista de diccionarios se suprime el diccionario es (.dic y .aff), pero sin embargo se sigue copiando al repositorio, lo que resulta icongruente; probablemente habrá que dejar de copiarlo.
- [x] Dictionary_es.mk (2): también en la lista de diccionarios se ha omitido el directorio "es" en la descripción de cada archivo, de forma que, en lugar de figurar "dictionaries/es/es_AR.aff" y "dictionaries/es/es_AR.dic", figura "dictionaries/es_AR.aff" y "dictionaries/es_AR.dic".
- [x] Dictionary_es.mk (3): se elimina la línea "dictionaries/es/README_hunspell_es.txt" y se añade la línea "dictionaries/es/README.txt", pero realmente el archivo existente sigue siendo dictionaries/es/README_hunspell_es.txt.
- [x] Dictionary_es.mk (4): se elimina la línea "dictionaries/es/RLA-ES.png", pero el archivo sigue existiendo.
- [x] es/dictionaries.xcu (1): esto seguramente no es un error, solo lo comento para asegurar que es correcto. Se suprime la entrada con valor "es", probablemente sea lo correcto, pero debe ser congruente con la eliminación de los archivos es.aff y es.dic, así como las entradas correspondientes en Dictionaries_es.mk.
- [x] es/dictionaries.xcu (2): cada uno de los nodos de las distintas variantes regionales cambian el nombre para usar guion en lugar de subrayado (p.e.: "HunSpellDic_es_CL" por "HunSpellDic_es-CL"). En la [página de desarrollo de diccionarios de LibreOffice](https://wiki.documentfoundation.org/Development/Dictionaries) se sigue usando la versión con subrayado. Ignoro si tiene incidencia o no.

**Comment by olea** [comment]
>  es/LGPLv2.1.txt (1): la primera línea modificada respecto a la versión existente actualmente en el repositorio dictionaries es "<<<<<<< HEAD:LICENSE/LGPLv2.1.txt", que sobra.
 es/LGPLv2.1.txt (1): debajo del contenido actual se añade una sección para OpenThesaurus, que tiene dos partes diferenciables: unas notas de OpenThesaurus con su descripción, versión, requisitos e instalación, que en mi opinión no debe figurar ahí, y una nueva copia de la licencia LGPLv2.1, que entiendo que también sobraría.

Este no es un problema del script, sino cambios que se quedaron mal hechos (probablemente por mi) en ambos repositorios. Arreglado en repo local.

**Comment by RickieES** [comment]
Más que arreglarlo ya mismo, que yo lo estoy tocando a mano, me gustaría confirmar lo que es correcto y lo que es error en Dictionary_es.mk (1) y en es/dictionaries.xcu (1 y 2). Con esto termino de hacer los ajustes a mano en el repositorio dictionaries de LO y subo el parche para cumplir lo de tener la 2.8 finalizada antes de que acabe agosto. :smile:

**Comment by olea** [comment]
Hoy estoy trabajando en ello. Quisiera validar los cambios con la subida final a LO.

**Comment by olea** [comment]
Arreglado en #312 .
