### ISSUE TITLE
Documentar separación silábica y uso de sinónimos (era ¿Cómo se activa la separación silábica?)

### ISSUE THREAD

**Issue by introlinux** [sbosio/rla-es#32]
Selecciono una palabra, voy a herramientas-> idioma-> división de palabras... e inmediatamente me sale una ventana: "Ha finalizado la separación silábica"; pero en realidad no ha ocurrido nada.

**Comment by sbosio** [comment]
Generalmente eso sucede cuando el documento tiene mal seleccionado el
idioma, que difiere de los diccionarios que tú tienes instalados.

El idioma del texto de lo muestra en la barra de estado, generalmente a la
derecha del estilo actual.

Para cambiar el idioma a todo el documento puedes ir a "Editar" ->
"Seleccionar todo" (o presionar Ctrl+E), y luego en "Formato" -> "Carácter"
cambias el idioma que se encuentra en la pestaña "Tipo de letra". Debes
seleccionar un idioma para el que tengas el diccionario instalado. Estos
idiomas aparecen con un tilde con las letras "ABC" a la izquierda.

Saludos,

Santiago

El 12 de septiembre de 2015, 3:53, Antonio Sánchez <notifications@github.com

**Comment by introlinux** [comment]
Gracias por tu pronta respuesta.

Tengo todo en español. La corrección ortográfica va bien y los sinónimos
también, lo único que no me funciona es lo de la separación silábica. ¿Hay
alguna forma de debuggear para saber lo que está fallando?

Un saludo.

El 12 de septiembre de 2015, 14:52, Santiago Bosio <notifications@github.com

**Comment by sbosio** [comment]
Si lo haces sobre una selección, creo que la herramienta solo operará sobre
esa selección. Por lo tanto, si la palabra que seleccionaste no está al
final de una línea, o no hay espacio para separarla, pues sencillamente
Writer no hará nada, exactamente como describes, pero no sería un error,
sino que no existe la necesidad o la posibilidad de separarla. ¿Probaste
sin seleccionar nada, para ver si funciona sobre el documento completo?

Saludos,

Santiago.

**Comment by introlinux** [comment]
No lo había probado, pero ahora me dice: "¿Quiere continuar la revisión en
el principio del documento?"
Le digo que sí y me sale la ventanita que informa de que ha terminado, pero
igualmente no hace nada.

He probado a activar el entorno de ejecución de java, que recordaba que lo
había desactivado para que cargara LibO más rápido, pero ni así funciona :-/

**Comment by RickieES** [comment]
Yo nunca había usado la separación silábica, pero sin hacer nada especial, al ejecutarla me ha comenzado a sugerir separaciones silábicas en algunas palabras.

Para estar seguro de si la separación silábica está funcionando correctamente lo que excepcionalmente tienes que hacer es pegar un texto suficientemente largo para que ocupe varias líneas en Writer, y una vez hecho, busca la última palabra de la primera línea y cámbiala por una palabra suficientemente larga (como, por ejemplo, "suficientemente"). Si es lo suficientemente larga, la palabra debería pasar a la línea siguiente y, al mismo tiempo, debes asegurarte de que su primera sílaba cabría en la primera línea si se activa la separación silábica. A continuación, haz la prueba y cuéntanos a ver qué pasa.

Para tu referencia, con la configuración por defecto de Writer, pegando el párrafo anterior debería proponerte dividir silábicamente algunas palabras como "excepcionalmente", "suficientemente" y "debería".

**Comment by introlinux** [comment]
Sorry, estoy gilipollas, la separación de palabras en realidad lo que hace es romper la palabra al final de línea con un guión y yo esperaba que me separara las palabras al estilo:
"suficientemente" --> su-fi-cien-te-men-te  :-P

Ya siento las molestias. Como comenta @RickieES funciona perfectamente.

**Comment by RickieES** [comment]
En absoluto te sientas incómodo (no voy a citarte literalmente). ;-) Creo que el contenido de este issue nos puede servir para añadir una página en el wiki que explique el funcionamiento de la separación silábica, así que yo te agradezco que lo hayas abierto. Voy a convertir el issue en uno sobre documentación del wiki y a ver qué piensan otros miembros sobre recopilar la información y añadirla.

**Comment by ezeperez26** [comment]
He probado si funciona correctamente la separación silábica y sí lo hace. De todas maneras, me gustaría advertir que en la versión 2, los archivos correspondientes a la separación silábica y otros están en formato ISO y no en UTF-8 como deberían estar. Supongo que eso afectará en el reconocimiento de algunas separaciones. Manejaré en un fork el tema de los archivos que no se convirtieron a UTF-8.

**Comment by sbosio** [comment]
Puse un comentario en el pull-request de Ezequiel.

Por ahora, sin tiempo para hacer pruebas más detalladas, no deberíamos
hacer el cambio de ISO a UTF-8 en los ficheros de la separación silábica, y
debería revertirse el cambio en el encabezado del fichero hyph_es_ANY.dic
(puse un issue separado para esto).

**Comment by RickieES** [comment]
¿Creéis que queda algo por hacer aquí, o podríamos cerrar el _issue_?

**Comment by RickieES** [comment]
Yo creo que, un año después sin que haya habido comentarios, es un buen indicio de que podemos cerrar el _issue_.
