### ISSUE TITLE
Duda acerca de la estructura de archivos en este proyecto

### ISSUE THREAD

**Issue by vmurcia** [sbosio/rla-es#323]
Hola:

Estoy interesado en colaborar en mejorar el diccionario de este proyecto y he estado leyendo documentación técnica sobre el funcionamiento de los diccionarios Hunspell, en especial sobre todo lo relativo a las reglas de afijos. A este respecto, me surgen dudas sobre la estructura de archivos en este proyecto, las cuales me gustaría aclarar con el propósito de que mis contribuciones futuras se ajusten a las directrices ya existentes y estén alineadas con las contribuciones del resto de colaboradores.

- ¿Por qué existe la distinción entre «RAE» y «no RAE» para términos que, aun cuando no aparecen explícitamente en el _Diccionario de la lengua española_, son completamente correctos, pues se ajustan a las reglas de formación de palabras válidas? Por ejemplo, ¿acaso no resultaría más útil/apropiado construir los adverbios de modo terminados en «-mente» mediante una regla de sufijación, en vez de hacerlo de manera aislada en un fichero «no RAE» de adverbios, uno por uno de forma explícita?

- Lo mismo sucede para los diminutivos terminados en «-ito» o «-ita». ¿No reside la verdadera utilidad del sistema de afijos de Hunspell en crear palabras con reglas de prefijación o sufijación a partir de una raíz común? ¿Qué ventajas tiene hacerlo como se hace en este proyecto, de manera separada?

**Comment by cosmoscalibur** [comment]
@vmurcia , sobre la primera pregunta, esto se relaciona con entender el origen de los lemas y la posibilidad de verificar. Esto es, poder aplicar finalmente una práctica de revisión. No es algo explícito, pero la [documentación](https://github.com/sbosio/rla-es/wiki/Clasificaci%C3%B3n-de-lemas#fuente-de-los-lemas) menciona la posibilidad de consultar y validar.  
Adicional a esto, nos da la posibilidad de generar una versión de diccionario solo RAE y una versión extendida que tendrá mayor peso.
