### ISSUE TITLE
Falta "Desinstalación" en el diccionario.

### ISSUE THREAD

**Issue by sgilfra** [sbosio/rla-es#324]
Buenos días.
Es la primera vez que informo de un problema así que espero no cag... fastidiarla.
Según la RAE; Desinstalación es "1. f. Inform. Acción y efecto de desinstalar." Sin embargo se marca como errónea y ofrece como alternativas:
Des instalación
Des-instalación
Instalación
Destilación
Destinación

Gracias.

**Comment by cosmoscalibur** [comment]
@sgilfra , gracias por el reporte. En la siguiente versión saldrá el cambio gracias a @jorgesumle
