### ISSUE TITLE
patch es_CL, agregar palabras polera, polerón, trapicar, cahuinear y cahuinero

### ISSUE THREAD

**Issue by RAcl** [sbosio/rla-es#327]
El tar.gz contiene 5 parches, cada uno corresponde a una palabra utilizada en Chile, dos de ellas RAE:
- Polera
  >     modificados:     ortografia/palabras/RAE/l10n/es_CL/NombresFemeninos.txt
- Trapicar
  >     modificados:     ortografia/palabras/RAE/l10n/es_CL/VerbosPronominales.txt

Tres palabra NO RAE, pero que están en la ASALE
- Polerón
  >      modificados:     ortografia/palabras/noRAE/l10n/es_CL/NombresMasculinos.txt
- Cahuinear
  >      nuevo:                ortografia/palabras/noRAE/l10n/es_CL/VerbosIntransitivos.txt
- Cahuinero
  >      modificados:     ortografia/palabras/noRAE/l10n/es_CL/Adjetivos.txt

/* Es mi primer colaboración acá, espero estar bien con los formatos. */

[patch-es_cl.tar.gz](https://github.com/sbosio/rla-es/files/14390191/patch-es_cl.tar.gz)

**Comment by cosmoscalibur** [comment]
@RAcl , gracias.
Puedes dejarnos un PR, ya que noto que igual identificas los archivos.

**Comment by RAcl** [comment]
> @RAcl , gracias.
> Puedes dejarnos un PR, ya que noto que igual identificas los archivos.

Perdón, ¿qué es un PR?

**Comment by cosmoscalibur** [comment]
> > @RAcl , gracias.
> > Puedes dejarnos un PR, ya que noto que igual identificas los archivos.
> 
> Perdón, ¿qué es un PR?

@RAcl , un _Pull Requests_. De esa forma, queda también la autoría de tu contribución. Y ya una vez lo dispongas, me puedes marcar como revisor y yo lo fusiono.

**Comment by cosmoscalibur** [comment]
@RAcl , queda para la siguiente versión.
