### ISSUE TITLE
Error en archivo es_ES.dic de LibreOffice

### ISSUE THREAD

**Issue by carlos-h-h** [sbosio/rla-es#329]
Hola, me mandaron de LibreOffice a reportar acá: https://github.com/LibreOffice/dictionaries/issues/45

No sé cuál es el archivo correspondiente en este proyecto. En la entrada "calendarizar" del diccionario español (España) a alguien se le escapó un Ctrl-V y agregó la palabra "Andalucía", que habría que borrar.

Gracias y saludos.

**Comment by cosmoscalibur** [comment]
@carlos-h-h , muchas gracias por el reporte.
Estoy validando, y esto aunque no está en los lemarios fuente, está en el lemario compilado.
@olea @RickieES @sbosio , no tengo contexto de los códigos en el directorio de herramientas, y no logro identificar esto donde podría ocurrir. Esto incluso viene de versiones anteriores, no es exclusivo de la última.

**Comment by RickieES** [comment]
El problema me resulta difícil de diagnosticar, aunque es fácil de solucionar. La concatenación de calendarizar y Andalucía se produce entre las líneas 601 y 608 del script make_dict.sh (lógicamente, invocándolo para es_ES con herramientas/make_dict.sh -l es_ES). Probablemente sea más bien un problema con el contenido del script remover_comentarios.sh.

Es fácil solucionarlo añadiendo un salto de línea al final de /home/rpalomares/Repos/rla-es-git/ortografia/palabras/noRAE/l10n/es_ES/VerbosTransitivos.txt. He generado el OXT y parece estar correcto.

Sin embargo, la inmensa mayoría de los archivos de palabras terminan sin un salto de línea adicional, así que no termino de entender qué hace que esto no funcione. A mí ahora mismo me resulta imposible dedicarme a ello, no sé si @olea podría verlo. Si vemos que no responde, podemos preparar un parche, pero nos obligaría a generar una nueva versión, que también lleva un tiempo del que no sé si voy a disponer.

**Comment by carlos-h-h** [comment]
Hola, @RickieES. Estuve revisando y todos los archivos que vi terminan con el byte 0A (new line). `.../noRAE/l10n/es_ES/VerbosTransitivos.txt` es el único que no lo hace.

Saludos.

**Comment by cosmoscalibur** [comment]
@carlos-h-h , muchas gracias por tu inspección.
El archivo subí ya el cambio, pero hay que esperar a que hagamos liberación de la versión 2.9.
