### ISSUE TITLE
Como usuario español ¿tendría que instalar solo el diccionario "es_ES" o tendría que instalar los diccionarios "es_ES" y "es"?

### ISSUE THREAD

**Issue by alexojegu** [sbosio/rla-es#330]
Me gustaría saber, desde el punto de vista de un usuario español, que diccionarios tendría que instalar.

Entiendo que el diccionario `es` es común para todos los países que hablan español y el diccionario `es_ES` es especifico para España pero ¿en el diccionario `es_ES` ya se incluye el diccionario `es` o hay que instalar ambos?

**Comment by Almorca** [comment]
es solo contiene el español que es común mientras que los diccionarios locales, como es_ES, contienen la parte común más los localismos. Así que con solo instalar es_ES te sirve.
