### ISSUE TITLE
Script palabras.sh

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#34]
Revisando las cosas que hay que pasar a UTF-8 me he topado con el script palabras.sh que hay que actualizar. El script está diseñado para usar svn como repositorio por lo que habría que cambiarlo a git y habría que revisar el funcionamiento del mismo.

**Comment by RickieES** [comment]
Yo ando estos días muy liado acabando mi proyecto de fin de carrera (sí, debería haberlo hecho hace 20 años). :sob: Cuando termine, en un par de semanas, espero ser más constante en mis colaboraciones en RLA-ES (idealmente, un día a la semana),

**Comment by sbosio** [comment]
Este script es una herramienta muy vieja, que nunca fue muy útil. Yo
propondría eliminarlo del repositorio, ya que no aporta mucho, me parece a
mí. Fue en su momento algo que hice para mi uso personal, buscando
facilitarme la edición de los archivos de palabras, pero luego no lo usé
mucho porque tampoco era muy cómodo, pero por alguna razón quedó flotando
por ahí. Creo que no vale el esfuerzo de reacondicionarlo para el cambio a
UTF-8 y Git.

Saludos,

Santiago

**Comment by Almorca** [comment]
Si nadie se opone en unos días, elimino el script.

**Comment by RickieES** [comment]
Adelante con ello, por favor.
