### ISSUE TITLE
Eliminar países de noRAE/NombresPropiosSiglas.txt

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#36]
Tras el pull request #35 y su integración en el repositorio, tenemos palabras duplicadas en el archivo NombresPropiosSiglas.txt, que contiene nombres de países ahora incluidos en los topónimos. Posiblemente tengamos que revisar también los scripts de creación de diccionarios.

**Comment by Almorca** [comment]
Ya me haréis un resumen de como ha quedado el tema de la "política de merges" porque con git estoy más que verde y me he enterado de poco.

**Comment by RickieES** [comment]
La "política" que he seguido yo esta vez, que también soy nuevo, ha sido aplicar el merge rápido para no bloquear a nadie ni tener que lidiar con posteriores conflictos. Otro día hacemos una prueba más complicada. :smile:

**Comment by RickieES** [comment]
Vaya, me he colado al escribir la referencia al issue. El siguiente commit también está relacionado con este issue:

https://github.com/sbosio/rla-es/commit/41ead870694ae9346d4d1d376663d24d73208a15

Y con él creo que podemos dar por cerrado este issue y el 38.
