### ISSUE TITLE
Modificar script de creación del diccionario

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#39]
Hay que hacer algunas modificaciones en el script de creación del diccionario:

- añadir los topónimos
- revisar que el paso de SVN a GIT no implica ningún cambio en el script y, en caso contrario, ajustarlo
- cambiar la codificación de ISO-8859-1 a UTF-8

Respecto del primer punto, hay que decidir cómo incluirlos. Yo, en principio, soy partidario de no añadir más modificadores al script, porque no creo que sea necesaria tanta granularidad para generar el diccionario. Así pues, tenemos dos modificadores que podríamos considerar:

- **r**: incluir solo las palabras de la RAE. Si no se indica, se incluyen también las palabras de noRAE.
- **c**: incluir también los sinónimos y separación.

Podemos decidir que las entidades territoriales son parte de la colección de palabras y, en concreto, asimilables a palabras no RAE, en cuyo caso las incluiríamos siempre que no se indique el modificador **r**. O bien podemos decidir que son un contenido extra distinto de la colección de palabras en sí, y entonces incluirlos solo si se indica el modificador **c**.

Yo me inclino más por la primera opción, es decir, incluir las entidades territoriales siempre que no se indique **r**, considerándolas una lista más de palabras con la misma categoría que las que hay en noRAE. Incluyo vuestros alias, @olea, @Almorca, @eksperimental, @EquisTango, @sbosio, y @KNTRO, para que podáis opinar.

Mientras opináis, voy a ir preparando los cambios para ganar tiempo. Nos interesa actualizar el script para poder generar los diccionarios y probar que los cambios que hacemos funcionan.

**Comment by Almorca** [comment]
Me uno a tu propuesta de tratar los topónimos igual que si fuesen palabras de noRAE y no añadir más modificadores al script.

**Comment by RickieES** [comment]
Pues el script funciona y la única opinión sobre los modificadores apoya lo que he hecho en la versión provisional, así que voy a cerrarlo.

**Comment by RickieES** [comment]
Reabro este issue para modificar la línea que añade los topónimos de modo que usemos un prefijo para los archivos, permitiendo así dejar en el directorio otros archivos que no se incluyan en el diccionario.

**Comment by eksperimental** [comment]
@RickieES creo que no es conveniente abrir issues viejas que han sido cerradas para agregar un cambio, especialmente cuando tienen tantos puntos a resolver como esta. Creo que es mejor si es algo muy puntual y que no depende de los puntos listados arriba, abrir una issue nueva, y cuando se resuelve se cierra y listo.

solo mi punto de vista. nada crucial que afecte el desarrollo de la aplicacion.

de todos modos tengo comentarios respecto a este punto pero respondo en la otra conversacion

**Comment by RickieES** [comment]
Cierro de nuevo y definitivamente. Cuando abordemos las propuestas de normalización de nombrados de archivo probablemente haya que abrir otro issue similar.
