### ISSUE TITLE
Palabras faltantes en 0.7

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#4]
Corresponde al registro 752 de de RLA-ES en Forja.rediris.es
Creado por @almorca con fecha y hora 2013-09-09 12:05

=================================================
Listado de palabras que faltan en la versión 0.7:

consultoría, esquinera / o, rocódromo, fumigación, papiroflexia

**Comment by Almorca** [comment]
Añado una nueva tanda de palabras que he ido descubriendo en estos meses.

amortiguación
apruébalo
calendar
casuístico/a
concienciación
digísteis 
felicítala
inalámbrico
incrementales
ingesta 
instálalo 
ínfulas
mapear
Muñequero / a
musculación
planificador 
recambios 
Remodelación 
reutilización
señalización
sicológico
trazabilidad 
validador
verticalizar
vuélvelo

@sbosio  Si no te importa me asigno el bug y empezaré a trabajar en él en los próximos días.

**Comment by RickieES** [comment]
¿Seguro que "digísteis" es una palabra válida? "Dijísteis" sí corresponde a la segunda persona del plural del pretérito perfecto simple del verbo "decir", pero con "g" no me suena.

**Comment by Almorca** [comment]
Es un fallo mío. La palabra correcta es dijisteis sin tilde y con g así que en esta no he dado ni una.

**Comment by RickieES** [comment]
La verdad es que estamos fatal, cuando vea esto la gente dirá "¿Y estos son los que mantienen el diccionario?" :-) Yo digo que "dij**í**steis" es la buena, tú me corriges y dices que la correcta es "dijisteis, sin tilde y **con g**"... :-) Esta visto que tenemos que pararnos a pensar antes de escribir. :-)

**Comment by RickieES** [comment]
Cambio el milestone a Después, ya que no llegamos a la versión 0.8.

**Comment by RickieES** [comment]
Recopilo aquí todas las palabras del bug que siguen siendo marcadas como incorrectas tras instalar la versión 0.8, ordenadas, puestas en singular (salvo un caso específico en el que solo falla el plural) y sin mayúscula inicial:

amortiguación
apruébalo
atrápalo
calendar
casuístico
catadióptrico
catalogación
cedente
comprímelo
concienciación
contraprestación
copita
correduría
demagógica
domiciliación
felicítala
fumigación
hipermercado
inalámbrico
incremental
infrautilizar
ínfula
ingesta 
instálalo 
mapear
megalómano
muñequero
musculación
optimización
orarlo
papiroflexia
planificador 
porrón
quítatelo
recambios (plural; singular sí se reconoce; creo que se está derivando desde el verbo cambiar en VerbosTransitivosIntransitivosPronominales.txt)
reflectante
remodelación 
reutilización
señalización
señalización
sicológico
sicólogo
teletexto
terrario
tipología
trazabilidad
triatlón
uy
validador
verticalizar
volumetría
vuélvelo

**Comment by Almorca** [comment]
También está pendiente eliminar la palabra mareomotriz ya que se recomienda usar maremotriz ( http://www.fundeu.es/recomendacion/mareomotriz-165/ )

**Comment by RickieES** [comment]
@Almorca, figuras como encargado de este issue. Yo acabo de subir cambios del issue  #1, así que se pueden hacer cambios en los ficheros sin miedo a colisiones entre los cambios.

Por otra parte, creo que debemos publicar una versión en este mes, y hay cambios suficientes para dejar esta colección para una próxima versión. ¿Qué opinas?

**Comment by Almorca** [comment]
Me parece bien crear una versión este mes e intentar dar un nuevo empujón para sacar una nueva versión antes de febrero que es cuando se publica Libreoffice 5.1.

**Comment by RickieES** [comment]
Me he liado la manta a la cabeza y he fijado como fecha para tener lista la 0.9 el 30 de noviembre. Creo que es mejor publicar dejando fuera algunas cosas que querríamos, que estar atrasando más y más para poder incluir esas cosas.

**Comment by RickieES** [comment]
@Almorca, hoy es 29 y deberíamos preparar la versión 0.9 -> 2.0. ¿Tienes algo preparado de este issue, o lo replanificamos para la próxima versión?

**Comment by Almorca** [comment]
Pásalo a la siguiente versión porque no he hecho nada y además estoy con las palabras de la wikipedia.

**Comment by RickieES** [comment]
Reduzco la lista de palabras marcadas como incorrectas a la que aparece con la versión 2.0 instalada:

amortiguación
calendar
casuístico
catadióptrico
catalogación
cedente
comprímelo
concienciación
contraprestación
copita
correduría
demagógica
domiciliación
fumigación
hipermercado
inalámbrico
incremental
infrautilizar
ínfula
ingesta
mapear
megalómano
muñequero
musculación
optimización
orarlo
papiroflexia
planificador
porrón
quítatelo
recambios (plural; singular sí se reconoce; creo que se está derivando desde el verbo cambiar en VerbosTransitivosIntransitivosPronominales.txt)
reflectante
remodelación
reutilización
señalización
señalización
sicológico
sicólogo
teletexto
terrario
tipología
triatlón
uy
validador
verticalizar
volumetría

**Comment by ezeperez26** [comment]
Dado que @Almorca se encuentra trabajando con las palabras de la Wikipedia, yo podría continuar con este _issue_.

**Comment by Almorca** [comment]
Por mi parte adelante.

**Comment by ezeperez26** [comment]
Analizando un bloque de 10 palabras:

* amortiguación deriva de “amortiguar” que ya se encuentra en el diccionario, se agrega flag -ción (A).

* calendar según RAE es un verbo transitivo poco usado. En Google los resultados se refieren a la acepción inglesa. ¿Se agrega?

* casuístico se encuentra en RAE, se incluye en  RAE/Adjetivos.txt con flag de femenino y plural.

* catadióptrico se encuentra en RAE, se incluye en RAE/Adjetivos.txt con flag de femenino y plural.

* catalogación deriva de “catalogar”  que ya se encuentra en el diccionario, se agrega el flag -ción (A).

* cedente se encuentra en RAE, se incluye en RAE/Adjetivos.txt con flag de plural.

* comprímelo es conjugación de “comprimir” que ya se encuentra en el diccionario. Agregar flags ÌÏØ.

* concienciación deriva del verbo “concienciar” que ya se encuentra en el diccionario. Agregar flag -ción (A).

* contraprestación se encuentra en RAE, se agrega en RAE/NombresFemeninos.txt con flag de plural (S) para contraprestaciones.

* copita Agregar el flag U de diminutivo a copa.

A excepción de "calendar", las 9 palabras restantes fueron incluidas y están disponibles en el PR #63.

**Comment by RickieES** [comment]
Ya he fusionado el PR #63, muchas gracias.

Yo opino que no merece la pena añadir "calendar" como verbo. Casi nadie lo va a usar y solo puede llevar a que no se marque como incorrecta el término en inglés.

**Comment by Almorca** [comment]
He buscado en CORPES y veo que todos los casos donde aparece calendar es para referirse a Google Calendar por lo que me parece bien que no se añada.

**Comment by ezeperez26** [comment]
Analizando otro bloque de 10 palabras:

* correduría deriva de “corredor”, pero no existe sufijo -uría. Se encuentra en RAE, se agrega a RAE/NombresFemeninos.txt con sufijo de plural.

* demagógica se encuentra en RAE, se agrega demagógico en RAE/Adjetivos.txt con sufijo de femenino y plural.

* domiciliación deriva de “domiciliar” que ya se encuentra en el diccionario. Agrego _flag_ A para sufijo -ción.

* fumigación deriva de “fumigar” que ya se encuentra en el diccionario. Agrego _flag_ A para sufijo -ción.

* hipermercado se encuentra en RAE, se agrega en RAE/NombresMasculinos.txt con sufijo de plural.

* inalámbrico/ca se encuentra en RAE, se agrega en RAE/Adjetivos.txt con sufijo de femenino y plural.

* incremental no se encuentra en RAE. Tiene 30 millones de resultados en google. Entre CORPES y NDHE hay 127 apariciones. Se agrega en noRAE/Adjetivos.txt con sufijo de plural.

* infrautilizar se encuentra en RAE, se agrega en RAE/VerbosTransitivos.txt con sufijos RED.

* ínfula se encuentra en RAE, se agrega en RAE/NombresFemeninos.txt con sufijo de plural.

* ingesta se encuentra en RAE, se agrega en RAE/NombresFemeninos.txt con sufijo de plural.

La única "duda" sería con la palabra "incremental", pero de todas maneras la agregué a noRAE ya que por lo que vi en CORPES XXI, se usa mucho en la actualidad.

Los cambios ya están disponibles en el PR #65.

**Comment by ezeperez26** [comment]
Como ya dieron el visto bueno al PR del anterior bloque, procedo con otras 10 palabras:

* mapear se encuentra en RAE, se agrega a RAE/VerbosTransitivos.txt con sufijos de verbos.

* megalómano se encuentra en RAE, se agrega a RAE/Adjetivos.txt con sufijo de femenino y plural.

* muñequero se encuentra en RAE, se agrega a RAE/NombresMasculinosFemeninos.txt con sufijo de femenino y plural.

* musculación, según RAE, es la acción y efecto de muscular. La palabra “muscular” ya se encuentra en el diccionario, pero dentro de Adjetivos, tal como la cataloga RAE. ¿Es correcto agregar el _flag_ A de sufijo _-ción_ a un adjetivo cuando en realidad está pensado para verbos? ¿O directamente agrego la palabra “musculación” en RAE/NombresFemeninos.txt?

* optimización deriva de “optimizar”, que ya se encuentra en el diccionario. Se agrega el _flag_ A de sufijo _-ción_.

* orarlo sería una conjugación de “orar”, que ya se encuentra en el diccionario (en VerbosTransitivosIntransitivos.txt). Sin embargo no aparece en CORPES ni en CNDHE.  En caso de que se decida agregar, hay que incluir al verbo “orar” el _flag_ À.

* papiroflexia se encuentra en RAE, se agrega en RAE/NombresFemeninos.txt.

* planificador se encuentra en RAE, se agrega a RAE/Adjetivos.txt con sufijo de femenino y plural.

* porrón se encuentra en RAE, se agrega en RAE/NombresMasculinos con _flag_ de plural.

* quítatelo sería conjugación de “quitar”, que ya se encuentra en el diccionario. Sin embargo no hay un sufijo para agregar dicha palabra.

Aún no preparé un PR. Esperaré a que me guíen sobre cómo proceder con las palabras **musculación**, **orarlo** y **quítatelo**.

**Comment by Almorca** [comment]
En cuanto a muscular, la categorización de las palabras no es más que una forma de ordenación sin ninguna utilidad. Yo, siempre que sea posible, usaría los afijos disponibles.
Orarlo yo creo que es una palabra incorrecta y no la añadiría.
Quítatelo lo añadiría como una nueva palabra y dejaría para más adelante ver si hay alguna norma que permita derivar una nueva regla en afijos.

**Comment by RickieES** [comment]
> musculación, según RAE, es la acción y efecto de muscular. La palabra “muscular” ya se encuentra en el diccionario, pero dentro de Adjetivos, tal como la cataloga RAE. ¿Es correcto agregar el flag A de sufijo -ción a un adjetivo cuando en realidad está pensado para verbos? ¿O directamente agrego la palabra “musculación” en RAE/NombresFemeninos.txt?

Pues yo discrepo de @Almorca en este caso. :smile: El "muscular" al que se refiere la RAE es el verbo muscular, que no me suena que sea de uso frecuente, aunque tampoco creo que esté en desuso. Yo creo que, o añadimos el verbo "muscular" y, a partir de ahí, añadimos el afijo, o añadimos directamente la palabra "musculación".

En las otras dos cosas (orarlo y quitatelo) estoy de acuerdo con su opinión.

**Comment by ezeperez26** [comment]
Analicé otras 10 palabras y agregué 9 de ellas:

* recambios deriva de "recambio", acción y efecto de "recambiar". El verbo "recambiar" ya es reconocido por el diccionario, pero no he encontrado un sufijo que relacione un verbo con su sustantivo masculino que forme "recambiar" a "recambios". Sí reconoce "recambio" porque es una conjugación de "recambiar". 

* reflectante se encuentra en RAE, se agrega en RAE/Adjetivos.txt con sufijo de plural.

* remodelación deriva de "remodelar", que no es reconocida por el diccionario. Remodelar se encuentra en RAE, se agrega a RAE/VerbosTransitivos.txt con _flags_ REDA (la A para sufijo _-ción_).

* reutilización deriva de "reutilizar" que ya se encuentra en el diccionario. Reutilización se encuentra en RAE, se agrega el _flag_ A de sufijo _-ción_.

* señalización deriva de "señalizar" que ya se encuentra en el diccionario. Señalización se encuentra en RAE, se agrega el _flag_ A de sufijo _-ción_.

* sicológico se encuentra en RAE. Se agrega a RAE/Adjetivos.txt con sufijos de femenino y plural.

* sicólogo se encuentra en RAE. Se agrega a RAE/NombresMasculinosFemeninos.txt con sufijos de femenino y plural.

* teletexto se encuentra en RAE (deriva de una marca registrada). Se agrega a RAE/NombresMasculinos.txt con sufijo de plural.

* terrario se encuentra en RAE. Se agrega a RAE/NombresMasculinos.txt con sufijo de plural.

* tipología se encuentra en RAE. Se agrega a RAE/NombresFemeninos.txt con sufijo de plural.

Los cambios ya se encuentran en el PR #70.

**Comment by ezeperez26** [comment]
Finalizo la revisión de las últimas 5 palabras:

* triatlón se encuentra en RAE. Se agrega a RAE/NombresMasculinos.txt con sufijo de plural (para admitir triatlones).

* uy se encuentra en RAE. Se agrega a RAE/Interjecciones.txt.

* validador se encuentra en RAE. Se agrega a RAE/Adjetivos.txt con sufijos de femenino y plural (para admitir validadores, validadora, validadoras).

* verticalizar se encuentra en RAE. Se agrega a RAE/VerbosTransitivos.txt con _flags_ RED de verbos regulares y _flag_ A para sufijo _-ción_ (para admitir verticalización).

* volumetría se encuentra en RAE. Se agrega a RAE/NombresFemeninos.txt con sufijo de plural (para admitir volumetrías).

Los cambios ya están disponibles en el PR #71.

**Comment by ezeperez26** [comment]
A modo de resumen, todas las palabras de este _issue_ han sido agregadas salvo las siguientes:

* **calendar** se decidió no añadirla ya que en español está en desuso y puede traer confusiones al marcarla como correcta cuando se refiere a la forma inglesa.
* **orarlo** se decidió no agregarla por no considerarla correcta.
* **quítatelo** no se puede derivar de ningún afijo existente. Se consideró agregarla pero no supe donde va.
* **recambios** no se puede derivar de ningún afijo existente. Una solución "barata" es agregar `recambio/S` a `RAE/NombresMasculinos.txt`, a pesar de que la palabra "recambio" ya es reconocida actualmente.

**Comment by RickieES** [comment]
>     calendar se decidió no añadirla ya que en español está en desuso y puede traer
>     confusiones al marcarla como correcta cuando se refiere a la forma inglesa.

A mí me parece bien no añadirla.

>     orarlo se decidió no agregarla por no considerarla correcta.

Ídem.

>     quítatelo no se puede derivar de ningún afijo existente. Se consideró agregarla
> pero no supe donde va.

Veamos. Quítatelo es "quita" (imperativo, segunda persona del singular) más enclítico de complemento indirecto ("le") más enclítico de complemento directo ("lo").

En LibreOffice tengo instalado el diccionario actualizado y estas tres formas no se reconocen:

quítamelo
quítatelo
quítaselo

En cambio, de estas tres, solo la segunda persona no se reconoce:

declínamela
declínatela
declínasela

Las que se reconocen lo son por el afijo "Ï", pero nos faltan reglas para los verbos terminados en -itar, y reglas para la segunda persona. No sé si @sbosio podría aclararnos por qué no se incluyó la segunda persona en este afijo.

>  recambios no se puede derivar de ningún afijo existente. Una solución "barata" es
> agregar recambio/S a RAE/NombresMasculinos.txt, a pesar de que la palabra
> "recambio" ya es reconocida actualmente.

En mi opinión, no es una solución "barata", sino la correcta. Como tú dijiste, "recambio" se reconoce por conjugación del verbo recambiar (o cambiar con el prefijo re-), pero recambio es un sustantivo en sí mismo (no creo ni que debamos derivarlo desde el sustantivo "cambio").

**Comment by ezeperez26** [comment]
Agregué `recambio/S` a `RAE/NombresMasculinos.txt`como se había sugerido.
Había planteado la posibilidad de que se derive de verbos porque hay muchos sufijos para derivar los sustantivos de "acción y efecto" a partir de verbos. Pero se ve que no existe el sufijo para este caso en particular.

He pensado en la posibilidad de no incluir "quítatelo", pero tiene 12 apariciones en CORPES XXI y 16 en CORPES, incluso en textos clásicos como _Las mil y una noches_.
Para no demorar el cierre de este _issue_ y por ende la publicación de la próxima versión, se podría tratar dicha palabra en otro _issue_, ya que hay que analizar los afijos y quizás haya que modificarlos.

**Comment by RickieES** [comment]
Me parece bien. Entonces puedes cerrar ya este _issue_, ¿verdad?

**Comment by ezeperez26** [comment]
Ya armé el _issue_ #75 sólo para la forma "quítatelo".

Doy por cerrado este _issue_.
