### ISSUE TITLE
Definir criterios para incluir nombres propios

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#41]
En el issue #1 se proporciona una lista de nombres propios. En esa lista hay nombres que pueden considerarse de ámbito general, y otros que probablemente solo van a encontrarse normalmente en algunos países. Sin embargo, como nombres propios que son, puede haber debate en cuanto a si deben considerarse de ámbito regional o no.

Este issue que abro es para que debatamos qué criterios seguir. También, con el fin de tener un ejemplo en el que apoyarnos para debatir, traslado aquí la lista de nombres propuesta en el issue #1.

**Comment by RickieES** [comment]
Lista de nombres propuestos para añadir:

Abel
Abigail
Alan
Analía
Ayelén
Bianca
Bibiana
Brenda
Camila
Carina
Celina
Christian
Cinthia
Cintia
Claribel
Clarissa
Cynthia
Daiana
Dalila
Dalma
Dámaris
Débora
Eleonora
Eliana
Elsa
Érica
Erick
Estefanía
Fabiana
Fanny
Gabriela
Gianina
Giannina
Gimena
Giorgina
Gisela
Gisele
Giselle
Gissele
Gisselle
Graciela
Griselda
Iliana
Ivana
Jésica
Jimena
Judith
Julieta
Karen
Karina
Katia
Kevin
Kiara
Letizia
Liu
Luciana
Lucila
Lucrecia
Ludmila
Mabel
Maia
Maira
Malena
Malvina
Marianela
Marianella
Maribel
Mariela
Marisa
Marisol
Mary
Mayra
Melody
Mia
Michelle
Miriam
Mirta
Nadia
Nancy
Nélida
Nelly
Nelson
Noemí
Priscila
Priscilla
Rosana
Roxana
Sabrina
Silvana
Solange
Tamara
Umberto
Vanessa
Vanina
Vannina
Viviana
Walter
Wendy
Ximena
Yamila
Yanina
Yésica
Zahira
Zaira
Zulma

**Comment by Almorca** [comment]
A mí se me ocurreo como criterio cierto número de apariciones en Google (no sé si aquí 50.000 es un número apropiado) y que al menos algún personaje conocido de origen hispano lleve ese nombre.

El tema es que a mí hay muchos que me suenan raro pero seguro que en sudamérica son de lo más normal.

Por cierto, Abigaíl lleva tilde y entiendo que Mía también.

**Comment by eksperimental** [comment]
El tema es que en algunos paises esta permitido darle el nombre que quieras a tus hijos, cuando en otros esta estipulado cuales son los permitidos por el registro Civil o de las personas (esto nos facilita la tarea a la hora de componer la lista por paises), entonces en paises como Colombia hay una infinidad de nombres...

Creo que lo mejor seria tener un listado de nombres comunes a todas las regiones, y otros separados por paises, que extienda esta lista.

Una pregunta es, si deberían incluirse nombres en otros idiomas. como en ingles. ya que se muy comun corregir un texto y encontrarse con estos nombres. Pero quiza escape a la funcion de este projecto.

**Comment by RickieES** [comment]
¿Abigail lleva tilde? Es aguda y no acaba en vocal, n o s, ¿no? ¿O ya se me están olvidando las reglas de acentuación? :smile: 

Yo preveo muchas diferencias de criterio entre España y seguramente toda Latinoamérica. Por ejemplo, uno de los últimos nombres de la lista es "Yésica". No estoy seguro de haber visto escrito ese nombre aquí, pero sí me suena que ha comenzado a usarse hace un tiempo aquí y siempre me lo he imaginado transcrito en la versión original, "Jessica". La cuestión es: ¿los nombres propios están sujetos a las reglas ortográficas? Si no lo están, ¿tiene sentido incluir una lista de nombres "correctos"?

**Comment by Almorca** [comment]
Con respecto a Abigail/Abigaíl parece que las 2 formas son correctas https://twitter.com/raeinforma/status/337464795974496256

En cuanto a los nombre yo sí que incluiría los más extendidos y creo que lo mejor es hacer 2 listas, una para España y otra para sudamérica. A lo mejor para no incluir cientos de ellos se puede incluir los que aparezcan en Google mínimo 1 millón de veces. Siendo así Abigail y Yamila entrarían y Yésica se quedaría fuera. ¿A alguien de sudamérica le parece que hay más Abigailes y Yamilas que Yésicas?

También veo el problema de que hay nombre con muchas variaciones: Érica/Erika (En España suele usarse Erika y en sudamérica Érica).

**Comment by eksperimental** [comment]
@Almorca varía mucho de pais en país. Creo que sería un gran error hacer estos dos grandes grupos.

**Comment by Almorca** [comment]
@eksperimental Imagino que los nombres en Argentina no tendrán nada que ver con los de México. Fallo mío el no tenerlo en cuenta y tratar sudamérica como un todo.

Se me ocurre buscar las estadísticas de cada país y meter los n nombres y apellidos más frecuentes. En España hay estadísticas de nombres y apellidos en http://www.ine.es/daco/daco42/nombyapel/nombyapel.htm
Imagino que en el resto de países también habrá algo similar y puede ser una solución objetiva para cada país aunque lleve más trabajo.

**Comment by eksperimental** [comment]
va a ser un trabajo complicado, pero yo creo que tambien cubriendo 5 paises, se va a tener una lista bastante grande como para cubrir el gran porcentaje de los nombres en otros paises, y de a poco ir agrandando la lista.

he estado trabajando analizando las palbras de wikipedia.
puedo hacer un script with tome la lista de nombres y coloque en una columna cuantas apariciones tiene en wikipedia (puede ser algo mucho mas facil y determinar la popularidad utilzando google.
ya que estamos hablando de mas de diez mil nombres.

**Comment by cosmoscalibur** [comment]
Un punto importante es también considerar que wikipedia no tiene porque contener personajes realmente representativos a nivel regional en abundancia, sino que su mención más que una situación de popularidad puede corresponder a sus aportes o participación en algo. Tal vez, pueda ser una mejor forma, usar las categorías de búsquedas que muestran el top 50 (si alcanzan los 50) de los personajes. De esa forma, tendríamos un criterio de uso que no depende primero de crear la lista de nombres cuya popularidad se va a comparar, sino que ya tenemos una lista _absoluta_ de popularidad por categorías (atletas profesionales, presidentes, actores, empresarios, artistas y políticos son algunas de estas categorías que se pueden consultar por región).

**Comment by cosmoscalibur** [comment]
Hola @olea, en el caso de Colombia la lista que da el instituto equivalente no es tan amplia (ni la obtenida a través de medios que le consulten directamente) y existen personajes muy nombrados en el país cuyos nombres no coinciden con los populares de registro civil. Aquí hay que pensar, ¿nos interesan nombres populares por registro o por uso en documentos/medios?

**Comment by olea** [comment]
@cosmoscalibur por lo que a mi respecta no tengo ni la menor duda: los nombres más populares por uso. Yo creo que a todo el mundo le molesta más que su nombre, especialmente si es muy común, le aparezca como errata que el de un personaje popular.

**Comment by cosmoscalibur** [comment]
Sin embargo @olea un diccionario no se basa en gustos ni disgustos. Si alguien durante su trabajo de colegio o universidad va a hablar de personajes de alguna disciplina o de historia, necesita que el corrector le ayude con la forma correcta de los nombres de los personajes y no del nombre propio que solo aparece en la portada (y que uno mismo sabe escribir). Al punto que voy es que la adopción de una herramienta depende de lo amigable que sea para uso cotidiano, y el uso cotidiano no es escribir los nombres que más ciudadanos tengan sino los nombres de los que más se hablan (así existan pocos con el nombre).

**Comment by olea** [comment]
>  el uso cotidiano no es escribir los nombres que más ciudadanos tengan sino los nombres de los que más se hablan 

Me fascina que puedas afirmarlo con tanta seguridad. ¿Serías tan amable de indicarme las referencias a los estudios que documentan el hecho?

Yo soy tan torpe que sólo se me ha ocurrido pensar en que las personas normalmente tratan con otras personas dirigiéndose con sus nombres, pero tal vez sólo se dediquen a hablar de famosos y yo no estaba apercibido. Debes tener más acceso que yo a la mayoría de los correo-e y documentos que se escriben en la Hispanidad.

En fin, yo ya he expresado mi punto de vista. Que cada cual haga lo que le parezca.

**Comment by RickieES** [comment]
Sin lugar a dudas, el diccionario de corrección ortográfica de RLA-ES aspira a ser de utilidad en el uso común, y eso respalda la posición de Ismael. Yo prefiero mil veces que me marque como incorrecta la palabra Chindasvinto (rey visigodo) a que me marque Alejandro, Alberto o Ismael. Y, por cierto, no hay nada que impida, por incluir Alejandro, Alberto o Ismael, que se incluya también Chindasvinto.

**Comment by cosmoscalibur** [comment]
@RickieES @olea si leen bien mi mención, yo también hablo de un criterio de uso común. Solo que veo diferencia en el significado de "uso común" entre ustedes y yo. Común no lo veo por registros civiles sino por lo frecuente que pueda ser citado. Pero reconozco igual una cierta exageración en la afirmación, pues la popularidad en citación y en registro varia no solo espacial sino también temporalmente, y por ende pueden existir regiones y epocas para las cuales exista concordancia entre la frecuencia del nombre en registros civiles y su citación.  
Por ejemplo, _Chindasvinto_, claramente no es uso común para mi (ni registro civil ni citado). No recuerdo haberlo visto nunca en clase de historia. Sin embargo, _Policarpa_ es el nombre de un personaje que para la historia colombiana (luego para la versión es_CO) es obligatorio conocerlo y para estudiantes de colegio será obligación escribir documentos con mención a ella cuando se vea historia de la independencia (estamos hablando por ende de por lo menos, una cota inferior de 10000 documentos al año solo por estudiantes). Sin embargo, ese nombre, al buscarlo en google solo se encontrará referencia a _Policarpa Salavarrieta_, y no a más personas (ni esta en listas de popularidad de nombres).  
Algo más actual puede ser el caso del nombre más citado en la web en 2015 acorde a __The Global Language Monitor__, _Donald Trump_, sin embargo el nombre _Donald_ ocupa la posición 488 acorde al histórico de los registros civiles de Estados Unidos.  
A esto me refiero con un criterio de uso común, no por registros sino por citación (que finalmente significa que si se escribe y que sería útil tenerlo en la corrección de nombre). No se si sea ya más claro mi punto al respecto.

**Comment by cosmoscalibur** [comment]
@RickieES , con el fin de dar limpieza a reportes, cómo ves que los reportes que correspondan a preguntas se cierren, y validar como movernos a discusiones de GitHub o por el telegram.
@sbosio , ¿hay forma de habilitar las discusiones?, o ¿@RickieES, tienes de pronto permisos administrativos del repo?

**Comment by RickieES** [comment]
No, no tengo permisos administrativos del repositorio. Por lo que he visto recientemente en otro repositorio del que sí soy propietario, no es posible añadir colaboradores con rol de administrador. Salvo que me digáis que estoy equivocado, creo que tiene que ser @sbosio quien lo habilite.

**Comment by cosmoscalibur** [comment]
Ante la inactividad del tema concreto y la ausencia de reportes asociados, se recomienda continuar el tema en un caso que requiera de esta definición
