### ISSUE TITLE
Limpiar / Ordenar el proyecto

### ISSUE THREAD

**Issue by eksperimental** [sbosio/rla-es#43]
- [ ] Estandarizar nombres de archivos en el proyecto #42
- [ ] Eliminar scripts/archivos que ya no son necesarios
- [ ] Renombrar directorio `ortograf` a `ortografia` ya que es es el único que se encuentra abreviado

podemos agregar mas items a la lista, pero me gustaría tener su opinión al respecto antes de realizar algún cambio

**Comment by RickieES** [comment]
El segundo punto me parece bien. El primero, como tiene su propio issue, lo hablamos ahí. Y el tercero no me parece necesario, pero tampoco me opondría si la mayoría lo cree conveniente.

**Comment by ezeperez26** [comment]
Con respecto al primer punto, dejé un comentario en su respectivo _issue_.

Sobre el segundo punto estoy de acuerdo, pero ¿se sabe cuáles son los scripts que ya no se usan más? Los más antiguos del proyecto sabrían tratar mejor ese punto. Por ejemplo, en el issue #34 se hace mención a que el script `palabras.sh` es una herramienta que no se usa y se podría borrar del repositorio.
El directorio `web` también tiene pinta que está obsoleto, parece corresponder al antiguo repositorio de Forja Red Iris.

Con respecto al tercero, sí, estoy de acuerdo. Es raro ver esa palabra cortada, ni que tuviésemos menos caracteres que Twitter para nombrar directorios  :stuck_out_tongue_closed_eyes:

También me gustaría proponer una mejora un poco más integral al proyecto, atendiendo el comentario que dejó @sbosio en el issue #38 sobre licencias y propiedad, con el fin de que el mismo pueda crecer de forma más organizada, como disponer de su propio repositorio de tesauros, incluso crear un repositorio para desarrollar un corrector gramatical, hasta tener un propio sitio web.
* Crear una [organización de GitHub](https://help.github.com/articles/about-organizations/) para alojar todos los proyectos de RLA-ES, además del diccionario que disponemos actualmente.
* Que los antiguos miembros y colaboradores más activos tengan [roles](https://help.github.com/articles/permission-levels-for-an-organization/) de _owner_ en esa organización, mientras que los demás tengan acceso como colaboradores.
* Que el actual propietario transfiera la propiedad de este repositorio a la organización. En su defecto, copiamos el código en un nuevo, pero perderíamos los issues y la wiki.
* Agregar licencias adecuadas a los repositorios, tal como sugiere [GitHub](https://help.github.com/articles/open-source-licensing/), agregando el archivo `LICENSE.md` al repositorio donde se indique las licencias que rigen sobre el proyecto.
* Ya que openthes-es ha desaparecido, crear nuestro propio proyecto (repositorio) de tesauros para poder mantenerlo y mejorarlo.
* Posibilidad de usar [GitHub Pages](https://pages.github.com/) como "sitio institucional" al proyecto.

He usado las organizaciones de GitHub, son muy potentes y podría aportar desde ese lado si es de interés.

**Comment by olea** [comment]
> * Crear una [organización de GitHub](https://help.github.com/articles/about-organizations/) para alojar todos los proyectos de RLA-ES, además del diccionario que disponemos actualmente.

No es una necesidad perentoria pero tampoco lo vería mal. @sbosio ¿alguna opinión del patriarca del proyecto?

**Comment by olea** [comment]
> *  Eliminar scripts/archivos que ya no son necesarios

Si me dais indicaciones concretas me pongo con ello.

**Comment by olea** [comment]
¿Alguna cosa que queráis que arregle antes de publicar la v2.6?

**Comment by eksperimental** [comment]
Deberiamos cerrar este issue?

**Comment by RickieES** [comment]
Pues, la verdad, no es que los puntos propuestos estén mal, lo que pasa es que, como no son importantes para que el proyecto funcione, nadie ha sentido la necesidad de hacerlo. La verdad es que, si nos lo tomamos en serio, en menos de una semana deberíamos tenerlo completo.

En cuanto al punto uno, @olea cerró el _issue_ #42 hace unos meses con la idea de que alguien con la suficiente motivación para hacerlo lo reabriera. Si se reabre y se quiere acometer, yo optaría por la propuesta de @edittler de usar solo minúsculas y separar con guion medio en todo el proyecto.

En cuanto al punto dos, es cuestión de revisar los archivos del directorio herramientas. Estoy viendo que merge_dic.sh (que se podría renombrar a merge_dict.sh o merge-dict.sh) lo que hace es usar los programas cuyo código fuente en C está en el mismo directorio, compilándolos si es necesario. Sirve para fusionar varios diccionarios en uno solo. No lo usamos habitualmente, pero me parece interesante.

Y el tercer punto solo requiere revisar el script make_dict.sh y renombrar el directorio.

**Comment by RickieES** [comment]
Pues, la verdad, no es que los puntos propuestos estén mal, lo que pasa es que, como no son importantes para que el proyecto funcione, nadie ha sentido la necesidad de hacerlo. La verdad es que, si nos lo tomamos en serio, en menos de una semana deberíamos tenerlo completo.

En cuanto al punto uno, @olea cerró el _issue_ #42 hace unos meses con la idea de que alguien con la suficiente motivación para hacerlo lo reabriera. Si se reabre y se quiere acometer, yo optaría por la propuesta de @edittler de usar solo minúsculas y separar con guion medio en todo el proyecto.

En cuanto al punto dos, es cuestión de revisar los archivos del directorio herramientas. Estoy viendo que merge_dic.sh (que se podría renombrar a merge_dict.sh o merge-dict.sh) lo que hace es usar los programas cuyo código fuente en C está en el mismo directorio, compilándolos si es necesario. Sirve para fusionar varios diccionarios en uno solo. No lo usamos habitualmente, pero me parece interesante.

Y el tercer punto solo requiere revisar el script make_dict.sh y renombrar el directorio.

**Comment by eksperimental** [comment]
Esta bien. Sólo estaba limpiando las issues que había creado, y como esta está próxima a cumplir 5 años, me preguntaba si tenía sentido que siguiera abierta.

**Comment by RickieES** [comment]
Cambio el _milestone_ a la versión 2.7, aunque probablemente tengamos que cambiarlo de nuevo si cumplimos los plazos.

**Comment by eksperimental** [comment]
> Cambio el _milestone_ a la versión 2.7, aunque probablemente tengamos que cambiarlo de nuevo si cumplimos los plazos.

Convenganmos que hay para hacer, y enviaré un PR.

**Comment by RickieES** [comment]
Yo es que creo que no vamos a terminar de convenir lo que hay que hacer aquí. El primer punto se trató en el issue 42 (está enlazado arriba) y se cerró sin hacer nada porque no conseguimos consenso (y yo apoyo a muerte el último comentario de Ismael Olea). :smile:

El segundo punto, revisar los scripts y borrar los que no sirvan, tiene como dificultad localizar todos los que existan y, sobre todo, saber si son útiles. Que no los usemos habitualmente no significa necesariamente que no sean útiles, habría que investigar uno por uno.

El tercero requiere modificar los scripts que referencien el directorio ortograf, así que solo tendría sentido hacerlo después del segundo punto. Por cierto, que a alguien le _pica_ que la palabra se corte en el nombre del directorio, pero ¿alguien más ha pensado que si lo renombramos para que la palabra esté entera nos va a _picar_ que ponga "ortografia" en lugar de "ortografía"?

**Comment by eksperimental** [comment]
> Yo es que creo que no vamos a terminar de convenir lo que hay que hacer aquí. El primer punto se trató en el issue 42 (está enlazado arriba) y se cerró sin hacer nada porque no conseguimos consenso (y yo apoyo a muerte el último comentario de Ismael Olea). smile
> 
> El segundo punto, revisar los scripts y borrar los que no sirvan, tiene como dificultad localizar todos los que existan y, sobre todo, saber si son útiles. Que no los usemos habitualmente no significa necesariamente que no sean útiles, habría que investigar uno por uno.
> 
> El tercero requiere modificar los scripts que referencien el directorio ortograf, así que solo tendría sentido hacerlo después del segundo punto. Por cierto, que a alguien le _pica_ que la palabra se corte en el nombre del directorio, pero ¿alguien más ha pensado que si lo renombramos para que la palabra esté entera nos va a _picar_ que ponga "ortografia" en lugar de "ortografía"?

Creo que tiene mucho mas sentido abrir el issue cuando realmente haya el interes o la necesidad de hacerlo. Si en casi 6 años no se ha hecho y estamos igual que hace casi 6 años respecto a que rumbo tomar, ¿qué sentido tiene dejarlo abierto?
