### ISSUE TITLE
Número de versión Español Argentina en Mozilla

### ISSUE THREAD

**Issue by edittler** [sbosio/rla-es#45]
Visto que ha salido de la versión 2.0 del diccionario (felicitaciones y gracias por el laburo!), me resultó interesante actualizar el [diccionario Español Argentina](https://addons.mozilla.org/es/firefox/addon/diccionario-espa%C3%B1ol-argentina/) que está publicado para Mozilla, ya que hace rato que está medio abandonado y con muchos errores. La numeración que lleva ese diccionario es 2.5.1.

Una propuesta podría ser que en ese caso se salte a la numeración 2.6.

No tengo acceso para actualizarlo, debería consultar a la lista argentina de Mozilla.

**Comment by RickieES** [comment]
Hola, justo el otro día hablé con Guillermo Movia sobre el asunto. Por lo que veo, el complemento lo subió Marcelo Poli, pero creo que, aunque mantiene la traducción de los productos Mozilla al día, no tiene mucha participación en la comunidad de Mozilla últimamente.

A mí personalmente me encantaría que los diccionarios que hay publicados en Mozilla Addons (es-VE, es-AR y es-MX, además de es-ES), los cuales son todos ellos derivados del proyecto RLA-ES, partieran siempre del contenido de este repositorio, aportándose aquí las mejoras regionales de cada variante y beneficiándose de las que hacemos con carácter general. Eso haría que no solo se mejorase el contenido para Mozilla, sino para LibreOffice y OpenOffice, todo ello sin estar duplicando el trabajo.

Podemos intentar mover el tema en el [foro de Mozilla Hispano](https://foro.mozilla-hispano.org/c/traduccion), si quieres. Para la versión 0.7 no tuve mucho éxito, pero lo podemos intentar de nuevo.

**Comment by ezeperez26** [comment]
En su momento me comuniqué en la lista de correos de Mozilla Argentina y ahí me comentaron que el diccionario tomaba como base el diccionario de RLA y KNTRO me informó que había reportado muchas palabras al respecto en el antiguo sitio donde estaba alojado el proyecto, pero nada más.

He visto pasar muchas versiones en este proyecto y el diccionario de Argentina alojado en Mozilla no ha sido actualizado. Mi participación en RLA es muy baja, pero no tengo ningún problema en comprometerme a administrar la publicación del diccionario alojado en Mozilla, así el mismo se mantiene actualizado.

Pregunta, ¿es correcto hacer la consulta en el subforo correspondiente a traducción? La extensión es un corrector ortográfico, no una traducción.

**Comment by RickieES** [comment]
Precisamente la versión 2.0 incluye muchas palabras proporcionadas por KNTRO (si le preguntas, seguramente te dirá, y tiene razón, que el bug lo cursó hace mucho tiempo, como dos años o así). Por cierto, ¿tú tienes acceso a los archivos de la versión 2.0? Pensé que, al tenerla publicada como _draft_, no la veía nadie aparte de los miembros del proyecto.

La publicación es muy sencilla, en el wiki tengo explicados los pasos para generar el XPI para es-ES y adaptarlo para es-AR es trivial, no te preocupes porque sea difícil. Lo único que sería necesario es que consigas que te den acceso a administrar el complemento en Mozilla Addons.

En realidad el foro de Mozilla Hispano es de __localización__, lo cual no se limita solo a la traducción, sino que incluye las personalizaciones propias de cada país/región. Voy a abrir yo el tema y así puedes participar en él. :smile:

**Comment by ezeperez26** [comment]
El armado del diccionario no creo que sea un problema, me habían explicado como hacerlo.
Cuando armes el tema avisa por acá, así participo y vemos como actualizamos el diccionario :wink:

Veo el release en draft. De todas maneras, creo que @sbosio me puso como colaborador cuando creó el repositorio, ya que era miembro en el antiguo sitio.

**Comment by RickieES** [comment]
¡OK, genial! :smile: 

Ya he creado el [tema en MH](https://foro.mozilla-hispano.org/t/nueva-version-del-diccionario-ortografico-quieres-publicar-un-xpi-para-tu-pais/21681). Puedes responder ahí y yo voy a avisar a gente de es-AR para que pueda comentar también. Mi idea es que podamos publicar de verdad a finales de esta semana, a ver si hay suerte.

**Comment by RickieES** [comment]
@ezeperez26, ahora que estamos a punto de acabar la versión 2.1, ¿conseguiste avanzar en algo para el mantenimiento del diccionario es-AR de Mozilla?

**Comment by ezeperez26** [comment]
En el hilo de Mozilla Hispano no ha respondido alguien responsable del actual corrector.

También he mandado un mail a la lista de correos de Mozilla Argentina, pero nadie me ha respondido.
Podría intentar nuevamente en estos días.

¿Que otras opciones hay? ¿Crear un nuevo addon?

**Comment by RickieES** [comment]
Tengo la dirección de correo de Marcelo Poli. Acabo de escribirle una carta de recomendación para que te dé acceso al complemento en Mozilla Add-ons. :smile: Por cierto, que no sé si tienes cuenta en ese sitio para poder subir complementos.

**Comment by RickieES** [comment]
@ezeperez26, ¿conseguiste acceso para poder publicar tú mismo las versiones del diccionario es-AR para Mozilla?

**Comment by ezeperez26** [comment]
Aún no. Supuestamente Marcelo perdió acceso a su cuenta de Addons y en cuanto recuperara el acceso, se iba a comunicar (creo que vos también estaban en el intercambio de correos).

Conocí personalmente a Guillermo en el último Flisol de Buenos Aires cuando visité el stand de Mozilla y le recordé el tema.

Pero en concreto no hay nada. Una opción es subir un addon nuevo y solicitar que redireccionen al nuevo diccionario. Aunque para hacer esto, debería comunicarme con la comunidad Argentina de Mozilla que es bastante activa en cuanto a traducción y localización, así lo resolvemos sin problemas.

**Comment by RickieES** [comment]
Hace unos días contacté con Guillermo Movia para que transmitiera a Marcelo nuestra preocupación sobre el asunto. Quedó encargado de decírselo, pero por el momento no he tenido respuesta.

**Comment by ezeperez26** [comment]
Bárbaro! Espero que hayan novedades positivas.

**Comment by ezeperez26** [comment]
Informo por este medio que ya tengo acceso como desarrollador del _addon_ del diccionario de Español de Argentina.
No se que tan relevante es mantener sincronizado el número de versión como se discutió en los _issues_ #26 y #28. En el caso del diccionario de es-AR de Mozilla la versión actual es 2.5.1.

Para no generar otro gran salto de versión en RLA-ES, mi propuesta es la siguiente:

| RLA-ES | es-AR Mozilla |
|:------:|:-------------:|
| 2.2    | 2.6           |
| 2.3    | 2.6.1         |
| 2.4    | 2.6.2         |
| 2.5    | 2.6.3         |
| 2.6    | 2.6.4         |
| 2.7    | 2.7           |

A partir de la versión 2.7 ya estarían sincronizados ambos diccionarios.

Otra propuesta es que el diccionario de RLA-ES pase en la próxima versión a 2.6 o 2.7, aunque no creo que la cantidad de cambios que hubo desde la versión 2.2 justifiquen tal salto de versión.

**Comment by RickieES** [comment]
Veo dos posibilidades más. Una es continuar la serie 2.5.x en es-AR hasta sincronizar en 2.6 (en la 2.5 de RLA-ES, es-AR sería 2.5.5).

La otra sería numerar haciendo que el último dígito coincida con el de RLA-ES:

RLA-ES|es-AR Mozilla
----------|-------------
2.2|2.6 (o 2.6.2)
2.3|2.6.3
2.4|2.6.4
2.5|2.6.5
2.6|2.6.6
2.7|2.7

**Comment by ezeperez26** [comment]
Creo que el salto a 2.6 es necesaria ya que sí hubo grandes cambios, entre ellos el cambio de codificación a UTF8. Me gustó la propuesta de utilizar el tercer dígito para distinguir el segundo dígito de RLA-ES. Una buen ayuda nemotécnia. Empezaría por 2.6 por si tengo que hacer nuevas publicaciones para corregir errores de principiante. Si no hay otras opiniones, utilizaría esa regla y en estos días realizo la nueva publicación.

**Comment by ezeperez26** [comment]
¡Ya se encuentra publicada la version 2.6! :tada: :tada:

**Comment by RickieES** [comment]
@ezeperez26 , este _issue_ ya se puede cerrar, ¿verdad?

**Comment by ezeperez26** [comment]
Se podría cerrar, aunque de mi parte usaré como recordatorio las tablas de versiones.

**Comment by RickieES** [comment]
@edittler, ¿te parece bien si cerramos este _issue_, o necesitas que permanezca abierto hasta la versión 2.7?

**Comment by edittler** [comment]
Si, lo cierro. Puedo documentar esto en el [repositorio del plugin](https://github.com/edittler/diccionario-mozilla-es-AR).
