### ISSUE TITLE
El cambio de codificación del archivo hyph_es_ANY.dic puede ocasionar mal funcionamiento de la separación silábica

### ISSUE THREAD

**Issue by sbosio** [sbosio/rla-es#49]
En el commit que se implementó el cambio de codificación se modificó el encabezado del archivo hyph_es_ANY.dic (separación silábica) de "ISO-8859-1" a "UTF-8", pero esto no se debía hacer. Hasta donde sé es obligatorio que este diccionario utilice una codificación de 8-bit. El cambio a UTF-8 deberíamos analizarlo mejor y hacer muchas pruebas, porque el algoritmo de separación silábica que se utiliza (heredado del software TeX) es tan viejo (lo desarrolló Donald Knuth, creo, para que se den una idea) que en ese momento no existían codificaciones de bytes múltiples como UTF-8.

Además, se cambió el encabezado, pero no se convirtió el contenido del archivo a UTF-8, con lo cual es casi seguro que la separación silábica no funcione con el conjunto de diccionarios publicados de la versión 2.0.

**Comment by ezeperez26** [comment]
Ayer probé el diccionario 2.0 en Writer de LibreOffice y realizaba separaciones silábicas.

Según el repositorio de [hyphen](https://github.com/hunspell/hyphen), la librería parece ser compatible con UTF-8. De todas maneras es un mero convertidor de los patrones de TeX.
¿Habría que volver a "entrenar" para generar el diccionario de separaciones silábicas?

**Comment by RickieES** [comment]
A mí también me funciona bien la separación silábica con la versión 2.0 actual. Yo, sinceramente, soy partidario de no deshacer nada, porque no parece que haya problema, los complementos están ya subidos al catálogo de LibreOffice y estamos esperando que alguien con permisos los suba a OpenOffice. En Mozilla para es-ES lo subo yo cuando el resto esté publicado.

**Comment by sbosio** [comment]
¿Han podido verificar si separa correctamente en los puntos de separación
que incluyen acentos?

Porque no creo que deje de funcionar. Simplemente es probable que ignore
los puntos de separación que están contiguos a cualquier carácter que en
UTF8 se escriba en 2 bytes. Ya que el resto de los caracteres tienen la
misma representación en UTF8 que en ISO-8859-1.

Saludos,

Santiago

**Comment by RickieES** [comment]
¡Cachis! Es lo que había pensado que tenía que hacer cuando leí el comentario de @ezeperez26 y al final no me fijé al hacerlo yo mismo. :smile: Pero sí, lo acabo de probar con palabras con tilde ("malísimamente", "increíblemente", "cabría") y permite hacer la separación en todas las sílabas que caben realmente en la línea. En el caso de la primera, me permitía dividir en todas las sílabas, incluyendo "malí-simamente".

**Comment by RickieES** [comment]
Creo que podemos cambiar el milestone a 2.1 y decidir si revertimos el cambio de codificación, como propone @ezeperez26 en su PR, o bien intentar recodificar el archivo a UTF-8 de verdad para dejar todo el proyecto con la misma codificación.

**Comment by RickieES** [comment]
Voy a mover esto a la 2.1 porque la 2.0 lleva publicada más de un mes y ayer actualicé el diccionario incluido en la descarga oficial de LibreOffice.

**Comment by RickieES** [comment]
Acabo de aplicar el pull request de @ezeperez26 para revertir el cambio. De todas formas, creo que lo ideal sería que intentemos recodificar realmente el fichero a UTF-8 y comprobar si funciona bien.

**Comment by sbosio** [comment]
Si van a recodificarlo, que sea únicamente el fichero resultante, y no los
de entrenamiento, sé que hay alguna manera de hacer que 'patgen' funcione
con UTF-8, pero es mucho más cómodo hacerlo funcionar con ISO-8859-1.

Saludos, y felicitaciones por el gran trabajo.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Este
correo electrónico se ha enviado desde un equipo libre de virus y protegido
por Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ezeperez26** [comment]
El archivo resultante a convertir a UTF-8 sería [/separacion/hyph_es_ANY.dic](https://github.com/sbosio/rla-es/blob/master/separacion/hyph_es_ANY.dic)?

Otra cosa, estaría bueno dejar documentación sobre cómo generar dichos archivos. La información que se encuentra al respecto es muy escasa. Con agregar un README.md en dicho directorio debería ser suficiente.

Saludos!

**Comment by RickieES** [comment]
He encontrado esto sobre el uso de UTF-8 con patgen:

http://tex.stackexchange.com/questions/205154/patgen-to-create-hyphenation-dictionary-for-utf-8-language

Yo tampoco conozco esta herramienta. Supongo que sería cuestión de ponernos a buscar por Internet con más detalle y podríamos documentarlo, pero ¿hasta qué punto tenemos un problema con la separación silábica actualmente?

Otra cosa, en el directorio `sinonimos` hay un archivo README. Hay que retocarlo para que haga referencia no solo a OpenOffice sino también a LibreOffice.

**Comment by RickieES** [comment]
¿Qué deberíamos hacer con este issue? Se cursó porque podía haber un problema con la codificación y, efectivamente, hay un commit tras el cual todo funciona bien. Tenemos la opción de cerrarlo y abrir otro separado sin fecha para analizar los enlaces que he puesto en el comentario anterior. ¿Os parece bien?

**Comment by Almorca** [comment]
Si por ahora funciona yo lo dejaría para la siguiente versión pero sin cerrar este issue

**Comment by ezeperez26** [comment]
El estado actual es que dicho archivo está con la codificación vieja. A pesar de eso, la separación silábica sigue funcionando. No se que ventajas nos traería codificar a UTF-8, salvo ser consistente con el resto del proyecto.

Como el único que parece conocer este tema es @sbosio, lo dejaría para que lo revise cuando pueda.
Quizás quedaría para después, no para la versión 2.1.

PD: los _issues_ se cierran cuando se resolvieron, se decidió no resolverlo, no es un error, etc; pero no se cierra porque no se llegó con los plazos de una versión (el problema/mejora sigue sin resolverse).

**Comment by RickieES** [comment]
En realidad, el _issue_ era que, al pasar a UTF-8, podía funcionar mal la separación silábica. Al aplicar tu cambio, se retornaba la codificación a ISO-8859-1[5], por lo que se resolvía el posible problema. :smile: Otra cosa es que queramos que siga funcionando bien con el fichero en UTF-8.

**Comment by ezeperez26** [comment]
Lo cierto es que según el _issue_ #17 se esperaba convertir todo el diccionario a UTF-8, quedando este archivo fuera de la conversión por un (supuesto) error y por falta de pruebas para verificar el correcto funcionamiento de la separación silábica.

Quizás el _issue_debería ser renombrado a "Convertir a UTF-8 el archivo `hyph_es_ANY.dic` y realizar pruebas de separación silábica" o cerrarlo en caso de que lleguemos al consenso de no convertir dicho archivo.

**Comment by sbosio** [comment]
Mi propuesta es dejarlo en *ISO8859-1*. Se justificaría el cambio a *UTF-8*, como se describe en los enlaces que pasaron, si el español no tuviera una representación válida en una codificación de 8 bits. Todos los diccionarios de separación silábica que he visto continúan usando *ISO8859-1*, salvo, por ejemplo, el ruso y el húngaro.

El proceso de **entrenar** un diccionario haciendo la traducción manual propuesta en el enlace y luego reconvirtiendo, es mucho más laborioso que directamente trabajar con esos ficheros en *ISO8859-1*, y no se justifica existiendo la codificación.

Además, salvo que se encuentre algún error en la separación, no es un archivo que deba modificarse frecuentemente. El fichero de entrenamiento lo armé con más de 8.000 palabras elegidas al azar del listado de palabras del diccionario, separadas manualmente de acuerdo con las recomendaciones más actualizadas de la RAE (en este momento no encuentro el enlace, pero cuando lo encuentre lo pongo aquí). Hasta ahora, creo que no hay ningún issue publicado que haga referencia a la separación silábica.

**Comment by RickieES** [comment]
Bueno, pues yo creo que lo cerramos. @ezeperez26, te lo asigno a ti porque tú enviaste el parche.

**Comment by ezeperez26** [comment]
En el directorio `separacion` agregué el archivo [README.md](https://github.com/sbosio/rla-es/blob/master/separacion/README.md) con una explicación de lo que se discutió en este _issue_, ya que una vez cerrado pierde visibilidad.

Además, encontré información sobre los algoritmos de separación silábica y completé lo más que pude, incluyendo los datos que nos proveyó @sbosio sobre cómo se construyó.

PD: según mi modalidad de trabajo, cuando un _issue_ se cierra, deja de tener responsables asignados, ya que ha finalizado su vida útil. ¿Aquí hay una forma diferente que deba conocer, ya que me fue asignado un _issue_ cerrado?

**Comment by RickieES** [comment]
> PD: según mi modalidad de trabajo, cuando un issue se cierra, deja de tener responsables asignados, ya que ha finalizado su vida útil. ¿Aquí hay una forma diferente que deba conocer, ya que me fue asignado un issue cerrado?

No sé cómo lo ven otros miembros. Para mí, el _issue_ debería quedar asignado a quien se encargó de ello, incluso una vez cerrado. Entre otras cosas, eso permite ver quién ha resuelto cada _issue_ con independencia de quién hizo el _commit_. También permitiría saber cuántos _issues_ ha cerrado cada colaborador. Por otra parte, si te he asignado un _issue_ ya cerrado, que alguno he asignado, no ha sido para deshacer tu desasignación (si la hiciste tú) sino porque creí que se nos había olvidado asignártelo. :smile:
