### ISSUE TITLE
Palabras para incluir en el diccionario

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#5]
Corresponde al registro 755 de de RLA-ES en Forja.rediris.es
Creado por Roberto Isaac González Gracia (riggr) con fecha y hora  2013-09-21 22:42

==================================================
Hola:
Les envío las siguientes palabras que no están el diccionario y que he colectado durante algún tiempo. Para su evaluación

Palabras RAE que no están en el diccionario
balacera
erógena
geoda
humanoide
insurgencia

Palabras NoRAE
latinoamérica
autoimagen
chaquetín
chapitas

Adjetivos RAE
atemporal
aperlada
existencialista
grandísimo
caleidoscópica ( de esta si está calidoscópica) 
preocupadísimo

Adverbios de modo RAE
Son palabras que su raíz si existe en RAE pero en su forma adverbial no están en el diccionario
abrigante
agitadamente
aromáticamente
electrizante
acechante
frustrante
insospechadamente
despreocupadamente
egoístamente
erráticamente
gigantescamente
destellante
desvaneciente
implorante
desorbitante
díjole
enciéndete
liberante
líbrame
libérame
inconcebiblemente
protégeme
bésame
enfócate
autoflagelarse
boquita

Nombres propios
Rosalba

**Comment by RickieES** [comment]
Voy con el primer bloque.

Balacera se considera nombre femenino usado en América. ¿Eso significa que deberíamos añadirlo en cada una de las variantes es_XX de Hispanoamérica pero no en es_ES? Yo me inclino más bien por interpretarlo como una palabra perteneciente a todas las variantes regionales, incluyendo es_ES, pero de uso más extendido en Hispanoamérica y, por tanto, añadirla con carácter general (sería balacera/S en NombresFemeninos.txt).

erógeno es erógeno/GS en Adjetivos.txt

geoda es geoda/S en NombresFemeninos.txt (sorprendentemente, tiene 380.000 resultados en Google)

humanoide sería humanoide/S en Adjetivos.txt de acuerdo con la RAE, aunque a mí me parece que también se puede usar como sustantivo. A efectos prácticos da igual, pero me llama la atención.

insurgencia sería insurgencia/S en NombresFemeninos.txt

**Comment by RickieES** [comment]
He subido el primer bloque aunque luego decidamos corregir alguna entrada.

Voy con el segundo bloque.

latinoamérica: es correcto que no la reconozca, debe escribirse con la inicial en mayúscula (Latinoamética)

autoimagen arroja unos 336.000 resultados en Google. Fundeu recomienda autofoto como alternativa a selfie, en lugar de autoimagen.

chaquetín arroja unos 54.000 resultados en Google. No podemos derivarlo de chaqueta. Si lo añadimos, sería en noRAE/NombresMasculinos.txt (no entiendo muy bien cuándo usar NombresComunes.txt porque, por ejemplo, chapa está en NombresComunes.txt en lugar de en NombresFemeninos.txt).

chapitas se deriva de chapa/S en NombresComunes.txt mediante el sufijo U de diminutivos.

Como aquí veo más dudas (autoimagen, chaquetín), no hago los cambios aún.

**Comment by ezeperez26** [comment]
Te ayudo con las palabras del 2° bloque y dejo mi análisis del resto de las palabras.

latinoamérica, concuerdo con @RickieES.

autoimagen tiene 300 mil resultados y no se refiere a la _selfie_. Según [Wikipedia](https://es.wikipedia.org/wiki/Autoimagen), hace referencia a conocerse a sí mismo. Para mí debería ser agregada.

chaquetín parece ser una palabra usada solamente en México y quizás en algún otro país de la zona. Yo lo agregaría sólo para México.

chapitas, concuerdo con @RickieES.

atemporal se encuentra en RAE y tiene más de un millón de resultados en google. Iría en RAE/Adjetivos.txt con el sufijo de plural.

aperlado se encuentra en RAE y tiene más de 300 mil resultados en google. Iría en RAE/Adjetivos.txt con los sufijos de género y plurales.

existencialista se encuentra en RAE y tiene más de 400 mil resultados en google. Iría en RAE/Adjetivos.txt con el sufijo de plural.

caleidoscópico se encuentra en RAE y tiene más 200 mil resultados en google. Iría en RAE/Adjetivos.txt con los sufijos de género y plural.

grandísimo no aparece en RAE como menciona, pero tiene casi 800 mil resultados en google. En RAE/Adjetivos.txt ya se encuentra “grande”, pero veo que no existe un sufijo -ísimo. ¿se puede agregar? Es un sufijo bastante común.

preocupadísimo no está en RAE como indica y tiene sólo 29 mil resultados en google. No se agregaría.

abrigante no se encuentra en RAE y tiene sólo 13 mil resultados en google. No entraría.

agitadamente no se encuentra en RAE y tiene más de 100 mil resultados en google. Entraría en noRAE/Advervios.txt

aromáticamente no se encuentra en RAE y tiene 15 mil resultados en google. No entraría.

electrizante se encuentra en RAE y tiene casi 500 mil resultados en google. Va en RAE/Adjetivos.txt con sufijo de plural. 

acechante aparece en RAE y tiene 76 mil resultados. ¿Entra? En caso afirmativo iría en RAE/Adjetivos.txt con sufijo de plural. 

frustrante aparece en RAE y tiene más de un millón de resultados en google. Entra en RAE/Adjetivos.txt con el sufijo de plural.

insospechadamente no aparece en RAE y tiene 27 mil resultados en google. No entraría.

despreocupadamente ya se encuentra en el diccionario.

egoístamente no se encuentra en RAE pero tiene casi 200 mil resultados en google. Entraría en no RAE/Adverbios.txt

erráticamente ya se encuentra en el diccionario.

gigantescamente no se encuentra en RAE y tiene 30 mil resultados en google. No entraría.

destellante no se encuentra en RAE y tiene 160 mil resultados en google. Iría en noRAE/Adjetivos.txt con el sufijo de plural.

desvaneciente no está en RAE, tiene más de 300 mil resultados en google. Iría en noRAE/Adjetivos.txt con sufijo de plural.

implorante se encuentra en RAE, va en RAE/Adjetivos.txt con sufijo de plural.

desorbitante no se encuentra en RAE y tiene 50 mil resultados en google.

díjole no se encuentra en RAE y no llega a los 100 mil resultados de google. Creo que esta expresión está en desuso.

enciéndete ya se encuentra en el diccionario 2.0

liberante no se encuentra en RAE y no tiene resultados que demuestren su uso.

líbrame es una conjugación de librar. En el archivo de sufijos hay algunos reemplazos para “ibrar”. Hay que agregar el reemplazo para formar la palabra “líbrame”.

libérame ya se encuentra en el diccionario 2.0

inconcebiblemente no se encuentra en RAE y tiene 30 mil resultados en google. No entraría.

protégeme es conjugación de "proteger". En el archivo de sufijos hay reemplazos para "eger", hay que agregar el reemplazo la palabra "protégeme"

bésame ya se encuentra en el diccionario 2.0

enfócate ya se encuentra en el diccionario 2.0

autoflagelarse sería una conjugación de “autoflagelación”, la cual tampoco se encuentra en el diccionario.

boquita se encuentra en RAE y aclara que su uso se da en Guatemala, Honduras, Nicaragua y Panamá.

**Comment by RickieES** [comment]
Muchas gracias, @ezeperez26. No sé si hoy me dará tiempo, pero en estos próximos días haré los cambios.

**Comment by ezeperez26** [comment]
Son bastantes palabras. Si quieres puedo ayudar a agregar las que se encuentran en RAE y estarían disponible para todas las localizaciones.

**Comment by RickieES** [comment]
Muchas gracias, @ezeperez26. Si no me equivoco, en el commit has llegado hasta completar todos los adjetivos, ¿verdad?

**Comment by RickieES** [comment]
BTW, espero poder hacer el resto yo. Aunque no veáis avances aquí, iré buscando huecos y subiendo cambios poco a poco.

**Comment by ezeperez26** [comment]
Agregué todos los adjetivos que se encuentran en RAE y "chapitas".
Las que no agregué son las no RAE (no estoy seguro cual es la regla que usan para incluir una palabra no RAE), las que son conjugaciones cuyo prefijo no está (no me animo a tocar el archivo de afijos por ahora).

En limpio, las palabras que aún no se encuentran en el diccionario son:

- **autoimagen** tiene 300 mil resultados y no se refiere a la _selfie_. Según [Wikipedia](https://es.wikipedia.org/wiki/Autoimagen), hace referencia a conocerse a sí mismo.

- **chaquetín** parece ser una palabra usada solamente en México y quizás en algún otro país de la zona. Yo lo agregaría sólo para México.

- **grandísimo** no aparece en RAE como menciona, pero tiene casi 800 mil resultados en google. En RAE/Adjetivos.txt ya se encuentra “grande”, pero veo que no existe un sufijo -ísimo. ¿se puede agregar? Es un sufijo bastante común.

- **preocupadísimo** no está en RAE como indica y tiene sólo 29 mil resultados en google. No se agregaría.

- **abrigante** no se encuentra en RAE y tiene sólo 13 mil resultados en google. No entraría.

- **agitadamente** no se encuentra en RAE y tiene más de 100 mil resultados en google. Entraría en noRAE/Advervios.tx

- **aromáticamente** no se encuentra en RAE y tiene 15 mil resultados en google. No entraría.

- **insospechadamente** no aparece en RAE y tiene 27 mil resultados en google. No entraría.

- **egoístamente** no se encuentra en RAE pero tiene casi 200 mil resultados en google. Entraría en no RAE/Adverbios.txt.

- **gigantescamente** no se encuentra en RAE y tiene 30 mil resultados en google. No entraría.

- **destellante** no se encuentra en RAE y tiene 160 mil resultados en google. Iría en noRAE/Adjetivos.txt con el sufijo de plural.

- **desvaneciente** no está en RAE, tiene más de 300 mil resultados en google. Iría en noRAE/Adjetivos.txt con sufijo de plural.

- **desorbitante** no se encuentra en RAE y tiene 50 mil resultados en google.

- **díjole** no se encuentra en RAE y no llega a los 100 mil resultados de google. Creo que esta expresión está en desuso.

- **liberante** no se encuentra en RAE y no tiene resultados que demuestren su uso.

- **líbrame** es una conjugación de librar. En el archivo de sufijos hay algunos reemplazos para “ibrar”. Hay que agregar el reemplazo para formar la palabra “líbrame”.

- **inconcebiblemente** no se encuentra en RAE y tiene 30 mil resultados en google. No entraría.

- **protégeme** es conjugación de proteger. En el archivo de sufijos hay reemplazos para “eger”, hay que agregar el reemplazo la palabra "protégeme".

- **autoflagelarse** sería una conjugación de “autoflagelación”, la cual tampoco se encuentra en el diccionario.

- **boquita** se encuentra en RAE y aclara que su uso se da en Guatemala, Honduras, Nicaragua y Panamá.

**Comment by RickieES** [comment]
>  En RAE/Adjetivos.txt ya se encuentra “grande”, pero veo que no existe un sufijo -ísimo. ¿se puede agregar? Es un sufijo bastante común.

Tenemos varias propuestas de afijos para añadir: prefijos micro-, macro-, mini- y maxi-, sufijos -ísimo y -mente (para los adverbios; este último lo propongo yo). Creo que debemos plantearnos lo de los afijos para la próxima versión, así que he abierto el issue #60.

**Comment by RickieES** [comment]
> autoimagen tiene 300 mil resultados y no se refiere a la selfie. Según Wikipedia, hace referencia a conocerse a sí mismo.

Añadida en noRAE/NombresFemeninos.txt: autoimagen/S

> chaquetín parece ser una palabra usada solamente en México y quizás en algún otro país de la zona. Yo lo agregaría sólo para México.

Para dejarlo documentado, no es fácil encontrar coincidencias de chaquetín (ni CORPES ni CDH devuelven resultados, y una búsqueda en Internet no devuelve páginas que definan la palabra desde un punto de vista formal). La asociación de la palabra que ezeperez26 hace con México yo también la hago si me fijo en los dominios de las páginas web que las usan, generalmente vendiendo artículos de ropa con ese nombre.

En definitiva, veo pocas referencias que nos permitan añadir la palabra de momento. He preguntado en el grupo de Telegram de Mozilla Hispano, que reúne colaboradores de muchos países de LATAM, a ver qué opinan. En función de lo que digan, informaré y veremos si merece la pena añadir la palabra.

> grandísimo no aparece en RAE como menciona, pero tiene casi 800 mil resultados en google. En RAE/Adjetivos.txt ya se encuentra “grande”, pero veo que no existe un sufijo -ísimo. ¿se puede agregar? Es un sufijo bastante común.

Al margen de que tratemos más adelante el asunto de los afijos para diversos prefijos y sufijos comunes, de momento añado "grandísimo" en noRAE/Adjetivos.txt como grandísimo/GS.

¿Por qué lo añado en noRAE, sobre todo teniendo en cuenta que, si finalmente creamos un afijo para -ísimo, lo derivaríamos desde RAE/Adjetivos.txt:grande? Pues para evitar tener que preparar argumentos si alguien abre un _issue_ diciendo "grandísimo" no está en el DLE de RAE pero se ha incluido en RAE/Adjetivos.txt.

> preocupadísimo no está en RAE como indica y tiene sólo 29 mil resultados en google. No se agregaría.

No lo añado, al margen de que pueda llegar a crearse el afijo más adelante y aplicarlo a preocupar.

> abrigante no se encuentra en RAE y tiene sólo 13 mil resultados en google. No entraría.

No la añado.

> agitadamente no se encuentra en RAE y tiene más de 100 mil resultados en google. Entraría en noRAE/Adverbios.txt

Añadida justo ahí.

> aromáticamente no se encuentra en RAE y tiene 15 mil resultados en google. No entraría.

No la añado.

> insospechadamente no aparece en RAE y tiene 27 mil resultados en google. No entraría.

No la añado.

> egoístamente no se encuentra en RAE pero tiene casi 200 mil resultados en google. Entraría en no RAE/Adverbios.txt.

Añadida justo ahí.

> gigantescamente no se encuentra en RAE y tiene 30 mil resultados en google. No entraría.

No la añado.

> destellante no se encuentra en RAE y tiene 160 mil resultados en google. Iría en noRAE/Adjetivos.txt con el sufijo de plural.

Añadida en noRAE/Adjetivos.txt como destellante/S.

> desvaneciente no está en RAE, tiene más de 300 mil resultados en google. Iría en noRAE/Adjetivos.txt con sufijo de plural.

Añadida en noRAE/Adjetivos.txt como desvaneciente/S.

> desorbitante no se encuentra en RAE y tiene 50 mil resultados en google.

A mí me parece suficientemente usual para añadirla, así que la añado en noRAE/Adjetivos.txt como desorbitante/S.

> díjole no se encuentra en RAE y no llega a los 100 mil resultados de google. Creo que esta expresión está en desuso.

Concuerdo contigo, no la añado.

> liberante no se encuentra en RAE y no tiene resultados que demuestren su uso.

Ídem, no la añado.

> líbrame es una conjugación de librar. En el archivo de sufijos hay algunos reemplazos para “ibrar”. Hay que agregar el reemplazo para formar la palabra “líbrame”.

Pues me voy a tirar a la piscina. "Librar" se conjuga como "amar", y el sufijo Í contiene la derivación (la palabra íntegra, en este caso) para ámame y ámanos, así que he añadido estas reglas:

SFX Í ibrar     íbrame   ibrar
SFX Í ibrar     íbranos  ibrar

en todos los ficheros afijos.txt, incrementando en 2 el número de reglas para ese afijo.

Los verbos acabados en -ibrar que veo son estos:

    $ grep -R -e ibrar/ *
    RAE/VerbosTransitivosPronominales.txt:desequilibrar/REDñô
    RAE/VerbosTransitivosPronominales.txt:equilibrar/REDÀÁÄÅñò
    RAE/VerbosTransitivosIntransitivos.txt:vibrar/RED
    RAE/VerbosTransitivosIntransitivosPronominales.txt:librar/REDÀÂñòôø
    RAE/VerbosTransitivos.txt:calibrar/REDÀ
    RAE/VerbosTransitivos.txt:desfibrar/RED

De ellos, los dos primeros seguramente lo aceptarían, pero no veo mucho uso a "des/equilíbrame", y tampoco a "calíbrame" o "desfíbrame", así que solo añado el afijo Í a librar. Si alguien lo pide más adelante, lo añadimos.

> inconcebiblemente no se encuentra en RAE y tiene 30 mil resultados en google. No entraría.

No la añado.

> protégeme es conjugación de proteger. En el archivo de sufijos hay reemplazos para “eger”, hay que agregar el reemplazo la palabra "protégeme".

¡Mecachis! Por no escribir lo que me pide el cuerpo. :sob: Es exactamente el mismo afijo el que hay que tocar. Bueno, no voy a añadirlo hasta generar un diccionario de prueba para ver si líbrame funciona bien. 

> autoflagelarse sería una conjugación de “autoflagelación”, la cual tampoco se encuentra en el diccionario.

O también desde "flagelar". El prefijo "d" antepone auto-, aunque debido a que los afijos no son acumulativos, creo que podríamos tener autoflagelar o flagelarse, pero no autoflagelarse.

> boquita se encuentra en RAE y aclara que su uso se da en Guatemala, Honduras, Nicaragua y Panamá.

Pues no sé si formalmente es solo de esas variantes, pero en España también es muy habitual decir, por ejemplo, "¡Vaya boquita que tienes!" cuando alguien suelta muchos tacos, así que añado la bandera U en RAE/NombresFemeninos.txt: boca/NSU.

**Comment by RickieES** [comment]
Justo encima de mi largo comentario figura el commit con esos cambios. Queda pendiente, de las excelentes sugerencias de @ezeperez26, "protégeme", que consiste en añadir dos reglas más en el sufijo Í, pero solo lo haré cuando compruebe que las que ya he añadido para líbrame funcionan bien. Entonces también volveré a añadir todas las palabras del _issue_ en un documento Writer para comprobar cuáles continúan siendo marcadas como incorrectas.

**Comment by RickieES** [comment]
Bien, he generado el diccionario (ya con los topónimos corregidos) y todo está como estaba previsto, marcando como incorrectas las que hemos decidido no añadir, con las siguientes excepciones:

protégeme
autoflagelarse

La primera requiere tocar de nuevo el sufijo Í, que ahora me pondré con él. La segunda requiere añadir el prefijo d al verbo flagelar, y no sé si funciona de manera acumulativa, pero probar es gratis, así que voy a subir los cambios del issue #68 y luego probaré esto.

**Comment by RickieES** [comment]
Pues ya solo queda Rosalba. ¿Alguien ve algún inconveniente en añadirla en noRAE/NombresPropiosSiglas.txt?

**Comment by RickieES** [comment]
Última palabra añadida. En unas horas cierro este issue si nadie dice nada.

**Comment by RickieES** [comment]
Como no ha habido quejas, cierro el issue. :clap: :clap:
