### ISSUE TITLE
Cambio de la marca OpenOffice.org a Apache OpenOffice

### ISSUE THREAD

**Issue by ezeperez26** [sbosio/rla-es#52]
En el año 2012, luego de que Oracle ceda el proyecto a Apache, por políticas de marcas de esta última, el proyecto OpenOffice.org [se renombró a Apache OpenOffice](https://blogs.apache.org/OOo/entry/openoffice_org_is_now_apache).

En este proyecto y las extensiones publicadas aún se hace mención a OpenOffice.org.

Para [README.md](https://github.com/sbosio/rla-es/blob/master/README.md) ya estaría corregido en el pull request #50, donde propuse una mejor version del README.md

En [ortograf/docs/README_base.txt](https://github.com/sbosio/rla-es/blob/master/ortograf/docs/README_base.txt) (el que aparece dentro del zip de las extensiones) se hace mención a versiones viejas de OpenOffice.org. Dado que hace más de 3 años del cambio de marca, a partir de la version 3.4 de Apache OpenOffice, se podria eliminar cualquier mención a versiones viejas.
Lo mismo con [separacion/README_hyph_es_ANY.txt](https://github.com/sbosio/rla-es/blob/master/separacion/README_hyph_es_ANY.txt).

Por ultimo, habría que revisar en las descripciones de las extensiones en los respectivos sitios de cada aplicacion.

**Comment by RickieES** [comment]
Me pongo con esto si nadie ha hecho nada aún.

**Comment by ezeperez26** [comment]
Adelante!!
Como comentario sobre la mejora a aplicar, en los README (ejemplo, [README_base.txt](https://github.com/sbosio/rla-es/blob/master/ortograf/docs/README_base.txt)) se encuentra el siguiente párrafo:

> NOTA: en el resto del documento, cada aparición de OpenOffice.org puede
entenderse referida también a LibreOffice. No obstante, tenga en cuenta que
la primera versión de LibreOffice es compatible con OpenOffice.org 3.x, por
lo que las menciones a OpenOffice.org 1.x y 2.x no son aplicables a LibreOffice.

Creo ahora deberíamos hacer mención a LibreOffice sobre Apache OpenOffice por 2 motivos:

* LibreOffice posee actualmente mayor popularidad que Apache OpenOffice. Es la suite ofimática instalada por defecto en la mayoría de las distribuciones GNU/Linux.

* Por políticas de marca de Apache, se debe escribir siempre "Apache OpenOffice" y no simplemente "OpenOffice" ni "OpenOffice.org".

Con respecto a OpenOffice.org 1.x y 2.x, ¿se poseen estadísticas de su uso actual?
O más bien, ¿poseen soporte por parte de Oracle o Apache?
Si su uso es prácticamente nulo o si no posee soporte dichas versiones, se podría eliminar el instructivo para dichas versiones.

**Comment by RickieES** [comment]
Esa nota la he eliminado y he asumido que Apache OpenOffice/LibreOffice implican el procedimiento usado a partir de la versión 3.

Yo también he pensado si tiene mucho sentido mantener las referencias a OpenOffice.org 1.x/2.x (manteniendo literalmente esa nomenclatura, ya que entiendo que quien lo use tendrá los binarios originales).

Prácticamente he acabado la revisión ya, y he usado Apache OpenOffice/LibreOffice. No tengo problema en invertir el orden a LibreOffice/Apache OpenOffice si lo preferís.

Aprovechando la revisión, voy a actualizar los enlaces de la página web traída desde forja.rediris, aunque seguramente no volvamos a usarla.

**Comment by RickieES** [comment]
Aquí adjunto el diff de cambios. En web/index.html, además de un cambio sobre la versión, he actualizado enlaces y licencia, y he formateado un poco el código.

En el README he añadido a @ezeperez26, que le teníamos discriminado. :smile: 

[issue52.txt](https://github.com/sbosio/rla-es/files/184147/issue52.txt)

**Comment by ezeperez26** [comment]
Gracias!!

Seré curioso, ¿que utilidad tiene el sitio web?
No lo veo publicado en algún lado, ni siquiera hemos aprovechado los beneficios de las [páginas de GitHub](https://pages.github.com/)

**Comment by RickieES** [comment]
El sitio web (contenido en una sola página) era una introducción breve al proyecto. Ahora seguramente con el README.md tenemos la misma información.

**Comment by RickieES** [comment]
Para ir cerrando los últimos issues, ¿entonces preferís que invierta el orden de Apache OpenOffice/LibreOffice a LibreOffice/Apache OpenOffice?

**Comment by ezeperez26** [comment]
Si aparecen ambos, el orden me resulta indistinto. Diría que lo dejes como está, a menos que alguien opine diferente.

**Comment by RickieES** [comment]
Pues cierro este _issue_, porque ya han pasado tres días desde que pregunté y no ha habido opiniones en contra.

**Comment by RickieES** [comment]
Soy muy listo. Añadí el diff, pero no hice el commit, así que los cambios no están en el repositorio.

**Comment by RickieES** [comment]
Vale, ahora sí. :blush:
