### ISSUE TITLE
Comunicación

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#56]
Abro esta incidencia para ver si conocéis algún método por el cual podamos comunicarnos. Echo en falta un sistema por el cual podamos coordinarnos, algo como una lista de correo o un pequeño foro. No sé si github tiene algo que cumpla esa función.

La duda me ha surgido porque quería comentar que fecha buscar para publicar la versión 2.1 y que issues deberíamos resolver para darlo por finalizado.

**Comment by RickieES** [comment]
Tengo la misma desazón que tú. :smile: Tengo un proyecto creado aquí (del que, por tanto, soy administrador) y no me suena haber visto nada similar a un foro o una lista de correo. Me da la sensación de que los _issues_ son el único medio de comunicación, pero a ver si hay alguien que pueda sacarnos de nuestro error.

Los _issues_ "que deberíamos resolver para finalizar la 2.1" tienen asignado ese hito, según una estimación que hice cuando acabamos la 2.0. Puedes verlos fácilmente si vas a la lista de _issues_, pulsas el botón **Milestones** y luego pulsas en el título "Versión 2.1".

Ahora mismo hay 7 _issues_ asignados, de los cuales 4 ya están hechos. Por supuesto, podemos añadir o quitar los que queramos, aunque el de las palabras de Wikipedia, estando a medias, yo lo dejaría ya dentro de la 2.1 hasta completar el bloque de 100 que comentabas. Sobre la fecha, probablemente ese bloque de 100 palabras sea el mejor indicador para dar por finalizada la versión. Finales de marzo me parece un tope razonable y, si podemos adelantarlo algo, mejor. Pero todo esto son elucubraciones mías que hago únicamente para que haya una referencia sobre la que podamos construir entre todos.

Para no contaminar el _issue_, acabo recordando que necesitamos a alguien que nos diga si hay posibilidad de asociar foros o listas de correo a un proyecto en GitHub, o si la forma de comunicación prevista es mediante _issues_

**Comment by ezeperez26** [comment]
Pensando en servicios que se puedan vincular con GitHub, conozco a [Gitter](https://gitter.im) que es una especie de chat IRC pero con ciertas mejoras como almacenar las conversaciones en la nube, referir _issues_, entre otras cosas. Es bastante popular y usado en proyectos grandes como [Angular.js](https://gitter.im/angular/angular.js) y otros.

Un servicio más similar a foros que también se puede vincular a los repositorios u organizaciones de GitHub es [Ost.io](http://ost.io). Aunque es mucho menos popular y por lo que vi es bastante simple y limitada la funcionalidad de foro. Por ejemplo, según el mismo sitio, [éste](http://ost.io/@brunch/brunch) es uno de los foros más populares.

GitHub es meramente un sistema de versionado de código, el cual le han añadido algunas funcionalidades como la gestión de _issues_, la wiki, páginas de repositorios, etc. 
Por suerte, alrededor de GitHub surgieron muchos servicios adicionales, como los que acabo de mencionar.

**Comment by eksperimental** [comment]
Parece q lo q necesitan es una lista de correos

**Comment by RickieES** [comment]
> Parece q lo q necesitan es una lista de correos

Sí, yo creo que realmente lo único que no nos convence de usar los propios _issues_ para comunicarnos es que la conversación queda registrada como un fallo o mejora.

Podría ser cuestión de acostumbrarnos a verlo de una manera ligeramente diferente. Por ejemplo, @Almorca comentaba esto como origen de este _issue_:

> La duda me ha surgido porque quería comentar que fecha buscar para publicar la versión 2.1 y
> que issues deberíamos resolver para darlo por finalizado.

La primera cuestión, la fecha de publicación, podría haberse gestionado creando un _issue_ con el título "Elegir fecha de publicación de la versión 2.1" y asignándolo al propio _milestone_ "Versión 2.1". En realidad, tiene cierto sentido: casi lo primero que hay que resolver para tener lista la versión 2.1 es decidir cuándo la queremos tener lista. :smile: 

La segunda cuestión, ver qué _issues_ hay que resolver para considerar la versión 2.1 lista, se puede obtener en un momento cualquiera como comenté más arriba ("...vas a la lista de issues, pulsas el botón Milestones y luego pulsas en el título Versión 2.1"). Determinar qué _issues_ nominamos para que se incluyan en la versión 2.1 se podría discutir en cada uno de esos _issues_. Si alguien (como he hecho yo mismo) marca algún _issue_ para una versión y otros miembros no lo ven correcto, pueden comentarlo en el mismo, o incluso eliminar esa asignación (supongo que no seré el único, además de Santiago Bosio, con permisos para asignar un _issue_ a un _milestone_, pero si fuera así, hay que pedirle a Santiago que dé permiso a más miembros).

Esto soluciona este ejemplo concreto de Alejandro; habrá otras cosas de las que interese hablar y no consideremos _issues_. Es cuestión de ir viéndolas y buscar formas de encajarlas con las herramientas que tenemos (repositorio, registro de incidencias y el wiki).

**Comment by olea** [comment]
Una alternativa es usar una sala de charla en jabber.org http://www.jabber.org/faq.html#chatrooms

**Comment by Almorca** [comment]
Ost.io que comenta @ezeperez26 no tiene mala pinta y se puede usar con la cuenta de github. Otra opción que he visto en algún proyecto es hacer un grupo de Google.

**Comment by olea** [comment]
Usar Gitter o Slack son antipatrones de herramientas de comunicación para
proyectos abiertos:
https://drewdevault.com/2015/11/01/Please-stop-using-slack.html

2016-02-02 10:45 GMT+01:00 Almorca <notifications@github.com>:

> Ost.io que comenta @ezeperez26 <https://github.com/ezeperez26> no tiene
> mala pinta y se puede usar con la cuenta de github. Otra opción que he
> visto en algún proyecto es hacer un grupo de Google.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbosio/rla-es/issues/56#issuecomment-178478076>.
>



-- 

Ismael Olea

http://olea.org/diario/

**Comment by ezeperez26** [comment]
Interesante artículo de @olea. Concuerdo que no tiene mucho sentido usar herramientas privativas en proyectos de código abierto.
Ost.io es libre según su sitio y hasta tienen el código publicado en GitHub.
Usar algo como [Freenode](http://freenode.net/) o Jabber no es útil, a menos que algún día coordinemos un horario para encontrarnos varios al mismo tiempo.
Aunque concuerdo con @RickieES, para el caso de la planificación de la versión 2.1 se podría haber creado un _issue_. Todo depende de las políticas que le demos al gestor de incidencias. Por ejemplo, proyectos sólo lo usan para reporte de errores.

**Comment by olea** [comment]
2016-02-02 15:51 GMT+01:00 Ezequiel <notifications@github.com>:

 Interesante artículo de @olea <https://github.com/olea>. Concuerdo que no
> tiene mucho sentido usar herramientas privativas en proyectos de código
> abierto.
>
 para mí no es tanto problema la licencia del código como de la
transparencia de la comunicación

> Usar algo como Freenode <http://freenode.net/> o Jabber no es útil, a
> menos que algún día coordinemos un horario para encontrarnos varios al
> mismo tiempo.
>
con Jabber sabéis que se pueden tener sesiones abiertas indefinidamente y
desde múltiples dispositivos, con lo que la persistencia de la comunicación
es muuucho más robusta que con IRC.

-- 

Ismael Olea

http://olea.org/diario/

**Comment by RickieES** [comment]
Yo coincido con @ezeperez26 en lo de Freenode. Como dice @eksperimental, probablemente lo que querríamos, si no conseguimos apañarnos con los propios _issues_, sería una lista de correo.

En otros sitios se están usando canales de Telegram, que imagino que es parecido en funcionalidades (envío de archivos e imágenes, histórico, etc., control de acceso por invitación...) a usar Jabber, aunque para crear la cuenta se requiere un teléfono móvil (pero luego no hay que hacerlo público). Es muy cómodo porque funciona en el móvil, en web, con posibilidad de tener varios clientes abiertos simultáneamente de manera completamente independiente (no necesitas tener el móvil encendido ni a mano para tener la versión web abierta en uno, dos o cinco equipos a la vez).

Yo, que ahora mismo ya no tengo cliente Jabber en el móvil, preferiría Telegram. Por supuesto, a quien no usa Telegram habitualmente le pasará lo mismo que a mí con Jabber, pero al revés.

Lo malo de una solución basada en mensajería instantánea es que es relativamente fácil acabar _chateando_ en lugar de hablando de la temática del grupo y suele producirse de una manera tan progresiva que, cuando el desmadre es notorio, nadie suele estar libre de pecado para poder poner orden.

**Comment by RickieES** [comment]
Mirando de nuevo, Ost.io tampoco me desagradaría mucho si no conseguimos organizarnos con lo que tenemos. Y tampoco descartaría el grupo de Google, que propone @Almorca, que seguramente es lo más cercano a lo que queremos (porque, a todo esto, la idea no es que cualquiera pueda aparecer por el canal de comunicación que sea a proponer o criticar lo que quiera, ¿no? Al fin y al cabo, eso ya lo pueden hacer con los _issues_ de Github y la propia estructura de los _issues_ es un filtro psicológico para que lo que se proponga tenga cierta argumentación). Con el grupo de Google imagino que podemos limitar la suscripción; no sé si con Ost.io también se puede limitar.

**Comment by edgardorios** [comment]
¡Saludos a todos!

Me parece un tema súper interesante. ¿Han platicado sobre usar un canal de IRC que estuviera unido a un grupo de Telegram? Yo pudiera ayudar a gestionar que en Mozilla (MozNet) tuviéramos un canal de IRC que estuviera unido a un grupo de Telegram mediante un "bot".

Espero les agrade la idea, me parece que sería algo muy positivo para todos.

Saludos.
Edgardo

**Comment by RickieES** [comment]
Perdón por el retraso en comentar sobre esto. Edgardo, ¿qué aporta enlazar un canal de IRC a un grupo de Telegram, si ambos son mensajería instantánea y el segundo mantiene el histórico sin que nadie tenga que permanecer en él conectado, como creo recordar que es necesario con IRC? Lo único que se me ocurre es que así puede participar quien no quiera usar Telegram.

**Comment by cosmoscalibur** [comment]
Tal vez con el aumento de popularidad entre la comunidad de desarrolladores, una buena alternativa podría ser reddit. El contenido queda público y debido a la diversidad de dicha red, es más fácil que alguien tenga una cuenta en reddit que en github. Pero si solo interesa incluir a quienes participan en github, basta con habilitar las notificaciones por correo de github, y eso sería equivalente a tener una lista de correo pública (usando simplemente los _issues_).

**Comment by eksperimental** [comment]
La unica opcion que veo viables sería una lista de correo. Tener discusiones en los issues seria abusar de ellos, ya que no es la finalidad de los mismos, y puede que terminen aburriendo a la gente que este interesada en contribuir codigo, pero no en discutir si una palabra deberia agregarse o no al diccionario.
Personalmente crear una cuenta en telegram, o reddit, o entrar a un grupo de charla en linea como IRC, no le veo mucho sentido, ya que de poco serviría debatir sobre algo en donde no hay certeza de que todos estén leyendo en ese momento.

**Comment by RickieES** [comment]
Cambio ligeramente de tema, pero dentro de lo que es la comunicación, o la información más bien. Como quizá hayáis visto, he estado categorizando la mayoría de los _issues_ y _pull requests_ por número de versión en relación a la fecha en que se cerraron, y me he encontrado algunas dudas:

- Algunos de los _issues_ no son tales, sino discusiones, preguntas, etc. que no provocan ningún cambio en el repositorio de ningún tipo. Si no los categorizo, me preocupa que, en una revisión posterior, vuelva a dudar de si me olvidé de categorizarlo o es que no incluía ningún cambio. Podríamos acordar que no se categoriza ningún _issue_ que tenga la etiqueta __pregunta__, pero no siempre serán preguntas. Por otro lado, podría haber preguntas que finalmente desemboquen en un cambio en el repositorio y, entonces, sí que deben quedar categorizadas en la versión en que se hacen públicos.
- Algunos _issues_ y _pull requests_ provocan cambios en el repositorio, pero no desembocan en cambios prácticos en el diccionario, bien porque se producen en las herramientas o el README.md, o porque (menos frecuentemente) hacen algún cambio en los ficheros, como reordenarlos, particionarlos en varios o recodificarlos. Yo soy partidario de, a pesar de todo, incluirlos como cambios que hay que documentar referidos a una versión, porque, aunque no afecten a nuestros _binarios_, sí que cambian nuestro _código fuente_.
- Algunos _pull requests_  acaban siendo descartados, bien porque no sirven en el fondo, o porque tienen algún error de forma que el autor original considera más cómodo corregir en un nuevo PR que modificando el que hay. ¿Deberíamos dejarlos marcados a pesar de todo, o usar la etiqueta __no se corregirá__?
- Y, en relación con todo lo anterior, alguno de vosotros nos presentó una utilidad que genera un registro de cambios automáticamente a partir de la colección de _issues_ y _pull requests_. Lo ideal es que las respuestas a mis dudas anteriores sean compatibles con esa herramienta.

**Comment by edittler** [comment]
Buenas, respondo por los mismos puntos que mencionas @RickieES 

* Se podría renombrar la etiqueta "pregunta" a "preguntas / discusiones". Cuando el resultado de la discusión sea una mejora en el repositorio, se cambia la etiqueta por "mejora" y se las coloca en el milestone que se incluyó la solución.
* Concuerdo que en los releases del proyecto se debe incluir una descripción de todos los cambios realizados en el proyecto, tanto la inclusión de nuevas palabras como los cambios en herramientas. Pero cuando se publican los diccionarios en los repositorios de LibreOffice, Mozilla, etc. al usuario final le interesa sólo los cambios referidos al diccionario, no al proyecto. En ese caso quien sube el diccionario aplica un "filtro" al changelog.
* Considero que los PRs descartados no deberían tener ninguna etiqueta ni estar en ningún milestone. Dicho sea de paso, no le encuentro mucha utilidad a la etiqueta "no se corregirá". Por qué no se corrige? Si el issue no reporta un error, se cierra sin etiqueta y listo. Si es por una cuestión de prioridad, se puede mantener abierto el issue con etiquetas que indiquen la prioridad (por ejemplo, "prioridad baja/media/alta")
* Yo fui quien presentó la herramienta para automatizar la generación del changelog. La verdad es que he dejado de utilizarla. En otros proyectos al changelog lo armo a mano mirando los issues y PRs que se encuentran en el milestone. Para eso previamente se tiene que verificar que el milestone contenga todos los issues y PRs que se incluyeron. Lo bueno de haber usado la herramienta es conocer una forma estándar de redactar los changelogs y estaría bueno que se mantenga. Acerca de convención de changelogs, [keepachangelog.com](http://keepachangelog.com/es-ES/1.0.0/) es un buen sitio de referencia.

Saludos!

**Comment by olea** [comment]
Sólo un aporte: desde hace unos meses estoy usando http://riot.im/ que incluye entre otras pasarelas a IRC. Ahora puedo mantenerme conectado a un canal sin perder info.

Me tiene bastante satisfecho.

FYI.

**Comment by RickieES** [comment]
@olea , lo estoy mirando, pero no sé si aporta gran cosa para los que no damos mucha importancia a la comunicación instantánea para este proyecto. La integración con Github parece limitarse a poder crear _issues_ desde Riot y hacer referencia a los abiertos, no creo que podamos volcar las conversaciones en _issues_. No obstante, si hay mucha gente interesada en tener conversaciones en tiempo real, puede ser una buena alternativa.

**Comment by olea** [comment]
@RickieES lo bueno de usar Matrix/Riot es que las conversaciones no tienen que ser exclusivamente en tiempo real porque las conexiones son permanentes. Pero vamos, que es sólo por contároslo :)

**Comment by Almorca** [comment]
Como este tema no lo vamos a avanzar cierro la incidencia para ir dejando más limpio todo.

**Comment by olea** [comment]
Entre unas cosas y otras también me despisté en decir por aquí que hemos improvisado un grupo privado en Telegram O:-)

Si alguien necesita apuntarse que me [escriba directamente](https://t.me/ismaelolea).

FYI
