### ISSUE TITLE
Valorar nuevos afijos

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#60]
En los _issues_ de las dos últimas versiones se ha ido hablando de la posibilidad de añadir posibles nuevos afijos. Abro este _issue_ para que no nos olvidemos de ellos, con la idea de abordarlos tras la 2.1. Los afijos son:
- [x] mini-
- [ ] maxi-
- [x] micro-
- [x] macro-
- [x] ex-
- [x] -ísimo
- [x] -mente

Podría ser que los cuatro primeros se agruparan en un mismo afijo, al estar tan relacionados entre sí.

**Comment by Almorca** [comment]
Una vez añadidos estos afijos abría que añadir las palabras densamente y presumiblemente.

**Comment by RickieES** [comment]
Aclaro también que me han pasado una lista de adverbios acabados en -mente, que seguramente incluirá muchas de las palabras que estamos considerando.

**Comment by RickieES** [comment]
El prefifo ex- ya está añadido con la bandera w en el issue #10

**Comment by RickieES** [comment]
Hola, @cosmocalibur. Planes no muchos, como has deducido. :smile: 

Estoy viendo que los cuatro primeros podrían integrarse en una única bandera. Puede dar lugar a lemas de raro uso (p.e.: falda →minifalda OK, microfalda Poco habitual, maxifalda OK, macrofalda Raro), aunque no creo que se puedan decir que son incorrectos. Si no nos sentimos cómodos con ello, podríamos crear dos banderas, una para mini y maxi y otra para micro y macro.

Recuerdo haber apreciado algún problema con -mente, pero ahora no lo recuerdo. Lo que sí veo claro es que sería más bien -amente (p.e.: definitivo → definitivamente), ya que el adverbio normalmente significa "de forma +adjetivo" (de forma definitiva) y siempre pasaría el lema a femenino.

En todo caso, tendríamos que dejarlo para después de la 2.5.

**Comment by RickieES** [comment]
Cambio también el _milestone_ a Después.

**Comment by cosmoscalibur** [comment]
`micro-` existía desde antes de este reporte https://github.com/sbosio/rla-es/commit/9d7b51829c7862ed2aff282b06f41a33779607a1 (lo dejo marcado).

**Comment by cosmoscalibur** [comment]
Se agrega 'macro-' en [bc7e84f](https://github.com/sbosio/rla-es/commit/bc7e84f5585b09192eed888d9747109891cf25e9)

**Comment by cosmoscalibur** [comment]
Se agrega `-mente` en [f32a786](https://github.com/sbosio/rla-es/commit/f32a78604b93e4809d5f3dd75a2bbf53949d3538)

**Comment by cosmoscalibur** [comment]
Se agrega el prefijo `mini-` en 35f35a8.

**Comment by cosmoscalibur** [comment]
@RickieES , para el caso de `-ísimo`, veo que este tal vez se sale del alcance de *hunspell*, porque necesitamos un *simulfix* y no solo un sufijo, ya que al tener acento el sufijo es necesario remover el acento que tenga el lema base.
En el caso de `maxi-`, no veo casos aplicables en el DLE ni en el DAMER para formación de neologismos, sino solo casos que lo tienen como parte de la base, entonces de momento no veo ganancia en crear la regla del prefijo.
La aproximación de las banderas separadas es porque no veo tan común que las formas generadas hagan mucho sentido en el uso práctico, entonces mejor que se genere cada caso a necesidad.

Me cuentas si con esto te parece adecuado cerrar el reporte, o si tienes algún caso de `maxi-` y lo agrego, y con ese cerrar (`-ísimo lo veo impráctico para montar y es mejor agregar los lemas directo)

**Comment by RickieES** [comment]
Sobre -isimo, he pedido la lista de palabras en DLE que terminan en ese sufijo, unos 40, y he buscado los términos de los que derivan. Solo he encontrado dos lemas raíz que tengan tilde: frígido,a y mérito (que está en desuso). En general, se produce un cambio importante en la raíz al aplicar ese sufijo (de amigo, amicísimo; de fiel, fidelísimo; de sagrado, sacratísimo). Realmente, son tan pocos lemas, y muchos de ellos ni siquiera son de uso habitual, que quizá no merezca la pena de crear la bandera. No obstante, lo que digo a continuación para maxi- también se aplica a este prefijo.

Sobre maxi-, pues es que si lo buscas en DLE, la entrada "maxi-" dice "Significa 'muy grande' o 'muy largo'. Maxifalda". Lo que quiere decir que es normal que no encontremos lemas con el prefijo aplicado, sin que la ausencia en DLE implique que no es un lema aceptado por la RAE. Repasando la lista de lemas acabados en -isimo presentes en el DLE no encuentro, por ejemplo, "potentísimo" y no creo que dudemos que es un lema válido. Tengo la sensación de que solo se incluyen explícitamente los lemas formados con prefijos o sufijos cuando, precisamente, producen una variación importante en la raíz del lema del que derivan.

¿Opciones? Podríamos optar por crear unas banderas simples y aplicarlas solo en los casos en los que funcionarían bien. En el caso de maxi- sería muy sencilla; creo que sería anteponer maxi- para todo lo que no comience por i, como maxialto, maxigranja;  y max- para lo que comience por i, como maxinfiel o maxirritante (no digo que los ejemplos sean lemas válidos, pero sirven para ver cómo funcionaría la bandera). Siempre hay que recordar que las banderas no crean palabras erróneas si no las asignamos a los lemas. :wink:

La otra opción, por supuesto, es lo que comentas: olvidarnos de maxi- e -ísimo hasta que veamos que existe una necesidad importante.

**Comment by cosmoscalibur** [comment]
@RickieES , listo, de acuerdo con el caso de `-ísimo`, y queda en la observación del archivo de afijos que no contiene los casos de acentros gráficos no agudos. [9910395](https://github.com/sbosio/rla-es/commit/991039521c4a515e0eb51e4d8c2508bb86203859). Ya asigné lemas documentados en los ejemplos del sufijo que vienen en DLE y DPD, y de #266  (los que se podían con la restricción).

Para el caso de `maxi-`, es que hasta el momento no veo un lema que se beneficie. Es decir, los casos que pones de ejemplo, claro que serían lemas que cumplen con la regla de formación, pero no veo lemas que sean de uso que se beneficien. Entonces es como para no llenar de "basura" el archivo de afijos.

Por mi parte, olvidaría `maxi-` hasta que tengamos casos de uso.

**Comment by cosmoscalibur** [comment]
@RickieES , listo, de acuerdo con el caso de `-ísimo`, y queda en la observación del archivo de afijos que no contiene los casos de acentros gráficos no agudos. [9910395](https://github.com/sbosio/rla-es/commit/991039521c4a515e0eb51e4d8c2508bb86203859). Ya asigné lemas documentados en los ejemplos del sufijo que vienen en DLE y DPD, y de #266  (los que se podían con la restricción).

Para el caso de `maxi-`, queda agregado y con el ejemplo de maxifalda del dle [fcf7e96](https://github.com/sbosio/rla-es/commit/fcf7e96a8513c87c612c1575c1f2f1ecdf7e9c2b)
