### ISSUE TITLE
herramientas y criterios para valorar propuestas

### ISSUE THREAD

**Issue by CaballerodelaTristeFigura** [sbosio/rla-es#61]
Estimados:
Este es el segundo tópico que planteo. También es mi segundo día aquí y, movido por el entusiasmo, he leído varios de sus aportes. También aprendí a tener paciencia, y que los aprendizajes llevan tiempo.
Pero voy a darle alas a mi inquietud y proponerles otro asunto; en todo caso, delego en ustedes decidir si me excedo en los propósitos de este espacio.
Acerca de mí mismo, hace unos nueve años soy colaborador asiduo de un diccionario en línea alemán-castellano, [LEO](http://dict.leo.org/forum/index.php?lang=es&lp=esde). Allí he acumulado ciertos trucos y experiencias, que quisiera compartir con ustedes. Creo que el intercambio será provechoso para todos.
En la primera discusión que abrí, la respuesta de Almorca me suscitó varias inquietudes. Esto provocó que mi réplica fuera, a mi juicio, extensa, y su contenido disperso. Por eso, decidí desdoblarla e iniciar nuevos temas a partir de sus distintos párrafos. Este es uno de ellos.
En distintos lugares de esta plataforma pude reconocer los siguientes criterios de selección, que paso a comentar:

**1) ceñirse a los términos admitidos por la RAE**
Muevo hacia aquí lo que había respondido a Almorca:

> Respecto de la reticencia a absorber términos no incluidos en el DLE, por una parte la entiendo, puesto que un diccionario es una empresa seria y debe ser llevada adelante con escrúpulos; por la otra, sin embargo, y con la mano en el corazón, todo hablante culto del castellano echa de menos una multitud de términos en el diccionario académico. La norma le va muy en zaga al uso. Y aquél que, además, ha tenido la suerte de aprender lenguas extranjeras, ve cuán aventajadas están respecto de la nuestra en trabajos lexicográficos que recogen el amplio espectro del habla. Entonces, alguien empeñado en generar una herramienta agil y útil a los tiempos que corren, debe ingeniárselas para sortear los tiempos y las burocracias de la Academia, sin por ello sacrificar rigor.

**2) comprobar la difusión de un término mediante una búsqueda en Google**
Actualmente soy usuario de Startpage, hace tiempo que no utilizo Google, pero cuando lo hacía, muchas veces arrojaba resultados engañosos, tal que al querer consultar la décima página de resultados, no llegaba más allá de la tercera, y el número de _hits_ descendía brutalmente. Ignoro si hoy por hoy esta falla habrá sido corregida. Por otra parte, indudablemente un número abultado de resultados atestigua la difusión de una palabra, aunque no necesariamente su corrección. Eso no sería un problema para expresiones bien conocidas, pero sí para casos dudosos. Tengo, entonces, mis reservas al momento de aceptar el dictamen de don Google como criterio decisorio de inclusión. En ese sentido, el formato libro pareciera ser, en general, más fiable que las páginas web, ya que para que un libro salga a la luz hay todo un proceso que de por sí da ciertas garantías de recibir un producto depurado. Google Books se presenta pues como una alternativa piola a la hora de encarar la expansión de un diccionario.

**3) utilizar Wikipedia**
Un aporte fenomenal, ya que hay mucha gente muy capaz trabajando allí y el material reunido es monumental. He visto, también, el rigor que mantienen al tratar semejante masa de información.

De mi parte puedo aportar un par de _tipps_: 
- En primer lugar, los _corpora_ bibliográficos y documentales que utiliza la RAE para confeccionar sus diccionarios. Yo diría, la fuente más confiable para evaluar lemas aún no presentes en el DLE con miras a su inclusión. Equivaldría a echar una ojeada en el taller mismo del diccionario de referencia. Particularmente útiles son el [Corpes XXI](http://web.frl.es/CORPES/view/inicioExterno.view) y el [CDH](http://web.frl.es/CNDHE/view/inicioExterno.view).
- Otra fuente fresca de vocabulario, si bien más informal, son los distintos glosarios existentes de carácter regional, o para determinadas ramas del quehacer humano. Del foro en el que habitualmente participo, les comparto [este compendio](http://dict.leo.org/forum/viewGeneraldiscussion.php?idThread=433847&idForum=22&lp=esde&lang=es). Allí tropezarán con comentarios en alemán, si no lo manejan, simplemente ignórenlos y concéntrense en los links, o presten atención solamente a las intervenciones en castellano.

En fin, estoy ansioso por saber qué opinan ustedes sobre estos temas. Les dejo un gran saludo.

**Comment by ezeperez26** [comment]
A mi también me parece un poco engañoso una mera búsqueda en google, más aún sabiendo que google aplica [filtros personalizados](http://www.ted.com/talks/eli_pariser_beware_online_filter_bubbles/transcript?language=es) a nuestras búsquedas.

Usar el Corpes XII y CDH me parece una buena idea. Habría que saber cuándo usar cada uno, ya que el CDH tiene textos de hasta el año 2000 y el Corpes XXI contiene textos de 2001 en adelante. Lo que me gustó de ambos es que se puede consultar las estadísticas por país, que nos ayuda a clasificar mejor cuándo una palabra debe agregarse a una localización en particular y no en forma general. Habría que recolectar varias palabras no RAE y ver que métrica usar para definir si una palabra se agrega o no.

**Comment by RickieES** [comment]
> 1) ceñirse a los términos admitidos por la RAE
> (...) otra, sin embargo, y con la mano en el corazón, todo hablante culto del castellano echa de
> menos una multitud de términos en el diccionario académico.

Para esto tenemos el directorio noRAE. Una buena referencia alternativa (aunque no necesariamente la única) para lo que sintamos correcto pero no esté en el DLE de la RAE puede ser Fundeu (http://www.fundeu.es/). En general, sus propuestas a mí me parecen bastante razonables. El CDH y el Corpes XXI también, por supuesto; solo tenemos que aprender a usarlos, y definir criterios, como dice Almorca.

> 2) comprobar la difusión de un término mediante una búsqueda en Google
> (...) Google Books se presenta pues como una alternativa piola a la hora de encarar la expansión
> de un diccionario.

Pues me parece buena idea la de Google Books.

> 3) utilizar Wikipedia
> Un aporte fenomenal, ya que hay mucha gente muy capaz trabajando allí y el material reunido
> es monumental.

Ahí está el _issue_ que está acometiendo Almorca. Aunque no he estado muy encima de esa lista de palabras, las veces que lo he mirado me ha parecido que, junto a muchas palabras que se podían añadir, también hay una lista notable de términos que son errores tipográficos o incorrectos. Quizá, una vez se termine de añadir esa lista, podemos pensar en pedir a quien nos la pasó que la genere periódicamente (¿anualmente?) para ver nuevas incorporaciones.

**Comment by Almorca** [comment]
Para las palabras RAE la norma sería:
Añadir bajo RAE todas las palabras que estén en el DLE o en el Diccionario panhispánico de dudas salvo que estén marcadas como en desuso en cuyo caso se estudiará cada caso concreto.

Para las palabras no admitidas por la RAE es dónde debemos fijar un criterio claro ahora que somos más. Yo usaría el Corpes y la Fundeu (aunque sobre esta tengo dudas de si las palabras que aparecen en ella deberían ir en RAE).

En cuanto a Google Books me parece bien como último recurso. La Wikipedia no la usaría ya que lingüísticamente ya que suele haber muchos anglicismos.

Si os parece bien podemos redactar una página en la wiki para dejar allí una norma clara e ir modificándola según vayamos afinándola.

**Comment by CaballerodelaTristeFigura** [comment]
Pues, ¡estoy de acuerdo con todas y cada una de sus apreciaciones! No lo tenía al diccionario de Fundeu, gracias por ese dato; y también por la entrevista a Mark Zuckerberg, muy interesante. Dicho sea de paso, el buscador que yo utilizo, [Startpage](https://startpage.com/esp/protect-privacy.html?hmb=1), utiliza Google, con la diferencia que oculta la IP y no realiza seguimiento alguno; en este sentido, permitiría obtener resultados más "objetivos".
Escribiendo en el otro asunto, me salió un término norteño (de AR), y aproveché la movida para vincularles una definición en el [Diccionario de Americanismos](http://www.asale.org/recursos/diccionarios/damer) de la ASALE. El DLE consigna como americanismos aquellos vocablos que mínimamente son aceptados por las academias de tres países; aquellos que no cumplen este requisito, y sin embargo son reconocidos por las respectivas academias vernáculas, los recoge el DAMER. Entonces, a la par del DLE, considero que aquél debería ser incorporado al canon de obras de referencia.
Con respecto a los _corpora_ bibliográficos de la RAE, ciertamente pueden realizarse búsquedas estadísticas de suma utilidad y gran refinamiento. El CDH es resultado de la fusión de sus predecesores [CORDE](http://corpus.rae.es/cordenet.html) y [CREA](http://corpus.rae.es/creanet.html), el primero abarcando desde los inicios hasta 1974, el segundo desde 1975 a 2004. El CDH dispone para sus búsquedas de casillas de verificación, con las cuales puede restringirse a alguno de dichos períodos (si bien abarca hasta el año 2000, para evitar superposiciones con el Corpes XXI).
El CORDE puede ser útil cuando uno trata con textos antiguos, por caso, escaneados con OCR con miras a su edición digital. Una cuestión a definir sería pues la inclusión de arcaísmos en el diccionario, o acaso la edición, a futuro, de un glosario de arcaísmos aparte para estos casos especiales.
En cuanto al CREA, ya su nombre mismo ya nos indica que se trata de español actual, y por tanto, su masa documental debería ser tenida en cuenta junto a la del Corpes XXI.

**Comment by sbosio** [comment]
@Almorca, @CaballerodelaTristeFigura, @edittler, @RickieES:

Yo creo que este registro podría cerrarse, ya que hay un buen nivel de consenso alcanzado en las herramientas (corpus) a consultar en el caso de las palabras en las que existan dudas sobre su inclusión, y ya se añadió la documentación sobre los criterios a la página principal de la Wiki.

Si nadie tiene objeciones al respecto, yo daría por terminada la discusión y cerraría este registro. Quizás algo que podríamos modificar es añadir un enlace en la sección que explica los criterios en la Wiki a este registro, ya que la discusión aquí es más detallada y me parece muy enriquecedora.

Si no hay opiniones en contrario, cerremos el registro en un par de días.

**Comment by EdgardoRios** [comment]
Saludos a todos:

Con el fin de enriquecer el diccionario corrector para español de México. Me gustaría usar como referencia la [Academia Mexicana de la Lengua](http://www.academia.org.mx/) e ir agregando palabras del [diccionario de mexicanismos](http://www.academia.org.mx/DiccionarioDeMexicanismos). Espero esto sea aceptable.

**Comment by olea** [comment]
> Con el fin de enriquecer el diccionario corrector para español de México. Me gustaría usar como referencia la [Academia Mexicana de la Lengua](http://www.academia.org.mx/) e ir agregando palabras del [diccionario de mexicanismos](http://www.academia.org.mx/DiccionarioDeMexicanismos). Espero esto sea aceptable.

No se me ocurre ningún motivo por el que no sea aceptable al menos en es_MX aunque el enlace al diccionario no funciona y no sé cuál sería el equivalente actual.

**Comment by olea** [comment]
Aparte, por concluir el hilo: ¿están suficientemente contemplados los criterios de admisión con lo descrito en el wiki? https://github.com/sbosio/rla-es/wiki/Clasificaci%C3%B3n-de-lemas

Si sí, cierro este boletín.
Si no, ¿sería alguien tan amable de presentar un borrador con las mejoras de aquel texto?

**Comment by cosmoscalibur** [comment]
Actualmente tenemos en la Wiki la información asociada a la clasificación de lemas, que da cuenta de las fuentes recomendadas y criterios actuales. El reporte más de 4 años sin actividad.
