### ISSUE TITLE
¿Cómo puedo armar un parche?

### ISSUE THREAD

**Issue by CaballerodelaTristeFigura** [sbosio/rla-es#62]
Esta es la última "migración de párrafos" que hago desde mi primer tópico:

> Soy un recién llegado en Linux y todo este universo en general es muy nuevo para mí, aunque, desde luego, mi intención es aprender y poder colaborar cada vez un poquito más con este proyecto tan necesario. A propósito de esto, una pregunta: He leído en la wiki lo concerniente a colaboración, estructura, afijos; también, he abierto varios de los archivos _txt_ en los directorios del diccionario. Lo que no me queda claro es cómo confeccionar un parche: ¿Debo editar el archivo _txt_ correspondiente? ¿Debo subir dicho archivo modificado a esta plataforma? ¿O es que acaso hay algún formulario en línea específico para esto? Les agradeceré que me expliquen cómo hacerlo :-]

**Comment by RickieES** [comment]
Te contesto aquí con algo que espero que te sirva para el resto de _issues_ abiertos. Somos comparativamente pocos y con poco tiempo para poder hacer todo lo que sería necesario, por lo que te ruego que tengas paciencia. Los _issues_ no se dejan en el olvido; simplemente, tardamos mucho en poder ir resolviéndolos. :smile: 

Sobre los parches, te hago solo una explicación general y, a medida que tengamos tiempo, la completamos y la llevamos al wiki de documentación. Hay una manera estándar de toda la vida y otra que solo funciona porque estamos alojados en Github. En ambos casos, debes obtener una copia del repositorio (pulsando en la pestaña Code tendrás acceso en la parte derecha a enlaces para descargarlo o crear un _fork_).

Con el método estándar te descargas una copia en tu equipo y haces los cambios allí, para luego ejecutar una instrucción que genera un listado de diferencias en un formato determinado, legible para un ser humano, pero también tratable por la máquina). Ese listado, guardado en un archivo, se adjuntaría como parche. Alguno de los que tenemos acceso al repositorio evaluamos el parche, intentamos aplicarlo y, si no hay conflictos, queda integrado el cambio.

Con el otro método específico de Github haces una copia (_fork_) de este repositorio. De esa copia tú eres propietario y puedes modificarla, bien descargándola como con el método anterior, bien usando las herramientas que ofrece la web. Una vez hechos los cambios y confirmados (_commit_), y dado que el sistema sabe que tu copia lo es de este repositorio y no de otro, Github permite hacer un _pull request_ (abreviado como PR) que es una petición en el repositorio principal de admitir los cambios que has hecho tú en tu copia. Si lo aceptamos alguno de los que tenemos permiso, se integra el cambio y listo.

**Comment by ezeperez26** [comment]
Mi forma de trabajo es revisar _issues_ viejos, de manera de asignarme alguno y trabajar en él.
Sobre todo porque aún hay _issues_ de la antigua plataforma que ya tienen más de 2 años.
De todas maneras, dado que hiciste el aporte de unas cuantas palabras, podrías empezar por ese _issue_, te motivaría más.

Trabajar con _fork_ y _pull request_ a mi me ha resultado muy cómodo. Además, permite una mejor revisión del parche aplicado y se puede realizar comentarios en el mismo.

**Comment by CaballerodelaTristeFigura** [comment]
Bien, muchachos, les agradezco sus respuestas. De a poco se me redondea más el concepto. Soy nuevo en Linux y aquí, aún no estoy familiarizado con este entorno; de hecho, algunos conceptos como "repositorio" todavía me resultan oscuros. Si entendí bien, se trata del archivo ZIP que uno descarga de la pestaña Code. En tal caso, ya lo tengo. Según el viejo método, entonces, simplemente debería modificar los archivos TXT incorporando los nuevos términos, o dotando los existentes de banderines faltantes. Pero ahí se me hace una laguna: para comparar las modificaciones, debo tener dos archivos a comparar, ergo, tengo que copiar el archivo original con otro nombre y luego editarlo; finalmente, comparar las diferencias entre uno y otro para generar el parche, que luego habrá de ser enviado a ustedes. ¿Estoy razonando bien?
@ezeperez26 me encantaría ayudar con tópicos abiertos previos, aunque mucho me temo que de momento me falta el tiempo para ello. Llegué aquí atraído por la curiosidad de conocer a los duendecillos bienhechores que se esconden tras el diccionario de OpenOffice, expresarles mi gratitud y ofrecerles mi humilde aporte, fruto de mi tiempo sentado frente al Writer. Una vez que me ponga ducho en estas materias y mis tiempos me lo permitan, tal vez me aventure a ir más allá y los asista con más frecuencia.
¡Buen fin de semana!

P.D.: Dicho sea paso, escribiendo estas líneas, noto que _faltantes_ y _duendecillos_ no están en el diccionario.

**Comment by RickieES** [comment]
> Bien, muchachos, les agradezco sus respuestas. De a poco se me
> redondea más el concepto. Como les decía, soy nuevo en Linux y aquí,
> aún no estoy familiarizado con este entorno; de hecho, algunos
> conceptos como "repositorio" todavía me resultan oscuros. Si entendí
> bien, se trata del archivo ZIP que uno descarga de la pestaña Code.

No exactamente; el archivo ZIP tiene una instantánea del estado del repositorio.

Un repositorio es un conjunto de ficheros versionados. Es como un pequeño sistema de ficheros, con sus directorios y archivos, cuyo acceso está controlado por un servidor que se encarga de registrar cada cambio que se produce en los ficheros (para lo que suele usar una base de datos interna).

En el caso de Github usamos como repositorio GIT, que es un sistema de control de versiones distribuido. Esto quiere decir que cada usuario que se descarga una copia del repositorio tiene, en su copia local (en su equipo), todo lo necesario para restaurar el repositorio completo en caso de que desapareciera la copia principal.

Una vez tienes un repositorio en tu equipo, puede haber hasta tres versiones de un mismo archivo (sin complicar mucho las cosas):

- la del repositorio principal, tal como figura en su base de datos
- la de tu repositorio local, tal como figura en la base de datos
- la del directorio de tu disco duro, que puedes haber modificado respecto a la versión guardada en la base de datos del punto anterior; al directorio del disco duro se le llama _directorio de trabajo_.

Pasar del último al segundo punto se llama _confirmar los cambios_ o, usando jerga, _hacer commit_. Pasar del segundo al primero se llama _subir los cambios al repositorio principal_ o, usando jerga, _hacer push_.

El archivo de diferencias que comentamos se hace, tras asegurarse de que las versiones de los puntos 1 y 2 están sincronizadas, comparando las versiones de 2 y 3 (tu copia local en la base de datos vs. la copia en el directorio de trabajo). Se usa una instrucción específica de cada tipo de repositorio; en el caso de git, `git diff`. La salida de esa instrucción se puede desviar a un fichero con una redirección (`git diff >parche.txt`) y subir ese fichero al _issue_. Si se aprueba, se incorpora al repositorio principal y lo puedes descargar como conjunto de cambios a tu repositorio local y, de ahí, al directorio de trabajo.

Con el mecanismo que usa ezeperez26 se puede hacer más o menos los mismo a través de la web, pero personalmente creo que hace falta conocer muy bien lo que conceptualmente representa, y la mejor manera de entenderlo es trastear primero con ello en tu propio equipo para _palparlo de verdad_.

Como ves, sin ser difícil, puede ser engorroso o complicado para gente que no esté acostumbrada a estas herramientas (hay que estar instalando el software del sistema de control de versiones en tu equipo, configurando herramientas auxiliares para tratar las diferencias, las credenciales de acceso, etc.). Normalmente quien pueda llegar a ese paso ya sabe cómo manejarse con los sistemas de control de versiones y no necesita tanto detalle. Por analogía, quien esté dispuesto a ayudar a construir la casa no necesita que le enseñemos a usar el martillo, a mezclar cemento, arena y agua o distinguir qué es un ladrillo, sino que entremos en detalles sobre qué ladrillos usamos, de qué grosor y altura hacemos las paredes o cómo distribuimos las habitaciones.

> P.D.: Dicho sea paso, escribiendo estas líneas, noto que faltantes y duendecillos
> no están en el diccionar

Como ya habrás deducido, nos hace mucha ilusión que los _issues_ aporten pocas palabras, porque los podemos cerrar rápidamente. :smile:

**Comment by CaballerodelaTristeFigura** [comment]
Excelente, @RickieES , con todo esto creo que ya tengo para empezar, o al menos hacer mis primeros tanteos, agradezco mucho tu explicación detallada. Y si bien ahora tengo otras urgencias, no bien se me haga una luz me lanzaré a la tarea. ¡Saludos!

**Comment by sbosio** [comment]
Cierro el registro, porque me parece que no hay mucho más para poder hacer. ¿Quizás pasar las instrucciones detalladas que escribió @RickieES a alguna página de la wiki? Aunque es casi un off-topic, ya que se trata de cómo trabajar con Git, pero podría resultar útil para más personas. Si alguien opina que sería útil, puede abrirse un nuevo registro .
