### ISSUE TITLE
¿extensión para colectar sugerencias?

### ISSUE THREAD

**Issue by CaballerodelaTristeFigura** [sbosio/rla-es#64]
En mi carácter de nuevo en el barrio, prosigo con mi tormenta de ideas. Sólo espero no empaparlos demasiado ;-] Hace varios años me volqué hacia OpenOffice, mucho tiempo antes de pasarme a Linux. Y por mi actividad, el Writer es una herramienta de uso cotidiano. Durante largos años lo utilicé sin reflexionar demasiado, pero recientemente y debido a ciertos avatares biográficos, tomé conciencia más aguda de que los utensilios de que me sirvo a diario están hechos del esfuerzo voluntario de personas iguales que yo. Largo tiempo, a fines de que el corrector no me molestara la vista con sus subrayados rojos, opté por incluir las palabras faltantes en "standard.dic" del menú contextual. Ahora, ganando algo de perspectiva, entiendo que se trata de un registro interno del programa, disociado del diccionario y solamente útil para mí durante el tiempo en que conserve a aquél instalado en mi computadora. Entonces, se me ocurrió ir un paso más allá y, en lugar de conservar mis inclusiones para mí solo, compartirlas con los desarrolladores del diccionario a los efectos de su mejora. Y aquí me ven. Pero ahora que estoy aquí, se me ocurre algo más: ¿Qué tal si los usuarios de OO, LibreOffice, Firefox, etc. dispusieran de una opción sencilla para enviar propuestas de mejora al diccionario? Por caso, que al hacer click derecho sobre una palabra, junto a la opción de "incluir en el standard.dic" (como en el caso de OO) sea posible "sugerir a rla-es/a editores del diccionario"; también, por supuesto, la posibilidad de hacerlo desde la ventana emergente durante la revisión ortográfica. De haber tenido a mano un comando así, hace varios años habrían recibido noticias mías, jeje. Y estimo que esa es la situación de muchos como yo en el mundo hispanohablante, beneficiarios de este proyecto, con los cuales se podría entablar un _feedback_, bajo el lema: "Yo te proveo de un diccionario, vos ayudame a mejorarlo." Por supuesto, esto los confrontaría con el desafío de una masa inconmensurable de información que procesar; también, quizá, con gente bromista o malintencionada que quiera abusar de una posibilidad así. Tal vez todo esto ya ha sido pensado y discutido _ad nauseam_, y descartado en algún otro rincón de la red, y yo simplemente no lo sé. Ustedes dirán

**Comment by RickieES** [comment]
La idea es buena, pero no sé si técnicamente la podríamos llevar a cabo. Un problema común a una hipotética extensión de LibreOffice/AOO y una de Mozilla es que las sugerencias tendrían que acabar materializándose en un _issue_ de Github y, para ello, haría falta que, o bien cada usuario tuviera cuenta en Github (con la inconveniencia que le supondría a muchos de ellos que no suelen participar en este sitio), o bien usáramos una cuenta específica para las extensiones. Esto último supondría un riesgo de seguridad importante (¿dónde guardamos la contraseña, si la extensión es de código abierto?) y la primera alternativa también suscitaría suspicacias (¿guardará la extensión la contraseña del usuario en algún sitio si se la doy?).

En el caso de Mozilla hay otro problema añadido, y es que están en proceso de simplificar la arquitectura de extensiones, para hacerlas más compatibles con otros estándares. Eso afectará, sin duda, a la potencia que actualmente tienen y podría no ser factible hacer lo que deseas.

Y luego hay otro detalle insignificante y menor: al menos yo no sé cómo escribir extensiones para ninguno de las dos arquitecturas. :smile: Sé Java (que creo que es lo que sigue usando LibreOffice/AOO) y conozco superficialmente XUL, HTML, CSS y JS, pero todas las API y los marcos de trabajo necesarios son completos desconocidos para mí.

**Comment by sbosio** [comment]
Igualmente hay una manera sencilla de exportar las listas de palabras de
los diccionarios personales con un par de herramientas que están por ahí en
el árbol del proyecto. Así que una buena forma de colaborar es adjuntar el
diccionario personal en un issue de Github, por ejemplo, o enviárselo a
alguno de los integrantes si no se tiene una cuenta de Github.

Obviamente no es algo tan sencillo como lo de la extensión que se planteó
inicialmente.

Saludos,

Santiago


Este correo electrónico se ha enviado desde un equipo libre de virus y
protegido por Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

El 13 de febrero de 2016, 18:25, Ricardo Palomares <notifications@github.com

**Comment by CaballerodelaTristeFigura** [comment]
Ajá, gracias por sus respuestas. El placer de estar charlando con el padre y el padrino del diccionario :-] Mis conocimientos de programación son cercanos a 0, de manera que me confío a vuestra mayor sapiencia. Con todo, me pregunto si no se le podrá encontrar la vuelta a la recolección de datos sin que contraseñas o dispositivos de seguridad se vean vulnerados. Por ejemplo, que al cierre de sesión las palabras sugeridas sean almacenadas en un archivo (una especie de _cookie_ lingüística), y éste enviado a los editores. ¿Podría hacerse esto sin riesgos o estoy diciendo un barbarazo?
@sbosio Claro, ese _standard.dic _es un archivo, y como tal localizable y compartible. No obstante, no fui consciente de ello todo el largo tiempo que lo utilicé. En ese sentido, merecería la pena alertar sobre esto en la Wiki. Entretanto, una medida de implementación sencilla, y que a mi juicio facilitaría el contacto, sería modificar el enlace al proyecto que se despliega en el administrador de extensiones de AOO, tal que remita directamente a la Wiki ( [](https://github.com/sbosio/rla-es/wiki) ) más amigable para el público lego que la pestaña Code a la que se arriba por defecto. El _quid_ de la cuestión es, en efecto, poner en contacto a _dummies_ de la informática, aunque eventuales hablantes avezados del castellano, con los hacedores del lexicón. 
¡Que tengan una buena semana!

P. D.: [Barbarazo](http://lema.rae.es/damer/?key=barbarazo), a la par que me delata como norteño, tampoco está incluida en el diccionario.

**Comment by olea** [comment]
Cuando tengamos una herramienta propuesta reabrimos el hilo.
