### ISSUE TITLE
Versión 2.1

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#67]
Abro este hilo para ver si podemos tener la versión 2.1 en Marzo para que entre en la próxima versión de Libreoffice que se publica en la semana del 4 de abril y que probablemente sea la que vaya por defecto en Ubuntu 16.04. Yo voy a intentar dar un empujón a los temas que tengo asignados entre este fin de semana para cerrar en semana santa todo lo que tenga en el aíre.

@olea @sbosio @ezeperez26 ¿Cómo lo veis?

**Comment by ezeperez26** [comment]
Para esa fecha podría finalizar el _issue_ #4 en el cual me encuentro trabajando.
De todas maneras, el último diccionario se publicó hace un poco más de 3 meses. Se podría considerar como la publicación más reciente y no veo el apuro para liberar una nueva versión.

**Comment by Almorca** [comment]
Aunque la última versión sea reciente ser han añadido bastantes palabras desde entonces y es interesante que eso se refleje en la nueva versión de Ubuntu, una versión que por ser LTS va a ser usada por mucha gente.

**Comment by RickieES** [comment]
Perdón por el silencio hasta ahora. Sí, yo abogo por publicar una versión antes de que acabe marzo (_release early, release often_). :smile: 

Por cierto, que el otro día generé un diccionario es_ES para probar algunos de los cambios con los que estoy, y descubrí que tenemos un problemilla con los topónimos. Por algún motivo, deshice el cambio en el script que agregaba los topónimos por nombre de fichero `toponimos-*.txt`, lo que hace que haya muchos en España que no se reconocen. También fallan aún algunas palabras que, teóricamente, están incluidas. A ver si este fin de semana puedo abrir _issues_ con cada uno de los problemas y los arreglo.

**Comment by RickieES** [comment]
¿Os parece muy precipitado si asignamos como fecha tope para tener lista la versión 2.1 el domingo 27 de marzo?

**Comment by Almorca** [comment]
A mí me parece bien

**Comment by ezeperez26** [comment]
La cuenta regresiva a comenzado.
Ya he finalizado el _issue_ #4 (¡por fin  :tada:, era muy largo!).

Estuve revisando todos los _issues_ y los que están marcados para el [_milestone_ 2.1](https://github.com/sbosio/rla-es/milestones/Versi%C3%B3n%202.1).
Considero que los issues que están marcados para la version 2.1 son suficientes y necesarios.
Y que los mismos se podrían resolver para el día 27 si cooperamos entre todos  :smile:.

**Comment by RickieES** [comment]
Fecha 27 de marzo fijada para publicar el diccionario.

**Comment by olea** [comment]
Sólo deciros que aunque yo no estoy colaborando en nada os voy leyendo y
estoy tan entusiasmado como agradecido por el magnifico ritmo de trabajo
que imprimís al grupo ¡<3!

**Comment by RickieES** [comment]
Cierreo este _issue_ abierto por @Almorca (por eso se lo asigno a él), ya que tenemos fecha decidida y acabo de abrir el que documenta el proceso de publicación en sí.
