### ISSUE TITLE
Arreglar desastre en tratamiento de topónimos

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#68]
Antes de nada: el desastre lo provoqué yo. :-1: 

Vamos por partes. El _issue_ #40 introdujo varios archivos de topónimos de Argentina y de España. En el caso de España, pasamos por varias fuentes de palabras: teníamos un archivo con cerca de 8.000 nombres, que resultaba inmanejable. Como consecuencia de los comentarios en ese _issue_, en lugar de ese gran archivo, preparamos tres para, respectivamente, las comunidades autónomas, las provincias y los municipios de más de 30.000 habitantes.

Por no perder el archivo original, mi propuesta fue llamar a los archivos de topónimos `toponimos-*.txt` y modificar el script de generación del diccionario para incluir solo los archivos con ese esquema de nombrado.

Justo antes del _issue_ #40 había abierto el _issue_ #39 para modificar el script para diversos arreglos en él. Lo cerré justo antes de terminar de arreglar el 40 y, por ello, decidí reabrirlo para sustituir la inclusión de un único archivo llamado `entidades-territoriales.txt` por el patrón `toponimos-*.txt`. No sé muy bien el motivo, pero hice el commit y, a continuación, lo deshice, de manera que los nuevos topónimos no se han incluido en la versión 2.0.

Lo que es más, al ver que no se reconocían los topónimos que esperaba y repasar la colección de palabras completa, he encontrado que se están incluyendo nombres completos de, por ejemplo, comunidades autónomas (_Castilla La Mancha_, todo en una línea). Que esté así no sirve para que se marque como correcta (actualmente, se marca como errónea _Castilla_ y correctas las otras dos porque las tenemos como palabras comunes RAE).

Además, los directorios de topónimos tienen archivos duplicados, cada uno con diferente nombre. Por ejemplo, en el directorio `toponimos` tenemos `entidades-territoriales.txt` y `toponimos-mundo.txt`, cuyo contenido es idéntico. En es_AR sucede igual.

Por último, en es_ES tenemos dos archivos comenzando por `entidades-territoriales`, uno de contenido y el otro de consideraciones, que creo que ya no vamos a usar y que pueden confundir a quien llegue a ayudar de nuevas.

Mi propuesta para arreglar todo esto es:

- Reaplicar el commit del script que toma los archivos de topónimos con el patrón `toponimos-*.txt`
- Borrar los archivos que comienzan por `entidades-territoriales`
- Generar un diccionario y arreglar cualquier posible problema sobre la base de los dos puntos anteriores

Lo quiero arreglar deprisa, así que si no me decís nada en unas horas, me pongo con ello.

**Comment by ezeperez26** [comment]
No se si sería correcto "reaplicar" el commit del script, ya que luego lo modifiqué yo. Supuestamente mis modificaciones no afectaron a la funcionalidad del script, pero nunca se sabe...

**Comment by RickieES** [comment]
Yo soy muy chapucero :smile: y no pensaba reaplicar el changeset como tal, sino volver a hacer manualmente los cambios, que tampoco son gran cosa.

**Comment by RickieES** [comment]
Bueno, pues solucionado.
