### ISSUE TITLE
Zarautz es nombre oficial de topónimo en España

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#69]
En `...toponimos/l10n/es_ES/toponimos-municipios.txt` figura "Zarauz", que es el nombre en castellano de la localidad, pero no "Zarautz", que es el nombre en euskera y es considerado el nombre oficial. Dado que hemos incluido otros topónimos en euskera, como Araba, he pensado que es mejor incluirlo.

**Comment by RickieES** [comment]
Añadido.

**Comment by ezeperez26** [comment]
@RickieES, desde que reportas el _issue_ hasta que lo resolvés, el tiempo es tan reducido que los demás no pueden verlo y/o comentar lo que consideren pertinente al respecto.

Sobre el _issue_ propiamente dicho, RAE especifica [cómo tratan los topónimos](http://www.rae.es/diccionario-panhispanico-de-dudas/que-contiene/tratamiento-de-los-toponimos).
Sobre el término "Zarautz", se pueden aplicar 3 de las reglas que aparecen en el sitio:

> 1. Topónimos con forma tradicional plenamente vigente en español, que, no obstante, aparecen con cierta frecuencia en los medios de comunicación con nombres o grafías propios de otras lenguas. Se prefiere la forma española, a no ser que haya caído en desuso o se haya producido un cambio de denominación: Amberes (no Antwerpen ni Anvers), Ciudad del Cabo (no Cape Town), Milán (no Milano) o Nueva York (no New York).

> 3. Topónimos cuya forma tradicional en español ha caído en desuso en favor de la forma local. Se da primacía a la forma local: Ankara (antes Angora), Bremen (antes Brema) o Maastricht (antes Mastrique).

> 4. Topónimos con cambio de denominación oficial en favor de la forma local, pero que cuentan con una forma tradicional española plenamente vigente. Se prefiere la forma española: Calcuta (no Kolkata), Moldavia (no Moldova), Bombay (no Mumbai) o Esmirna (no Izmir). Solo en aquellos casos en que se ha producido un verdadero cambio de nombre (y no una mera reivindicación de las formas locales de este) se recomienda la nueva denominación, que debe sustituir a la anterior: Burkina Faso (antiguo Alto Volta) o Sri Lanka (antiguo Ceilán).

En conclusión, dicho término es válido agregarlo si **la denominación española está en desuso, la denominación local es muy popular o se ha producido un verdadero cambio de nombre (y no una mera reivindicación de las formas locales de este) se recomienda la nueva denominación, que debe sustituir a la anterior**.

Como no soy de la península ibérica, no conozco en detalle la popularidad de la nueva denominación.

Pero para incluir denominaciones que no son españolas considero que se debería dejar constancia de que la actual denominación española se encuentra en desuso, demostrar con resultados de búsquedas la frecuencia de aparición de la nueva denominación o alguna forma similar.

En caso de que se acuerde agregar dicha palabra no española, se podría dejar un comentario
`# Denominación euskera de Zarauz` para dejar constancia de que la denominación no es la española.

**Comment by RickieES** [comment]
Perdón por la rapidez. Lo hice tan deprisa porque tenemos otros casos ya añadidos, como comentaba en el issue, y si no aceptamos Zarautz tendríamos que retirar las formas locales de Álava, Lleida, Ourense, Vizcaya y Guipúzcoa.

Es una situación un poco peliaguda. Por cuestiones que tienen que ver más con la política que con la corrección lingüística, los nombres oficiales de distintos topónimos han cambiado de la forma en castellano a la forma en gallego, catalán o euskera. Según tengo entendido, a los niños que estudian les llegan a quitar puntos por usar en un examen el nombre en castellano en lugar del nombre oficial, aunque estén estudiando en una comunidad autónoma en la que la única lengua oficial sea el castellano. Mejor no digo lo que pienso personalmente de esto, :smile: pero el caso es que creo que es conveniente aceptar ambas formas.

Sin embargo, como digo es lo que creo yo, y me parece bien que podamos discutirlo, así que reabro el issue.

**Comment by Almorca** [comment]
A mí me suena mejor Zarautz que Zarauz sin embargo veo que la Wikipedia opta por la última siguiendo su normativa que está en https://es.wikipedia.org/wiki/Wikipedia:Top%C3%B3nimos_de_Espa%C3%B1a

Yo soy partidario de añadir las 2 formas. En el fondo las 2 se usan y las 2 son correctas.

**Comment by ezeperez26** [comment]
@RickieES, luego de la aclaración que has hecho sobre la puntuación en los colegios, concuerdo con agregar ambas formas al diccionario. No sea cosa que le echen la culpa al corrector por sus calificaciones  :confused:.

De todas maneras, me parece interesante enterarnos de estas situaciones y tomar decisiones en base a eso  :wink:.

**Comment by RickieES** [comment]
OK, pues cierro este issue también. Va quedando poco. :smile:

**Comment by eksperimental** [comment]
creo que para casos así, es mas indicado enviar un PR, y dejarlo unos dias para que los otros lo revisen, ahi mismo se puede comentar en el codigo, y comentar en el PR mismo. se hace algo engorroso que para cada cambio que haya, se cree en Issue.

**Comment by ezeperez26** [comment]
Buena sugerencia la que comenta @eksperimental. Los _issues_ son gratis  :laughing:, pero ya que se tiene el parche preparado, sería más ordenado (y menos pasos) enviarlo como PR, en vez de crear el _issue_ y hacer el _commit_ inmediatamente.

**Comment by Almorca** [comment]
Si podéis poned todo esto explicado en el wiki para que quede centralizada la normativa. Si además explicáis o ponéis algún enlace a como se genera un PR ya queda de 10.

**Comment by RickieES** [comment]
En mi caso, hacer PR me resulta un poco incordio. El motivo es que yo, como @Almorca y @Sbosio, y a diferencia del resto de vosotros, no trabajo con un fork del repositorio, sino directamente en el principal. Ojo, si se hicieran PR no saldrían en la generación automatizada del changelog que proponías, @ezeperez26.

Esto es un poco cuestión de culturas de desarrollo. En Mozilla, que se trabaja con forks pero generalmente no en GitHub, todo cambio en el repositorio debe ir acompañado de un bug/issue que documente el cambio. Se adjunta un parche al bug, se analiza y, cuando se da el visto bueno, o se aplica directamente por el colaborador, o por el revisor. Yo estoy acostumbrado a ese procedimiento, al menos para los bugs de código, porque se agrupa la definición del problema o mejora, la discusión del mismo y el resultado y la aplicación del cambio. Si no me equivoco, con los PR descartados, aunque sea por errores de formato, todo eso se pierde porque se descarta el PR y se crea uno nuevo.

**Comment by ezeperez26** [comment]
La generación del registro de cambios tiene posibilidad de incluir PRs, pero lo he desactivado porque, o ya tenían un _issue_ relacionado, o resolvían cosas que no eran conflictos en el diccionario en sí (por ejemplo, las mejoras al script del generador del diccionario). La única pega es que los PRs se agrupan dentro de una sección "Pull Requests cerrados", es decir, no los clasifica en "mejoras" o "errores corregidos". Así que si es por este lado, creo que es más razonable lo que plantea @RickieES.

Como conclusión, considero que somos pocos aún como para hacer rígida la forma en que se colabora al proyecto, a diferencia de grandes proyectos como Mozilla o AOO/LibreOffice que han tenido que imponer un poco de "burocracia" para poner un poco de orden entre tantos voluntarios.
Colaboremos de la forma en que nos resulte más cómodo y seamos felices  :smile:

Por lo pronto, creo que lo importante es documentar bien este proyecto. Yo me sumé hace poco y he aprendido algunas cosas a cuentagotas gracias al alma mater @sbosio que ha aclarado muchas dudas sobre cómo se han resuelto algunas cosas y me he tomado el trabajo de documentarlas como lo hice cuando habían dudas con la [separación silábica](https://github.com/sbosio/rla-es/blob/master/separacion/README.md).

**Comment by eksperimental** [comment]
@RickieEs la forma que dices de trabajar como lohacen en Mozilla me parece que es puede hacer perfectamente. Toda la información acerca de los cambios deberia ir en la descrpicion del commit,  y ya si necesitas consultar los cambios o compartirlos, crear un PR, o si no es necesario hacer un push directamente de ese commit.

De hecho, para mi es mala practica que dichas explicaciones no queden documentadas en el log del repositorio, y queden  por fuera ... como son las issues (o podría ser un PR). El día de mañana github cierra, o se decide moverse a otor sistema git, o un proyecto sale como fork de este ,y toda esa informacion es probable que quede perdida.

Creo que las issues son buenas para reportar errores, hacer _feature requests_. Pero se me hace algo dificil seguir un proyecto en el que por cada cambio que se cree (que como fue en este caso sólo consistía de una sola palabra) se cree un issue.

Otra sugerencia que me animaría  a dar sería elegir titulos lo mas descriptivos y concisos posibles tanto para las issues, PR, y commits.
y en especial en los commits, donde el titulo debe ser corto y conciso, y en el cuerpo del comit puede uno explayarse listando las palabras que se agregaron.
(tiren un `git log` para ver de lo que estoy hablando)

Quiza lo de la lista de correo para discutir temas como el inicial de esta issue (acerca de si se utiliza el topónimo en su idioma original o  no) sería un lugar mas acertado.

El projecto tiene una paritcularidad que muchos de estos titulos seran del tipo "Agrego nuevo grupo de palabras" o "palabras no reconocidas por el diciconario".
Sería bueno quiza encontrar una forma de poder referirse individualmente a estos puntos.

**Comment by RickieES** [comment]
Refiriéndome al último punto, normalmente la diferencia entre los commits de este proyecto y los de uno de desarrollo es que el contenido del commit es autoexplicativo en nuestro caso. En un cambio de un programa, si hay más de unas pocas líneas, puede que sea más fácil leer el comentario del commit y, si es necesario, acudir al _issue_ para entender qué se quería cambiar.

En nuestro proyecto, para ver qué palabras se quieren añadir con el commit, lo mejor es ver el cambio en sí.

Por supuesto, hay excepciones, entre ellas: crear o modificar afijos, los cambios en los scripts o en la organización de directorios del proyecto, y quizá también en los README, si el cambio afecta a partes específicas de cierto contenido de ellos.

Por otro lado, más de la mitad de los _issues_ que teníamos hasta hace no mucho eran colecciones de palabras para añadir. Decidir qué palabras se añaden y cuáles no de entre las propuestas no es factible realizarlo en el comentario del commit o un PR, en mi opinión. Para esas colecciones de palabras yo creo que seguiría siendo necesario el _issue_.

En definitiva, para mí lo más importante no es si hay un _issue_ o un PR, sino que haya la oportunidad de someter a la comunidad lo que se quiere cambiar antes de hacerlo. La explicación detallada en el commit sin que exista un _issue_ o un PR deja muy bien documentado el cambio, pero no permite opinar a priori y, seamos sinceros, lo habitual es que no nos pongamos a repasar cada cambio que vemos producirse en el repositorio.

Yo voy un poco por la conclusión de @ezeperez26: quien prefiera hacer un _issue_ para documentar el cambio y someterlo a discusión antes de subirlo al repositorio principal, que lo haga así (y que en el título del commit referencie el _issue_ para que se enlace automáticamente a este). Quien esté más cómodo trabajando sobre su fork y haciendo un PR, que lo haga así. Colaborar a cambio de nada en un proyecto de código abierto implica que hay que sentirse feliz y cómodo haciéndolo, porque esa es la recompensa y, si no la tienes, no hay tampoco nada que nos impida dejar de colaborar.
