### ISSUE TITLE
Generación del archivo de historial de cambios (changelog)

### ISSUE THREAD

**Issue by edittler** [sbosio/rla-es#72]
Actualmente dentro del paquete de los diccionarios se incluye un archivo llamado `Changelog.txt` que debe ser editado manualmente y es bastante "simple", es decir, se le podría incluir más información, como por ejemplo, la fecha en la que se lanzó cada versión.

Además, es una [buena práctica](http://keepachangelog.com/) tener en los repositorio un archivo llamado `CHANGELOG.md` que contiene los cambios que ocurren de una versión a otra en el proyecto.

Por suerte hay muchas herramientas que ayudan a automatizar la generación de estos archivos. En particular, estuve probando la herramienta [github-changelog-generator](https://github.com/skywinder/github-changelog-generator).

Generé tantos _changelogs_ hasta que encontré el resultado deseado.
Les comparto el comando por si se decide usarlo:

``` sh
github_changelog_generator --bugs-label="**Errores corregidos**" --enhancement-label="**Mejoras implementadas**" --issues-label="**Issues cerrados**" --bug-labels='error,Error' --enhancement-labels='mejora,Mejora' --include-labels='error,mejora' --exclude-labels='duplicado,pregunta,inválido,solicitud de ayuda,no se arreglará' --no-pull-requests --no-author --no-compare-link
```

**Comment by RickieES** [comment]
Si ya hiciste la prueba, ¿podrías pegar el resultado aquí para que le echemos un ojo?

Tengo la idea (el prejuicio, probablemente) de que los archivos .md son específicos de GitHub. También pienso que han de estar en la raíz del repositorio, lo que complicaría su inclusión en los OXT. Por último, creo que, cuando subimos los OXT a los catálogos de extensiones de LibreOffice y Apache OpenOffice, solemos pegar la sección de cambios de la nueva versión en un campo de la ficha de la versión, y no sé si admitirá formato _markdown_, lo que podría obligarnos a estar revisando el texto.

A pesar del párrafo anterior, me parece buena idea probarlo para ver si nos merece la pena usarlo, en sustitución de, o como complemento y punto de partida para, el actual Changelog.txt.

**Comment by ezeperez26** [comment]
Subí al repositorio 3 archivos:

* `.github_changelog_generator` posee gran parte de la configuración del _changelog_, no hace falta pasarle las opciones desde el comando.
* `HISTORY.md` contiene el _changelog_ previo que no posee _releases_ en el repositorio de GitHub.
* `CHANGELOG.md` es el _changelog_ generado automáticamente por `github-changelog-generator`.

A pesar de que el archivo `.github_changelog_generator` contiene la configuración, hay un parámetro que no lo estaría tomando, por lo que se debe pasar aún un parámetro en el comando (ya será reportado ese error). El comando a ejecutar sería:

```sh
github_changelog_generator --exclude-labels='duplicado,pregunta,inválido,solicitud de ayuda,no se arreglará'
```

Hago unas aclaraciones con respecto a lo que has comentado luego.

Los archivos `.md` **no** son específicos de GitHub, es un formato que indica que su contenido es en _markdown_. Sin embargo, GitHub les da un tratamiento especial al abrirlos, dando formato a su contenido.

Que el archivo se encuentre en el directorio raíz no debería suponer ningún problema. Se lo puede localizar fácilmente con `bash` (sí, implicaría ajustar el script para que lo localice).

Y por último, referido al campo de versión, si no admite _markdown_ se puede "limpiar" el archivo eliminando unos pocos caracteres que son los que dan formato _markdown_. Llegado el caso de que sea incómodo se podría armar un script que "limpie" el archivo.

**Comment by RickieES** [comment]
Estuve viendo el archivo generado. Está bien, pero ¿no habrá alguna solución que no implique instalar otro entorno de lenguaje más? Lo digo porque está hecho con Ruby; ¿no habrá algo con PHP, Python, Bash, Perl o Java?

**Comment by ezeperez26** [comment]
El mismo autor del generador indica otras [alternativas](https://github.com/skywinder/Github-Changelog-Generator/wiki/Alternatives) y hay para varios gustos. Hay 8 que están basado JavaScript (la mayoría como paquetes en npm), 2 basado en C#, 3 en Ruby, 1 en php.

Los que están basados en C# quedarían descartados por no funcionar en GNU/Linux. Los de JavaScript también porque implicaría instalar nodejs y a muchos les puede resultar engorroso.
El que está escrito en php, es una "copia" de la solución que estuve probando, pero parece estar descontinuado. He probado esta herramienta en particular porque es la que encontré entre las más populares de GitHub, y con mucha honra, es de los más completos.

Con respecto a la plataforma, Ruby ya viene instalado por defecto en la mayoría de los SO Unix, por lo que sólo implica instalar la gema correspondiente y ejecutar el comando. Si es por simplificar el asunto, podría armar un script Bash que verifique si se encuentra Ruby instalado, instale la gema y genere el Changelog.

Como has mencionado a Python, te comento que Ruby es un lenguaje muy similar en muchos aspectos y goza de mucha popularidad desde que nació Ruby on Rails, haciendo que se extienda a otros usos insospechados. Y como dije anteriormente, se encuentra instalado en la mayoría de los SO Unix y es muy estable, haciendo que haya una buena compatibilidad entre distintas versiones (a diferencia de Python que ha generado una ruptura entre la versión 2 y 3).

Simplemente es una propuesta para facilitar la generación del Changelog y documentar mejor el historial del proyecto. Pero si se ve que es difícil, no hay problema en desistir del uso de esta herramienta.

**Comment by RickieES** [comment]
No sé si venía instalado por defecto en mi distribución (uso Linux Mint) o no, pero como suelo hacer limpieza de lo que no uso, ahora no tengo los paquetes de Ruby. También es verdad que he mirado y parece que instalarlo solo requiere tres paquetes en total. Eso sí, he visto que la versión por defecto en mi distro es la 1.9 y hay paquetes de la 2.0. ¿Es importante elegir una u otra?

He mirado también la versión en PHP. Me gusta su simplicidad (son dos archivos PHP nada más), pero reconozco que tampoco la he probado.

La generación automatizada es muy cómoda y más completa, pero por otra parte es menos flexible que hacerlo a mano. Me parece interesante comparar el [resultado de tu prueba](https://github.com/sbosio/rla-es/blob/master/CHANGELOG.md) en el apartado de la versión 2.0 con el del [Changelog.txt](https://github.com/sbosio/rla-es/blob/master/ortograf/docs/Changelog.txt) mantenido a mano, para hacernos una idea de lo que ganamos y perdemos. A ver qué opina otra gente; por el momento, lo que sí me parece buena idea es ejecutar el script justo antes de comenzar con la generación de la versión 2.1.

**Comment by Almorca** [comment]
Sin haberlo mirado en detalle, si todas las versiones son iguales, yo soy partidario de la versión en PHP por no añadir otro lenguaje de programación más.

**Comment by olea** [comment]
Mis conclusiones al respecto:

- me parece muy conveniente usar una herramienta de este estilo;
- viendo cómo se instalan las alternativas (ruby, php, python) los procedimientos de instalación son casi igual de complicados, aunque si los usuarios principales van a usar Linux la complejidad es casi mínima;
- elegir una alternativa u otra según su lenguaje de programación casi que ni importa: una vez que se deja todo instalado apenas sólo hay que saber invocar la herramienta dejándolo todo lo más precocinado posible;
- si de mi dependiera elegiría una con python o con ruby sobretodo porque es posible crear instalaciones independientes del sistema, en espacio de usuario (excepto las herramientas básicas como el propio intérprete y la herramienta de instalación de componentes externos que deben estar disponibles en cualquier Linux) y las conozco como para dejaros algo preparado;
- y si en estos días que estoy on-fire con el proyecto me indicáis la alternativa lo preparo yo mismo ya, y si no pues lo mejor será cerrar este boletín hasta que surja otra opinión :-)

Estoy a vuestras órdenes.

**Comment by Almorca** [comment]
Yo no conozco ruby ni python pero tampoco le puedo dedicar tiempo a hacer nada ni probablemente a mantener el código que se haga así que me parece bien que elijas el lenguaje que creas más conveniente.

**Comment by cosmoscalibur** [comment]
Pensando en buscar capacidad de mantenimiento de código, me sentiría conforme con Python, de Ruby estoy nulo. Pero no sé que tan útil puede ser, si muchos de los reportes que tenemos son masivos y los avances son de tipo parcial. Por el momento, estaría más de acuerdo con cerrar el reporte pues esta alternativa dejará múltiples avances por fuera.

**Comment by olea** [comment]
Parece que finalmente no vamos a utilizar ninguna herramienta para esto. Cierro el boletín por ahora.
