### ISSUE TITLE
Revisión de entradas en noRAE

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#73]
Algunos lemas en noRAE ya están admitidos por la RAE, por lo que deberíamos trasladarlos.

**NombresComunes.txt**

internauta/S
ninja/S

**Adjetivos.txt**

actitudinal/S
acultural/S
anatomopatológico/GS
antiautoritario/GS
antihorario/GS
autodenominado/GS # cubierto por denominar
bidireccional/S
colaborativo/GS
contextualizado/GS # cubierto por contextualizar
diédrico/GS
franquiciado/GS
globalizado/GS # cubierto por globalizar
inefectivo/GS
mareomotriz/S
monopólico/GS
multidisciplinario/GS
organizacional/S
participativo/GS
poblacional/S
predictivo/GS
prescriptor/GS
ranurado/GS # cubierto por ranurar
semielaborado/GS
sexualizado/GS # cubierto por sexualizar, que está en la RAE y tenemos que añadirlo

**NombresFemeninos.txt**

autocompasión/S
autoconfianza/S
autoprotección/S       # Contribuida por César Romé
cumplimentación/S
fundamentación/S
meritocracia/S
sandwichera/S
vinoteca/S
vocalía/S

**NombresMasculinos.txt**

datáfono/S
dimensionamiento/S
flexómetro/S
franquiciado/S
hiperenlace/S
hipervínculo/S
máster/S
ranurado/S
swing

**NombresMasculinosFemeninos.txt**

prescriptor/GS

**Preposiciones.txt**

versus

**VerbosIntransitivos.txt**

interactuar/IRD

**VerbosTransitivos.txt**

dimensionar/REDT
ranurar/RED
refrentar/RED

**VerbosTransitivosPronominales.txt**

reorientar/RED

Al mismo tiempo, he visto algunas palabras que realmente no deberíamos aceptar como válidas, ni siquiera como noRAE, ya que parecen desviaciones de palabras que sí existen en el diccionario, o no es correcta la forma (como los plurales de siglas), o no están bien acentuadas (como Oscar, aunque aquí quizá tengamos que pensarlo, porque podría referirse a la grafía en inglés).

NombresMasculinos.txt

kiosko/S (en lugar de kiosco/S)
portabroca/S (en lugar de portabrocas)
refrentado (debería generarse a partir del verbo refrentar)

NombresPropiosSiglas.txt

CDs # revisar
DVDs # revisar
Oscar # revisar

**Comment by AyelGoth** [comment]
Agrotóxico/s
Agroquímico/s
Holístico/a

**Comment by RickieES** [comment]
Tengo un problema con los lemas que figuran categorizados en Adjetivos.txt. Como veis, hay varios que también se generan a partir de los verbos. En realidad, muchos participios de verbos también se configuran como adjetivos, tantos, que si los incluimos, vamos a estar duplicando muchísimas entradas, y siempre nos faltarán por añadir.

Sé que duplicar lemas que pueden corresponder simultáneamente a varias categorías gramaticales es algo que preferimos hacer para poder tener un mantenimiento correcto del proyecto en los diferentes archivos que usamos, pero en este caso, se me hace un poco raro. ¿Qué opináis?

**Comment by Almorca** [comment]
Yo no los duplicaría..

**Comment by cosmoscalibur** [comment]
En mi caso me parece importante para conservar la información gramatical. Creo que considerar la no duplicación de estos elimina la idea futura del corrector de gramática de este proyecto o que sirva de base para otros proyectos (por ejemplo, tengo en lista de espera implementar un conversor para usar estos lemarios en LT) o poder en un futuro incorporar el etiquetado de hunspell de una forma sistemática.

**Comment by RickieES** [comment]
@cosmoscalibur, ¿cómo piensas implementar ese conversor? Me refiero a que, si no tratas las banderas, te quedarán muchos lemas por añadir y, si lo haces, tendrás que tener en cuenta que muchos de esos lemas creados por aplicación de las banderas varían su categoría gramatical. En este segundo caso, ¿cuál sería el problema de, al aplicar la bandera de verbos que genera el participio, duplicar la entrada gramatical como participio y como adjetivo? Que conste que esto último lo escribo mientras me doy cuenta que tenemos que comprobar si la bandera que genera los participios también crea los femeninos y plurales ya que, de no hacerlo, no serviría.

**Comment by RickieES** [comment]
> Que conste que esto último lo escribo mientras me doy cuenta que tenemos que comprobar si la bandera que genera los participios también crea los femeninos y plurales ya que, de no hacerlo, no serviría.

Sí lo hace (sufijo D, SFX D).

**Comment by RickieES** [comment]
> NombresComunes.txt
> internauta/S
> ninja/S

El DLE dice que ninja es masculino ("el ninja"), pero supongo que una mujer ninja puede ser "una ninja", ¿no?

Ninja, por cierto, también es adjetivo, según el DLE.

**Comment by RickieES** [comment]
sandwichera solo se admite en DLE como femenino de sandwichero, propio de Argentina, Chile, Paraguay y Uruguay:

http://dle.rae.es/?w=sandwichera

Por tanto, en lugar moverlo de noRAE a RAE/NombresFemeninos.txt, lo mantendría en noRAE/NombresFemeninos.txt y lo añadiría en RAE/NombresComunes.txt de esas cuatro localizaciones.

**Comment by RickieES** [comment]
> NombresMasculinos.txt
> (...)
> franquiciado/S
> (...)
> ranurado/S

Realmente, según el DLE no son nombres masculinos, sino adjetivos (y participios). ;)

> swing

El DLE lo sigue etiquetando como voz inglesa.

**Comment by RickieES** [comment]
> NombresMasculinosFemeninos.txt
>
> prescriptor/GS

El DLE lo marca como adjetivo usado más como sustantivo, por lo que entiendo que tendríamos que añadirlo en ambas categorías.

**Comment by RickieES** [comment]
> Preposiciones.txt
> VerbosIntransitivos.txt
> VerbosTransitivos.txt
> VerbosTransitivosPronominales.txt

En estos no veo ningún posible conflicto, así que procedo con ellos.

**Comment by RickieES** [comment]
En el caso de portabroca, no existe en el DLE, pero sí portabrocas, así que lo traslado corregido. Refrentado no existe en el DLE como adjetivo ni como nombre, sino que es el participio de refrentar, así que lo elimino; en la práctica, la palabra no deja de estar reconocida, pero no se categorizaría gramaticalmente como nombre ni adjetivo.

Aplico también estos cambios.

**Comment by RickieES** [comment]
Sobre los lemas de NombresPropiosSiglas.txt, que son plurales ("CDs", "DVDs"), a pesar de que estemos hablando de la categoría noRAE, creo que debemos eliminarlo, ya que el DPD es bastante claro sobre lo incorrecto de añadir una "s" al final de las siglas para formular su plural en forma escrita:

http://lema.rae.es/dpd/?key=sigla

¿Qué opináis? Yo, desde luego, estoy a favor de eliminar las entradas.

**Comment by RickieES** [comment]
> Agrotóxico/s
> Agroquímico/s
> Holístico/a

Agrotóxico no figura en el DLE. Agroquímico y holístico sí, como adjetivos. Los añado.

**Comment by RickieES** [comment]
> NombresComunes.txt
> Adjetivos.txt
> NombresFemeninos.txt
> NombresMasculinos.txt
> NombresMasculinosFemeninos.txt

Esos son los grupos de cambios que quedan por aplicar, a falta de vuestros comentarios.

**Comment by RickieES** [comment]
He aplicado los cambios que quedaban. Dejo abierto el _issue_ un tiempo por si veis algo raro.

**Comment by cosmoscalibur** [comment]
Hola @RickieES , observo en 8afafa0 que [ninja] fue agregado como nombre común siendo [nombre masculin](http://dle.rae.es/?id=QVrkES0). Como comente antes, no existen mujeres ninja, porque culturalmente había una separación en la formación, y su concepto equivalente es [kunoichi](https://es.wikipedia.org/wiki/Kunoichi). Por lo demás, no veo cosas raras.

**Comment by RickieES** [comment]
> Hola @RickieES , observo en [8afafa0](https://github.com/sbosio/rla-es/commit/8afafa08da10e4cf6d102276f4c8dfc70338a812) que [ninja] fue agregado como nombre común siendo [nombre masculino](http://dle.rae.es/?id=QVrkES0). Como comente antes, no existen mujeres ninja, porque culturalmente había una separación en la formación, y su concepto equivalente es [kunoichi](https://es.wikipedia.org/wiki/Kunoichi). Por lo demás, no veo cosas raras.

Pues es verdad, gracias. Lo corrijo.

**Comment by RickieES** [comment]
No ha habido más quejas, así que cierro el _issue_.
