### ISSUE TITLE
Palabras que faltan en la versión 2.1

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#76]
Abro este hilo con palabras nuevas que el diccionario no detecta.

calendarizar, calendarización, conóceme, currículum, démoselo, desconcentrarme, dietética, drogadicción, estándolo, guacamole, hazmerreír, historificar, insonorización, irlo, licenciador, mándamelo, manetas, maquetación, mándamelo, nutricionales, paracetamol, paramétrica, parametrizado/a, priori, priorización, renombrará, socavón, socorrismo, subgrupo, válgame

**Comment by Almorca** [comment]
Tengo un par de dudas:

calendarizar, calendarización --> para la RAE solo en Chile, Cuba, El Salv. y Hond. Para mí va en el diccionario general ya que en España yo sí la uso habitualmente. calendarizar/RED en VerbosTransitivos.txt

conóceme -->  Creo que habría que modificar la regla Í y añadir la terminación ojer igual a ojar. ¿Es correcto?

**Comment by RickieES** [comment]
Yo jamás he usado "calendarizar"; personalmente no me suena como un término de uso frecuente.

Bueno, conocer no termina en "ojer". :smile: Imagino que te refieres a añadir estas dos líneas:

SFX Í ocer      óceme    ocer
SFX Í ocer      ócenos   ocer

Eso funcionaría para conocer y para cocer, al menos. El DLE permite ahora pedir palabras que terminan de una forma determinada, y pidiendo "ocer" me salen estas:


    cocer
    cognocer
    conocer
    descocer
    desconocer
    escocer
    preconocer
    recocer
    reconocer
Yo creo que sí, que las dos líneas de arriba son correctas. Recuerda que habrá que añadir las dos líneas y aumentar el número de reglas del afijo Í en cada localización, además de en el general.

**Comment by Almorca** [comment]
Yo calendarizar lo uso cuando gestionamos un proyecto y tenemos que marcar las fechas de los hitos pero si no lo veis claro se añade sólo para los países que indica la RAE. Otra opción es RAE para unos países y meterlo en noRAE para España.

**Comment by Almorca** [comment]
Pongo a continuación el listado de cambios de este bug.

calendarizar, calendarización --> sólo en Chile, Cuba, El Salv. y Hond. calendarizar/RED en VerbosTransitivos.txt. En España iría en noRAE
conóceme --> añadir prefijo h a conocer (desconocer) y prefijo p (reconocer) y eliminarlos de VerbosTransitivosPronominales.txt
currículum --> currículum en NombresMasculinos.txt
Cambiar cursillo/S en  NombresMasculinos.txt
démoselo --> añado démoselo en ConjugacionesIrregulares.txt
desconcentrarme --> elimino reconcentrar/RED y sustituyo por afijo hp en concentrar
dietética --> dietético/GS en Adjetivos.txt
drogadicción --> drogadicción en NombresFemeninos.txt
estándolo --> estándolo en ConjugacionesIrregulares.txt
guacamole --> añado guacamole/S en NombresMasculinos.txt
hazmerreír --> hazmerreír/S  en NombresMasculinos.txt
historificar --> historificar/RED en VerbosTransitivos.txt
insonorización --> insonorización/S en NombresFemeninos.txt
irlo --> irlo en ConjugacionesIrregulares.txt
licenciador --> licenciador/GS en Adjetivos.txt
manetas --> según RAE sólo para Hond. y Nic. maneto/GS en Adjetivos.txt. En Español en noRAE.
maquetación --> maquetación/S en NombresFemeninos.txt
nutricionales --> nutricional/S en Adjetivos.txt
paracetamol --> añado en NombresMasculinos.txt
paramétrica --> paramétrico/GS en Adjetivos.txt
parametrizado/a --> parametrizar/RED en VerbosTransitivos.txt
priorización --> priorización/S en noRAE/NombresFemeninos.txt
renombrará --> Elimino renombrar de VerbosAnticuadosDesusados.txt. Añado p a nombrar en VerbosTransitivos.txt
socavón --> socavón/S en NombresMasculinos.txt
socorrismo --> añado O a socorro en NombresMasculinos.txt
subgrupo --> añado s a grupo/sS en NombresMasculinos.txt

Añadiría en afijos la regla específicada por @RickieEs

mándamelo, priori y válgame por ahora no sé como añadirlas al diccionario. Tengo que darles una pensada.

Aprovecho también para añadir testándolo --> añado Ä en testar/REDÄ VerbosTransitivos.txt
Elimino a de NombresFemeninos.txt porque ya está en preposiciones

**Comment by sbosio** [comment]
@Almorca:

Como sugerencia, no conviene eliminar palabras de los archivos por
duplicación, salvo que se dupliquen dentro del mismo archivo (cosa que creo
que no ocurre). La 'a' en NombresFemeninos.txt corresponde al nombre
(sustantivo) que corresponde a la letra del alfabeto, en cambio en
Preposiciones.txt corresponde a la preposición.

Actualmente, el diccionario únicamente se utiliza para la corrección
ortográfica, pero la separación de los listados de palabras en distintos
ficheros con su categoría semántica (nombre, adjetivo, verbo, preposición,
etc.) tenía como objetivo a futuro generar el diccionario etiquetado
(POS-tagging). Por eso hay tanta información semántica también en el
fichero de afijos en forma de comentarios, porque para el diccionario POS
hace falta también añadir a cada regla del fichero de afijos cómo
transforma semánticamente la palabra base.

**Comment by Almorca** [comment]
@sbosio El problema que le veo a esto es que para las nuevas palabras no estamos siguiendo ese criterio. Yo sólo las añado en dónde indique la primera acepción de la RAE.

Por otro lado puedes explicar un poco lo del POS-tagging por qué nunca lo había oído.

**Comment by RickieES** [comment]
Perdón por el retraso. He estado mirando la lista de entradas y tengo las siguientes sugerencias:

> drogadicción --> drogadicción en NombresFemeninos.txt

¿Por qué no añadir el plural? Por ejemplo, podría aparecer en "Hay distintos tipos de drogadicciones".

> hazmerreír --> hazmerreír/S en NombresMasculinos.txt

Y al contrario: ¿tiene sentido el plural aquí? ¿Ves probable usar "hazmerreíres"?

> historificar --> historificar/RED en VerbosTransitivos.txt

historificar no está admitido por la RAE.

> manetas --> según RAE sólo para Hond. y Nic. maneto/GS en Adjetivos.txt. En Español en noRAE.

A mí maneta en España solo me suena en femenino y como sustantivo (la maneta del freno de la bicicleta, por ejemplo).

**Comment by Almorca** [comment]
Con drogradicción tienes razón, falta el plural.
En cuanto a hazmerreíres no es muy usado pero existe y no veo mal añadirla.
En cuanto a historificar me baso en http://www.fundeu.es/consulta/historificar-historizar-2517/ Se puede añadir a noRAE.
La definición de manetas en España es justo la que tu pones. Lo añadiré en NombreFemeninos.txt en noRAE para es_ES.

**Comment by Almorca** [comment]
He añadido los cambios que había comentado. Ahora mismo quedan pendientes de solucionar mándamelo, priori y válgame.

**Comment by RickieES** [comment]
> mándamelo

El afijo que hay que usar es Ï, pero habría que añadir las reglas en todas las localizaciones. Ahora mismo hay estas entradas (entre otras 312, más o menos):

SFX Ï ancar     áncamela    ancar
SFX Ï ancar     áncamelas   ancar
SFX Ï ancar     áncamelo    ancar
SFX Ï ancar     áncamelos   ancar
SFX Ï ancar     áncanosla   ancar
SFX Ï ancar     áncanoslas  ancar
SFX Ï ancar     áncanoslo   ancar
SFX Ï ancar     áncanoslos  ancar
SFX Ï ancar     áncasela    ancar
SFX Ï ancar     áncaselas   ancar
SFX Ï ancar     áncaselo    ancar
SFX Ï ancar     áncaselos   ancar

Si añadimos las equivalentes para verbos terminados en -andar, debería funcionar:

SFX Ï andar     ándamela    andar
SFX Ï andar     ándamelas   andar
SFX Ï andar     ándamelo    andar
SFX Ï andar     ándamelos   andar
SFX Ï andar     ándanosla   andar
SFX Ï andar     ándanoslas  andar
SFX Ï andar     ándanoslo   andar
SFX Ï andar     ándanoslos  andar
SFX Ï andar     ándasela    andar
SFX Ï andar     ándaselas   andar
SFX Ï andar     ándaselo    andar
SFX Ï andar     ándaselos   andar

> priori

"a priori" es una locución adverbial y no podemos incluirla como tal, así que yo la dejaría fuera.

> válgame

Creo que no hay regla para derivar. "Válgame" en España se usa de modo coloquial ("¡Válgame la Virgen!"); quizá podríamos añadir solo ese lema en noRAE/l10n/es_ES/VerbosIrregulares.txt (sería un fichero nuevo).

**Comment by sbosio** [comment]
Creo que 'priori' podría añadirse. Si bien la locución completa 'a priori'
no puede agregarse como tal, vi por ahí la consulta de qué había que poner
en el fichero de Frases.txt. Precisamente este fichero estaba para poner
palabras cuya ortografía está correcta, como en este caso, pero que no
tienen valor semántico sin estar acompañadas por otras palabras. Por caso,
todas las locuciones, sobre todo latinas que contienen más de una palabra
pueden añadirse aquí (sólo que a una palabra por línea).

El corrector, obviamente, no va a marcar como error si al lema 'priori' no
se le antepuso el adverbio 'a', pero eso sería tarea del corrector
gramatical, no del ortográfico.

Saludos,

**Comment by RickieES** [comment]
@Almorca, ¿has decidido si añades las reglas del afijo? De todas maneras, si no me equivoco, ya llegamos tarde a la versión de LibreOffice,¿no?

**Comment by Almorca** [comment]
Esta tarde me pongo a ello y lo cerramos. Lo que no me termina de gustar es Válgame pero tampoco encuentro una solución mejor.

Con un poco de suerte sí llegamos a la versión 5.2.1 de Libreoffice.

**Comment by Almorca** [comment]
Ya están añadidos los últimos cambios.

**Comment by Almorca** [comment]
He creado un gist [ https://gist.github.com/Almorca/d5c4997b1df2bcd3d058347956a2cf1e ] con la lista de palabras que he usado para probar que todo estaba correcto.

Para probar el diccionario se genera el mismo, se descomprime en el mismo directorio que el fichero y se ejecuta
 hunspell -d es_ANY -G bug76_OK.txt

El proceso devolverá aquellas palabras que el diccionario considera erróneas, en este caso no debería haber ninguna.
