### ISSUE TITLE
Nuevas palabras que entran al diccionario de la RAE

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#77]
En 2014 se añadieron nuevas palabras al diccionario de la RAE que habría que revisar. Hay una lista en http://www.lavanguardia.com/cultura/20141016/54417980074/nuevas-palabras-diccionario-rae.html

**Comment by cosmoscalibur** [comment]
Se agregan en 87bc26d 5bc0859 2bd427a 8c17de0 d09e416  

✓agroturismo. m. Turismo rural, especialmente el que incluye actividades agrícolas y ganaderas.
✓anisakiasis. f. Med. Enfermedad parasitaria gastrointestinal causada por las larvas del anisakis y transmitida al hombre por pescado infestado que se consume crudo o poco cocinado.
✓anisakis. (Del lat. cient. Anisakis, y este del gr. νισ κις anisákis 'un número desigual de veces', por tener los machos espículas desiguales). m. Gusano nematodo parásito cuyas larvas se encuentran ocasionalmente en algunos peces, mamíferos marinos y cefalópodos, y que puede provocar en el hombre anisakiasis.
✓antipersona. adj. Dicho de una mina: Preparada para, al ser pisada, matar o mutilar a una persona.
✓antipersonal. adj. antipersona .
✓audioguía. (De audio- y guía). f. Dispositivo electrónico portátil de uso individual que, a través de grabaciones, proporciona información en la visita a una exposición, paseos turísticos, etc.
✓birra. (Del it. birra, y este del al. Bier). f. coloq. cerveza .
✓blaugrana. (Del cat. blaugrana, de blau 'azul' y grana 'grana2'). adj. azulgrana . Afición blaugrana. Apl. a pers., u. t. c. s.
✓bótox. (De Botox®, marca reg.). m. Quím. Toxina bacteriana utilizada en cirugía estética.
✓brik. (Acort.). m. tetrabrik .
✓burka. (Del ingl. burka, y este del ár. burqa‘). m. o f. Vestidura femenina propia de Afganistán y otros países islámicos, que oculta el cuerpo y la cabeza por completo, dejando una pequeña abertura de malla a la altura de los ojos. U. m. c. m.
✓cagaprisas. m. y f. malson. coloq. Persona impaciente, que siempre tiene prisa.
✓cameo. (Del ingl. cameo, y este del it. cammeo 'camafeo'). m. Intervención breve de un personaje célebre, actor o no, en una película o una serie de televisión.
✓ciclogénesis. (Del ingl. cyclogenesis, de cyclone 'ciclón' y -genesis '-génesis'). f. Meteor. Formación de un ciclón.
✓cortoplacismo. (De la loc. [a] corto plazo e -ismo). m. Conducta o actitud del cortoplacista.
✓cortoplacista. adj. Que persigue resultados o efectos a corto plazo. Apl. a pers., u. t. c. s.
✓euríbor. (Del ingl. euribor, acrón. de euro interbank offered rate 'tipo europeo de oferta interbancaria'). m. Econ. Tipo de interés que se aplica a los préstamos en euros entre grandes bancos, y que se usa con frecuencia como referencia en los préstamos hipotecarios a tipos de interés variables.
✓europarlamentario , ria. adj. 1. Perteneciente o relativo al Parlamento europeo. m. y f. 2. Diputado del Parlamento europeo.
✓hiyab. (Del ár. i b). m. Pañuelo usado por las mujeres musulmanas para cubrirse la cabeza.
✓homoparental. (De homo- y parental). adj. 1. Dicho de una familia: Formada por dos personas del mismo sexo y los hijos. 2. Perteneciente o relativo a la familia homoparental.
✓medicalización. f. Acción de medicalizar.
✓multiculturalidad. f. Cualidad de multicultural.
✓naturópata. adj. Dicho de un médico: Especialista en naturopatía. U. t. c. s.
✓pilates. (De J. H. Pilates, 1883-1967, especialista alemán en salud que desarrolló y divulgó este método). m. Método gimnástico que aúna el ejercicio corporal con el control mental, basado en la respiración y la relajación.
✓positividad. f. Cualidad de positivo.
✓serendipia. (Adapt. del ingl. serendipity, y este de Serendip, hoy Sri Lanka, por alus. a la fábula oriental The Three Princes of Serendip 'Los tres príncipes de Serendip'). f. Hallazgo valioso que se produce de manera accidental o casual. El descubrimiento de la penicilina fue una serendipia.
✓ interbancario. adj.
✓ naturopatía. f.

**Comment by cosmoscalibur** [comment]
Agregado en d68c349

azulgrana/S: 1. adj. Perteneciente o relativo al Fútbol Club Barcelona. 2. adj. Jugador o seguidor del Fútbol Club Barcelona. U. t. c. s.
espícula/S: 1. f. Corpúsculo calcáreo o silíceo que forma el esqueleto de esponjas, radiolarios y otros animales.
tetrabrick: 1. m. Envase de cartón impermeabilizado, cerrado herméticamente, y generalmente de forma rectangular, para bebidas y alimentos líquidos.
