### ISSUE TITLE
Página web

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#83]
Tenemos en el repositorio la antigua página web que se usaba en la forja de rediris. Habría que revisar si sirve para algo o lo borramos del repositorio.

**Comment by eksperimental** [comment]
github da alojamiento por cada projecto.
hay que crear un branch que se llame `gh-pages`
pero para la información que hay ahi, quiza con migrarlo a un archivo markdown, y que se enlace desde el README puede que baste

**Comment by ezeperez26** [comment]
En el _issue_ #52 @RickieES modificó/actualizó la página web. En esa oportunidad le consulté sobre su utilidad y la respuesta fue la siguiente:

> El sitio web (contenido en una sola página) era una introducción breve al proyecto. Ahora seguramente con el README.md tenemos la misma información.

Si se crea el _branch_ `gh-pages` la URL del sitio sería `http://sbosio.github.io/rla-es`, la cual tampoco es una gran mejora respecto a la actual `https://github.com/sbosio/rla-es`.

La información de esa página web ya se encuentra en el `README.md` principal del proyecto y en la wiki. Por mí, se podría eliminar el directorio `web` así nos evitamos el trabajo de tener que mantener otra  fuente de información.

**Comment by RickieES** [comment]
Por mí también se puede quitar, creo que ya hay más información en el README.md.
