### ISSUE TITLE
No funcionan los Sinónimos en v2.0 en UbuntuStudio 16.04, pero anterior 0.8 si

### ISSUE THREAD

**Issue by wachin** [sbosio/rla-es#84]
Hola a todos. Yo uso Spanish dictionary desde UbuntuStudio 14.04 y siempre funcionó a la perfección, y ahora que instalé desde cero 16.04 cuando entro en la página encuentro que hay una nueva versión que es la 2.0 pero en esta no funcionan los sinónimos, para nada, así que la desinstalé y volví a instalar la versión anterior que es la 0.8, ésta si funciona. Lo que pasa es que también yo iba a hacer un tutorial para Youtube de "Cómo instalar el diccionario de sinónimos en Ubuntu" porque en ningún derivado de Ubuntu viene instalado por defecto. Siempre he querido hacer faciles las cosas, pero esto lo dificulta para los usuarios ya que no les podría dar el link más corto para que descarguen la versión 2.0 sino uno largo, el de la versión 0.8

http://extensions.libreoffice.org/extension-center/spanish-dictionaries/pscreleasefolder.2012-04-18.1033472248/0.8

 y deberé de explicarles que no funciona la más nueva. Pregunto si esto se podrá arreglar para esperar hasta que esté arreglada la extensión o si nomás continúo y hago el video con la versión 0.8

Me gusta hacer algun tutorial sobre Sofware Libre o programas gratuitos

https://www.youtube.com/user/indacocheawachin

**Comment by sbosio** [comment]
Confirmado el error también en la última versión, 2.1.

El problema se introdujo al cambiar la codificación de ISO-8859-1 a UTF-8. Al ser UTF-8 una codificación multibyte, se corrompió completamente el archivo de índices.
Los índices en el archivo th_es_ES_v2.idx, hacen referencia al desplazamiento (en bytes) a partir del cual aparecen los sinónimos de ese término en el archivo th_es_ES_v2.dat. Los índices actuales están calculados para una codificación de byte único como la ISO-8859-1.

Las soluciones son dos: revertir el cambio y volver este diccionario a la codificación ISO-8859-1, ya que por ahora este diccionario está fijo, ya que el proyecto OpenThes_ES está muerto, o crear un script que parsee nuevamente la lista de términos y modifique todos los índices teniendo en cuenta los nuevos desplazamientos.

**Comment by sbosio** [comment]
@RickieES, @Almorca: ¿Les parece que revierta el cambio de codificación? ¿Les parece publicar un "hotfix" como 2.1.1, o esperamos a la 2.2?

**Comment by Almorca** [comment]
Yo revertería el cambio y publicaría una versión 2.1.1 ya que no parece que haya una fecha cercana para sacar la versión 2.2

**Comment by RickieES** [comment]
Lo que sucede es que yo no voy a poder dedicar todo el tiempo que requiere la publicación de una versión (como podéis imaginar, el proceso de publicación es el mismo para una versión con un cambio mínimo que con uno de más entidad).

De la fecha de publicación, Ezequiel propuso julio o agosto y serían buenas fechas, pero ninguno hemos dicho nada más, la verdad. Ezequiel decía que así nos podíamos tomar un descanso tras la 2.1, pero quizá deberíamos ir dando por terminadas las vacaciones. :smile:

**Comment by ezeperez26** [comment]
Imagino que hablar de "revertir cambios" se refiere a revertir sólo los archivos del diccionario gramatical. No habría porqué hacerlo a los demás, dado que el diccionario ortográfico anda bien.

Actualmente estoy en la misma situación de Ricardo, no estoy con tiempo para una nueva publicación mayor en una fecha cercana. Justamente las fechas que propuse (julio o agosto) son las que tengo más tiempo para dedicarle.

Si el cambio es sencillo de realizar, sería conveniente sacar una versión 2.1.1 que resuelva sólo este problema, así se puede ofrecer un diccionario sin errores lo más rápido posible.

**Comment by sbosio** [comment]
Exacto, @ezeperez26, revertiríamos únicamente los dos ficheros que componen el diccionario de sinónimos al último commit donde funcionaban correctamente. Sería el commit anterior al que implementó el cambio de codificación.

**Comment by sbosio** [comment]
Se revirtió el cambio de codificación en este [commit](https://github.com/sbosio/rla-es/commit/efd7768274ef8147c105d0e35b428a7260e0665e).
Se abrió el issue #85 para documentar la publicación de la versión 2.1.1, que integrará la corrección. Desde la publicación de la versión 2.1 no hay cambios en el master más que las correcciones que @ezeperez26 realizó en la herramienta de generación del diccionario, que quedarán incluidas en el tag de esta versión.
Con esto queda cerrado este issue.
