### ISSUE TITLE
Publicación de la versión 2.1.1

### ISSUE THREAD

**Issue by sbosio** [sbosio/rla-es#85]
Este issue se crea para documentar la publicación de la versión de parche 2.1.1 para resolver el inconveniente del issue #84.

**Comment by sbosio** [comment]
Ya publiqué la versión de pre-release como 2.1.1 en Github.
Verifiqué en mi instalación de LibreOffice 5 y está funcionando correctamente de nuevo el diccionario de sinónimos. Yo verifiqué únicamente la localización es_AR, pero debería ser lo mismo con todas.
Sería bueno que otros descargaran los paquetes de su localización y verificaran el funcionamiento, para pasarla al estado de publicación definitiva, y completar la publicación en los sitios de extensiones.

**Comment by eksperimental** [comment]
@sbosio solo comentar que según mi criterio no dería haberse etiquetado como 2.1.1, sino como 2.1.1-rc1, o -alpha, o algo que lo identifique como una version no final y menor. Porque va a crear conflictos, ya que no vas a poder usar el tag 2.1.1 cuando quieras etiquetar la version final.
Lo de pre-release es algo que usar github para ofrecer sus releases, pero es trabajo de uno ponerle la etiqueta correspondiente

**Comment by RickieES** [comment]
> Sería bueno que otros descargaran los paquetes de su localización y verificaran el funcionamiento, para pasarla al estado de publicación definitiva, y completar la publicación en los sitios de extensiones.

Descargué ayer la versión es-ES y acabo de probarla. Las correcciones ortográficas siguen funcionando, pero no me ofrece ningún sinónimo para palabras comunes que deberían tener alguna.

**Comment by sbosio** [comment]
El "debería" puede no ser tan así, porque no sé hasta dónde avanzó
OpenThesES antes de que terminara.

Prueba mejor con palabras que sepas que sí tienen sinónimos. Puedes guiarte
con los mismos ficheros (son ficheros de texto plano).

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Almorca** [comment]
Yo lo he probado con Alá que es la primera palabra que hay en el fichero y sí me funciona para es_ES.

Por cierto, Alá no está en el diccionario.

**Comment by RickieES** [comment]
He revisado el archivo de sinónimos y, sí, estaba usando palabras incluidas en él (eran palabras bastante comunes). :smile: Pero el motivo de que no me ofrezca palabras es que no identifica el diccionario como que incluya sinónimos; he cambiado el idioma a inglés y he escrito algunas palabras en ese idioma y sí me  ha ofrecido sinónimos.

Lo que sí es verdad es que no he intentado desinstalar la extensión 2.1 antes de instalar sobre ella la 2.1.1.

**Comment by RickieES** [comment]
He desinstalado la extensión, pero me parece que, como la instalación de LibreOffice está paquetizada en la distribución de Linux, debe de incluir una colección de diccionarios y por eso no incluye los sinónimos. Es la única explicación que encuentro, porque me sigue ofreciendo sugerencias de corrección del diccionario y de separación silábica, pero no de sinónimos, a pesar de que ahora mismo no tengo ningún diccionario en el gestor de extensiones.

**Comment by Almorca** [comment]
@RickieES Yo estoy en la misma situación que tú. Conseguí probarlo en un Windows ya que en kubuntu no me cogía el diccionario.

**Comment by ezeperez26** [comment]
Noté que los paquetes que están subidos en el _release_ no posee el tesauro. Los paquetes que contiene el tesauro pesan más de 1 MB. Se ha omitido el flag `-c` a la hora de generarlos.

Con respecto a LibreOffice, también me pasó que sin tener un diccionario instalado en el gestor de extensiones, igualmente me comprueba la ortografía. Esto es debido a que en el SO hay un diccionario instalado. En mi caso (xubuntu 14.04), lo resolví desinstalando el paquete `myspell-es` y LibreOffice dejó de comprobar la ortografía.

Por lo que dije al principio, para verificar si sugiere sinónimos, generé un diccionario completo (es_AR) con el estado actual del repositorio. Vi que el menú contextual tiene el ítem "Sinónimos", pero me da la leyenda "(ninguno)".

**Comment by ezeperez26** [comment]
Como dije en el comentario anterior, los diccionarios subidos no están generados con el flag `-c`, quedando sin el tesauro.
Si quieren puedo volver a generarlos para volver a subir los diccionarios, publicar el diccionario y cerrar este _issue_ antes de que salga la versión 2.2.
La consulta que tengo, ¿Se pueden generar los diccionarios de todas las localizaciones con un único comando, o hay que generarlos de a uno?

**Comment by RickieES** [comment]
No, no se pueden generar, y como alguien que ha generado los de las últimas versiones publicadas, te puedo decir que es un auténtico co*azo, o una auténtica paja, que me han soplado que se dice en Argentina. :smiley: Ya había pensado alguna vez en añadir un modificador para que lo haga el script automáticamente.

**Comment by sbosio** [comment]
Con la publicación de la 2.2 tan cerca, no haría el esfuerzo de la 2.1.1.
La idea mía era sacar esa versión rápido para corregir el problema con los
diccionarios de sinónimos que se corrompieron con el cambio a UTF-8, pero
me olvidé de utilizar el flag '-c', como comentas y quedaron incompletos.
Yo no publicaría dicha versión. Le pondría esfuerzo a la 2.2 y listo.

Por otro lado, si bien la herramienta de generación no tiene la opción para
generar todas las localizaciones, desde una terminal puedes usar un comando
como este:

[user@host:~/rla-es/ortograf/herramientas]$ ./make_dict.sh -c; for i in
$(ls ../../ortograf/palabras/RAE/l10n/); do ./make_dict.sh -l $i -c; done

El primer ''make_dict.sh" es para generar el 'es_ANY' y luego con un lazo
for generas todas las localizaciones.

¡Saludos!

**Comment by RickieES** [comment]
Muchas gracias por el truco, @sbosio, ya lo he añadido al wiki. :+1:

**Comment by ezeperez26** [comment]
Excelente el método @sbosio!
El _release_ estaba marcado como _pre-release_, así que se estaba a tiempo de volver a subir los archivos.
Ya están los nuevos archivos disponibles con el tesauro en [v2.1.1](//github.com/sbosio/rla-es/releases/v2.1.1).
Se podría dar por finalizada la publicación de la versión 2.1.1 y cerrar este _issue_.
