### ISSUE TITLE
duplicate flag declarations in ES-ANY

### ISSUE THREAD

**Issue by baarsrj** [sbosio/rla-es#86]
There are multiple issues with the ES-ANY variant: 
error: line 2552: multiple definitions of an affix flag
error: line 2560: multiple definitions of an affix flag
error: line 2658: multiple definitions of an affix flag
error: line 2684: multiple definitions of an affix flag
error: line 2822: multiple definitions of an affix flag
error: line 2922: multiple definitions of an affix flag
error: line 3452: multiple definitions of an affix flag
error: line 3704: multiple definitions of an affix flag
error: line 4078: multiple definitions of an affix flag
error: line 4128: multiple definitions of an affix flag
error: line 4310: multiple definitions of an affix flag
error: line 4356: multiple definitions of an affix flag
error: line 5106: multiple definitions of an affix flag
error: line 5436: multiple definitions of an affix flag
error: line 5822: multiple definitions of an affix flag
error: line 5884: multiple definitions of an affix flag
error: line 6086: multiple definitions of an affix flag
error: line 6136: multiple definitions of an affix flag
error: line 6214: multiple definitions of an affix flag
error: line 6304: multiple definitions of an affix flag
error: line 6475: multiple definitions of an affix flag
error: line 6748: multiple definitions of an affix flag

Probably it is better tu change to FLAG LONG

**Comment by Almorca** [comment]
Arreglo el error con el commit ebb5353adef387bdf32251cf3a04d0669e0dcc69

El problema es que para que hunspell considere que un fichero de afijos está en formato UTF-8 hay que añadir el flag FLAG UTF-8 ya que el flag SET UTF-8 sólo indica el formato del fichero .dic

Para comprobar el error se usa el comando 
hunspell -d es_ES
para ver que el diccionario funciona correctamente y no devuelve ningún error.

**Comment by baarsrj** [comment]
What you are saying is not exactly true.

When SET UTF-8 is used, both file sshould be in utf8.
But then, not all chars are valid in a flag.

To make things more manageble, one could consider to use FLAG long, 
making plain readable two letter flags (without diacriticals) in the 
affix file as well as the .dics.

When I look at the ES_ANY, there are multiple sections for the same 
flag; that is really invalid.

Ruud



Almorca schreef op 2016-06-07 21:28:

**Comment by Almorca** [comment]
@baarsrj Sorry but I don't understand why we can't use all UTF-8 chars in a flag and because with FLAG long yes. Why do you thing that we should use FLAG long?

What is the problem with es_ANY? Where do you see multiple sections?

**Comment by baarsrj** [comment]
Just use es_any frim the commanline, like in hunspell -d es_any -L test.txt, and you will see errors reported.

Verzonden van mijn mobiele telefoon.

----- Bericht beantwoorden -----
Van: "Almorca" <notifications@github.com>
Aan: "sbosio/rla-es" <rla-es@noreply.github.com>
CC: "R. Baars" <baarsrj@xs4all.nl>, "Mention" <mention@noreply.github.com>
Onderwerp: [sbosio/rla-es] duplicate flag declarations in ES-ANY (#86)
Datum: do, jun. 9, 2016 20:49

@baarsrj Sorry but I don't understand why we can't use all UTF-8 chars in a flag and because with FLAG long yes. Why do you thing that we should use FLAG long?

What is the problem with es_ANY? Where do you see multiple sections?

&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Almorca** [comment]
@baarsrj I have tested the file es_ANY and I can not see any error with the git version of dictionary. Could you post a image of your error?

**Comment by pgajdos** [comment]
This depends on version of hunspell, it seems. I get the warning with 1.3.2, but not with 1.4.1.

**Comment by h-2-0** [comment]
@Almorca 

I am getting the same error as @baarsrj when I run a python script that calls hunspell. I do not have any version of hunspell installed but I do have libhunspell-dev installed AND no errors show when I run the same script in another server.

The dictionary version I use can be found here:
http://recursospython.com/wp-content/uploads/2016/02/hunspell-es.zip

Where I can get the git version of the dictionary? Or how do I solve the problem?

Thanks.

**Comment by h-2-0** [comment]
Ok, people. I did a little more research and found the following comment from Caolan McNamara in this [bug report at hunspell](https://sourceforge.net/p/hunspell/bugs/138/):

`To fix this add "FLAG UTF-8" to your aff file to indicate that the flags are encoded UTF-8. The default mode is to assume the flags are single bytes, and in this case È and Ì are encoded as UTF-8 and are multi-byte codes and the lead byte of each multi-byte code is the same, hence the warning. The SET UTF-8 only states that the .dic is in UTF-8. Its a little odd I accept, but give "FLAG UTF-8" a go.`

So I edited the es_ANY.aff  and changed the line SET UTF-8 at the top of the file to FLAG UTF-8 and the error went away!

**Comment by cosmoscalibur** [comment]
@h-2-0 [last version](https://github.com/sbosio/rla-es/releases/tag/v2.4) fixes that issue. Uncompress the OXT file and use DIC and AFF files.

**Comment by h-2-0** [comment]
@cosmoscalibur

Thanks for letting me know. But I don't know which OXT file you talk about. I was always used the DIC and AFF files found in the zip file I linked above.

**Comment by cosmoscalibur** [comment]
@h-2-0 follow the link of the -> [last version](https://github.com/sbosio/rla-es/releases/tag/v2.4) <-. Download OXT file of the localization that you need. Uncompress OXT, this contains DIC and AFF files.

**Comment by h-2-0** [comment]
Thanks so much, @cosmocalibur ! I downloaded them already.

**Comment by RickieES** [comment]
@h-2-0, did it work? Can we mark this issue as fixed?

Thanks in advance.
