### ISSUE TITLE
Agregar al script una opción para generar todos los diccionarios

### ISSUE THREAD

**Issue by edittler** [sbosio/rla-es#87]
En el _issue_ #85 @sbosio compartió su método para generar todos los diccionarios.
Consiste en ejecutar en la consola lo siguiente:

``` sh
./make_dict.sh -c; for i in $(ls ../../ortograf/palabras/RAE/l10n/); do ./make_dict.sh -l $i -c; done 
```

Sería cómodo agregar dicha funcionalidad dentro del _script_, pudiendo ejecutarse con las opciones `--todos` y su versión reducida `-t`.

**Comment by sbosio** [comment]
Añadi la opción en el commit 725e1bbb28c761937af575a44c41841297dd62fe.
