### ISSUE TITLE
Evaluar separar las siglas en un archivo diferenciado

### ISSUE THREAD

**Issue by RickieES** [sbosio/rla-es#88]
En el _issue_ #8 se proponía separar las siglas en un archivo separado. Actualmente no hay apenas siglas en el archivo NombresPropiosSiglas.txt neutral, por lo que lo primero que tenemos que decidir es si merece la pena. En el _issue_ comentado yo dije esto:

> Ahora bien, ahora mismo contaríamos con la increíble cifra de... 2 siglas (CD y DVD). :smile: ¿Merece la pena? ¿Añadimos otras siglas, como ADSL, ONU, UNESCO, FAO, FMI, UE, USA, UK, SEPA, IBAN, BIC, SWIFT? Seguiríamos teniendo solo catorce entradas.

A lo que @ezeperez26 contestó:

> Por ahora añadiría las siglas que no se refieran a organizaciones, por ejemplo, no añadiría ONU, UNESCO, FAO, FMI. Las siglas de países o regiones tampoco las agregaría a menos que se demuestre su uso frecuente, por ejemplo, como podría ser UE en España (sólo en es_ES).
> 
> Hay siglas que están reconocidas por RAE, pero están dentro de noRAE, como también aparecen los plurales de siglas, que no están permitidas por RAE.

lo que me lleva a pensar que primero tenemos que aclarar los criterios para incluirlas, para posteriormente, si el volumen de siglas lo aconseja, hacer la separación efectiva del archivo.

**Comment by cosmoscalibur** [comment]
Observo que el tema de siglas se quedo frenado hace mucho tiempo. ¿Finalmente bajo cuales parámetros se deben incluir? En #137 incluí nombres propios populares acorde a la localización de Colombia pero ahora mi idea (mientras recopilo el listado de nombres ilustres colombianos) es realizar la lista de las siglas más usuales en Colombia (que corresponden finalmente a entidades). Pero con la observación de este tópico abierto iría en dirección contraria.  
Ejemplos en mi país de uso extendido son ICBF y DANE (entidades del gobierno), al igual que las siglas que son parte del nombre oficial de múltiples universidades como EAFIT, UNAD y CESDE.

**Comment by RickieES** [comment]
Puede ser el momento de retomar esto. Para que conste, yo no veo un motivo especial para diferenciar las siglas de organizaciones de otras siglas. Sí veo motivo para separar algunas por su ámbito regional.

**Comment by olea** [comment]
Cierro el boletín.

Si alguien retoma la tarea reabrimos alegremente :-)

**Comment by cosmoscalibur** [comment]
Discusión inactiva desde 2020, y en el hilo de discusión se hacía mención al cierre del reporte, sin embargo no fue cerrado. Se procede a cerrar.
