### ISSUE TITLE
Archivo Frases.txt

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#89]
Hay un archivo Frases.txt que no sé que debería contener y si sigue teniendo sentido mantenerlo.

**Comment by RickieES** [comment]
Anda, no seas egoísta y dinos dónde está, que lo veamos todos. :smile:

**Comment by Almorca** [comment]
En ortograf/palabras/RAE/Frases.txt

**Comment by Almorca** [comment]
En este comentario https://github.com/sbosio/rla-es/issues/76#issuecomment-236964663
explica @sbosio que el fichero estaba para poner palabras cuya ortografía está correcta, como en este caso, pero que no tienen valor semántico sin estar acompañadas por otras palabras.

Por mi parte o añadimos un comentario al fichero o lo explicamos en la wiki pero en algún sitio hay que dejarlo explicado.

**Comment by RickieES** [comment]
He añadido unas notas en el propio archivo, que me parece lo más rápido y cómodo. Si tuviéramos en el wiki una explicación del contenido de cada archivo, lo añadiríamos ahí, pero como no es el caso, de momento creo que es suficiente con las notas en el archivo.

**Comment by ezeperez26** [comment]
Concuerdo, documentar sobre los mismos archivos es más cómodo.
Se podría seguir la misma idea con los demás archivos, creando un encabezado "estándar" tal como tienen las secciones de afijos.
