### ISSUE TITLE
Paralimpiada

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#90]
Ahora que estamos en época olímpica hay que prestarle atención. Faltan:  paralimpiada, paralimpíada.

**Comment by RickieES** [comment]
Mi propuesta (aún no subida):

diff --git a/ortograf/palabras/RAE/NombresFemeninos.txt b/ortograf/palabras/RAE/
index f6793ff..5ca6c8e 100644
--- a/ortograf/palabras/RAE/NombresFemeninos.txt
+++ b/ortograf/palabras/RAE/NombresFemeninos.txt
@@ -7706,6 +7706,8 @@ paráfrasis
 paraguaya/S
 paralaje/S
 paralela/S
+paralimpiada/S
+paralimpíada/S
 parálisis
 paralización/S
 parangona/S

**Comment by Almorca** [comment]
Perfecto

**Comment by RickieES** [comment]
Lo subo entonces, ¿vale?
