### ISSUE TITLE
Add apostrophe to WORDCHARS

### ISSUE THREAD

**Issue by Carmina16** [sbosio/rla-es#91]
There is currently an issue with es_ANY dictionary splitting proper names containing an apostrophe.
Please add `WORDCHARS '` declaration to the affix file.

**Comment by RickieES** [comment]
Can you give us an example of a Spanish word causing that problem, please?

**Comment by Carmina16** [comment]
"d'Auvigny", it gets split into "d" and "Auvigny" by hunspell, which is wrong.

**Comment by RickieES** [comment]
"d'Auvigny" is not an Spanish word. I wouldn't expect that Hunspell marks as correct "London" while using Spanish or "Rügen Cliffs" while using English.

I don't like the idea of adding a character to be considered as part of Spanish words, when it is not, just for the sake of not marking as incorrect words that are not Spanish. From the Hunspell manual:

> WORDCHARS characters
> WORDCHARS extends tokenizer of Hunspell command line interface with additional word character. For example, dot, dash, n-dash, numbers, percent sign are word character in Hungarian.

If we add the apostrophe, why should we reject later a request to add the dot or dash?

@Almorca, @ezeperez26, @sbosio

**Comment by Almorca** [comment]
¿Qué os parece si cerramos esta incidencia?

**Comment by RickieES** [comment]
Me parece bien. No se me ocurre ningún lema en español que incluya un apóstrofe como parte de su grafía.

Por cierto, que nuestro diccionario no reconoce como válida "apóstrofe". :smile: Voy a añadir la palabra en el _issue_ que creaste tú, @Almorca.
