### ISSUE TITLE
Mayúscula en «internet» 

### ISSUE THREAD

**Issue by RGB-es** [sbosio/rla-es#92]
Actualmente el diccionario considera «internet» (con minúscula inicial) como error y sugiere «Internet» (con mayúscula), pero en realidad ambas serían correctas, con una tendencia internacional a utilizar la versión en minúsculas. Para más datos, consultar este artículo de Alberto Bustos:

‘Internet’: ¿mayúscula o minúscula?
http://blog.lengua-e.com/2016/internet-mayuscula-o-minuscula/

**Comment by Almorca** [comment]
La Fundéu también lo cree igual http://www.fundeu.es/consulta/internet-internet-650/
