### ISSUE TITLE
Palabras que faltan en la versión 2.2

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#93]
Estas son las palabras que he encontrado que faltan en la versión 2.2 del diccionario:

aperiódico, ataraxia, Bádminton, barbárica, entendible, extrapolables, granularidad, hinchables, maquetar, megafonía, menéame, metadato, orientativos, particionado, pásame, podólogo, proactivo, pronación, rúbrica, teleindicador, unívocamente, vacunaciones, velcro

**NORAE**: 
desestresaría
inasumible --> https://twitter.com/raeinforma/status/499100704913776640
http://www.elperiodicoextremadura.com/noticias/universa/palabras-margen-ley-rae_83769.html

**Comment by RickieES** [comment]
Añado apóstrofe. Iría aquí:

palabras/RAE/NombresMasculinos.txt | apóstrofe/S

**Comment by Almorca** [comment]
Esta son las reglas que yo añadiría

aperiódico --> periódico/aGS en añado a en Adjetivos.txt
ataraxia --> ataraxia/S en NombresFemeninos.txt
Bádminton --> bádminton en NombresMasculinos.txt
barbárica --> barbárico/GS en Adjetivos.txt
entendible --> entender/hrstIRTDÀÁÃÄÂÐÑñòù (añado hrstT en VerbosTransitivosIntransitivosPronominales.txt)
--> elimino subentender/IRD de VerbosTransitivosPronominales.txt
--> elimino sobrentender/IRD de VerbosTransitivosPronominales.txt
--> elimino superentender/IRD de VerbosTransitivos.txt
--> elimino VerbosPronominales.txt:desentender/IRDñ
extrapolables --> extrapolable/S en Adjetivos.txt
granularidad --> granularidad/S en noRAE/NombresFemeninos.txt
hinchables --> hinchable/S en Adjetivos.txt
maquetar --> maquetar/RED en VerbosTransitivos.txt
megafonía --> megafonía/S en NombresFemeninos.txt
menéame --> añado Í a menear en VerbosTransitivosPronominales.txt
metadato --> metadato/S en noRAE/NombresMasculinos.txt
orientativos --> orientativo/GS en Adjetivos.txt
particionado --> particionar/RED noRAE/VerbosTransitivosPronominales.txt
La RAE ha opinado en https://twitter.com/raeinforma/status/664018366424854528
pásame --> no he encontrado regla que la forme.
--> elimino repasar añadiendo p a pasar
podólogo --> podólogo/GS en NombresMasculinosFemeninos.txt
proactivo --> añado o a activo en Adjetivos.txt
pronación --> pronación en NombresFemeninos.txt
rúbrica --> rúbrica/S en NombresFemeninos.txt
teleindicador --> teleindicador/S en NombresMasculinos.txt
unívocamente --> unívocamente en Adjetivos.txt
vacunaciones --> añado A a vacunar
--> elimino revacunar y sustituyo por p en vacunar
velcro --> velcro/S en NombresMasculinos.txt

Revisad principalmente lo que he puesto en noRAE y a ver si vemos como se puede añadir pásame.

**Comment by RickieES** [comment]
> pásame --> no he encontrado regla que la forme.

El afijo es:

SFX Í

pero no incluye la regla. Sería anteponer estas dos líneas:

SFX Í asar      ásame    asar
SFX Í asar      ásanos   asar

Pero, claro, en todas las localizaciones. :smirk: 

Todo lo demás lo veo bien.

**Comment by Almorca** [comment]
He añadido  la regla a los ficheros de afijos y las nuevas palabras.

**Comment by RickieES** [comment]
He creado el _milestone_ 2.3 y se lo he asignado a este _issue_ para no perderlo de vista cuando llegue el momento.
