### ISSUE TITLE
Compendio de palabras faltantes de la Wikipedia en castellano

### ISSUE THREAD

**Issue by Almorca** [sbosio/rla-es#95]
Abro esta incidencia para seguir con el listado de palabras de la incidencia #24 
@eksperimental ¿Puedes generar una nueva lista de palabras?
Si no continuaré con la lista https://gist.github.com/eksperimental/acfc34a7bed80b967a42 con las palabras del 101 al 200.

**Comment by eksperimental** [comment]
@Almorca voy a actualizar los diccionarios, y veré si puedo bajar una copia mas reciente de Wikipedia, pero   no creo que haya mayor diferencia en las palabras del tope de la lista.

Te agradecería que las palabras que no incluyas por equis motivo, me las compartas en un archivo de texto (si es por grupos mejor), asi las incluyo en mi script, y podemos ir generando lo mas correcta posible.

**Comment by eksperimental** [comment]
@Almorca puedes asignarme tambien a esta issue? asi no lo pierdo de vista en las cosas que tengo que hacer.

**Comment by Almorca** [comment]
@eksperimental No me deja asignarte la incidencia. Imagino que será porque no estás puesto como desarrollador del proyecto.

**Comment by eksperimental** [comment]
entiendo. no hay problema.

**Comment by Almorca** [comment]
@eksperimental De todas maneras el sacar un nuevo listado es sólo si no te implica mucho trabajo. Como bien dices los resultados no deberían variar mucho de la lista actual.

**Comment by eksperimental** [comment]
lleva bastante tiempo correr el script y a veces el compu se apagaba por el excesivo uso de recursos, y los archivos de wikipedia pesan varios Gigas, pero voy a ver de hacerlo de todos modos.

**Comment by cosmoscalibur** [comment]
No se que tan descabellado sea considerar para este tipo de situaciones, al ser justamente un recurso abierto, considerar ese proceso de revisión de Wikipedia integrando un servicio CI, como lo es [Travis](https://travis-ci.org/). Dado que el proyecto es abierto, no tendría un costo asociado el servicio y no dependeríamos de los ordenadores propios. Igualmente se podría pensar en particionar la información, y por bloques podemos ejecutar el _script_ varias personas.

**Comment by eksperimental** [comment]
Disculpen, pero antes de que me olvide, el script que creé se encuentra en
https://github.com/eksperimental/qorpora
no se encuentra ni en version alfa, pero decidí subirlo porque no creo que en un futuro cercano ni mediano pueda tenerlo listo. Así que al menos le pueda servir a alguien como referencia, o incluso para crear sus propias listas de palabras.

Referido a correr el script en Travis sería:
- una locura
- abusar de los servicio que Travis da gratuitamente a la comunidad de código libre
- un sin-sentido, porque como ya dije anteriormente, Wikipedia no va a cambiar ni en un mes ni en un año, ni mucho menos en el dia a dia que se suba un nuevo PR y haya que ver que palabra cambios. Hay una lista lo suficientemente grande como preocuparnos por alguna palabra que pueda aparecer nueva, o que cambien de posición algunas palabras que ya se encuentran en la lista.

**Comment by RickieES** [comment]
¿Convendría valorar cambiar el _milestone_ de este _issue_, si no lo vamos a tener listo próximamente?

**Comment by cosmoscalibur** [comment]
@eksperimental  en eksperimental/qorpora#1 reporte 236 lemas para incluir en la lista negra con el respectivo motivo de exclusión. Aún tengo una lista de 162 lemas pendientes de validar (posibles noRAE) y los demás están confirmados como lemas validos (RAE y noRAE).  
Al igual que @RickieES me parece pertinente cambiar el _milestone_. Espero poder tener resuelta la adición de los lemas RAE (estoy elaborando una rutina para la adición masiva partiendo de la definición extraída del DLE) en enero pero los noRAE pendientes de validar aún son muchos.

**Comment by RickieES** [comment]
Cambio el milestone a Después en espera de que terminemos la 2.3 y cree el milestone 2.4.

**Comment by cosmoscalibur** [comment]
Para ir adelantando, el reporte 95 tiene pendientes los siguientes lemas RAE (los noRAE los tengo pendientes por validar): https://gist.github.com/cosmoscalibur/34f5d326efc5864a65b9c022b0fc792d  
Por la cantidad, dispongo este avance en la revisión de definiciones y categorías para que otros puedan colaborar en la adición. Aún tengo pendiente implementar una rutina que se encargue de la adición masiva.

**Comment by RickieES** [comment]
Por el tamaño de la lista que indica @cosmocalibur, creo preferible pasar este _issue_ también a Después.

**Comment by eksperimental** [comment]
> Para ir adelantando, el reporte 95 tiene pendientes los siguientes lemas RAE (los noRAE los tengo pendientes por validar): https://gist.github.com/cosmoscalibur/34f5d326efc5864a65b9c022b0fc792d
> Por la cantidad, dispongo este avance en la revisión de definiciones y categorías para que otros puedan colaborar en la adición. Aún tengo pendiente implementar una rutina que se encargue de la adición masiva.

Muchas gracias @cosmoscalibur.
Acabo de ordenar la lista de palabras RAE, por su porcentaje. lo pueden encontrar aquí.
https://gist.github.com/eksperimental/cb451fe1d0312551921a8cab4201ac0d

Creo que sería bueno cubrir el 90% (son solo 33 palabras) y luego ir por metas, de 1 en 1%, hasta llegar al 95%.
Al menos si se van a agregar palabras, tiene sentido que sean las mas populares, y especialmente las que estan reconocidas por la RAE, por el simple motivo de que evita tener que debatir si se las incluye o no.

**Comment by cosmoscalibur** [comment]
@eksperimental puedes validar las frecuencias de la lista del reporte #15 ([lista](https://gist.github.com/cosmoscalibur/f89526d0432911b4ab57309432c10b0d)). Y con la lista del #11 (la original del reporte). Sería de gran ayuda para priorizar los lemas que se agregan y hacer más fácil el avance a estados parciales que sean realmente útiles y no lemas aleatorios.

**Comment by eksperimental** [comment]
> @eksperimental puedes validar las frecuencias de la lista del reporte #15 ([lista](https://gist.github.com/cosmoscalibur/f89526d0432911b4ab57309432c10b0d)). Y con la lista del #11 (la original del reporte). Sería de gran ayuda para priorizar los lemas que se agregan y hacer más fácil el avance a estados parciales que sean realmente útiles y no lemas aleatorios.

Estas son las palabras que estan en el top 95% de Wikipedia en español para la issue 15.
https://gist.github.com/eksperimental/6f7e7ac1d5289e342379a92d10700046
El resto que son las mayoria, fuera de este rango del 95%.

**Comment by eksperimental** [comment]
y esta es de la issue 11.
https://gist.github.com/eksperimental/08d94e26cd34774292a91e609b8944b7

**Comment by eksperimental** [comment]
Sinceramente no le veo sentido cuales son las palabras de cada issue, porque ya estan listadas en la lista que publique del 95%. más alla de que aparezcan en otras issues, van a seguir siendo las palabras que se analizó en Wikipedia y que son las mas populares y que siguen faltando agregar. lo que sí se podría hacer sería on un lematizador, extraer los lemas y crear una nueva lista.

**Comment by eksperimental** [comment]
mi comentario anterior hacía referencia a la issue 11.
Para la issue 15 sí tiene sentido porque son las palabras aceptadas por la RAE.

**Comment by eksperimental** [comment]
No le veo demasiado sentido encontrar en la issue #11 cuáles son las palabras, porque ya estan listadas en la lista que publique del 95%.
Lo que sí se podría hacer sería on un lematizador, extraer los lemas y crear una nueva lista de las palabras segun frecuencia en Wikipedia.

**Comment by cosmoscalibur** [comment]
Gracias @eksperimental . Estoy validando con esas listas reducidas cuales nos faltan para priorizar.

**Comment by cosmoscalibur** [comment]
Se cierra reporte al completar los criterios de
- 95% de frecuencia normalizada respecto al _corpus_ de Wikipedia.
- Lemas RAE general completos
- Lemas RAE l10n en su mayoría
