### ISSUE TITLE
Agregar la palabra [sintonía]

### ISSUE THREAD

**Issue by edgardorios** [sbosio/rla-es#96]
Hola a todos:

Me parece que la palabra [sintonía] no existe en el diccionario es-ES.
Me gustaría ayudar a agregarla yo mismo, pero creo que aún me falta mucho por aprender.

Si debo hacer algo más, les pido de favor me lo digan.

Saludos.
Edgardo

**Comment by ezeperez26** [comment]
Hola Edgardo,

Efectivamente, falta el lema "sintonía". Como dicha palabra es un nombre femenino y se encuentra admitida por la RAE, se incluye en el archivo `ortograf/palabras/RAE/NombresFemeninos.txt`. Se le agrega además el flag `S` para incluir el sufijo de plural, marcando como válida la forma "sintonías".

Ya hice los cambios en el commit dc7f5e1 para que puedas ver como ejemplo. Si tienes más palabras, no dudes en probar haciendo los cambios por tu cuenta. Algunos criterios para palabras que no se encuentran en RAE están documentados en la [wiki](https://github.com/sbosio/rla-es/wiki#criterios-usados-para-admitir-palabras). Podés consultar si tenés dudas sobre dónde o cómo añadirlas. Luego harías un _pull request_ y una vez aprobado las palabras serán incluidas en la próxima versión del diccionario.

Saludos

**Comment by edgardorios** [comment]
Hola Ezequiel:

Muchas gracias por tu apoyo. Seguiré tu consejo e intentaré hacer las siguientes aportaciones por mi cuenta. Acá seguimos en contacto.

Saludos.
Edgardo

**Comment by ezeperez26** [comment]
La palabra "sintonía" que es lo que se solicitó incluir ya está incluida para la versión 2.3. Procedo a marcar como resuelto este _issue_.
